### ISSUE TITLE
Merging not working since new installation

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#600] opened 2018-07-08 14:06 UTC
I removed and reinstalled Seurat sometime ago. Since then merging function is not working. It used to work fine for me unitl now.

Kindly address.
Here is the code and the error

#Read matrix data into R and create Seurat Object with cells expressing at least 200 genes and genes expressed atleast in 3 cells
raw.data_d0 <- Read10X(data.dir = raw.data_d0path)
so_d0 <- CreateSeuratObject(raw.data = raw.data_d0, min.cells = 3,min.genes = 200, project = "D0_Sample")
raw.data_d1 <- Read10X(data.dir = raw.data_d1path)
so_d1 <- CreateSeuratObject(raw.data = raw.data_d1, min.cells = 3, min.genes = 200, project = "D1_Sample")
raw.data_d3 <- Read10X(data.dir = raw.data_d3path)
so_d3 <- CreateSeuratObject(raw.data = raw.data_d3, min.cells = 3,min.genes = 200, project = "D3_Sample")
#Merge Seurat Object 1 and 2 to create merged object s0_01
so_d0d1 <- MergeSeurat(object1 = so_d0, object2 = so_d1, add.cell.id1 = "D0", 
						add.cell.id2 = "D1", project = "D0D1")
**Error in MergeSeurat(object1 = so_d0, object2 = so_d1, add.cell.id1 = "D0",  : 
  Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names**
This code has worked fine before. Individual Seurat objects looks fine though.

**Comment by leonfodoulian** [comment] 2018-07-08 14:10
Hi,

This is a duplicate of multiple previous issues. Please check issue #549 for a fix.

Best,
Leon

**Comment by andrewwbutler** [comment] 2018-07-08 16:12
Updating to version 2.3.3 should resolve this issue.

**Closed by andrewwbutler** 2018-07-08 16:12 UTC
Labels: duplicate
