### ISSUE TITLE
SCTransform fails with error: no applicable method for 'as.sparse' applied to an object of class "c('double', 'numeric')"

### ISSUE THREAD

**Issue by nigiord** [satijalab/seurat#8912] opened 2024-05-18 10:41 UTC
I have the following Seurat object (v5)

```
An object of class Seurat 
23515 features across 10001 samples within 1 assay 
Active assay: RNA (23515 features, 0 variable features)
 1 layer present: counts
```
that I simply try to normalize using the following command

```R
seuratobj <-  Seurat::SCTransform(seuratobj, vst.flavor = "v2", vars.to.regress = "percent.mt", min_cells = 5, verbose = TRUE)
```

but after computing everything, it fails at the end with:

```
Error in UseMethod(generic = "as.sparse", object = x) :
no applicable method for 'as.sparse' applied to an object of class "c('double', 'numeric')"
```

I only have this issue with this particular object (it's one sample among dozens, after multiple filtering of barcodes). The issue is reproducible on multiple platform (HPC cluster, locally on linux, locally on osx-64). I tried to update Matrix, Seurat and SeuratObject with no effect. I think there might be something wrong with my object but I'm unsure what, it was build in my pipeline the same way then all the others. Googling the error did not help much, and I tried diving into Seurat and sctransform code base but no clue so far.

The object is only 50 MB so I created a link at the end of this issue to download it.

## Extra information

Complete log:
```
Running SCTransform on assay: RNA
Running SCTransform on layer: counts
vst.flavor='v2' set. Using model with fixed slope and excluding poisson genes.
Variance stabilizing transformation of count matrix of size 23515 by 10001
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 5000 cells
Found 168 outliers - those will be ignored in fitting/regularization step

Second step: Get residuals using fitted parameters for 23515 genes
Computing corrected count matrix for 23515 genes
Calculating gene attributes
Wall clock passed: Time difference of 35.39095 secs
Determine variable features
Regressing out percent.mt
  |======================================================================| 100%
Centering data matrix
  |======================================================================| 100%
Getting residuals for block 1(of 3) for counts dataset
Getting residuals for block 2(of 3) for counts dataset
Getting residuals for block 3(of 3) for counts dataset
Error in UseMethod(generic = "as.sparse", object = x) :
  no applicable method for 'as.sparse' applied to an object of class "c('double', 'numeric')"
```

sessionInfo()

```
R version 4.3.2 (2023-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Debian GNU/Linux trixie/sid

Matrix products: default
BLAS/LAPACK: <snip>.miniconda3/envs/scrnaseq-analysis/lib/libopenblasp-r0.3.27.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Paris
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Seurat_5.0.1       SeuratObject_5.0.1 sp_2.1-4          

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3          jsonlite_1.8.8             
  [3] magrittr_2.0.3              spatstat.utils_3.0-4       
  [5] zlibbioc_1.48.0             vctrs_0.6.5                
  [7] ROCR_1.0-11                 DelayedMatrixStats_1.24.0  
  [9] spatstat.explore_3.2-6      RCurl_1.98-1.14            
 [11] htmltools_0.5.8.1           S4Arrays_1.2.0             
 [13] SparseArray_1.2.2           sctransform_0.4.1          
 [15] parallelly_1.37.1           KernSmooth_2.23-24         
 [17] htmlwidgets_1.6.4           ica_1.0-3                  
 [19] plyr_1.8.9                  plotly_4.10.4              
 [21] zoo_1.8-12                  igraph_2.0.3               
 [23] mime_0.12                   lifecycle_1.0.4            
 [25] pkgconfig_2.0.3             Matrix_1.6-5               
 [27] R6_2.5.1                    fastmap_1.2.0              
 [29] GenomeInfoDbData_1.2.11     MatrixGenerics_1.14.0      
 [31] fitdistrplus_1.1-11         future_1.33.2              
 [33] shiny_1.8.1.1               digest_0.6.35              
 [35] colorspace_2.1-0            patchwork_1.2.0            
 [37] S4Vectors_0.40.2            tensor_1.5                 
 [39] RSpectra_0.16-1             irlba_2.3.5.1              
 [41] GenomicRanges_1.54.1        progressr_0.14.0           
 [43] fansi_1.0.6                 spatstat.sparse_3.0-3      
 [45] httr_1.4.7                  polyclip_1.10-6            
 [47] abind_1.4-5                 compiler_4.3.2             
 [49] fastDummies_1.7.3           MASS_7.3-60                
 [51] DelayedArray_0.28.0         tools_4.3.2                
 [53] lmtest_0.9-40               httpuv_1.6.15              
 [55] future.apply_1.11.2         goftest_1.2-3              
 [57] glmGamPoi_1.14.0            glue_1.7.0                 
 [59] nlme_3.1-164                promises_1.3.0             
 [61] grid_4.3.2                  Rtsne_0.17                 
 [63] cluster_2.1.6               reshape2_1.4.4             
 [65] generics_0.1.3              gtable_0.3.5               
 [67] spatstat.data_3.0-4         tidyr_1.3.1                
 [69] data.table_1.15.2           utf8_1.2.4                 
 [71] XVector_0.42.0              BiocGenerics_0.48.1        
 [73] spatstat.geom_3.2-9         RcppAnnoy_0.0.22           
 [75] ggrepel_0.9.5               RANN_2.6.1                 
 [77] pillar_1.9.0                stringr_1.5.1              
 [79] spam_2.10-0                 RcppHNSW_0.6.0             
 [81] later_1.3.2                 splines_4.3.2              
 [83] dplyr_1.1.4                 lattice_0.22-6             
 [85] survival_3.6-4              deldir_2.0-4               
 [87] tidyselect_1.2.1            miniUI_0.1.1.1             
 [89] pbapply_1.7-2               gridExtra_2.3              
 [91] IRanges_2.36.0              SummarizedExperiment_1.32.0
 [93] scattermore_1.2             stats4_4.3.2               
 [95] Biobase_2.62.0              matrixStats_1.0.0          
 [97] stringi_1.8.4               lazyeval_0.2.2             
 [99] codetools_0.2-20            tibble_3.2.1               
[101] cli_3.6.2                   uwot_0.1.16                
[103] xtable_1.8-4                reticulate_1.36.1          
[105] munsell_0.5.1               Rcpp_1.0.12                
[107] GenomeInfoDb_1.38.1         globals_0.16.3             
[109] spatstat.random_3.2-3       png_0.1-8                  
[111] parallel_4.3.2              ggplot2_3.5.0              
[113] dotCall64_1.1-1             sparseMatrixStats_1.14.0   
[115] bitops_1.0-7                listenv_0.9.1              
[117] viridisLite_0.4.2           scales_1.3.0               
[119] ggridges_0.5.6              leiden_0.4.3.1             
[121] purrr_1.0.2                 crayon_1.5.2               
[123] rlang_1.1.3                 cowplot_1.1.3    
```

## Reproducible example

Download the Rds object [49.3 MB]  [here](https://uncloud.univ-nantes.fr/index.php/s/mfX294iEsqgmTr5) and run:
```r
library(Seurat)
seuratobj <- readRDS("DUMMYNAME.scrnaseq.filtered-only-tumor-cells.seurat-object.Rds")
Seurat::SCTransform(seuratobj, vst.flavor = "v2", vars.to.regress = "percent.mt", min_cells = 5, verbose = TRUE)
```

Any help would be greatly appreciated!

Cheers,
−Nils

**Comment by zskylarli** [comment] 2024-05-31 17:39
Hi! I tried to debug your object, and it seems like because there are exactly 10001 cells, the last single cell is being put into a separate third block when calculating residuals, since the number of subsampled cells used to build the nonbinomial regression is set to 5000 by default. If you just set the `ncells` argument to another number, i.e. 3000, this should be fixed. Let me know if you have additional questions!

**Closed by zskylarli** 2024-05-31 17:39 UTC
Labels: bug

**Comment by JoelMoro** [comment] 2025-01-09 16:05
Hi All,

I got here for the same error message but this time, when going through label transfer function: FindTransferAnchors.

 **Simple code**

```
DefaultAssay(obj1) <- "RNA"
DefaultAssay(obj2) <- "RNA"

transfer_anchors <- FindTransferAnchors(
  reference = obj1,
  query = obj2,
  reference.reduction = "harmony",
  recompute.residuals = FALSE,
  dims = 1:50
)
```

 **Retrieves**

```
Projecting cell embeddings
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': no applicable method for 'as.sparse' applied to an object of class "c('double', 'numeric')"
```

Interestingly, if I try to use standard pca reduction instead of harmony it works without any problem. For sure, using harmony reduction has worked for me in the past plenty of times with Seurat v5.
Also, it is quite different to the problem with SCTransform, given that it doesn't rely on ncells from my knowledge

**Extra information**

The objects preview

```
obj1
obj2
```
```
An object of class Seurat 
13448 features across 21488 samples within 1 assay 
Active assay: RNA (13448 features, 2000 variable features)
 3 layers present: data, counts, scale.data
 4 dimensional reductions calculated: pca, umap, harmony, umap.harmony

An object of class Seurat 
15555 features across 12234 samples within 1 assay 
Active assay: RNA (15555 features, 1313 variable features)
 3 layers present: counts, data, scale.data
 5 dimensional reductions calculated: pca, harmony, umap
```

It is also intriguing why doing it reversely doesn't end up in an error (meaing swapping query and reference).

```
transfer_anchors <- FindTransferAnchors(
  reference = obj2,
  query = obj1,
  reference.reduction = "harmony",
  recompute.residuals = FALSE,
  dims = 1:50
)

```
```
Projecting cell embeddings
Finding neighborhoods
Finding anchors
	Found 621 anchors
```
### Session info

```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.04

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] parallel  grid      stats4    stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] doParallel_1.0.17                 iterators_1.0.14                  foreach_1.5.2                     Pando_1.1.1                      
 [5] presto_1.0.0                      Rcpp_1.0.13-1                     BSgenome.Hsapiens.UCSC.hg38_1.4.5 BSgenome_1.66.3                  
 [9] rtracklayer_1.58.0                Biostrings_2.66.0                 XVector_0.38.0                    ShinyCell_2.1.0                  
[13] RColorBrewer_1.1-3                glue_1.8.0                        gridExtra_2.3                     R.utils_2.12.3                   
[17] R.oo_1.27.0                       R.methodsS3_1.8.2                 hdf5r_1.3.11                      Matrix_1.6-4                     
[21] data.table_1.16.2                 scico_1.5.0                       scCustomize_2.1.2                 clustree_0.5.1                   
[25] ggraph_2.2.1                      DoubletFinder_2.0.4               SingleCellExperiment_1.20.1       SummarizedExperiment_1.28.0      
[29] Biobase_2.58.0                    GenomicRanges_1.50.2              GenomeInfoDb_1.34.9               IRanges_2.32.0                   
[33] S4Vectors_0.36.2                  BiocGenerics_0.44.0               MatrixGenerics_1.10.0             matrixStats_1.1.0                
[37] Signac_1.14.0                     sceasy_0.0.7                      reticulate_1.40.0                 Seurat_5.1.0                     
[41] SeuratObject_5.0.2                sp_2.1-4                          orthogene_1.4.2                   lubridate_1.9.3                  
[45] forcats_1.0.0                     stringr_1.5.1                     dplyr_1.1.4                       purrr_1.0.2                      
[49] readr_2.1.5                       tidyr_1.3.1                       tibble_3.2.1                      ggplot2_3.5.1                    
[53] tidyverse_2.0.0                  

loaded via a namespace (and not attached):
  [1] ggprism_1.0.5             scattermore_1.2           bit64_4.5.2               knitr_1.49                irlba_2.3.5.1             DelayedArray_0.24.0      
  [7] RCurl_1.98-1.16           generics_0.1.3            RhpcBLASctl_0.23-42       callr_3.7.6               cowplot_1.1.3             usethis_3.0.0            
 [13] RANN_2.6.2                future_1.34.0             ggpointdensity_0.1.0      bit_4.5.0                 tzdb_0.4.0                spatstat.data_3.1-4      
 [19] httpuv_1.6.15             viridis_0.6.5             xfun_0.49                 hms_1.1.3                 jquerylib_0.1.4           babelgene_22.9           
 [25] evaluate_1.0.1            promises_1.3.2            restfulr_0.0.15           fansi_1.0.6               readxl_1.4.3              igraph_2.1.1             
 [31] htmlwidgets_1.6.4         spatstat.geom_3.3-4       ellipsis_0.3.2            paletteer_1.6.0           RSpectra_0.16-2           ggpubr_0.6.0             
 [37] backports_1.5.0           gprofiler2_0.2.3          sparseMatrixStats_1.10.0  deldir_2.0-4              vctrs_0.6.5               remotes_2.5.0            
 [43] ROCR_1.0-11               abind_1.4-8               cachem_1.1.0              withr_3.0.2               ggforce_0.4.2             grr_0.9.5                
 [49] progressr_0.15.1          sctransform_0.4.1         GenomicAlignments_1.34.1  treeio_1.22.0             goftest_1.2-3             cluster_2.1.4            
 [55] ape_5.8                   dotCall64_1.2             lazyeval_0.2.2            crayon_1.5.3              spatstat.explore_3.3-3    pkgconfig_2.0.3          
 [61] labeling_0.4.3            tweenr_2.0.3              pkgload_1.4.0             nlme_3.1-159              vipor_0.4.7               devtools_2.4.5           
 [67] pals_1.9                  rlang_1.1.4               globals_0.16.3            lifecycle_1.0.4           miniUI_0.1.1.1            fastDummies_1.7.4        
 [73] dichromat_2.0-0.1         ggrastr_1.0.2             cellranger_1.1.0          polyclip_1.10-7           RcppHNSW_0.6.0            lmtest_0.9-40            
 [79] aplot_0.2.3               carData_3.0-5             zoo_1.8-12                beeswarm_0.4.0            processx_3.8.4            ggridges_0.5.6           
 [85] GlobalOptions_0.1.2       rjson_0.2.23              png_0.1-8                 viridisLite_0.4.2         bitops_1.0-9              KernSmooth_2.23-20       
 [91] spam_2.11-0               shape_1.4.6.1             spatstat.univar_3.1-1     parallelly_1.39.0         spatstat.random_3.3-2     rstatix_0.7.2            
 [97] gridGraphics_0.5-1        ggsignif_0.6.4            scales_1.3.0              memoise_2.0.1             magrittr_2.0.3            plyr_1.8.9               
[103] ica_1.0-3                 zlibbioc_1.44.0           compiler_4.2.1            BiocIO_1.8.0              fitdistrplus_1.2-1        homologene_1.4.68.19.3.27
[109] Rsamtools_2.14.0          snakecase_0.11.1          cli_3.6.3                 urlchecker_1.0.1          listenv_0.9.1             ps_1.8.1                 
[115] patchwork_1.3.0.9000      pbapply_1.7-2             Formula_1.2-5             MASS_7.3-58.1             tidyselect_1.2.1          stringi_1.8.4            
[121] yaml_2.3.10               ggrepel_0.9.6             sass_0.4.9                fastmatch_1.1-4           tools_4.2.1               timechange_0.3.0         
[127] future.apply_1.11.3       circlize_0.4.16           rstudioapi_0.17.1         janitor_2.2.0             farver_2.1.2              Rtsne_0.17               
[133] digest_0.6.37             BiocManager_1.30.25       shiny_1.9.1               car_3.1-3                 broom_1.0.7               harmony_1.2.1            
[139] later_1.4.1               RcppAnnoy_0.0.22          httr_1.4.7                colorspace_2.1-1          XML_3.99-0.17             fs_1.6.5                 
[145] tensor_1.5                splines_4.2.1             uwot_0.2.2                yulab.utils_0.1.7         RcppRoll_0.3.1            rematch2_2.1.2           
[151] tidytree_0.4.6            spatstat.utils_3.1-1      graphlayouts_1.2.1        mapproj_1.2.11            renv_1.0.5                ggplotify_0.1.2          
[157] sessioninfo_1.2.2         plotly_4.10.4             xtable_1.8-4              jsonlite_1.8.9            ggtree_3.13.1             tidygraph_1.3.1          
[163] ggfun_0.1.6               R6_2.5.1                  profvis_0.3.8             pillar_1.9.0              htmltools_0.5.8.1         mime_0.12                
[169] fastmap_1.2.0             BiocParallel_1.32.6       codetools_0.2-19          maps_3.4.2.1              pkgbuild_1.4.4            utf8_1.2.4               
[175] lattice_0.20-45           bslib_0.8.0               spatstat.sparse_3.1-0     curl_6.0.1                ggbeeswarm_0.7.2          leiden_0.4.3.1           
[181] survival_3.4-0            rmarkdown_2.29            desc_1.4.3                munsell_0.5.1             GenomeInfoDbData_1.2.9    reshape2_1.4.4           
[187] gtable_0.3.6    
```

Please let me know if it is better that I open a new thread. I figured that, since the problems are related, it makes sense to answer here. Thanks in advance for your collaboration. If you need more from my side let me know.

**Comment by JoelMoro** [comment] 2025-01-10 09:24
Hi again,

I have realised after checking the harmony reduction that, for some reason, obj2 do harmony feture.loadings is empty, which relates to issue [https://github.com/satijalab/seurat/issues/8402](url).

However in my case, I use harmony as follows without any major problem:

```
mouse2 <- IntegrateLayers(
  object = mouse2, method = HarmonyIntegration,
  orig.reduction = "pca", new.reduction = "harmony",
  verbose = FALSE)
```

Is thereareason why feature.loadings is empty, which most likely derives in the earlier mentioned error? In the other object the harmony reduction does have the loadings without a problem

Thanks.
