### ISSUE TITLE
Error to  Read10X file

### ISSUE THREAD

**Issue by JayalalKJ** [satijalab/seurat#2221] opened 2019-10-18 09:13 UTC
[Error in scan(file, nmax = nz, quiet = TRUE, what = list(i = integer(), : scan() expected 'an integer', got '2Âªø'
SHOW TRACEBACK
3.
scan(file, nmax = nz, quiet = TRUE, what = list(i = integer(), j = integer(), x = numeric()))
2.
readMM(file = matrix.loc)
1.
Read10X(data.dir = "C:/Users/G19678-016573_SampleID_2_Mln28_1")](url)

**Comment by timoast** [comment] 2019-10-18 18:31
Hi, can you describe what the issue is and provide a reproducible example if possible? Can you also provide the output of `sessionInfo()`?

**Comment by JayalalKJ** [comment] 2019-10-18 18:42
> Hi, can you describe what the issue is and provide a reproducible example if possible? Can you also provide the output of `sessionInfo()`?

It was a corrupted file(I don"t why it got corrupted_I was re-running same data for more than 100 times in R notebook). But, the problem got solved after current file replacement with the first version).

**Comment by JayalalKJ** [comment] 2019-10-18 18:53
> Hi, can you describe what the issue is and provide a reproducible example if possible? Can you also provide the output of `sessionInfo()`?
I was running the same R Notebook file. It was reading well but after the many repeats, I got this issue. I don"t why? But, The problem got solved once I replaced with the problematic old version of "mm10_withIgTCRgenes" file

**Comment by timoast** [comment] 2019-10-18 19:34
Ok if this solved then and I'll close the issue

**Closed by timoast** 2019-10-18 19:34 UTC
