### ISSUE TITLE
invalid class “LogMap” object: Rownames must be supplied When trying to create a Seurat object

### ISSUE THREAD

**Issue by Sharonbdr** [satijalab/seurat#8105] opened 2023-11-28 21:47 UTC
I've been trying to create a Seurat object:

`nuc.seurat <- CreateSeuratObject(counts = as.matrix(UMIs), project = i, min.cells = 3, min.features = 200)`

however I keep on getting the following error:

```
Error in validObject(.Object) : 
  invalid class “LogMap” object: Rownames must be supplied
```

The weird thing is, just a day ago it worked completely fine with the exact same pipline. UMIs in this case is a count dataframe, and it has rownames (despite what the error is suggesting):

```
         Sample1 Sample2 Sample3 Sample4
A1BG          21       0       6       1
A1BG-AS1       2       0       0       0
A1CF           9       3       8       2
A2M           17       0       4       0
A2M-AS1        0       0       0       0
```
(UMIs is a lot larger this is just a subset)

I do not have a lot of experience in R or using Seurat so any input would help! Thank you!

I have tried removing some of the input args of CreateSeuratObject and that did work:

`nuc.seurat <- CreateSeuratObject(counts = as.matrix(UMIs), project = i, min.cells = 3)`

However, filtering by min.features at this step reduces object size and eliminates other error down the line (NA data and so on). So it's not a good enough solution.

Also, trying to downgrade Matrix produces an incompatibility error so I cannot run CreateSeuratObject .

Seurat v 5.0.1
Matrix v 1.6-3

**Comment by longmanz** [comment] 2023-12-01 21:22
Hi,
Sorry. It is indeed a Matrix issue and has been reported multiple time. When you say you cannot downgrade Matrix, what kind of error message did you receive? 
`remotes::install_version("Matrix", version = "1.6-1.1")`

**Comment by longmanz** [comment] 2023-12-01 22:14
Hi, 
This is strange. Can you try re-install Seurat and SeuratObject from CRAN directly? The latest SeuratObject (v5.0.1) will install the latest Matrix (v.1.6-4) will be installed. This should no longer cause any issue. 
Can you check your `as.matrix(UMIs)` to see if there is really enough min.features (>=200) ?

**Comment by longmanz** [comment] 2023-12-15 21:23
Hi,
This is really strange and we cannot reproduce it from our end. Glad that the workaround of not using min.features works. If possible, please try using the latest Matrix package and try again. Or if you can provide us a minimal reproducible dataset (either your own data or any data from our vignette) it will be very helpful.

**Comment by stupidstupidstupidstupid** [comment] 2024-01-02 10:57
Hello, seurat. I met the same question too. Here is my code and data:

CODE:
#### Preprocessing the data! #####
# Loading in the reference data & creating Seurat object #
ref_counts <- read.csv(paste0(data_dir, 'Fetal-Brain3_dge.txt'), row.names=1)
ref_meta <- read.csv(paste0(data_dir, 'Fetal-Brain3_Anno.csv'), row.names=1)
print(all(rownames(ref_meta)==colnames(ref_counts)))
ref_seurat <- CreateSeuratObject(ref_counts, meta.data=ref_meta)

DATA:
#Fetal-Brain3_dge.txt:    https://bis.zju.edu.cn/HCL/data/DGE/Fetal-Brain3_dge.txt.gz
#Fetal-Brain3_Anno.csv: https://figshare.com/articles/HCL_DGE_Data/7235471 -- 
                                      annotation_rmbatch_data_revised417.zip --
                                      Fetal-Brain3_rmbatchAnno.csv

ERROR MESSAGE:
#### Preprocessing the data! #####
> # Loading in the reference data & creating Seurat object #
> ref_counts <- read.csv(paste0(data_dir, 'Fetal-Brain3_dge.txt'), row.names=1)
> ref_meta <- read.csv(paste0(data_dir, 'Fetal-Brain3_Anno.csv'), row.names=1)
> print(all(rownames(ref_meta)==colnames(ref_counts)))
[1] TRUE
> ref_seurat <- CreateSeuratObject(ref_counts, meta.data=ref_meta)
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Data is of class data.frame. Coercing to dgCMatrix.
Error in validObject(.Object) : 
  invalid class “LogMap” object: Rownames must be supplied 

I would be very appreciate if you can help. @longmanz

**Comment by stupidstupidstupidstupid** [comment] 2024-01-02 12:09
[Fetal-Brain3_Anno.csv](https://github.com/satijalab/seurat/files/13809795/Fetal-Brain3_Anno.csv)

**Comment by stupidstupidstupidstupid** [comment] 2024-01-02 12:09
[Fetal-Brain3_dge.txt.gz](https://github.com/satijalab/seurat/files/13809797/Fetal-Brain3_dge.txt.gz)

**Comment by longmanz** [comment] 2024-01-12 20:58
Hi,
I am closing this issue for now. I will re-open if the issue persists.

**Closed by longmanz** 2024-01-12 20:58 UTC
Labels: bug

**Comment by aaltulea** [comment] 2024-06-27 13:49
This table here can produce this error if you still want to investigate the issue. It is publicly available under GSM5140521

[GSM5140521_Young-2-ProxCol.csv.gz](https://github.com/user-attachments/files/16014997/GSM5140521_Young-2-ProxCol.csv.gz)

```
library(tidyverse)
library(Seurat)
table = read.csv("GSE168448_ageing_colon/data/GSM5140521_Young-2-ProxCol.csv.gz") %>% column_to_rownames("X")
seurat = CreateSeuratObject(table, min.cells = 20, min.features = 50)
```
Error in validObject(.Object) (test.R#4): invalid class “LogMap” object: Rownames must be supplied

**Comment by szhaoaf** [comment] 2024-07-09 04:38
I have seen the same error and it turns out to be your min.features parameters is too high, thus leading to no filtered features (genes of your rownames) detected. Try to low down your min.features = 1. And the error will be resolved.

Bests.

**Comment by chris257-ux** [comment] 2024-08-17 10:31
I meet the same question. So I check the data and find that there isn't really any cell with enough min.features (>=200) .

**Comment by RodrigoGM** [comment] 2024-09-06 19:04
Hi, this issue was posted on Stackoverflow, I've posted an answer there.  Here is the link to the post:

https://stackoverflow.com/questions/77503371/invalid-class-logmap-object-rownames-must-be-supplied-when-trying-to-create-a
