### ISSUE TITLE
Seurat v.3.0 CreateAssayObject error

### ISSUE THREAD

**Issue by lquek** [satijalab/seurat#1185] opened 2019-02-28 11:23 UTC
Hi,
I using Seurat v.3.0 to analyse CITE-seq data.  My gene expression (GEX) data matrix was generated by Cellranger 3.0 and the ADT matrix by CITE-seq count.
I have generated a Seurat object with my gene expression data, and now want to add the ADT data:

OX3018D5GEX[["ADT"]] <- CreateAssayObject(counts = OX3018D5.ADT)
Error: All cells in the object being added must match the cells in this object.

The cell barcodes from the Cellranger matrix was used to as a 'whitelists' for CITE-seq count, so the cells should be identical (I checked the rows and columns: and both the gene expression and ADT datasets have the same number of cells), but not arranged in the same order.

Can you please advise?  Thanks.

**Comment by mojaveazure** [comment] 2019-02-28 21:06
Hi @lquek,

Seurat v3 will automatically rearrange cells in assays if all the cells are named exactly the same. What's the output if you run the following?

```R
ncol(x = OX3018D5GEX) == ncol(x = CreateAssayObject(counts = OX3018D5.ADT)) && all(colnames(x = OX3018D5GEX) %in% colnames(x = CreateAssayObject(counts = OX3018D5.ADT)))
```

**Comment by lquek** [comment] 2019-02-28 21:17
Hi, thanks for getting back to me.  
 ncol(x = OX3018D5GEX) == ncol(x = CreateAssayObject(counts = OX3018D5.ADT)) && all(colnames(x = OX3018D5GEX) %in% colnames(x = CreateAssayObject(counts = OX3018D5.ADT)))
[1] TRUE

so it looks like they are the same.  I wonder what the problem is ?

**Comment by mojaveazure** [comment] 2019-02-28 21:50
Huh, interesting. Are you using a relatively recent version of Seurat v3? Reordering has been present since  August 2018 (commit 6b2aaed). Can you try installing the latest version and if it's still not working, can you send me your data so we can debug this?

**Comment by lquek** [comment] 2019-02-28 22:08
The version is 3.0.0.9000 (Date: 2018-10-31), and I'm running it using R 3.5.1.  Is this the version you of Seurat you suggest?

**Comment by mojaveazure** [comment] 2019-02-28 22:11
Try running `devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')` from a fresh R session (no packages loaded, no data in your environment). Then, try adding your ADT data again.

**Comment by lquek** [comment] 2019-02-28 22:31
Do I have to re-create the gene expression Seurat object?

**Comment by lquek** [comment] 2019-02-28 22:33
Hmm I have a problem: I have done as you mentioned above, and now:
> library(Seurat)
Error in library(Seurat) : there is no package called ‘Seurat’

**Comment by lquek** [comment] 2019-02-28 22:34
There was an installation error:
Error: (converted from warning) cannot remove prior installation of package ‘rlang’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by notimenocall** [comment] 2019-04-10 15:28
I encounter the exact same issue here. Did you figure out how to fix it? Thank you!

**Comment by mojaveazure** [comment] 2019-04-10 16:13
@lquek, I am unable to reproduce your installation errors. Try reinstalling `devtools`/`remotes` and then reinstalling Seurat v3. Please note, whenever you reinstall a package, you should always do it from a fresh R session. R is not good at hot-swapping packages, so you always want to install packages without anything else loaded.

@notimenocall What version of Seurat v3 are you using? This should be fixed in the latest versions of Seurat v3.

**Comment by notimenocall** [comment] 2019-04-10 20:34
@mojaveazure Thanks for your response. It was v3 but I just reinstalled it which fixes the problem.

**Closed** 2019-04-19 14:39 UTC

**Comment by duocang** [comment] 2021-09-01 00:06
@mojaveazure 
Hi.

I have met this issue when `SCTransform` a `Seurat` object from `sebset`: [Please check the seurat object](https://1drv.ms/u/s!AtjLM4-mbBLkx9R6M97Egk08QdXZgQ?e=F9KtCa)

![image](https://user-images.githubusercontent.com/14146871/131590929-cf30a2e0-ce12-404f-8625-ffa2746640ac.png)
