### ISSUE TITLE
Seurat after running cellranger multi

### ISSUE THREAD

**Issue by mbartl13** [satijalab/seurat#5369] opened 2021-12-07 16:32 UTC
We ran several samples with 5'GEX, BCR, and TCR libraries using cellranger multi (all processed at once). But when loading into Seurat, we were unsure of how to split out by sample, is there a Seurat command we can use to parse by sample?

**Comment by samuel-marsh** [comment] 2021-12-08 13:18
Hi,

Not member of the dev team but hopefully can be helpful.  So if you ran all of the samples in the same multi run then they should have had barcode suffixes added (in the order of the samples on the csv that you provided to multi).  So then when importing and creating your Seurat object simply add 2 extra parameters and Seurat will split samples in the `orig.ident` column of the meta.data slot.

```
# MATRIX is the count matrix you imported into R.
obj <- CreateSeuratObject(counts = MATRIX, names.field = 2, names.delim = "-")
```

Best,
Sam

**Comment by mbartl13** [comment] 2021-12-08 16:31
Thanks Sam!
________________________________

**Comment by mbartl13** [comment] 2021-12-08 16:47
Hey Sam, I tried this approach but it labeled all as barcode-1? Attached is the csv for cellranger if that's useful.


________________________________

**Comment by samuel-marsh** [comment] 2021-12-08 17:16
I don't see attached file but that's ok.  If you run this code on your raw data matrix does it return any values?

`cells <- grep(pattern = "$-2", x = colnames(x = MATRIX), value = TRUE)`

Best,
Sam

**Comment by mbartl13** [comment] 2021-12-08 21:45
Thanks Sam,

I get:

> cells <- grep(pattern = "$-2", x = colnames(x = matrix), value = TRUE)
> cells
character(0)

________________________________

**Comment by samuel-marsh** [comment] 2021-12-09 14:30
Ok so that means that the files from cell ranger don't contain any other suffixes.  Did you run all the samples together on multi?  Did you specify different samples on the samplesheet?

Best,
Sam

**Comment by mbartl13** [comment] 2021-12-09 15:06
Hey Sam, 
I ran all the samples together in one run. I was able to split.by("ident") but it gave a different number than I was anticipating (3 samples but the ident number is 
`> SplitObject(seurat_object_brain, split.by = "ident")
$`6`
An object of class Seurat 
32388 features across 1338 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`0`
An object of class Seurat 
32388 features across 4426 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`5`
An object of class Seurat 
32388 features across 1630 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`1`
An object of class Seurat 
32388 features across 3867 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`22`
An object of class Seurat 
32388 features across 250 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`3`
An object of class Seurat 
32388 features across 2047 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`9`
An object of class Seurat 
32388 features across 1007 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`14`
An object of class Seurat 
32388 features across 621 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`13`
An object of class Seurat 
32388 features across 678 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`17`
An object of class Seurat 
32388 features across 450 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`28`
An object of class Seurat 
32388 features across 104 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`12`
An object of class Seurat 
32388 features across 679 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`2`
An object of class Seurat 
32388 features across 2692 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`19`
An object of class Seurat 
32388 features across 317 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`25`
An object of class Seurat 
32388 features across 183 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`4`
An object of class Seurat 
32388 features across 1816 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`11`
An object of class Seurat 
32388 features across 781 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`20`
An object of class Seurat 
32388 features across 300 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`21`
An object of class Seurat 
32388 features across 257 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`15`
An object of class Seurat 
32388 features across 602 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`10`
An object of class Seurat 
32388 features across 860 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`7`
An object of class Seurat 
32388 features across 1271 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`8`
An object of class Seurat 
32388 features across 1009 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`16`
An object of class Seurat 
32388 features across 458 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`18`
An object of class Seurat 
32388 features across 389 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`26`
An object of class Seurat 
32388 features across 168 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`23`
An object of class Seurat 
32388 features across 233 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`24`
An object of class Seurat 
32388 features across 191 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap

$`27`
An object of class Seurat 
32388 features across 127 samples within 2 assays 
Active assay: RNA (32285 features, 2000 variable features)
 1 other assay present: Protein
 2 dimensional reductions calculated: pca, umap`

[Multi_config_sinv_brain.csv](https://github.com/satijalab/seurat/files/7685879/Multi_config_sinv_brain.csv)

**Comment by mbartl13** [comment] 2021-12-09 16:25
Correct- this is from the outs>multi>counts>matrix
________________________________

**Comment by samuel-marsh** [comment] 2021-12-10 13:14
So not entirely sure where the issue is.  When I download multi example from 10X (https://www.10xgenomics.com/resources/datasets/human-b-cells-from-a-healthy-donor-pre-and-post-flu-vaccination-v-2-2-standard-5-0-0) I get the proper barcode suffixes and ability to split samples when importing.  Therefore it would appear this is issue with Cell Ranger output rather than Seurat.

**Comment by mbartl13** [comment] 2021-12-10 13:36
Thanks Sam, will see if 10x has suggestions.
________________________________

**Comment by timoast** [comment] 2021-12-17 17:17
Closing this since it sounds like an issue with the input data rather than Seurat

**Closed by timoast** 2021-12-17 17:17 UTC
