### ISSUE TITLE
No output when drawing heatmap using cluster markers

### ISSUE THREAD

**Issue by dahun73** [satijalab/seurat#5921] opened 2022-05-06 03:11 UTC
Hello everyone!

I'm not sure whether I upload this question here. I extracted cluster marker gens to draw heatmap but there is no output(actually, only white screen).
![image](https://user-images.githubusercontent.com/52641420/167058639-a11b287b-0d61-4c95-9edc-cab51bd2dde7.png)

When I subset 1000 cells, however, I succeed to draw heatmap. I don't know the reason why heatmap of total cell could not be drawn....

Thank you for in advance!!

```r
pdf("heatmap_for_clu0_markers.pdf",height = 50,width = 50)
DoHeatmap(inte.combined,features = clu0_markers$gene,assay = 'integrated')+NoLegend()
dev.off()
```

```r
R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=ko_KR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=ko_KR.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=ko_KR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=ko_KR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggrepel_0.9.1               ggfortify_0.4.14            SCINA_1.2.0                 gplots_3.1.1               
 [5] MASS_7.3-57                 metap_1.8                   multtest_2.50.0             SeuratObject_4.0.4         
 [9] Seurat_4.1.0                devtools_2.4.3              usethis_2.1.5               scRNAseq_2.8.0             
[13] RColorBrewer_1.1-3          pheatmap_1.0.12             SingleR_1.8.1               celldex_1.4.0              
[17] SingleCellExperiment_1.16.0 SummarizedExperiment_1.24.0 Biobase_2.54.0              GenomicRanges_1.46.1       
[21] GenomeInfoDb_1.30.1         IRanges_2.28.0              S4Vectors_0.32.4            BiocGenerics_0.40.0        
[25] MatrixGenerics_1.6.0        matrixStats_0.62.0          ggpubr_0.4.0                ggsignif_0.6.3             
[29] ggplot2_3.3.5               cowplot_1.1.1               patchwork_1.1.1             dplyr_1.0.8                

loaded via a namespace (and not attached):
  [1] rappdirs_0.3.3                rtracklayer_1.54.0            scattermore_0.8               tidyr_1.2.0                  
  [5] bit64_4.0.5                   multcomp_1.4-18               irlba_2.3.5                   DelayedArray_0.20.0          
  [9] data.table_1.14.2             rpart_4.1.16                  KEGGREST_1.34.0               RCurl_1.98-1.6               
 [13] AnnotationFilter_1.18.0       generics_0.1.2                GenomicFeatures_1.46.5        ScaledMatrix_1.2.0           
 [17] TH.data_1.1-0                 callr_3.7.0                   RSQLite_2.2.12                RANN_2.6.1                   
 [21] future_1.25.0                 bit_4.0.4                     mutoss_0.1-12                 spatstat.data_2.2-0          
 [25] xml2_1.3.3                    httpuv_1.6.5                  ggsci_2.9                     assertthat_0.2.1             
 [29] viridis_0.6.2                 hms_1.1.1                     promises_1.2.0.1              fansi_1.0.3                  
 [33] restfulr_0.0.13               progress_1.2.2                caTools_1.18.2                dbplyr_2.1.1                 
 [37] tmvnsim_1.0-2                 igraph_1.3.0                  DBI_1.1.2                     htmlwidgets_1.5.4            
 [41] spatstat.geom_2.4-0           purrr_0.3.4                   ellipsis_0.3.2                RSpectra_0.16-1              
 [45] backports_1.4.1               biomaRt_2.50.3                deldir_1.0-6                  sparseMatrixStats_1.6.0      
 [49] vctrs_0.4.1                   remotes_2.4.2                 ensembldb_2.18.4              ROCR_1.0-11                  
 [53] abind_1.4-5                   cachem_1.0.6                  withr_2.5.0                   sctransform_0.3.3            
 [57] GenomicAlignments_1.30.0      prettyunits_1.1.1             mnormt_2.0.2                  goftest_1.2-3                
 [61] cluster_2.1.3                 ExperimentHub_2.2.1           lazyeval_0.2.2                crayon_1.5.1                 
 [65] labeling_0.4.2                pkgconfig_2.0.3               qqconf_1.2.3                  vipor_0.4.5                  
 [69] nlme_3.1-157                  pkgload_1.2.4                 ProtGenerics_1.26.0           rlang_1.0.2                  
 [73] globals_0.14.0                lifecycle_1.0.1               miniUI_0.1.1.1                sandwich_3.0-1               
 [77] filelock_1.0.2                BiocFileCache_2.2.1           mathjaxr_1.6-0                rsvd_1.0.5                   
 [81] AnnotationHub_3.2.2           rprojroot_2.0.3               polyclip_1.10-0               lmtest_0.9-40                
 [85] Matrix_1.4-1                  carData_3.0-5                 zoo_1.8-10                    beeswarm_0.4.0               
 [89] ggridges_0.5.3                processx_3.5.3                png_0.1-7                     viridisLite_0.4.0            
 [93] rjson_0.2.21                  bitops_1.0-7                  KernSmooth_2.23-20            Biostrings_2.62.0            
 [97] blob_1.2.3                    DelayedMatrixStats_1.16.0     stringr_1.4.0                 parallelly_1.31.1            
[101] spatstat.random_2.2-0         rstatix_0.7.0                 beachmat_2.10.0               scales_1.2.0                 
[105] memoise_2.0.1                 magrittr_2.0.3                plyr_1.8.7                    ica_1.0-2                    
[109] zlibbioc_1.40.0               compiler_4.1.3                BiocIO_1.4.0                  plotrix_3.8-2                
[113] fitdistrplus_1.1-8            Rsamtools_2.10.0              cli_3.2.0                     XVector_0.34.0               
[117] listenv_0.8.0                 pbapply_1.5-0                 ps_1.7.0                      mgcv_1.8-40                  
[121] tidyselect_1.1.2              stringi_1.7.6                 yaml_2.3.5                    BiocSingular_1.10.0          
[125] grid_4.1.3                    tools_4.1.3                   future.apply_1.8.1            parallel_4.1.3               
[129] rstudioapi_0.13               gridExtra_2.3                 farver_2.1.0                  Rtsne_0.16                   
[133] digest_0.6.29                 BiocManager_1.30.17           shiny_1.7.1                   Rcpp_1.0.8.3                 
[137] car_3.0-12                    broom_0.8.0                   scuttle_1.4.0                 BiocVersion_3.14.0           
[141] later_1.3.0                   RcppAnnoy_0.0.19              httr_1.4.2                    AnnotationDbi_1.56.2         
[145] Rdpack_2.3                    colorspace_2.0-3              brio_1.1.3                    XML_3.99-0.9                 
[149] fs_1.5.2                      tensor_1.5                    reticulate_1.24               splines_4.1.3                
[153] uwot_0.1.11                   sn_2.0.2                      spatstat.utils_2.3-0          scater_1.22.0                
[157] plotly_4.10.0                 sessioninfo_1.2.2             xtable_1.8-4                  jsonlite_1.8.0               
[161] testthat_3.1.3                R6_2.5.1                      TFisher_0.2.0                 pillar_1.7.0                 
[165] htmltools_0.5.2               mime_0.12                     glue_1.6.2                    fastmap_1.1.0                
[169] BiocParallel_1.28.3           BiocNeighbors_1.12.0          interactiveDisplayBase_1.32.0 codetools_0.2-18             
[173] pkgbuild_1.3.1                mvtnorm_1.1-3                 utf8_1.2.2                    lattice_0.20-45              
[177] spatstat.sparse_2.1-1         tibble_3.1.6                  numDeriv_2016.8-1.1           ggbeeswarm_0.6.0             
[181] curl_4.3.2                    leiden_0.3.9                  gtools_3.9.2                  limma_3.50.3                 
[185] survival_3.3-1                desc_1.4.1                    munsell_0.5.0                 GenomeInfoDbData_1.2.7       
[189] reshape2_1.4.4                gtable_0.3.0                  rbibutils_2.2.8               spatstat.core_2.4-2          
```

**Comment by yuhanH** [comment] 2022-05-20 18:39
Hi, 
could you send me a reproducible example?

**Comment by yuhanH** [comment] 2022-06-17 18:51
Since I didn't new reply for a long time, I will close this issue first.

**Closed by yuhanH** 2022-06-17 18:51 UTC
Labels: more-information-needed
