### ISSUE TITLE
Re-Run SCT leads to error in integrate layer.

### ISSUE THREAD

**Issue by pdimitron** [satijalab/seurat#8224] opened 2023-12-26 21:03 UTC
Hello,

Thanks as always for maintaining this great package. I was wondering why I'm getting the following error message. 

I want to try to re-run SCT after subsetting some of my cells per [this prior post](https://github.com/satijalab/seurat/issues/4392). I was hoping to get some guidance on the proper way to do these. I can get _SCTransform_ to run, but when I try to re-run _IntegrateLayers_, I get the following error.

```
obj <- IntegrateLayers(object = obj, method = HarmonyIntegration,
  orig.reduction = "pca", new.reduction = 'harmony', assay = "SCT", normalization.method = "SCT",

verbose = FALSE)
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
In addition: Warning message:
HarmonyMatrix is deprecated and will be removed in the future from the API in the future

```
I'm wondering if I even need to re-integrate layers after re-running SCT. Sorry if any of this has been discussed previously, I couldn't find my answer elsewhere and I'm still trying to wrangle the changes in V5.

All the best,
Peter

**Comment by saketkc** [comment] 2024-01-12 20:30
Hi @pdimitron, what is the output of `Layers(obj)`

**Comment by pdimitron** [comment] 2024-01-17 12:48
Hi @saketkc 

Below is the output. Thanks for following up!

`Layers(obj)
 [1] "counts.HS-000158"        "counts.HS-000158_stim"
 [3] "counts.HS-000163"        "counts.HS-000163_stim"
 [5] "counts.HS-000195"        "counts.HS-000195_stim"
 [7] "counts.HS-000415"        "counts.HS-000415_stim"
 [9] "counts.HS-000423"        "counts.HS-000423_stim"
[11] "counts.HS-000440"        "counts.HS-000440_stim"
[13] "counts.HS-000473"        "counts.HS-000473_stim"
[15] "counts.HS-000497"        "counts.HS-000497_stim"
[17] "counts.HS-000131"        "counts.HS-000131_stim"
[19] "counts.HS-000152"        "counts.HS-000152_stim"
[21] "counts.HS-000170"        "counts.HS-000170_stim"
[23] "counts.HS-000174"        "counts.HS-000174_stim"
[25] "counts.HS-000175"        "counts.HS-000175_stim"
[27] "counts.HS-000264-2"      "counts.HS-000264-2_stim"
[29] "counts.HS-000380"        "counts.HS-000380_stim"
[31] "counts.HS-000482"        "counts.HS-000482_stim"
[33] "data.HS-000158"          "data.HS-000158_stim"
[35] "data.HS-000163"          "data.HS-000163_stim"
[37] "data.HS-000195"          "data.HS-000195_stim"
[39] "data.HS-000415"          "data.HS-000415_stim"
[41] "data.HS-000423"          "data.HS-000423_stim"
[43] "data.HS-000440"          "data.HS-000440_stim"
[45] "data.HS-000473"          "data.HS-000473_stim"
[47] "data.HS-000497"          "data.HS-000497_stim"
[49] "data.HS-000131"          "data.HS-000131_stim"
[51] "data.HS-000152"          "data.HS-000152_stim"
[53] "data.HS-000170"          "data.HS-000170_stim"
[55] "data.HS-000174"          "data.HS-000174_stim"
[57] "data.HS-000175"          "data.HS-000175_stim"
[59] "data.HS-000264-2"        "data.HS-000264-2_stim"
[61] "data.HS-000380"          "data.HS-000380_stim"
[63] "data.HS-000482"          "data.HS-000482_stim"
[65] "scale.data"
`

**Comment by saketkc** [comment] 2024-01-17 15:07
Thanks @pdimitron, can you email me your object at schoudhary@nygenome.org - if the size is too large and you can replicate this issue with a smaller dataset (with fewer layers for example), that would be best.

**Comment by mycecilia** [comment] 2024-01-19 09:39
I ran into the same error message with same analysis.

**Comment by rakszewska** [comment] 2024-02-27 15:18
I also am getting the same error with very similar analysis.

**Comment by jiangbonong** [comment] 2024-02-28 12:34
I also am getting the same error with very similar analysis.

**Comment by hamidghaedi** [comment] 2024-03-01 16:19
Same here, I'm trying to re-run Seurat v4  analysis using with Seurat v5,  

`
merged_seurat <- SCTransform(merged_seurat, vars.to.regress = c("mitoRatio", "orig.ident"))

Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
`

**Comment by hamidghaedi** [comment] 2024-03-02 03:44
proofread:
Oops, I inadvertently deleted my previous comment, and I assume that @saketkc replied to that comment. For those who drop by, I used Seurat v4 and ran an analysis in 2023. I later updated to Seurat v5.0.1 and encountered an error  `contrasts can be applied only to factors with 2 or more levels` , when running the following :

```
merged_seurat <- filtered_seurat %>%
    NormalizeData() %>%
    FindVariableFeatures(selection.method = "vst", nfeatures = 3000) %>% 
    ScaleData() %>%
    SCTransform(vars.to.regress = c("mitoRatio", "orig.ident"))
```
It seems that `SCTransform()` expects at least two categories per categorical variable. This makes sense, but the issue is that in v5.0.1, `SCTransform()` deals with one sample at a time. So, if the sample ID (orig.ident) serves as a batch ID, it cannot proceed because you will have only one category under orig.ident anyway.

I can confirm that updating to v5.0.2 resolved the issue. Thanks to Saket and the team!

**Closed** 2024-04-10 20:23 UTC
Labels: more-information-needed

**Comment by ybaeus** [comment] 2024-08-23 02:07
Hi, I also face the same issue with Seurat 5.1.0 when i run IntegrateLayers using harmony.

```
obj_SCT <- IntegrateLayers(  
  object = obj_SCT,
  method = HarmonyIntegration,          
  normalization.method = "SCT", 
  new.reduction = "integrated.harmony", 
  verbose = F
)
```

Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
contrasts can be applied only to factors with 2 or more levels

Could anyone follow up on this? Thanks a lot in advance.

**Comment by kathbosc** [comment] 2024-09-10 12:25
Same here, I'm experiencing the same issue as @ybaeus using Seurat 5.1.0. Any advice? Thanks a lot!

**Comment by kalanir** [comment] 2024-11-01 17:12
I'm also having the same issue with v5.0.2

**Comment by Jorges1000** [comment] 2024-12-17 15:43
Same problem, only with certain Seurat objects.
Version 5.1.0
