### ISSUE TITLE
Integrating data - issue with memory ~300k cells / 5 datasets

### ISSUE THREAD

**Issue by nmalwinka** [satijalab/seurat#1720] opened 2019-06-20 14:50 UTC
Hi,
I am trying to integrate 5 scRNAseq datasets, together ~300k cells. I keep getting error at the integration data step.
````
Error in .rbind2Csp(x, y) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 92
Calls: IntegrateData ... rbind -> rbind2 -> rbind2 -> rbind2sparse -> .rbind2Csp
Execution halted
````
Any suggestions?
Thanks

**Comment by satijalab** [comment] 2019-06-21 15:05
This is likely because you are trying to run CCA on a very large matrix, which can cause memory errors.  We are getting ready to introduce new functionality that will dramatically improve speed and memory utilization for alignment/integration, and overcome this issue. I will close this issue for now, but please do watch the website for updates.

**Closed by satijalab** 2019-06-21 15:05 UTC

**Comment by davemcg** [comment] 2019-07-31 17:39
Any updates on this? I'm getting the same issue with ~400K cells across 30 datasets. Should I just switch to RPCA for now?

**Comment by satijalab** [comment] 2019-07-31 17:47
Yes, we would suggest switching to RPCA for analyses of this nature. You can also use reference-based integration for further improvements in efficiency.

**Comment by davemcg** [comment] 2019-07-31 17:50
Thanks so much. Would you recommend using CCT for the normalization?

e.g. use `SCTranform` on each dataset instead of the  "standard" `NormalizeData`, `FindVariableFeatures` two step

**Comment by satijalab** [comment] 2019-07-31 17:52
Yes, we always recommend SCTransform normalization (especially with UMI data), but support both workflows.

**Comment by davemcg** [comment] 2019-07-31 17:57
Thanks I'll give it ago!

**Comment by davemcg** [comment] 2019-07-31 18:15
Hmm, I'm running `SCTransform` on each individual dataset, putting into list, then running `SelectIntegrationFeatures`, then `PrepSCTIntegration`.

When I try and run `FindIntegrationAnchors` with 'rpca' method then it complains I haven't done the `RunPCA` and `ScaleData` steps....what am I missing? Is there a guide / example that uses the `SCT` functions with `rpca` for integration?

**Comment by davemcg** [comment] 2019-07-31 18:29
I guess the question I really have is: should I scale the `SCTransform`ed data or set scale to FALSE in `FindIntegrationAnchors` ?

**Comment by andrewwbutler** [comment] 2019-08-01 18:43
Hi,

Here's an example of doing SCTransform + RPCA for integration using the example interferon stimulation dataset:

```R
library(Seurat)
library(SeuratData)
InstallData("ifnb.SeuratData")
data(ifnb)

ifnb.list <- SplitObject(ifnb, split.by = "stim")
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
  x <- SCTransform(x)
  # Don't run ScaleData here
  x <- RunPCA(x, verbose = FALSE)
})

features <- SelectIntegrationFeatures(object.list = ifnb.list, nfeatures = 3000)
ifnb.list <- PrepSCTIntegration(object.list = ifnb.list, anchor.features = features)
anchors <- FindIntegrationAnchors(object.list = ifnb.list, anchor.features = features, normalization.method = "SCT", reduction = "rpca")
ifnb.integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT")
# Don't run ScaleData here after integration
ifnb.integrated <- RunPCA(ifnb.integrated, verbose = FALSE)
ifnb.integrated <- RunUMAP(ifnb.integrated, dims = 1:30)
DimPlot(ifnb.integrated, group.by = "stim")
```

**Comment by davemcg** [comment] 2019-08-02 13:27
Andrew thanks. I actually already tried doing that, but I can't make it work for more than 2 datasets. Is this as intended?

I can make your toy example work. 

But it fails for my data (integrating 45 files) with the error
```
Error in GetAssayData(object = object.1, slot = "scale.data")[common.features,  :
  subscript out of bounds
```

when running `FindIntegrationErrors`

If I reduce my data to two datasets, it works.

If I increase it to three, it fails with the same error.

**Comment by andrewwbutler** [comment] 2019-08-02 15:35
Hi David,

Sorry for the confusion. We'll add some better error checking here but can you try moving the PCA computation to after you determine the reduced feature set and run `PrepSCTIntegration`? Here's an example that worked for me with more than 2 datasets.

```R
library(SeuratData)
InstallData("hcabm40k.SeuratData")
data("hcabm40k")

hca.list <- SplitObject(hcabm40k, split.by = "orig.ident")
hca.list <- hca.list[1:3]
hca.list <- lapply(X = hca.list, FUN = function(x) {
  x <- SCTransform(x)
})

features <- SelectIntegrationFeatures(object.list = hca.list, nfeatures = 3000)
hca.list <- PrepSCTIntegration(object.list = hca.list, anchor.features = features)
hca.list <- lapply(X = hca.list, FUN = RunPCA, verbose = FALSE, features = features)
anchors <- FindIntegrationAnchors(object.list = hca.list, anchor.features = features, normalization.method = "SCT", reduction = "rpca")
hca.integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT")

hca.integrated <- RunPCA(hca.integrated, verbose = FALSE)
hca.integrated <- RunUMAP(hca.integrated, dims = 1:30)
DimPlot(hca.integrated, group.by = "orig.ident")

```

**Comment by davemcg** [comment] 2019-08-02 15:41
Ah that does it (at least with four of my datasets)!

Thanks for your help. 

Time to scale it up!

**Comment by saeedfc** [comment] 2019-08-22 07:42
Sorry for a silly question here. But it will be important to decide. Is 128GB RAM sufficient for the pipeline to run on 200k cells (~18000 features). Processor will be i9 (12 Cores with multithreading). I am buying one. So far I have only worked with a normal workstation for upto 8k cells. But seeing this thread @davemcg using 300GB RAM and still not able to work with 400k cell, I am not sure about what to buy.

**Comment by atakanekiz** [comment] 2019-10-27 07:16
This suggestion didn't work for me (integrating 16 different 10X runs). Everything works but `IntegrateData` step fails with the following error message: `Error: cannot allocate vector of size 875.2 Mb`. Any ideas?

**Comment by davemcg** [comment] 2019-10-27 15:50
You ran out of memory. Run again on a cluster / computer with more mem.

**Comment by tushard1987** [comment] 2019-11-14 10:53
> Hi David,
> 
> Sorry for the confusion. We'll add some better error checking here but can you try moving the PCA computation to after you determine the reduced feature set and run `PrepSCTIntegration`? Here's an example that worked for me with more than 2 datasets.
> 
> ```r
> library(SeuratData)
> InstallData("hcabm40k.SeuratData")
> data("hcabm40k")
> 
> hca.list <- SplitObject(hcabm40k, split.by = "orig.ident")
> hca.list <- hca.list[1:3]
> hca.list <- lapply(X = hca.list, FUN = function(x) {
>   x <- SCTransform(x)
> })
> 
> features <- SelectIntegrationFeatures(object.list = hca.list, nfeatures = 3000)
> hca.list <- PrepSCTIntegration(object.list = hca.list, anchor.features = features)
> hca.list <- lapply(X = hca.list, FUN = RunPCA, verbose = FALSE, features = features)
> anchors <- FindIntegrationAnchors(object.list = hca.list, anchor.features = features, normalization.method = "SCT", reduction = "rpca")
> hca.integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT")
> 
> hca.integrated <- RunPCA(hca.integrated, verbose = FALSE)
> hca.integrated <- RunUMAP(hca.integrated, dims = 1:30)
> DimPlot(hca.integrated, group.by = "orig.ident")
> ```

Thanks a lot. This is extremely helpful.
Can we run normal workflow (e.g. find neighbors and clusters as shown here- https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html)  after creating the integrated data?

**Comment by romanhaa** [comment] 2020-01-23 13:18
I've tried the same procedure but receive an error during the `IntegrateData()` step:

```
Merging dataset 26 8 into 23 17 13 10 24 2 1 16 20 19 25 7 12 4 3 6 9 18 5 15 14 11 22 21 28
Extracting anchors for merged samples
Finding integration vectors
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  fast code path error starting vector near the null space; re-trying with fastpath=FALSE.
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  starting vector near the null space
```

I suspect that it has to do with data set 26 because I got the same error before when it tried to integrate only data set 26 into the others (which I used as references in that case). However, I don't find any obvious differences between that data set and the others.

Anyway, even after removing that data set, the integration works but immediately afterwards I get an error in the `RunPCA()` step:

```
seurat_integrated <- RunPCA(seurat_integrated, assay = 'integrated', npcs = 50)
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive
In addition: Warning message:
In PrepDR(object = object, features = features, verbose = verbose) :
  The following 3000 features requested have zero variance (running reduction without them): LYZ, HBA1, S100A8, S100A9, HBB, HBA2, HBD, CA1, GNLY, AHSP, S100A12, CCL5, CXCL8, TYROBP, CST3, HIST1H4C, CD74, HLA-DRA, CA2, FCN1, NKG7, LST1, KLRB1, LGALS1, IGLL1, JCHAIN, IGLC2, IGKC, IGLC3, FCER1G, GZMB, CTSS, G0S2, AIF1, CCL3, CSTA, HLA-DRB1, STMN1, PRDX2, VCAN, HLA-DPB1, CCL4, TUBA1B, MZB1, HLA-DPA1, GZMK, HMGB2, FCGR3A, GZMA, SNCA, TUBB, HLA-DQB1, IGHM, TRDC, GZMH, MNDA, RETN, CD79A, SAT1, SLC25A37, BLVRB, CD79B, CMC1, FCER1A, VPREB3, SPINK2, FGFBP2, HEMGN, SOX4, SLC4A1, HLA-DQA1, MS4A1, SERPINA1, TMCC2, S100A11, COTL1, AZU1, LTB, IFITM3, UBE2C, CXCL2, MS4A6A, CCL3L3, CFD, KLRD1, PRF1, CD14, CST7, PRSS57, IGHG1, IL32, CD8B, S100A4, IGHG3, S100A6, EREG, IGHD, KLRF1, HLA-DRB5, IRF8, ITM2C, LGALS2, SRGN, IGHA1, HOPX, NEAT1, CLIC3, RGS1, JUN, RGS2, PTTG1, HMGB1, PSAP, IRF7, PLAUR, CLEC7A, CTSW, TYMP, IFI30, CD68, FTL, MAFB, CCL4L2, NAMPT, SPON2, NUSAP1, VIM, KLF4, TOP2A, CENPF, FGL2, TRAC, BPG [... truncated]
```

No idea what I should do. These errors are hard to interpret.

**Comment by romanhaa** [comment] 2020-02-03 19:13
Just to add: I was able to make it work using the code posted above and, importantly, severely down-sampling the data set from ~120k cells to ~25k cells and reducing the number of reference samples from 25 to 10. Not ideal but it did work in the end.

**Comment by Cumol** [comment] 2020-05-29 07:24
> Hi David,
> 
> Sorry for the confusion. We'll add some better error checking here but can you try moving the PCA computation to after you determine the reduced feature set and run `PrepSCTIntegration`? Here's an example that worked for me with more than 2 datasets.
> 
> ```r
> library(SeuratData)
> InstallData("hcabm40k.SeuratData")
> data("hcabm40k")
> 
> hca.list <- SplitObject(hcabm40k, split.by = "orig.ident")
> hca.list <- hca.list[1:3]
> hca.list <- lapply(X = hca.list, FUN = function(x) {
>   x <- SCTransform(x)
> })
> 
> features <- SelectIntegrationFeatures(object.list = hca.list, nfeatures = 3000)
> hca.list <- PrepSCTIntegration(object.list = hca.list, anchor.features = features)
> hca.list <- lapply(X = hca.list, FUN = RunPCA, verbose = FALSE, features = features)
> anchors <- FindIntegrationAnchors(object.list = hca.list, anchor.features = features, normalization.method = "SCT", reduction = "rpca")
> hca.integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT")
> 
> hca.integrated <- RunPCA(hca.integrated, verbose = FALSE)
> hca.integrated <- RunUMAP(hca.integrated, dims = 1:30)
> DimPlot(hca.integrated, group.by = "orig.ident")
> ```

I did this and the integration ran. However, I do not get a new "integrated" assay as in the default integration workflow.

When I try 

> Hi David,
> 
> Sorry for the confusion. We'll add some better error checking here but can you try moving the PCA computation to after you determine the reduced feature set and run `PrepSCTIntegration`? Here's an example that worked for me with more than 2 datasets.
> 
> ```r
> library(SeuratData)
> InstallData("hcabm40k.SeuratData")
> data("hcabm40k")
> 
> hca.list <- SplitObject(hcabm40k, split.by = "orig.ident")
> hca.list <- hca.list[1:3]
> hca.list <- lapply(X = hca.list, FUN = function(x) {
>   x <- SCTransform(x)
> })
> 
> features <- SelectIntegrationFeatures(object.list = hca.list, nfeatures = 3000)
> hca.list <- PrepSCTIntegration(object.list = hca.list, anchor.features = features)
> hca.list <- lapply(X = hca.list, FUN = RunPCA, verbose = FALSE, features = features)
> anchors <- FindIntegrationAnchors(object.list = hca.list, anchor.features = features, normalization.method = "SCT", reduction = "rpca")
> hca.integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT")
> 
> hca.integrated <- RunPCA(hca.integrated, verbose = FALSE)
> hca.integrated <- RunUMAP(hca.integrated, dims = 1:30)
> DimPlot(hca.integrated, group.by = "orig.ident")
> ```

I tried this and got an integrated assay with an empty counts slot as mentioned here: https://github.com/satijalab/seurat/issues/2252

Is that intended behavior?
