### ISSUE TITLE
Error with FindAllMarkers 

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#281] opened 2018-01-24 16:58 UTC
Hi,

If I am using MAST as the method in FindAllMarkers I am getting the following error

```R
> D04.markers <- FindAllMarkers(object = D04, only.pos = TRUE, min.pct = 0.25, return.thresh = 0.05,
+                               logfc.threshold = 0.25, test.use = "MAST")
Error in eval(e, x, parent.frame()) : object 'avg_logFC' not found
```

Thanks,

Bibaswan

**Comment by leonfodoulian** [comment] 2018-01-25 23:40
Hi,

This post is a duplicate of [issue #273](https://github.com/satijalab/seurat/issues/273). 

Best,
Leon

**Comment by andrewwbutler** [comment] 2018-01-26 15:42
Closing to consolidate this to #273.

**Closed by andrewwbutler** 2018-01-26 15:42 UTC
