### ISSUE TITLE
Supervised or subsetted anchors using IntegrateLayers() in v5? Or v4 workflow?

### ISSUE THREAD

**Issue by simpakkk** [satijalab/seurat#8095] opened 2023-11-26 22:44 UTC
Hi,

I am looking to use Seurat v5 to perform RPCA integration on SCTransform normalized data. My dataset contains hashtags to mark cell-types in pooled samples, and previously I have used this information to restrict the permitted anchors within an AnchorSet across 10x lanes by subsetting AnchorSets after FindIntegrationAnchors() using the ident.matrix variable to restrict allowed pairings to identical hashtags (e.g. only allow hashtag1 to pair with hashtag1 and not hashtag2). The main reason for doing this is that only one tagged population (unstimulated, hashtag1) is biologically consistent across the timecourse of my dataset of 10x lanes run on separate days, and I do not want to over-integrate by matching cell types that have identical hashtags but should have large biological differences between timepoints. I want to supervise the integration by placing greater emphasis on the identical reference cells between my timepoints, as this population was included specifically for this purpose.

In Seurat v5 however, the ability to modify allowed anchor pairings via subsetting AnchorSets appears to have been removed in the streamlined workflow. I found this pull request: [#7714](https://github.com/satijalab/seurat/pull/7714)

However it appears that the pull request was closed and that this feature does not seem to have been added to the IntegrateLayers() function at this time.

Is there a plan to implement this feature of confining integration to account for 'allowed' and 'disallowed' cell-type pairings in the near future? And if not, or in the meantime, how do you recommend we proceed in situations where we want to supervise integration in Seurat v5 based on cell-type, and have more say over which Anchor pairings are allowed, short of downgrading to Seurat v4 and the v4 workflow?

I have tried performing integration in Seurat v5 with my old v4 workflow because all the functions used are still supported in v5 (e.g. FindIntegrationAnchors(), IntegrateData()). However, this fails for the SCT assay during the IntegrateData() step because of keys not matching pattern in the SCT assay:

```
object.split <- SplitObject(object, split.by = "lane")
object.split <- lapply(object.split,
                          FUN = SCTransform,
                          assay = "RNA",
                          vst.flavor = "v2",
                          vars.to.regress = c("percent.mt"),
                          variable.features.n = 3000,
                          return.only.var.genes = FALSE,
                          verbose = TRUE)

sct.features <- SelectIntegrationFeatures(object.list = object.split, nfeatures = 3000, assay = c("SCT", "SCT"))
object.split <- PrepSCTIntegration(object.list = object.split, anchor.features = sct.features)
object.split <- lapply(X = object.split, FUN = RunPCA, features = sct.features)
immune.anchors.rpca <- FindIntegrationAnchors(object.list = object.split, normalization.method = "SCT",
                                              anchor.features = sct.features, dims = 1:30, reduction = "rpca")
anchor_subset_rna <- subset(immune.anchors.rpca, group.by = "sample", ident.matrix = anchor_M) # where anchor_M is a logical matrix defining 'allowed' anchor pairs between "sample" (e.g. HT1 vs HT1 = TRUE, HT1 vs HT2 = FALSE)

integrated_object<- IntegrateData(anchorset = anchor_subset_rna, normalization.method = "SCT", dims = 1:30, new.assay.name = "integrated.SCT")
```

Everything runs in v5 until the last line above (IntegrateData()) which returns the following error:

```
[1] 1
[1] 2
Merging dataset 2 into 1
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Error in validObject(.Object) : 
  invalid class "Assay" object: Keys must match the pattern '^[a-zA-Z][a-zA-Z0-9]*_$'
In addition: Warning messages:
1: Different cells and/or features from existing assay SCT 
2: Different cells and/or features from existing assay SCT 
```

Is there a way to workaround this problem easily without needing to downgrade to Seurat v4?

Separately, there are other situations in which being able to manipulate features used during integration is also helpful - for example, being able to remove certain technical features (e.g. cell stress related) from the anchor.features used to generate dimensionality reductions if they are not able to be regressed adequately during SCT itself with 'vars.to.regress' and are overshadowing the most interesting or 'ground-truth' relevant sources of biological variation. Do you also have a recommended approach to remove select 'blacklisted' genes from integration in the v5 workflow?

I understand that the goal of IntegrateLayers() was to simplify integration into a single command, but it would still be great to have the ability to customize parameters of the Integration where needed, while taking advantage of other aspects of the v5 release.

Thank you in advance!! And here is my sessionInfo():

```
sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /appl/R-4.2/lib64/R/lib/libRblas.so
LAPACK: /appl/R-4.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      stats4    stats     graphics  grDevices utils     datasets  methods  
[9] base     

other attached packages:
 [1] BSgenome.Mmusculus.UCSC.mm10_1.4.3 BSgenome_1.66.3                   
 [3] rtracklayer_1.58.0                 Biostrings_2.66.0                 
 [5] XVector_0.38.0                     multimode_1.5                     
 [7] rhdf5_2.42.1                       SummarizedExperiment_1.28.0       
 [9] MatrixGenerics_1.10.0              Rcpp_1.0.11                       
[11] Matrix_1.6-3                       matrixStats_1.1.0                 
[13] data.table_1.14.8                  plyr_1.8.9                        
[15] magrittr_2.0.3                     gtable_0.3.4                      
[17] gtools_3.9.4                       gridExtra_2.3                     
[19] ArchR_1.0.2                        stringr_1.5.1                     
[21] EnsDb.Mmusculus.v79_2.99.0         ensembldb_2.22.0                  
[23] AnnotationFilter_1.22.0            GenomicFeatures_1.50.2            
[25] GenomicRanges_1.50.2               patchwork_1.1.2                   
[27] GenomeInfoDb_1.34.9                ggplot2_3.4.4                     
[29] dplyr_1.1.4                        Signac_1.12.0                     
[31] Seurat_5.0.1                       SeuratObject_5.0.1                
[33] sp_1.5-1                           AnnotationDbi_1.60.2              
[35] IRanges_2.32.0                     S4Vectors_0.36.2                  
[37] Biobase_2.58.0                     BiocGenerics_0.44.0               

loaded via a namespace (and not attached):
  [1] rappdirs_0.3.3            scattermore_1.2           tidyr_1.3.0              
  [4] bit64_4.0.5               knitr_1.45                irlba_2.3.5.1            
  [7] DelayedArray_0.24.0       rpart_4.1.19              KEGGREST_1.38.0          
 [10] RCurl_1.98-1.13           generics_0.1.3            cowplot_1.1.1            
 [13] RSQLite_2.3.3             RANN_2.6.1                future_1.31.0            
 [16] bit_4.0.5                 spatstat.data_3.0-0       xml2_1.3.3               
 [19] httpuv_1.6.12             xfun_0.41                 hms_1.1.3                
 [22] promises_1.2.1            fansi_1.0.5               restfulr_0.0.15          
 [25] progress_1.2.2            dbplyr_2.3.2              igraph_1.5.1             
 [28] DBI_1.1.3                 htmlwidgets_1.6.2         spatstat.geom_3.0-3      
 [31] purrr_1.0.2               ellipsis_0.3.2            RSpectra_0.16-1          
 [34] ks_1.13.5                 backports_1.4.1           biomaRt_2.54.0           
 [37] deldir_1.0-6              sparseMatrixStats_1.10.0  vctrs_0.6.4              
 [40] ROCR_1.0-11               abind_1.4-5               cachem_1.0.8             
 [43] withr_2.5.2               progressr_0.12.0          checkmate_2.1.0          
 [46] sctransform_0.4.1         GenomicAlignments_1.34.1  prettyunits_1.2.0        
 [49] mclust_6.0.0              goftest_1.2-3             cluster_2.1.4            
 [52] dotCall64_1.0-2           lazyeval_0.2.2            crayon_1.5.2             
 [55] spatstat.explore_3.0-5    pkgconfig_2.0.3           labeling_0.4.3           
 [58] nlme_3.1-160              vipor_0.4.5               ProtGenerics_1.30.0      
 [61] nnet_7.3-18               diptest_0.76-0            rlang_1.1.2              
 [64] globals_0.16.2            lifecycle_1.0.4           miniUI_0.1.1.1           
 [67] filelock_1.0.2            fastDummies_1.6.3         BiocFileCache_2.6.0      
 [70] dichromat_2.0-0.1         ggrastr_1.0.1             polyclip_1.10-4          
 [73] RcppHNSW_0.4.1            lmtest_0.9-40             Rhdf5lib_1.20.0          
 [76] zoo_1.8-11                base64enc_0.1-3           beeswarm_0.4.0           
 [79] ggridges_0.5.4            png_0.1-8                 viridisLite_0.4.2        
 [82] rjson_0.2.21              rootSolve_1.8.2.3         bitops_1.0-7             
 [85] KernSmooth_2.23-20        spam_2.9-1                rhdf5filters_1.10.1      
 [88] blob_1.2.4                DelayedMatrixStats_1.20.0 parallelly_1.34.0        
 [91] spatstat.random_3.0-1     jpeg_0.1-9                scales_1.2.1             
 [94] memoise_2.0.1             ica_1.0-3                 zlibbioc_1.44.0          
 [97] compiler_4.2.2            BiocIO_1.8.0              RColorBrewer_1.1-3       
[100] fitdistrplus_1.1-8        Rsamtools_2.14.0          cli_3.6.1                
[103] listenv_0.9.0             pbapply_1.6-0             htmlTable_2.4.1          
[106] Formula_1.2-4             MASS_7.3-58.1             tidyselect_1.2.0         
[109] stringi_1.8.1             glmGamPoi_1.10.0          yaml_2.3.7               
[112] latticeExtra_0.6-30       ggrepel_0.9.4             VariantAnnotation_1.44.0 
[115] fastmatch_1.1-3           tools_4.2.2               future.apply_1.10.0      
[118] parallel_4.2.2            rstudioapi_0.14           foreign_0.8-83           
[121] farver_2.1.1              Rtsne_0.16                digest_0.6.33            
[124] pracma_2.4.4              shiny_1.8.0               later_1.3.1              
[127] RcppAnnoy_0.0.21          httr_1.4.7                biovizBase_1.46.0        
[130] colorspace_2.1-0          XML_3.99-0.15             tensor_1.5               
[133] reticulate_1.26           splines_4.2.2             uwot_0.1.16              
[136] RcppRoll_0.3.0            spatstat.utils_3.0-1      plotly_4.10.3            
[139] xtable_1.8-4              jsonlite_1.8.7            R6_2.5.1                 
[142] Hmisc_4.7-1               pillar_1.9.0              htmltools_0.5.7          
[145] mime_0.12                 glue_1.6.2                fastmap_1.1.1            
[148] BiocParallel_1.32.6       codetools_0.2-18          mvtnorm_1.1-3            
[151] utf8_1.2.4                lattice_0.20-45           spatstat.sparse_3.0-0    
[154] tibble_3.2.1              curl_5.1.0                ggbeeswarm_0.6.0         
[157] leiden_0.4.3              interp_1.1-3              survival_3.4-0           
[160] munsell_0.5.0             GenomeInfoDbData_1.2.9    reshape2_1.4.4 
```

**Comment by simpakkk** [comment] 2023-12-12 19:12
Just following up on this - if we could just somehow resolve the issue where:

`integrated_object<- IntegrateData(anchorset = anchor_subset_rna, normalization.method = "SCT", dims = 1:30, new.assay.name = "integrated.SCT")`

Gives this error:

`invalid class "Assay" object: Keys must match the pattern '^[a-zA-Z][a-zA-Z0-9]*_$'`

Then should be able to move on in v5!

Appreciative of any help on getting past this error :)

**Comment by JohnScanlan** [comment] 2023-12-14 14:02
@simpakkk I am also experiencing the same error and have found no resolution yet.

**Comment by JasperGattiker** [comment] 2024-01-02 20:07
The galling thing for me is that I got it to work my first time, had to restart, and now see the same issue as stated above. I haven't the faintest idea what changed. As far as I remember I didn't update any packages between runs.

**Comment by simpakkk** [comment] 2024-01-08 20:30
Any update on a workaround for this? @saketkc @mhkowalski @gesmira

**Comment by cellmem** [comment] 2024-01-18 20:08
I was running into the same issue, and, as silly as this is, it think the problem is with the naming of the new key for the integrated dataset.  Seurat doesn't like the "." in new.assay.name = "integrated.SCT".  In Seurat 4, this just threw a warning "Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from integrated.sct_ to integratedsct_"

**Comment by simpakkk** [comment] 2024-01-22 22:26
!!! Ok, I am gonna try that as soon as our HPC is back up. Thanks for the info! I hope this fixes things!

**Comment by martuskaR** [comment] 2024-01-25 12:59
@cellmem Thanks for the suggestion, unfortunately, this didn't work for me. 

The interesting part is that I did not get this error when I did SCT integration, now I am doing AbSeq(surface protein data) and this error occurs. 

Is this normal that after running SplitObject(), the key of the assay disappears?

**Comment by cellmem** [comment] 2024-01-30 23:20
I just successfully ran cca integration using a subsetted anchorset using this command:

mESC_int<- IntegrateData(anchorset = anchor_subset_impgeno, normalization.method = "SCT", dims = 1:50,  sample.tree = matrix(c(-1,1,2,3,4,-3,-2,-4,-5,-6),ncol=2), k.weight = 25)

When I run this command with the new.assay.name specified, the run fails,  ie:

(mESC_int<- IntegrateData(anchorset = anchor_subset_impgeno, normalization.method = "SCT", dims = 1:50, new.assay.name = "integrated_geno.SCT",  sample.tree = matrix(c(-2,1,2,3,4,-6,-3,-1,-4,-5),ncol=2), k.weight = 25)), 

 Simply removing it seemed to fix the "Error in validObject(.Object) : 
  invalid class ?Assay? object: Keys must match the pattern '^[a-zA-Z][a-zA-Z0-9]*_$'" error message.

**Comment by martuskaR** [comment] 2024-01-31 09:48
Thanks for sharing the line that worked! By the way, how many modalities do you normally integrate? 
Also, I confirm removing new.assay.name from the code, does indeed solve the problem with error.

**Comment by killtherealigo** [comment] 2024-02-27 10:00
So what is the workflow for integrating the data? Is it https://satijalab.org/seurat/articles/integration_introduction? Or something else?
It really gives me a headache..

**Comment by igrabski** [comment] 2024-06-24 15:40
Hi, there appear to be a mix of a few different issues described here and some possible resolutions. I will close this issue for now, but if problems persist for anyone, please feel free to open a new issue with the following guidance:

1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.  
    
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
    
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the  
    
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.

**Closed by igrabski** 2024-06-24 15:40 UTC
