### ISSUE TITLE
CellsByIdentities produces wrong list?

### ISSUE THREAD

**Issue by noranekonobokkusu** [satijalab/seurat#8065] opened 2023-11-20 21:29 UTC
I'm trying to get a list of cells based on a particular metadata column using `CellsByIdentities`, but it produces the wrong list.

```r
Idents(seu) = seu$final_genotype_my
seu@meta.data %>% filter(final_genotype_my == "WT") %>% rownames()  # What I expect to get
 [1] "TCAAGCACACACGTGC-BM4.2"     "GGTTGTATCACGATCA-BM4.3"    
 [3] "TTACGTTGTTGGGATG-BM4.3"     "AGTACTGCAGGCGATA-SBM1173.1"
 [5] "AAGTCGTAGGGCAGGA-SBM1173.2" "AGGCATTCACGTCATA-SBM1173.2"
 [7] "CATTGCCTCCAAGCAT-SBM1173.2" "ACAGGGAGTGACATCT-SBM1173.3"
 [9] "CTCCCAATCTCCATAT-SBM1173.3" "GTCAAGTAGCATTTCG-SBM1143.2"
[11] "TTCTTGATCATTTGTC-SBM1184.1"
cells_to_highlight = CellsByIdentities(object = seu, idents = c("WT", "MUT", "WT_pot_fn"))
cells_to_highlight[["WT"]] # What I am getting
 [1] "GACTGATGTCCAGCGT-SBM1212.2" "ACTATGGTCGTGACTA-SBM1212.3"
 [3] "CACTTCGGTCAATGGG-SBM1212.3" "CACGTTCGTGACAACG-SBM1156.2"
 [5] "AATCACGTCGTAATGC-SBM1156.3" "ACTGATGTCCTCGATC-SBM1156.3"
 [7] "ATCGATGCAGTTGTCA-SBM1156.3" "GTCAAACAGACGACGT-SBM1156.3"
 [9] "TGGATCACAGAGTGAC-SBM1156.3" "GTCAAGTAGCATTTCG-SBM1143.2"
[11] "TTCTTGATCATTTGTC-SBM1184.1"
```

The list of cell names for "WT" produced by CellsByIdentities is different from what I see in the data. Is this an expected behavior and I'm missing something?

```
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] ggpubr_0.5.0                ggplot2_3.4.2              
 [3] dplyr_1.1.2                 SeuratObject_4.1.3         
 [5] Seurat_4.3.0                SingleCellExperiment_1.20.1
 [7] SummarizedExperiment_1.28.0 Biobase_2.58.0             
 [9] GenomicRanges_1.50.2        GenomeInfoDb_1.34.9        
[11] IRanges_2.32.0              S4Vectors_0.36.2           
[13] BiocGenerics_0.44.0         MatrixGenerics_1.10.0      
[15] matrixStats_1.0.0          

loaded via a namespace (and not attached):
  [1] utf8_1.2.3             spatstat.explore_3.0-5 reticulate_1.26       
  [4] tidyselect_1.2.0       RSQLite_2.2.19         AnnotationDbi_1.60.0  
  [7] htmlwidgets_1.5.4      grid_4.2.2             BiocParallel_1.32.4   
 [10] Rtsne_0.16             munsell_0.5.0          codetools_0.2-18      
 [13] ica_1.0-3              future_1.32.0          miniUI_0.1.1.1        
 [16] withr_2.5.0            spatstat.random_3.0-1  colorspace_2.1-0      
 [19] GOSemSim_2.24.0        progressr_0.13.0       ggalluvial_0.12.5     
 [22] rstudioapi_0.14        ROCR_1.0-11            ggsignif_0.6.4        
 [25] tensor_1.5             DOSE_3.24.2            listenv_0.9.0         
 [28] GenomeInfoDbData_1.2.9 polyclip_1.10-4        bit64_4.0.5           
 [31] parallelly_1.36.0      vctrs_0.6.2            treeio_1.22.0         
 [34] generics_0.1.3         R6_2.5.1               doParallel_1.0.17     
 [37] clue_0.3-63            locfit_1.5-9.6         bitops_1.0-7          
 [40] spatstat.utils_3.0-1   cachem_1.0.6           fgsea_1.24.0          
 [43] gridGraphics_0.5-1     DelayedArray_0.24.0    vroom_1.6.0           
 [46] promises_1.2.0.1       scales_1.2.1           gtable_0.3.3          
 [49] globals_0.16.2         goftest_1.2-3          rlang_1.1.1           
 [52] GlobalOptions_0.1.2    splines_4.2.2          rstatix_0.7.1         
 [55] lazyeval_0.2.2         spatstat.geom_3.0-3    broom_1.0.1           
 [58] reshape2_1.4.4         abind_1.4-5            backports_1.4.1       
 [61] httpuv_1.6.6           qvalue_2.30.0          tools_4.2.2           
 [64] ggplotify_0.1.0        ellipsis_0.3.2         RColorBrewer_1.1-3    
 [67] ggridges_0.5.4         Rcpp_1.0.10            plyr_1.8.8            
 [70] zlibbioc_1.44.0        purrr_1.0.1            RCurl_1.98-1.12       
 [73] deldir_1.0-6           pbapply_1.6-0          GetoptLong_1.0.5      
 [76] cowplot_1.1.1          zoo_1.8-11             ggrepel_0.9.3         
 [79] cluster_2.1.4          magrittr_2.0.3         data.table_1.14.6     
 [82] scattermore_0.8        ggtreeExtra_1.11.0     circlize_0.4.15       
 [85] lmtest_0.9-40          RANN_2.6.1             ggnewscale_0.4.8      
 [88] fitdistrplus_1.1-8     hms_1.1.2              patchwork_1.1.2       
 [91] mime_0.12              xtable_1.8-4           HDO.db_0.99.1         
 [94] XML_3.99-0.13          gridExtra_2.3          shape_1.4.6           
 [97] compiler_4.2.2         tibble_3.2.1           KernSmooth_2.23-20    
[100] crayon_1.5.2           htmltools_0.5.4        tzdb_0.3.0            
[103] ggfun_0.0.9            later_1.3.0            tidyr_1.3.0           
[106] geneplotter_1.76.0     aplot_0.1.9            DBI_1.1.3             
[109] ComplexHeatmap_2.15.1  MASS_7.3-58.1          readr_2.1.3           
[112] Matrix_1.5-3           car_3.1-1              cli_3.6.1             
[115] parallel_4.2.2         igraph_1.4.3           pkgconfig_2.0.3       
[118] sp_1.6-1               plotly_4.10.1          spatstat.sparse_3.0-0 
[121] foreach_1.5.2          ggtree_3.6.2           annotate_1.76.0       
[124] XVector_0.38.0         yulab.utils_0.0.5      stringr_1.5.0         
[127] digest_0.6.31          sctransform_0.3.5      RcppAnnoy_0.0.20      
[130] spatstat.data_3.0-0    Biostrings_2.66.0      leiden_0.4.3          
[133] fastmatch_1.1-3        tidytree_0.4.1         uwot_0.1.14           
[136] shiny_1.7.3            rjson_0.2.21           lifecycle_1.0.3       
[139] nlme_3.1-160           jsonlite_1.8.4         carData_3.0-5         
[142] viridisLite_0.4.2      fansi_1.0.4            pillar_1.9.0          
[145] lattice_0.20-45        KEGGREST_1.38.0        fastmap_1.1.0         
[148] httr_1.4.4             survival_3.4-0         GO.db_3.16.0          
[151] glue_1.6.2             png_0.1-8              iterators_1.0.14      
[154] bit_4.0.5              stringi_1.7.12         blob_1.2.3            
[157] DESeq2_1.38.1          memoise_2.0.1          irlba_2.3.5.1         
[160] future.apply_1.11.0    ape_5.7 
```

**Comment by samuel-marsh** [comment] 2023-11-21 00:12
Hi,

Not member of dev team but hopefully can be helpful.  I can't replicate this on my end.  Are you able to provide reproducible example with example dataset?  If not then potentially an issue with the meta.data of your object and the assignment of variables would be my best guess.

Here is my code with pbmc3k dataset.
```
library(tidyverse)
library(Seurat)

pbmc <- pbmc3k.SeuratData::pbmc3k.final
pbmc <- UpdateSeuratObject(pbmc)

pbmc$sample_id <- sample(c("sample1", "sample2", "sample3", "sample4", "sample5", "sample6"), size = ncol(pbmc),
                         replace = TRUE)


sample1_fil <- pbmc@meta.data %>% 
  filter(sample_id == "sample1") %>% 
  rownames()

Idents(pbmc) <- "sample_id"
cells_idents <- CellsByIdentities(object = pbmc, idents = c("sample1", "sample2"))


diff <- symdiff(x = cells_idents[["sample1"]], y = sample1_fil)
> diff
character(0)
```


Best,
Sam

**Comment by longmanz** [comment] 2023-12-21 21:31
Hi, 
Thank you @samuel-marsh. I was not able to reproduce it from my end as well. I am closing this for now as there is no follow-up response but I will reopen if this issue persists.

**Closed by longmanz** 2023-12-21 21:31 UTC
Labels: bug
