### ISSUE TITLE
Question about Reference mapping

### ISSUE THREAD

**Issue by tianchen2019** [satijalab/seurat#5364] opened 2021-12-07 09:11 UTC
When i use this tutorial (https://satijalab.org/signac/articles/integrate_atac.html) , i found i could not map my data to a integrated reference. My reference single-cell data have some batches, i want to move batches and then map data to this reference.
I found scRNA-seq tutorial told me to map data to an integrated dataset ( https://satijalab.org/seurat/articles/integration_mapping.html).
But when i run the code (pancreas.integrated <- IntegrateData(anchorset = pancreas.anchors, dims = 1:30) ) using scATAC-seq data, the error is Unable to allocate a 149.0GB vector.

**Comment by timoast** [comment] 2021-12-08 16:40
Duplicate of https://github.com/timoast/signac/issues/899

**Closed by timoast** 2021-12-08 16:40 UTC
