### ISSUE TITLE
Error in validObject(.Object) : invalid class “LowRankMatrix” object:  the supplied seed must support extract_array()

### ISSUE THREAD

**Issue by yinshanfang** [satijalab/seurat#8985] opened 2024-06-05 16:00 UTC
Hi, I tried to merge two Seurat Objects and then RunFastMNN. I got the error. Seurat 4.4.0 was loaded.
![image](https://github.com/satijalab/seurat/assets/76269351/7e7586e3-3926-48bc-911d-eeb47142c894)

![image](https://github.com/satijalab/seurat/assets/76269351/bc34e40a-936e-444a-9e2f-c190044e5e5c)

Can you help me figure it out?

**Comment by zskylarli** [comment] 2024-06-24 18:55
Hi @yinshanfang,

Thank you for reaching out! Unfortunately, with the details provided, we cannot reproduce your issue. Some notes:

1) Does this issue occur when you use Seurat v5? Additionally, is there any chance your object was created as a v5 object initially? 

2) Were these objects normalized with SCTransform, and if so, would the discussion in #5329 be of help? 

Since this is a SeuratWrapper function, it may be more useful to redirect this issue to the SeuratWrappers repository. To help us better understand and resolve this issue, please ensure that you provide the following information when reporting a bug:

1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.  
    
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
    
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the  
    
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.

We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost in the SeuratWrappers repository, and we will be more than happy to help you resolve the problem.

**Closed by zskylarli** 2024-06-24 18:55 UTC
Labels: bug
