### ISSUE TITLE
DEseq2 does not work in the function "FindMarkers" 

### ISSUE THREAD

**Issue by Rwl3088** [satijalab/seurat#2460] opened 2019-12-27 22:50 UTC
Dear all, 

I met the problem while I'm looking for the cluster markers using DESeq2 in the function "FindMarkers" after running the standard Seurat process and the previous steps are fine.

Here is my command:
`cluster1.markers <- FindMarkers(B_seurat_object,only.pos = TRUE, min.pct = 0.25, ident.1 = 0, test.use = "DESeq2"`

And Here is the error:
`Error in estimateSizeFactorsForMatrix(counts(object), locfunc = locfunc,  : 
  every gene contains at least one zero, cannot compute log geometric means`

I tried not to tandardize the data to the log form in the previous steps but it didn't work. Other methods, like wilcox, MAST, work fine.

**Comment by MoaES** [comment] 2020-01-09 14:46
Duplicate of #1570

**Closed** 2020-01-17 17:12 UTC
Labels: duplicate
