### ISSUE TITLE
Error dysplaying single-cell plots using DimPlot, FeaturePlot - raster argument mandatory?

### ISSUE THREAD

**Issue by ahorisberger** [satijalab/seurat#7466] opened 2023-06-18 18:16 UTC
I have installed Seurat 4.3.0 and when I use DimPlot or FeaturePlot, the plots show the axis and legends but the graph is empty. I don't get any error messages. My seurat object is otherwise correct and all the different slots have data, and if I extract the data from the seurat object I can manually do a UMAP plot using ggplot. When I tested wth seurat data, I realized that the issue did not occur using  "pbmc_small". And I realized it might be because of the size of the data. When I added raster = TRUE or raster = FALSE, the data displayed correctly using DimPlot and FeaturePlot. In previous Seurat packages, I didn't have to specify this argument, and raster TRUE was automatically performed if > 100,000 points. Is it an issue on my side, or is it due to the package update?

I don't have any specific code to share, as I didn't get any error message, but it was just the graph that was empty (see attachment).
The only code I used was (and I can't share this object): 
DimPlot(sobjt) -> gives an empty plot (axis are present but no data in the graph)
DimPlot(sobjt, raster = TRUE) -> gives a complete/normal plot

> sessionInfo()
R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SeuratData_0.2.2   SeuratObject_4.1.3 Seurat_4.3.0       sp_1.6-1          

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3     rstudioapi_0.14        jsonlite_1.8.5        
  [4] magrittr_2.0.3         spatstat.utils_3.0-3   farver_2.1.1          
  [7] nloptr_2.0.3           fs_1.6.2               vctrs_0.6.2           
 [10] ROCR_1.0-11            memoise_2.0.1          minqa_1.2.5           
 [13] spatstat.explore_3.2-1 usethis_2.2.0          htmltools_0.5.5       
 [16] curl_5.0.1             sctransform_0.3.5      parallelly_1.36.0     
 [19] KernSmooth_2.23-20     desc_1.4.2             htmlwidgets_1.6.2     
 [22] ica_1.0-3              plyr_1.8.8             plotly_4.10.2         
 [25] zoo_1.8-12             cachem_1.0.8           igraph_1.4.3          
 [28] mime_0.12              lifecycle_1.0.3        pkgconfig_2.0.3       
 [31] Matrix_1.5-4           R6_2.5.1               fastmap_1.1.1         
 [34] fitdistrplus_1.1-11    future_1.32.0          shiny_1.7.4           
 [37] digest_0.6.31          colorspace_2.1-0       patchwork_1.1.2       
 [40] ps_1.7.5               rprojroot_2.0.3        tensor_1.5            
 [43] irlba_2.3.5.1          pkgload_1.3.2          labeling_0.4.2        
 [46] progressr_0.13.0       fansi_1.0.4            spatstat.sparse_3.0-1 
 [49] httr_1.4.6             polyclip_1.10-4        abind_1.4-5           
 [52] compiler_4.3.0         remotes_2.4.2          withr_2.5.0           
 [55] pkgbuild_1.4.0         MASS_7.3-58.4          rappdirs_0.3.3        
 [58] sessioninfo_1.2.2      tools_4.3.0            lmtest_0.9-40         
 [61] httpuv_1.6.11          future.apply_1.11.0    goftest_1.2-3         
 [64] glue_1.6.2             callr_3.7.3            nlme_3.1-162          
 [67] promises_1.2.0.1       grid_4.3.0             Rtsne_0.16            
 [70] cluster_2.1.4          reshape2_1.4.4         generics_0.1.3        
 [73] gtable_0.3.3           spatstat.data_3.0-1    tidyr_1.3.0           
 [76] data.table_1.14.8      utf8_1.2.3             spatstat.geom_3.2-1   
 [79] RcppAnnoy_0.0.20       ggrepel_0.9.3          RANN_2.6.1            
 [82] pillar_1.9.0           stringr_1.5.0          later_1.3.1           
 [85] splines_4.3.0          dplyr_1.1.2            lattice_0.21-8        
 [88] survival_3.5-5         deldir_1.0-9           tidyselect_1.2.0      
 [91] miniUI_0.1.1.1         pbapply_1.7-0          gridExtra_2.3         
 [94] scattermore_1.2        devtools_2.4.5         matrixStats_1.0.0     
 [97] stringi_1.7.12         lazyeval_0.2.2         boot_1.3-28.1         
[100] codetools_0.2-19       tibble_3.2.1           cli_3.6.1             
[103] uwot_0.1.14            xtable_1.8-4           reticulate_1.30       
[106] munsell_0.5.0          processx_3.8.1         Rcpp_1.0.10           
[109] globals_0.16.2         spatstat.random_3.1-5  png_0.1-8             
[112] parallel_4.3.0         ellipsis_0.3.2         ggplot2_3.4.2         
[115] prettyunits_1.1.1      profvis_0.3.8          urlchecker_1.0.1      
[118] lme4_1.1-33            listenv_0.9.0          viridisLite_0.4.2     
[121] scales_1.2.1           ggridges_0.5.4         leiden_0.4.3          
[124] purrr_1.0.1            crayon_1.5.2           rlang_1.1.1           
[127] cowplot_1.1.1  

![Capture](https://github.com/satijalab/seurat/assets/102888401/38c5f1ad-3d58-461b-9234-b0e7937935cf)

**Comment by ChristinaSteyn** [comment] 2023-06-19 20:44
Hi there, I am not a developer but I was about to submit the same issue so just thought I would post it here. I have recently updated R and Seurat and now my plots are coming out blank just like yours (even when I run the code which previously worked). Here is my sessionInfo() for the record:
> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.3.so;  LAPACK version 3.8.0

locale:
 [1] LC_CTYPE=en_ZA.utf-8       LC_NUMERIC=C
 [3] LC_TIME=en_ZA.utf-8        LC_COLLATE=en_ZA.utf-8
 [5] LC_MONETARY=en_ZA.utf-8    LC_MESSAGES=en_ZA.utf-8
 [7] LC_PAPER=en_ZA.utf-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_ZA.utf-8 LC_IDENTIFICATION=C

time zone: Africa/Johannesburg
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] textclean_0.9.3             RColorBrewer_1.1-3
 [3] pryr_0.1.6                  RCurl_1.98-1.12
 [5] cowplot_1.1.1               scales_1.2.1
 [7] Matrix_1.5-4                lubridate_1.9.2
 [9] forcats_1.0.0               stringr_1.5.0
[11] dplyr_1.1.2                 purrr_1.0.1
[13] readr_2.1.4                 tidyr_1.3.0
[15] tibble_3.2.1                ggplot2_3.4.2
[17] tidyverse_2.0.0             SeuratObject_4.1.3
[19] Seurat_4.3.0                SingleCellExperiment_1.22.0
[21] SummarizedExperiment_1.30.1 Biobase_2.60.0
[23] GenomicRanges_1.52.0        GenomeInfoDb_1.36.0
[25] IRanges_2.34.0              S4Vectors_0.38.1
[27] BiocGenerics_0.46.0         MatrixGenerics_1.12.2
[29] matrixStats_1.0.0

loaded via a namespace (and not attached):
  [1] jsonlite_1.8.4          magrittr_2.0.3          spatstat.utils_3.0-3
  [4] farver_2.1.1            ragg_1.2.5              zlibbioc_1.46.0
  [7] vctrs_0.6.2             ROCR_1.0-11             spatstat.explore_3.2-1
 [10] htmltools_0.5.5         S4Arrays_1.0.4          qdapRegex_0.7.5
 [13] sctransform_0.3.5       parallelly_1.36.0       KernSmooth_2.23-20
 [16] htmlwidgets_1.6.2       ica_1.0-3               plyr_1.8.8
 [19] plotly_4.10.1           zoo_1.8-12              igraph_1.4.3
 [22] mime_0.12               lifecycle_1.0.3         pkgconfig_2.0.3
 [25] R6_2.5.1                fastmap_1.1.1           GenomeInfoDbData_1.2.10
 [28] fitdistrplus_1.1-11     future_1.32.0           shiny_1.7.4
 [31] digest_0.6.31           colorspace_2.1-0        patchwork_1.1.2
 [34] tensor_1.5              irlba_2.3.5.1           textshaping_0.3.6
 [37] labeling_0.4.2          progressr_0.13.0        timechange_0.2.0
 [40] fansi_1.0.4             spatstat.sparse_3.0-1   httr_1.4.6
 [43] polyclip_1.10-4         abind_1.4-5             compiler_4.3.0
 [46] withr_2.5.0             MASS_7.3-58.4           DelayedArray_0.26.3
 [49] tools_4.3.0             lmtest_0.9-40           httpuv_1.6.11
 [52] future.apply_1.11.0     goftest_1.2-3           glue_1.6.2
 [55] nlme_3.1-162            promises_1.2.0.1        grid_4.3.0
 [58] Rtsne_0.16              cluster_2.1.4           reshape2_1.4.4
 [61] generics_0.1.3          gtable_0.3.3            spatstat.data_3.0-1
 [64] tzdb_0.4.0              data.table_1.14.8       hms_1.1.3
 [67] sp_1.6-1                utf8_1.2.3              XVector_0.40.0
 [70] spatstat.geom_3.2-1     RcppAnnoy_0.0.20        ggrepel_0.9.3
 [73] RANN_2.6.1              pillar_1.9.0            later_1.3.1
 [76] splines_4.3.0           lattice_0.21-8          survival_3.5-5
 [79] deldir_1.0-9            tidyselect_1.2.0        miniUI_0.1.1.1
 [82] pbapply_1.7-0           gridExtra_2.3           scattermore_1.1
 [85] stringi_1.7.12          lazyeval_0.2.2          codetools_0.2-19
 [88] cli_3.6.1               uwot_0.1.14             systemfonts_1.0.4
 [91] xtable_1.8-4            reticulate_1.28         munsell_0.5.0
 [94] Rcpp_1.0.10             globals_0.16.2          spatstat.random_3.1-5
 [97] png_0.1-8               parallel_4.3.0          ellipsis_0.3.2
[100] bitops_1.0-7            listenv_0.9.0           viridisLite_0.4.2
[103] ggridges_0.5.4          leiden_0.4.3            crayon_1.5.2
[106] rlang_1.1.1

Any help would be greatly appreciated!

**Comment by ahorisberger** [comment] 2023-06-19 21:31
Hi, so in my case I have a large object with > 100,000 points. Adding "raster = TRUE" in DimPlot and FeaturePlot resolved the blank graphs. But I'm not sure why this happens.

DimPlot(seurat_object, raster = TRUE)
FeaturePlot(seurat_object, feature = feature, raster = TRUE)

**Comment by ChristinaSteyn** [comment] 2023-06-20 09:05
Thanks so much for your reply. It's so strange because I also have an object with >100,000 points and I tried setting "raster=TRUE" which didn't work but setting "raster=FALSE" did.

Not sure what's going on there but thank you for the suggestion!

**Comment by samuel-marsh** [comment] 2023-06-21 17:18
Hi @ChristinaSteyn @ahorisberger,

Not member of dev team but hopefully can be helpful.  This issue is duplicate of #7328 which results from changes made in the scattermore package.  To solve this you can either simply explicitly set a `pt.size` in function call and leave the raster parameter to set itself automatically based on object size.
```
DimPlot(obj, pt.size = 1)
```

Or you can downgrade just the scattermore package (unless you need new functionality elsewhere) by downloading the version 0.8 from CRAN archive ([see here](https://cran.r-project.org/src/contrib/Archive/scattermore/)) and installing from source:
```
install.packages("~/Downloads/scattermore_0.8.tar.gz", type = "source", repos = NULL)
```

Going to close now as this is duplicate but if either of these solutions don't solve your issue (they solved mine when I tested with object of 140K cells) then please post here and I'll reopen this for the Seurat team.

Best,
Sam

Best,
Sam

**Closed by samuel-marsh** 2023-06-21 17:18 UTC
Labels: bug

**Comment by longyingda** [comment] 2024-02-26 10:06
> Hi @ChristinaSteyn @ahorisberger,
> 
> Not member of dev team but hopefully can be helpful. This issue is duplicate of #7328 which results from changes made in the scattermore package. To solve this you can either simply explicitly set a `pt.size` in function call and leave the raster parameter to set itself automatically based on object size.
> 
> ```
> DimPlot(obj, pt.size = 1)
> ```
> 
> Or you can downgrade just the scattermore package (unless you need new functionality elsewhere) by downloading the version 0.8 from CRAN archive ([see here](https://cran.r-project.org/src/contrib/Archive/scattermore/)) and installing from source:
> 
> ```
> install.packages("~/Downloads/scattermore_0.8.tar.gz", type = "source", repos = NULL)
> ```
> 
> Going to close now as this is duplicate but if either of these solutions don't solve your issue (they solved mine when I tested with object of 140K cells) then please post here and I'll reopen this for the Seurat team.
> 
> Best, Sam
> 
> Best, Sam

DimPlot(obj, pt.size = 1, raster = T) well done!
