### ISSUE TITLE
SCTransform speed on cluster

### ISSUE THREAD

**Issue by ajgentles** [satijalab/seurat#3354] opened 2020-08-06 00:22 UTC
I have a feeling this is going to be super hard to diagnose, but... In integrating largish datasets (total ~50,000 cells across ~10 samples) , we sometimes run into insufficient memory with IntegrateData on our local linux server (92Gb memory), though interestingly the FindAnchors step works OK. We have an HPC cluster too, and I can request an rstudio session with plenty of memory. However, SCTransform runs like molasses on that system. And it seems to be *only* SCTransform. Other steps run quickly. So at the momet I have to run SCTransform on the local machine, save the output and transfer to the cluster to do the actual integration.

It has literally been stuck at 0% for 10 minutes, whereas by now on our local system would have made significant progress.

Calculating cell attributes for input UMI matrix
Variance stabilizing transformation of count matrix of size 21690 by 6776
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 6776 cells
  |                                                                                                                                                             |   0%

Any suggestions how to troubleshoot? Is SCTransform perhaps calling a compiled routine that might not be present on the cluster and it's falling back to a R native implementation? I'm at a loss. That node on the cluster shows the process is running at 100% CPU utilization so it's doing something.

**Comment by saketkc** [comment] 2020-08-14 20:54
Hi @ajgentles, it does look a bit strange. There are two things you could try (which are complementary):

- Try reducing the [number of cells](https://github.com/satijalab/seurat/blob/master/R/preprocessing.R#L1512) being passed to `sctransform`: `SCtransform(ncells=5000)` or `SCtransform(ncells=3000)`: _Reduces the runtime_ without significantly affecting the estimates
- Switch on the `conserve.memory` [flag](https://github.com/satijalab/seurat/blob/master/R/preprocessing.R#L1519) (though I am not sure if memory is the issue here):  `SCtransform(conserve.memory=TRUE)`: _Reduces the memory foot print by preventing creation of entire residual matrix but can lead to increased run time_

 Though I have had success with more number of cells (upto 68k) with no issues, though it does take longer with no noticeable changes in the estimates (as against 5k).

**Comment by ajgentles** [comment] 2020-08-28 21:27
Sorry, I forgot to post an update. I was not able to resolve the issue. Even downsizing to a few thousand cells, the exact same code runs much slower on a cluster with faster processor and more memory, solely for the SCtransform step. I think it must be some buried issue like an inefficiently compiled library on the system.

**Comment by saketkc** [comment] 2020-09-04 21:35
Hi @ajgentles, Would you be able to reproduce this with one of the public datasets? You can use the datasets available in [seurat-data](https://github.com/satijalab/seurat-data).

One way to figure out the bottleneck step inside `SCTransform` would be to run it through `Rprof`:

```r
Rprof(filename="sctransform.Rprof.out")
pbmc <- SCTransform(pbmc, ncells=5000, verbose = TRUE)
Rprof(NULL)
```
You can decrease the `ncells` parameter further.

And then run (assuming the above step finishes):
```r
summaryRprof(filename="sctransform.rprof.out")
```
I am not sure if this is because of an inefficiently compiled library, but this might help pinpoint the bottleneck step anyway.

**Comment by ajgentles** [comment] 2020-10-06 14:03
Sorry for the delayed reply, we have been trying all sorts of things such as reinstalling R, different versions etc. I can't tell you what the problem is, but it is something to do with Rstudio launched on our cluster through OnDemand. If I log directly into a node it runs perfectly fine. Through Rstudio, even going down to ncells=500 gives the following:

>library(Seurat)
>library(SeuratData)
>data(pbmc3k)
>Rprof(filename="sctransform.Rprof.out")
>pbmc3k <- SCTransform(pbmc3k, ncells=500, verbose = TRUE)

Calculating cell attributes from input UMI matrix: log_umi
Variance stabilizing transformation of count matrix of size 12572 by 2700
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 500 cells
  |====================================================================================================================| 100%
Found 150 outliers - those will be ignored in fitting/regularization step

Second step: Get residuals using fitted parameters for 12572 genes
  |                                                                                                                    |   0%


And it never progresses beyond that - 4 hours later, still at 0% despite the R session being at 100% CPU use. From the command line R, it runs in about 20 seconds as expected.

Anyway, thanks for the suggestions before. Someone suggested that some library call might be misidentifying the number of available cores and launched multiple threads on the same core, but as far as I can tell SCTransform does not use multithreading.

**Comment by saketkc** [comment] 2020-12-11 20:07
That looks strange. `SCTransform` can use multithreadhing if `future` is enabled. I would suggest a couple of things.

1. Update `SCTransform` from github develop branch: `remotes::install_github("ChristophH/sctransform@develop"`
2. Explicitly set  `plan("multiprocess", workers = 1)` after importing `library(futures)`

**Comment by ajgentles** [comment] 2020-12-11 20:14
> That looks strange. `SCTransform` can use multithreadhing if `future` is enabled. I would suggest a couple of things.
> 
>     1. Update `SCTransform` from github develop branch: `remotes::install_github("ChristophH/sctransform@develop"`
> 
>     2. Explicitly set  `plan("multiprocess", workers = 1)` after importing `library(futures)`

Yes something weird with launching Rstudio through Ondemand on the HPC cluster. There is some massive overhead in there somewhere. Our HPC people said they've seen similar with other packages.... It works as expected launched directly with SLURM.

**Comment by saketkc** [comment] 2020-12-11 20:25
Thanks for confirming. I will go ahead and close this, since it does not seem to be originating in Seurat/SCTransform. Feel free to reopen if you have any follow up questions.

**Closed by saketkc** 2020-12-11 20:25 UTC
