### ISSUE TITLE
The Sketch Data function specifies an invalid number of selected cells

### ISSUE THREAD

**Issue by haolangchen** [satijalab/seurat#8891] opened 2024-05-15 02:04 UTC
The Sketch Data function usually works properly, but sometimes this situation is encountered. I used the Sketch Data function to filter for a specified cell count, but it returned me the number of cells in the integrated set. How to solve it, what is the situation.
```r
> length(colnames(tmp_seurat))
[1] 4042



test <- SketchData(object = tmp_seurat,ncells = 500,method = "LeverageScore",sketched.assay = "sketch")


> length(colnames(test))
[1] 4042




```

**Comment by longmanz** [comment] 2024-06-24 19:38
Hi,
This is an expected behavior since test is a sketched representation of the original tmp_seurat data. Therefore, it still contains the original colnames. I will close this issue but please feel free to reopen it if there is any further issue related to this.

**Closed by longmanz** 2024-06-24 19:38 UTC
Labels: bug
