### ISSUE TITLE
How can I merge RDS data for specific clusters in multiple samples after removing batches？

### ISSUE THREAD

**Issue by JWJ13164328557** [satijalab/seurat#8994] opened 2024-06-07 01:30 UTC
> library(Seurat)
> library(sctransform)
> library(ggplot2)
> library(harmony)
> rm(list=ls())
> opt=list()
> opt$res=0.2
> opt$MinCell=10
> opt$MinFeatures=50
> opt$npca=30
> opt$indir='D:/Desktop/RDS/'
> opt$sample=c("T1object.rds","T2object.rds","T3object.rds")
> opt$outdir='D:/Desktop/RDS/'
> col = c("0"="#F56867", "1"="#FEB915", "2"="#C798EE","3"="#59BE86","4"="#7495D3","5"="#D1D1D1",
+         "6"="#6D1A9C","7"="#15821E","8"="#3A84E6","9"="#70e014","10"="#787878",
+         "11"="#DB4C6C","12"="#0430e0","13"="#554236","14"="#AF5F3C","15"="#ff7700","16"="#e00417",
+         "17"="#DAB370","18"="#fcfc05","19"="#268785","20"="#09f9f5","21"="#246b93","22"="#cc8e12",
+         "23"="#d561dd","24"="#c93f00","25"="#ddd53e","26"="#4aef7b","27"="#e86502","28"="#9ed84e",
+         "29"="#39ba30","30"="#6ad157","31"="#8249aa","32"="#99db27","33"="#e07233","34"="#ff523f")
> res=opt$res
> MinCell=opt$MinCell
> MinFeatures=opt$MinFeatures
> npca=opt$npca
> indir=opt$indir
> outdir=paste0(opt$outdir,"/","SCT","_C",MinCell,"_F",MinFeatures,"_P",npca,"_R",res)
> if(!dir.exists(outdir)){dir.create(path=outdir,recursive = TRUE)}
> dir=c(paste0(indir,"/",opt$sample))
> names(dir)=opt$sample
> expr <- list()
> obj <- list()
> single<-list()
> for(i in 1:length(dir)){  
+   expr[[i]] = readRDS(dir[i])  
+   obj[[i]] = CreateSeuratObject(counts = expr[[i]], assay = "RNA", min.cells = MinCell, min.features = MinFeatures)  
+   obj[[i]]@meta.data$orig.ident <- names(dir)[i]  
+   print(i)  
+ }
Error in h(simpleError(msg, call)) : 
  在为'colSums'函数选择方法时评估'x'参数出了错: comparison (>) is possible only for atomic and list types

**Comment by zskylarli** [comment] 2024-06-24 17:52
Hi @JWJ13164328557,

Thank you for reaching out! We’re always grateful when folks take the time to [blank] and help make Seurat better 🙂

Unfortunately, with the details provided, we cannot reproduce your issue. To help us better understand and resolve this issue, please ensure that you provide the following information when reporting a bug:

1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.  
    
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
    
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the  
    
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.

We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost and we will be more than happy to help you resolve the problem.

**Closed by zskylarli** 2024-06-24 17:52 UTC
