### ISSUE TITLE
Merging 2 10x multiome objects

### ISSUE THREAD

**Issue by wht10** [satijalab/seurat#5191] opened 2021-10-14 17:49 UTC
Hi,

Thank you for building and maintaining the Seurat toolkit. 

I am interested in merging 2 10x multiome objects. Combining just RNA assays from 10x runs has been straightforward using the [seurat merge vignette](https://satijalab.org/seurat/articles/merge_vignette.html).

The merge vignette for [10x ATAC assays](https://satijalab.org/signac/articles/merging.html), details how to create a common peak set using .bed files.

I didn't see any .bed files from the cell ranger output, so I am wondering what would be the best way to obtain these.

I was able to create the individual multiome objects and merge them (using the [WNN 10x multiome vignette](https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html), and the [10x multiome Signac vignette](https://satijalab.org/signac/articles/pbmc_multiomic.html)) , but I am not totally clear what the consequences are of not having a common peak set. 

Do you think you might be able to provide a vignette for merging and analyzing 10x multiome objects? 

Or if you could clarify what the consequences are of not having a common peak set, or how to obtain the .bed files necessary for creating a common peak set, I would really appreciate it. 

Thanks!

**Comment by timoast** [comment] 2021-10-14 18:17
Duplicate of https://github.com/timoast/signac/issues/824

**Closed by timoast** 2021-10-14 18:17 UTC
