### ISSUE TITLE
Error in FindIntegrationAnchors(). UNRELIABLE VALUE: Future (‘future_lapply-1’) unexpectedly generated random numbers without specifying argument 'future.seed'. How to solve this problem?

### ISSUE THREAD

**Issue by geng-lee** [satijalab/seurat#3944] opened 2021-01-18 11:56 UTC
###  Error in FindIntegrationAnchors(). How to solve this problem?

- UNRELIABLE VALUE: Future (‘future_lapply-1’) unexpectedly generated random numbers without specifying argument 'future.seed'. 

```r
sce.anchors <- FindIntegrationAnchors(object.list = sce.list, normalization.method = "SCT", anchor.features = sce.features, verbose = FALSE)


Warning message:
UNRELIABLE VALUE: Future (‘future_lapply-1’) unexpectedly generated random numbers without specifying
argument 'future.seed'. There is a risk that those random numbers are not statistically sound and the overall results
might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are
produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed=NULL', or set option
'future.rng.onMisuse' to "ignore". 
```

**Comment by saketkc** [comment] 2021-01-22 17:57
Hi @geng-lee, this is not a bug but a warning. This issue was fixed in Seurat v3.2. Can you try updating your installation?

**Closed by saketkc** 2021-01-22 17:57 UTC
Labels: bug

**Comment by iddryg** [comment] 2021-04-22 16:59
I also got this warning with Seurat_4.0.1

**Comment by planti-body** [comment] 2021-04-28 17:52
I also am getting this same error with Seurat v4.0.1

**Comment by wajm** [comment] 2021-05-10 22:36
I also am getting this same error with Seurat v4.0.1

**Comment by meltager** [comment] 2021-06-21 08:31
I also get this warning from the same function on updated version of Seurat (V 4.0.1) 
The function is called like this : 
data.anchors <- FindIntegrationAnchors(object.list = samples_list_1, anchor.features = features,verbose = FALSE)

The number of error message is a function of the number of the worker threads used by future lib., when i didn't init. it at all i got the error message of the memory limit
