### ISSUE TITLE
Error subsetting a multimodal Seurat object (filtering genes)

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#6548] opened 2022-10-13 10:24 UTC
Hi,

I am subsetting my multimodal Seurat object (RNA, ADT and HTO assays) to remove genes expressed in fewer than 3 cells as follows:

```
non_zero <- apply(GetAssayData(object = seurat_merged, slot = "counts"), 1, 
                  function(x) sum(x > 0))
at_least_3 <- non_zero[non_zero >= 3]

seurat_merged <- subset(seurat_merged, features = names(at_least_3))
```

Before subsetting, the `Assays()` function returns the three assays: RNA, ADT and HTO. However, after subsetting, I am left with only RNA and ADT.

I saw #3394, which is a similar issue, but there wasn't a solution.

Best wishes,
Lucy

`sessionInfo()`

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.2      stringr_1.4.1      dplyr_1.0.10       purrr_0.3.5       
 [5] readr_2.1.3        tidyr_1.2.1        tibble_3.1.8       ggplot2_3.3.6     
 [9] tidyverse_1.3.2    sp_1.5-0           SeuratObject_4.1.2 Seurat_4.2.0      

loaded via a namespace (and not attached):
  [1] readxl_1.4.1          backports_1.4.1       plyr_1.8.7            igraph_1.3.5         
  [5] lazyeval_0.2.2        splines_4.2.1         listenv_0.8.0         scattermore_0.8      
  [9] digest_0.6.29         htmltools_0.5.3       fansi_1.0.3           magrittr_2.0.3       
 [13] tensor_1.5            googlesheets4_1.0.1   cluster_2.1.4         ROCR_1.0-11          
 [17] tzdb_0.3.0            globals_0.16.1        modelr_0.1.9          matrixStats_0.62.0   
 [21] spatstat.sparse_2.1-1 colorspace_2.0-3      rvest_1.0.3           ggrepel_0.9.1        
 [25] haven_2.5.1           xfun_0.33             crayon_1.5.2          jsonlite_1.8.2       
 [29] progressr_0.11.0      spatstat.data_2.2-0   survival_3.4-0        zoo_1.8-11           
 [33] glue_1.6.2            polyclip_1.10-0       gtable_0.3.1          gargle_1.2.1         
 [37] leiden_0.4.3          future.apply_1.9.1    abind_1.4-5           scales_1.2.1         
 [41] DBI_1.1.3             spatstat.random_2.2-0 miniUI_0.1.1.1        Rcpp_1.0.9           
 [45] viridisLite_0.4.1     xtable_1.8-4          reticulate_1.26       spatstat.core_2.4-4  
 [49] htmlwidgets_1.5.4     httr_1.4.4            RColorBrewer_1.1-3    ellipsis_0.3.2       
 [53] ica_1.0-3             pkgconfig_2.0.3       uwot_0.1.14           dbplyr_2.2.1         
 [57] deldir_1.0-6          utf8_1.2.2            tidyselect_1.1.2      rlang_1.0.6          
 [61] reshape2_1.4.4        later_1.3.0           munsell_0.5.0         cellranger_1.1.0     
 [65] tools_4.2.1           cli_3.4.1             generics_0.1.3        broom_1.0.1          
 [69] ggridges_0.5.4        evaluate_0.17         fastmap_1.1.0         yaml_2.3.5           
 [73] goftest_1.2-3         knitr_1.40            fs_1.5.2              fitdistrplus_1.1-8   
 [77] RANN_2.6.1            pbapply_1.5-0         future_1.28.0         nlme_3.1-159         
 [81] mime_0.12             xml2_1.3.3            compiler_4.2.1        rstudioapi_0.14      
 [85] plotly_4.10.0         png_0.1-7             spatstat.utils_2.3-1  reprex_2.0.2         
 [89] stringi_1.7.8         rgeos_0.5-9           lattice_0.20-45       Matrix_1.5-1         
 [93] vctrs_0.4.2           pillar_1.8.1          lifecycle_1.0.3       spatstat.geom_2.4-0  
 [97] lmtest_0.9-40         RcppAnnoy_0.0.19      data.table_1.14.2     cowplot_1.1.1        
[101] irlba_2.3.5.1         httpuv_1.6.6          patchwork_1.1.2       R6_2.5.1             
[105] promises_1.2.0.1      renv_0.16.0           KernSmooth_2.23-20    gridExtra_2.3        
[109] parallelly_1.32.1     codetools_0.2-18      MASS_7.3-58.1         assertthat_0.2.1     
[113] withr_2.5.0           sctransform_0.3.5     mgcv_1.8-40           parallel_4.2.1       
[117] hms_1.1.2             grid_4.2.1            rpart_4.1.16          rmarkdown_2.17       
[121] googledrive_2.0.0     Rtsne_0.16            shiny_1.7.2           lubridate_1.8.0   
```

**Comment by lucygarner** [comment] 2022-10-13 10:45
https://github.com/mojaveazure/seurat-object/blob/9c0eda946e162d8595696e5280a6ecda6284db39/R/seurat.R

```
for (assay in assays) {
    assay.features <- features %||% rownames(x = x[[assay]])
    slot(object = x, name = 'assays')[[assay]] <- tryCatch(
        # because subset is also an argument, we need to explictly use the base::subset function
        expr = base::subset(x = x[[assay]], cells = cells, features = assay.features),
        error = function(e) {
            if (e$message == "Cannot find features provided") {
                return(NULL)
            } else {
                stop(e)
            }
        }
    )
}
```

I think this is returning NULL for the HTO object.

**Comment by lucygarner** [comment] 2022-10-13 10:57
I have got around this as follows.

```
seurat_merged[["RNA"]] <- subset(seurat_merged[["RNA"]], 
                                 features = names(at_least_3))
```

**Comment by Gesmira** [comment] 2023-08-23 19:21
Hi @lucygarner, closing now as it seems the issue is resolved. As you determined, the filtering was removing the HTO object due to lacking those features. Your solution seems satisfactory. Please reopen if the issue persists or you have other comments!

**Closed by Gesmira** 2023-08-23 19:21 UTC
Labels: bug
