### ISSUE TITLE
subset abnormal in a function

### ISSUE THREAD

**Issue by DawnEve** [satijalab/seurat#4058] opened 2021-02-10 14:12 UTC
```
downSample=function(SeuratObj, n=100){
    #SeuratObj=pbmc3;   n=100
    set.seed(314649593)
    sampled.cells=c()
    for(item2 in levels(SeuratObj)){
        print( paste("item2 =", item2 ) )
        small_=subset(SeuratObj, cellType == item2) #########  error here #############
        cids=colnames(small_@assays$RNA@counts)
        #
        cells.to.sample=ifelse(length(cids)>n, n, length(cids)) 
        cat( tp, "\t", length(cids),'\t', cells.to.sample, "\n")
        
        cid.tmp <- sample(x = cids, size = cells.to.sample, replace = F)
        sampled.cells=c(sampled.cells, cid.tmp)
    }
    
    # Create a vector of cells on which variable genes will be computed
    subset(SeuratObj, cells = sampled.cells)
}

# test
pbmc.small=downSample(pbmc3, n=100)
pbmc.small

[1] "item2 = CD14+ Mono"
Error in eval(expr = expr): object 'item2' not found
Traceback:

1. downSample(pbmc3, n = 100)
2. subset(SeuratObj, cellType == item2)   # at line 8 of file <text>
3. subset.Seurat(SeuratObj, cellType == item2)
4. WhichCells(object = x, cells = cells, idents = idents, expression = subset, 
 .     ...)
5. WhichCells.Seurat(object = x, cells = cells, idents = idents, 
 .     expression = subset, ...)
6. subset.data.frame(x = data.subset, subset = eval(expr = expr))
7. eval(e, x, parent.frame())
8. eval(e, x, parent.frame())
9. eval(expr = expr)
10. eval(expr = expr)
```

when not in function(){}, it works.

**Comment by mojaveazure** [comment] 2021-02-12 19:38
[As stated previously](https://github.com/satijalab/seurat/issues/1053#issuecomment-454512002), `subset` does not work in functions. In this case, it seems as though you're trying to downsample to `n` cells per identity. You can do this using `subset` as is

```R
pbmc.small <- subset(pbmc3, downsample = 100) # Downsample to a maximum of 100 cells per identity class
```

**Comment by mojaveazure** [comment] 2021-02-12 19:39
Duplicate of #1053

**Closed by mojaveazure** 2021-02-12 19:38 UTC
Labels: bug

**Comment by DawnEve** [comment] 2021-02-13 01:36
I'm new user. I searched help using F1 and Bing, but no solution.
Thanks for the explanation.
