### ISSUE TITLE
This may neglect other data.dir

### ISSUE THREAD

**Issue by DawnEve** [satijalab/seurat#5591] opened 2022-02-06 07:41 UTC
https://github.com/satijalab/seurat/blob/eaaf6750c8b1b85ea824b621596184f80ade9db3/R/preprocessing.R line 891

full.data <- list()
for (i in seq_along(along.with = data.dir)) {
   ...
  full.data[[length(x = full.data) + 1]] <- data # it seems full.data can store more than 1 data.dir
}

for (j in 1:length(x = full.data[[1]])) # but, here only the 1st will be remembered?

**Comment by andrewwbutler** [comment] 2022-05-13 23:27
Hi,

I'm not exactly sure what the issue is here. The function should properly handle the case where `data.dir` is a vector of directories. Do you have a reproducible example were that is not the case? Perhaps the confusion is coming from the fact that this also is handling multiple data types so `full.data` at that point in the code is a list of lists.

**Comment by DawnEve** [comment] 2022-05-16 14:57
I checked my notes, no hints found about this issue. Perhaps it is only a confusion that time, not a real bug.

But I find other 2 small bugs still exist in the new version: #5727, #5763,  especially the latter one.

**Comment by andrewwbutler** [comment] 2022-05-17 22:45
Ok, I will close this issue then. It looks like the PRs got closed automatically when the source repository was deleted (probably your fork of Seurat?) but we can take a look if you're able to reopen.

**Closed by andrewwbutler** 2022-05-17 22:45 UTC
Labels: bug, more-information-needed

**Comment by DawnEve** [comment] 2022-05-18 07:37
There's no reopen button on my side, either.

I opend a new PR #5970, which is the same as the old PR.
