### ISSUE TITLE
Issue with JoinLayers() and split()

### ISSUE THREAD

**Issue by SudhagarB** [satijalab/seurat#8182] opened 2023-12-13 02:40 UTC
Hi Seurat team, @saketkc 

#8153 

I have two datasets, namely Vasc_1 and Vasc_2. Prior to integration, I employ the following code. The variable features obtained are very similar to my observations in Seuratv4 and yield great results.

```
obj <- merge(vasc_1, vasc_2)
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)
vargenes <- VariableFeatures(obj)
```

However, upon combining the layers and subsequently splitting them again, I encounter a distinct set of variable genes, leading to a messy UMAP. I am not able to understand why this is happening when the layers (datasets) and matrices remain unchanged.

```
obj <- merge(vasc_1, vasc_2)
obj <- JoinLayers(obj)
obj <- split(obj, f = obj$dataset)
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)
vargenes <- VariableFeatures(obj)
```

Please advise on the optimal method for selecting features, similar to the behavior of Seuratv4 after JoinLayers() and split().

Many thanks

**Comment by SudhagarB** [comment] 2023-12-14 20:47
Hi Seurat team, @saketkc 

#8153 

I experimented with the provided codes (above) using the older V5 objects created during the Seurat V5 beta. The variable genes are consistent across both methods. However, I've encountered this problem only with the V5 objects generated using Seurat 5.0.1 and SeuratObject_5.0.1. Please advise on a resolution for this problem.

Many thanks

**Comment by Gesmira** [comment] 2023-12-21 21:07
Hi @SudhagarB, 
Currently, this is expected behavior. To give a bit of insight, when we find variable features with an object with 2 layers for example, we identify each layer's variable features, find the common variable features, and then supplement until n variable features are present in a list using the most variable features in the two lists that are also features in the other matrices. 

**To explain this process in more detail in your first vs. second scenario:** 
What you're encountering is that when you run the `JoinLayers()` command, it merges the counts into one matrix. Thus, any features that were not originally present in one matrix but were in the other, get added on as rows but filled with 0s. This would be the same as if you had merged the two counts matrices before and then created a Seurat object from those directly. 

Each individual layer's variable features stay the same across the two scenarios (and you can test this by calling `VariableFeatures` on the layer), but the behavior you're experiencing arises when we try to find a list of variable features of the object (aka both layers). 
- There will be a set of variable features that are in common between the two layers. This will stay the same between the two scenarios. 
- However, after all of these are listed, the function continues to identify variable features that are present in only one layer until it meets the requirement of n variable features. This will be different between the two scenarios because some features will be excluded in the first scenario if they are not present in both counts matrices. After joining and splitting, all features are the same in both counts matrices so none are excluded. 

In our testing, this did not cause a large difference in the features or visualizations. If you prefer the first version, perhaps there are uninformative genes that are being excluded. In that case, you can use the first version without joining and splitting. For now we will close the issue as this is expected behavior, but if you continue to run into problems that seem beyond this explanation, you may reopen.

**Closed by Gesmira** 2023-12-21 21:07 UTC
