### ISSUE TITLE
IntegrateData R Session Aborted

### ISSUE THREAD

**Issue by rodrigohermoza** [satijalab/seurat#8277] opened 2024-01-08 16:05 UTC
Hi, first of all, thanks for the amazing work you do. Now to the problem, I have a problem with the function IntegrateData. Whenever I use it, my R session is Aborted and I must start again. I wondered if you had similar problems and, hopefully, a solution. I saw that in older versions of Seurat, this happened a lot but I never saw a solution to it (except for using a more powerful computer). I am working with a dataset from GEO(https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE173706). I'm trying to replicate a paper(https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE173706) to practice and develop my skills. Sadly my computer only has 2 cores and 8 GB of RAM and it is pretty old, I still have hope that there's a solution :) .Here is my code:

```{r}
library(Seurat)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(harmony)
library(future.apply)
```

Aqui vamos a tratar de replicar lo de antes pero con otro aproach. Los siguientes dos bloques de codigo son útiles pero no funcionan correctamente ya sea en compilación o en velocidad

```{r}
data1<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277170_NS-AR001.csv.gz")
data2<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277171_NS-AR003.csv.gz")
data3<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277172_NS-AR004.csv.gz")
data4<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277173_NS-AR005.csv.gz")
data5<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277174_NS-AR006.csv.gz")
data6<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277175_NS-AR007.csv.gz")
data7<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277176_NS-AR008.csv.gz")
data8<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277177_NS-AR009.csv.gz")
data9<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277178_PN-30696.csv.gz")
data10<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277179_PN-30696V3.csv.gz")
data11<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277180_PN-31170.csv.gz")
data12<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277181_PN-31277.csv.gz")
data13<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277182_PN-369PC.csv.gz")
data14<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277183_PN-5851.csv.gz")
data15<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277184_PN-7802ED.csv.gz")
data16<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277185_PN-8659ED.csv.gz")
data17<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277186_PN-8940.csv.gz")
data18<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277187_PN-929.csv.gz")
data19<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277188_PN-9709PC.csv.gz")
data20<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277189_PP-30696.csv.gz")
data21<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277190_PP-30696V3.csv.gz")
data22<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277191_PP-31170.csv.gz")
data23<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277192_PP-31277.csv.gz")
data24<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277193_PP-31499.csv.gz")
data25<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277194_PP-369PC.csv.gz")
data26<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277195_PP-5851.csv.gz")
data27<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277196_PP-6215A.csv.gz")
data28<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277197_PP-6215B.csv.gz")
data29<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277198_PP-7802ED.csv.gz")
data30<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277199_PP-8659ED.csv.gz")
data31<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277200_PP-8940.csv.gz")
data32<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277201_PP-929.csv.gz")
data33<-read.csv("/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW/GSM5277202_PP-9709PC.csv.gz")
```

```{r}
# Directorio de destino
dest_dir <- "/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW"

# Lista para almacenar los datos
data_list <- list()

# Nombres de los archivos
file_list <- c(
  "GSM5277170_NS-AR001.csv.gz", "GSM5277171_NS-AR003.csv.gz", "GSM5277172_NS-AR004.csv.gz",
  "GSM5277173_NS-AR005.csv.gz", "GSM5277174_NS-AR006.csv.gz", "GSM5277175_NS-AR007.csv.gz",
  "GSM5277176_NS-AR008.csv.gz", "GSM5277177_NS-AR009.csv.gz", "GSM5277178_PN-30696.csv.gz",
  "GSM5277179_PN-30696V3.csv.gz", "GSM5277180_PN-31170.csv.gz", "GSM5277181_PN-31277.csv.gz",
  "GSM5277182_PN-369PC.csv.gz", "GSM5277183_PN-5851.csv.gz", "GSM5277184_PN-7802ED.csv.gz",
  "GSM5277185_PN-8659ED.csv.gz", "GSM5277186_PN-8940.csv.gz", "GSM5277187_PN-929.csv.gz",
  "GSM5277188_PN-9709PC.csv.gz", "GSM5277189_PP-30696.csv.gz", "GSM5277190_PP-30696V3.csv.gz",
  "GSM5277191_PP-31170.csv.gz", "GSM5277192_PP-31277.csv.gz", "GSM5277193_PP-31499.csv.gz",
  "GSM5277194_PP-369PC.csv.gz", "GSM5277195_PP-5851.csv.gz", "GSM5277196_PP-6215A.csv.gz",
  "GSM5277197_PP-6215B.csv.gz", "GSM5277198_PP-7802ED.csv.gz", "GSM5277199_PP-8659ED.csv.gz",
  "GSM5277200_PP-8940.csv.gz", "GSM5277201_PP-929.csv.gz", "GSM5277202_PP-9709PC.csv.gz"
)

# Leer y almacenar cada conjunto de datos en la lista
for (file in file_list) {
  csv_path <- file.path(dest_dir, file)
  data_list[[file]] <- read.csv(csv_path, header = TRUE, row.names = 1)
}

# Puedes acceder a los conjuntos de datos usando data_list$GSM5277170_NS-AR001.csv.gz, por ejemplo.

```

Una forma más eficiente aún:
```{r}
# Nombres de los archivos
file_list <- c(
  "GSM5277170_NS-AR001.csv.gz", "GSM5277171_NS-AR003.csv.gz", "GSM5277172_NS-AR004.csv.gz",
  "GSM5277173_NS-AR005.csv.gz", "GSM5277174_NS-AR006.csv.gz", "GSM5277175_NS-AR007.csv.gz",
  "GSM5277176_NS-AR008.csv.gz", "GSM5277177_NS-AR009.csv.gz", "GSM5277178_PN-30696.csv.gz",
  "GSM5277179_PN-30696V3.csv.gz", "GSM5277180_PN-31170.csv.gz", "GSM5277181_PN-31277.csv.gz",
  "GSM5277182_PN-369PC.csv.gz", "GSM5277183_PN-5851.csv.gz", "GSM5277184_PN-7802ED.csv.gz",
  "GSM5277185_PN-8659ED.csv.gz", "GSM5277186_PN-8940.csv.gz", "GSM5277187_PN-929.csv.gz",
  "GSM5277188_PN-9709PC.csv.gz", "GSM5277189_PP-30696.csv.gz", "GSM5277190_PP-30696V3.csv.gz",
  "GSM5277191_PP-31170.csv.gz", "GSM5277192_PP-31277.csv.gz", "GSM5277193_PP-31499.csv.gz",
  "GSM5277194_PP-369PC.csv.gz", "GSM5277195_PP-5851.csv.gz", "GSM5277196_PP-6215A.csv.gz",
  "GSM5277197_PP-6215B.csv.gz", "GSM5277198_PP-7802ED.csv.gz", "GSM5277199_PP-8659ED.csv.gz",
  "GSM5277200_PP-8940.csv.gz", "GSM5277201_PP-929.csv.gz", "GSM5277202_PP-9709PC.csv.gz"
)

# Directorio de destino
dest_dir <- "/Users/rodrigohermoza/Desktop/UTEC/2024-0/PoliSia/rstudio/scrna-seq-3-reproduction/tercera-reproduction/GSE173706_RAW"

# Lista para almacenar los datos (lectura paralela)
data_list <- future_lapply(file.path(dest_dir, file_list), read.csv, header = TRUE, row.names = 1)

# Puedes acceder a los conjuntos de datos usando data_list[[1]], data_list[[2]], etc.
```

Conseguimos los nombre de los documentos
```{r}
file_list_cleaned <- gsub(".csv.gz", "", file_list)
```
vamos a ver si se puede usar esos nombres
```{r}
for (x in c(1:33)) {
  name<-file_list_cleaned[x]
  assign(name, CreateSeuratObject( counts = data_list[[x]]))
}
```

Unimos los objetos Seurat en uno solo:

```{r}
merged_obj_seurat <- merge(
  `GSM5277170_NS-AR001`, 
  y = list(
    `GSM5277171_NS-AR003`, 
    `GSM5277172_NS-AR004`, 
    `GSM5277173_NS-AR005`, 
    `GSM5277174_NS-AR006`, 
    `GSM5277175_NS-AR007`,
    `GSM5277176_NS-AR008`,
    `GSM5277177_NS-AR009`,
    `GSM5277178_PN-30696`,
    `GSM5277179_PN-30696V3`,
    `GSM5277180_PN-31170`,
    `GSM5277181_PN-31277`,
    `GSM5277182_PN-369PC`,
    `GSM5277183_PN-5851`,
    `GSM5277184_PN-7802ED`,
    `GSM5277185_PN-8659ED`,
    `GSM5277186_PN-8940`,
    `GSM5277187_PN-929`,
    `GSM5277188_PN-9709PC`,
    `GSM5277189_PP-30696`,
    `GSM5277190_PP-30696V3`,
    `GSM5277191_PP-31170`,
    `GSM5277192_PP-31277`,
    `GSM5277193_PP-31499`,
    `GSM5277194_PP-369PC`,
    `GSM5277195_PP-5851`,
    `GSM5277196_PP-6215A`,
    `GSM5277197_PP-6215B`,
    `GSM5277198_PP-7802ED`,
    `GSM5277199_PP-8659ED`,
    `GSM5277200_PP-8940`,
    `GSM5277201_PP-929`,
    `GSM5277202_PP-9709PC`
  ),
  add.cell.ids = c(
    "GSM5277170_NS-AR001", 
    "GSM5277171_NS-AR003", 
    "GSM5277172_NS-AR004", 
    "GSM5277173_NS-AR005", 
    "GSM5277174_NS-AR006", 
    "GSM5277175_NS-AR007",
    "GSM5277176_NS-AR008",
    "GSM5277177_NS-AR009",
    "GSM5277178_PN-30696",
    "GSM5277179_PN-30696V3",
    "GSM5277180_PN-31170",
    "GSM5277181_PN-31277",
    "GSM5277182_PN-369PC",
    "GSM5277183_PN-5851",
    "GSM5277184_PN-7802ED",
    "GSM5277185_PN-8659ED",
    "GSM5277186_PN-8940",
    "GSM5277187_PN-929",
    "GSM5277188_PN-9709PC",
    "GSM5277189_PP-30696",
    "GSM5277190_PP-30696V3",
    "GSM5277191_PP-31170",
    "GSM5277192_PP-31277",
    "GSM5277193_PP-31499",
    "GSM5277194_PP-369PC",
    "GSM5277195_PP-5851",
    "GSM5277196_PP-6215A",
    "GSM5277197_PP-6215B",
    "GSM5277198_PP-7802ED",
    "GSM5277199_PP-8659ED",
    "GSM5277200_PP-8940",
    "GSM5277201_PP-929",
    "GSM5277202_PP-9709PC"
  ),
  project = "tercera"
)
```

Ahora vamos a manipular el nombre y modificar nuestra data para empezar el analisis

```{r}
merged_obj_seurat$Sample <- rownames(merged_obj_seurat@meta.data)
```

```{r}
merged_obj_seurat@meta.data <- separate(merged_obj_seurat@meta.data, col = "Sample", into = c("Patient","Type", "Barcode"), sep = "_")
```

#Analisis

Quality control

```{r}
merged_obj_seurat$mitoPercent <- PercentageFeatureSet(merged_obj_seurat, pattern = "^MT-")
filtered_obj_seurat <- subset(merged_obj_seurat, subset = nFeature_RNA > 500 & mitoPercent <10 & nCount_RNA > 100)
```

Normalization
```{r}
filtered_obj_seurat <- NormalizeData(filtered_obj_seurat)
```

Seleccionar genes variables
```{r}
variable_genes <- FindVariableFeatures(filtered_obj_seurat)
```
The FindIntegrationAnchors and IntegrateData functions were used to integrate the samples prepared using different 10X Chromium che- mistries.

```{r}
# Crear una lista de objetos Seurat
seurat_list <- lapply(seq_along(data_list), function(i) {
  name <- file_list_cleaned[i]
  CreateSeuratObject(counts = data_list[[i]])
})

anchors <- FindIntegrationAnchors(object.list = seurat_list)
```

```{r}
integrated_obj_seurat <- IntegrateData(anchorset = anchors)
```

**Comment by Gesmira** [comment] 2024-06-24 15:17
Hi @rodrigohermoza,

Thank you for reaching out! We’re always grateful when folks take the time to post issues and help make Seurat better 🙂

Unfortunately, with the details provided, we cannot reproduce your issue. To help us better understand and resolve this issue, please ensure that you provide the following information when reporting a bug:

1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.  
    
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
    
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the  
    
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.

We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost and we will be more than happy to help you resolve the problem.

**Closed by Gesmira** 2024-06-24 15:17 UTC
Labels: bug
