### ISSUE TITLE
Error while making Dimplot when using split.by in Sketch based Seurat V5 analysis.

### ISSUE THREAD

**Issue by vishnums007** [satijalab/seurat#7645] opened 2023-08-04 17:48 UTC
Hi, 
I am trying adopt the new seurat v5 for all my previously analyzed datasets. However, I am facing an issue while plotting the umap plot with split.by argument. 

DimPlot(zebra, reduction = "umap_cca", split.by = "Timepoint")
Warning message:
In `[<-.data.frame`(`*tmp*`, , split.by, value = list(Timepoint = c(1L,  :
  replacement element 1 has 73814 rows to replace 20000 rows

As result, my umap plot only shows 2 timepoints, 

![image](https://github.com/satijalab/seurat/assets/81267539/78e7223d-8079-41b6-801b-8c815ebeffce)

There are 4 timepoints in the dataset.
Here is my code trying to adopt sketch based analysis 

################################################################################################
Step 1: trying to convert my old seurat object to new seurat v5

library(BPCells)
library(Seurat)

options(Seurat.object.assay.version = "v5")
options(future.globals.maxSize = 3e+09)

zebra<- readRDS(file="ekab_uninj136_complete_labelled.rds")
write_matrix_dir(mat = zebra@assays$RNA@counts, dir = "rna_counts_ekab_full_BP")
metadata<- zebra@meta.data
counts.mat<- open_matrix_dir(dir = "rna_counts_ekab_full_BP")
zebrav5<- CreateSeuratObject(counts = counts.mat, meta.data = metadata)
saveRDS(object = zebrav5, file = "rna_counts_ekab_full_BP/ekab_uninj136_complete_labelled_v5.rds")

###########################################################################################
Step 2: Splitting my data based on different replicates and timepoints and performing different methods of integration.

library(BPCells)
library(Seurat)
library(ggplot2)

options(Seurat.object.assay.version = "v5")
options(future.globals.maxSize = 3e+09)

zebra<-readRDS(file ="rna_counts_ekab_full_BP/ekab_uninj136_complete_labelled_v5.rds")
zebra<- NormalizeData(zebra)
zebra[["RNA"]]<-split(zebra[["RNA"]], f=zebra$orig.ident)
zebra <- FindVariableFeatures(zebra)
zebra<- SketchData(object = zebra, ncells = 2500, method = "LeverageScore", sketched.assay = "sketch")
DefaultAssay(zebra) <- "sketch"
zebra<- ScaleData(zebra)
zebra <- RunPCA(zebra, verbose = T,npcs =50)
zebra <- IntegrateLayers(
  object = zebra, method = CCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.cca",
  verbose = T
)
zebra <- IntegrateLayers(
  object = zebra, method = RPCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.rpca",
  verbose = FALSE
)

zebra <- IntegrateLayers(
  object = zebra, method = HarmonyIntegration,
  orig.reduction = "pca", new.reduction = "harmony",
  verbose = FALSE
)

ElbowPlot(zebra,ndims = 50,reduction="pca")
ggsave("Elbowplot_50.png", width = 10, height =8,  dpi = 300)

write.csv(zebra@meta.data, file="ekab_uninj136_integrated_metadata.csv")
saveRDS(zebra, file = "rna_counts_ekab_full_BP/ekab_uninj136_integrated_v5.rds")

###############################################################################################
Step 3: Plotting the umap plot
library(dplyr)
library(Seurat)
library(ggplot2)
library(clustree)
options(java.parameters = "-Xmx16000m")
library(xlsx)
library(BPCells)

options(Seurat.object.assay.version = "v5")
options(future.globals.maxSize = 3e+09)

zebra<- readRDS(file = "rna_counts_ekab_full_BP/ekab_uninj136_integrated_v5.rds")
zebra<- FindNeighbors(zebra, reduction="integrated.cca", dims = 1:50)
zebra <- FindClusters(zebra, resolution = 1)
zebra <- RunUMAP(zebra, reduction = "integrated.cca", dims = 1:50, return.model = T, verbose = T, reduction.name = "umap_cca")
DimPlot(zebra, reduction = "umap_cca", split.by = "Timepoint")

################################################################################
And here is where the error is happening is happening, I am not sure what wrong here. 
Please help me. 
###############################################################################

> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xlsx_0.6.5              clustree_0.5.0          ggraph_2.1.0            dplyr_1.1.2             ggplot2_3.4.2          
[6] Seurat_4.9.9.9058       SeuratObject_4.9.9.9091 sp_2.0-0                BPCells_0.1.0          

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3     rstudioapi_0.15.0      jsonlite_1.8.7         magrittr_2.0.3         spatstat.utils_3.0-3  
  [6] farver_2.1.1           ragg_1.2.5             vctrs_0.6.3            ROCR_1.0-11            spatstat.explore_3.2-1
 [11] htmltools_0.5.5        sctransform_0.3.5      parallelly_1.36.0      KernSmooth_2.23-21     htmlwidgets_1.6.2     
 [16] ica_1.0-3              plyr_1.8.8             plotly_4.10.2          zoo_1.8-12             igraph_1.5.0.1        
 [21] mime_0.12              lifecycle_1.0.3        pkgconfig_2.0.3        Matrix_1.5-4.1         R6_2.5.1              
 [26] fastmap_1.1.1          fitdistrplus_1.1-11    future_1.33.0          shiny_1.7.4.1          digest_0.6.33         
 [31] colorspace_2.1-0       patchwork_1.1.2        tensor_1.5             RSpectra_0.16-1        irlba_2.3.5.1         
 [36] textshaping_0.3.6      labeling_0.4.2         progressr_0.13.0       fansi_1.0.4            spatstat.sparse_3.0-2 
 [41] httr_1.4.6             polyclip_1.10-4        abind_1.4-5            compiler_4.3.1         withr_2.5.0           
 [46] viridis_0.6.4          fastDummies_1.7.3      ggforce_0.4.1          MASS_7.3-60            tools_4.3.1           
 [51] lmtest_0.9-40          httpuv_1.6.11          future.apply_1.11.0    goftest_1.2-3          glue_1.6.2            
 [56] nlme_3.1-162           promises_1.2.0.1       grid_4.3.1             Rtsne_0.16             cluster_2.1.4         
 [61] reshape2_1.4.4         generics_0.1.3         gtable_0.3.3           spatstat.data_3.0-1    tidyr_1.3.0           
 [66] data.table_1.14.8      tidygraph_1.2.3        utf8_1.2.3             spatstat.geom_3.2-4    RcppAnnoy_0.0.21      
 [71] ggrepel_0.9.3          RANN_2.6.1             pillar_1.9.0           stringr_1.5.0          spam_2.9-1            
 [76] RcppHNSW_0.4.1         later_1.3.1            rJava_1.0-6            splines_4.3.1          tweenr_2.0.2          
 [81] lattice_0.21-8         survival_3.5-5         deldir_1.0-9           tidyselect_1.2.0       miniUI_0.1.1.1        
 [86] pbapply_1.7-2          gridExtra_2.3          scattermore_1.2        graphlayouts_1.0.0     matrixStats_1.0.0     
 [91] stringi_1.7.12         lazyeval_0.2.2         xlsxjars_0.6.1         codetools_0.2-19       tibble_3.2.1          
 [96] cli_3.6.1              uwot_0.1.16            xtable_1.8-4           reticulate_1.30        systemfonts_1.0.4     
[101] munsell_0.5.0          harmony_0.1.1          Rcpp_1.0.11            globals_0.16.2         spatstat.random_3.1-5 
[106] png_0.1-8              parallel_4.3.1         ellipsis_0.3.2         dotCall64_1.0-2        listenv_0.9.0         
[111] viridisLite_0.4.2      scales_1.2.1           ggridges_0.5.4         leiden_0.4.3           purrr_1.0.1           
[116] rlang_1.1.1

**Comment by longmanz** [comment] 2023-08-04 19:17
Hi,
Unfortunately we cannot reproduce this issue from our end. Have you confirmed if there are indeed 4 levels of "Timepoint" in your meta.data? Also, it would be helpful if you can provide a minimal dataset that reproduces this issue to us. Thank you!

**Comment by vishnums007** [comment] 2023-08-04 22:15
@longmanz , thank you so much for the quick response. 
I have uploaded a minimial dataset that reproduces the error[ here,](https://wustl.box.com/s/33736a3dlf9l1qsh5obrkoj11r5pu2zy) .

I also include the codes that I used.

**Comment by vishnums007** [comment] 2023-08-06 04:03
I figured it out, The split by argument won't work since the seurat_clusters column has lots of NAs since it assign cluster number only for those cells in the sketch. This caused the warning message. Once, I projected Integration and data, I can set the identity as cluster_full and then, the split.by argument works just fine.

**Comment by longmanz** [comment] 2023-08-16 20:45
Thank you for your response! I am closing this issue now.

**Closed by longmanz** 2023-08-16 20:45 UTC
