### ISSUE TITLE
Generating an integrated Seurat object from multiple velocyto-generateed .loom files

### ISSUE THREAD

**Issue by vitamindlab** [satijalab/seurat#3660] opened 2020-10-28 22:40 UTC
I am attempting to run RNA Velocity. I have three datasets (day 0, day 1, day 2) and I have generated three .loom files, one for each dataset, using velocyto. I have been able to generate Seurat objects for each .loom file individually and went forward with RNA Velocity on each of these. However, I want to run RNA Velocity on the combined dataset. However, I have not been able to integrate the three .loom files. Is this possible? If so, how do I do this?

Any help would be greatly appreciated.

**Comment by vitamindlab** [comment] 2020-10-28 23:01
Here is my code:

MSCday0<- ReadVelocity(file = "Desktop/velocyto-day0/velocyto-day0.loom")
Vday0 <- as.Seurat(x = MSCday0)
Vday0[["RNA"]] <- Vday0[["spliced"]]
Vday0[["percent.mt"]] <- PercentageFeatureSet(Vday0,pattern = "^MT-")
VlnPlot(Vday0,features = c("nFeature_spliced", "nCount_spliced","percent.mt"), ncol = 3)
Vday0 <- subset(Vday0, subset = nFeature_spliced> 2000 & nFeature_spliced < 7000 & percent.mt < 20)  

MSCday1<- ReadVelocity(file = "Desktop/velocyto-day1/velocyto-day1.loom")
Vday1 <- as.Seurat(x = MSCday1)
Vday1[["RNA"]] <- Vday1[["spliced"]]
Vday1[["percent.mt"]] <- PercentageFeatureSet(Vday1,pattern = "^MT-")
VlnPlot(Vday1,features = c("nFeature_spliced", "nCount_spliced","percent.mt"), ncol = 3)
Vday1 <- subset(Vday1, subset =nFeature_spliced > 1500 & nFeature_spliced < 7000 & percent.mt < 20)  

MSCday2<- ReadVelocity(file = "Desktop/velocyto-day2/velocyto-day2.loom")
Vday2 <- as.Seurat(x = MSCday2)
Vday2[["RNA"]] <- Vday2[["spliced"]
]Vday2[["percent.mt"]] <- PercentageFeatureSet(Vday2,pattern = "^MT-")
VlnPlot(Vday2,features = c("nFeature_spliced", "nCount_spliced","percent.mt"), ncol = 3)
Vday2 <- subset(Vday2, subset =nFeature_spliced > 1500 & nFeature_spliced < 7000 & percent.mt < 20)

Msc.combined <- merge(Vday0,y = c(Vday1, Vday2), add.cell.ids = c("Day0", "Day1","Day2"), project = "Day0_1_2")
msc.list <-SplitObject(Msc.combined, split.by ="orig.ident")
for (i in 1:length(msc.list)){msc.list[[i]] <- SCTransform(msc.list[[i]], assay = "spliced")}
msc.features <-SelectIntegrationFeatures(object.list = msc.list, nfeatures = 3000, assay = "SCT")
msc.list <-PrepSCTIntegration(object.list = msc.list, anchor.features = msc.features, assay= "SCT")
msc.anchors<- FindIntegrationAnchors(object.list = msc.list, normalization.method = "SCT",anchor.features = msc.features)

*It is at this point that I get the following error:
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Error in which(x = object.classes, useNames = TRUE) : 
  argument to 'which' is not logical

**Comment by andrewwbutler** [comment] 2020-10-30 18:55
Hi,

This should be possible. Are you able to share a reproducible example?

**Comment by vitamindlab** [comment] 2020-11-13 21:59
Hi, I am not sure what you mean be a reproducible example. Can you clarify?

**Comment by andrewwbutler** [comment] 2020-11-18 16:37
If you're able to provide an example (code + data) that we can run on our end which results in the same error, that would be very helpful in terms of identifying/resolving the problem. If you are able to share the data you used in the code examples above, that would work. Feel free to post a download link here or email (abutler@nygenome.org).

**Comment by vitamindlab** [comment] 2020-11-18 18:40
I have just sent an email with the data files. Let me know if there is an issue downloading them and I can look into alternate ways of providing you the data.

**Comment by andrewwbutler** [comment] 2020-11-18 21:48
Thanks for sending the data. It looks like your problem comes from these lines

```R
Msc.combined <- merge(Vday0,y = c(Vday1, Vday2), add.cell.ids = c("Day0", "Day1","Day2"), project = "Day0_1_2")
msc.list <-SplitObject(Msc.combined, split.by ="orig.ident")
```
If you want to run the integration workflow, you need to provide an object list that contains more than one object. At this point, splitting by `orig.ident` results in a single object.

**Comment by vitamindlab** [comment] 2020-11-18 21:55
Thanks so much for your quick response and for your identification of the issue. 

What alteration do I need to make to the two lines of code to ensure that the object list contains all three objects?

**Comment by andrewwbutler** [comment] 2020-11-18 23:12
I assume what you want here is probably:

```R
msc.list <- list(Vday0, Vday1, Vday2)
```

**Comment by mojaveazure** [comment] 2021-01-08 19:32
Hi @vitamindlab, just pinging on the status of this. Did Andrew's proposal solve the issue for you?

**Closed** 2021-01-22 20:07 UTC
Labels: more-information-needed
