### ISSUE TITLE
subset ： Error: No cells found

### ISSUE THREAD

**Issue by suhuanhou** [satijalab/seurat#7448] opened 2023-06-14 07:04 UTC
I want to extract a subset of the seurat object (d1) and the subset command gives an error, how can I fix it? It is better to keep the meta.data information.

> head(d1[["status"]])
      status
1    singlet
2    singlet
3    doublet
4 unassigned
5    singlet
6    singlet

> d2 <- subset(x = d1, subset = status == "singlet")
Error: No cells found

**Comment by mhkowalski** [comment] 2023-06-16 19:19
Could you provide a reproducible example of this, such as with pbmc_small? I am not able to reproduce this, as this line works for me.

**Comment by mhkowalski** [comment] 2023-06-30 19:26
Hi, 

I am closing this due to lack of a response. Please let us know if you are continuing to have problems.

**Closed by mhkowalski** 2023-06-30 19:26 UTC
Labels: more-information-needed
