### ISSUE TITLE
Error Normalizing data for ADT assay when seurat object contains multiple samples

### ISSUE THREAD

**Issue by NNazeu** [satijalab/seurat#9196] opened 2024-08-09 08:20 UTC
I am working with Seurat v5.0 and created my Seurat object which contains 2 assays, RNA and ADT for 10 samples. This is a simplification of the main steps in which I create my seurat object, add the ADT assay.
```
hdf5 = parallel::mclapply(Sample_Ntop,function(sample){
      Seurat::Read10X_h5(filename = paste0(sample,'/sample_filtered_feature_bc_matrix.h5'),
                         use.names = TRUE,
                         unique.features = TRUE)}
      ,mc.cores = length(Sample_Ntop))
      
counts.rna <- lapply(hdf5, `[[`, 'Gene Expression')
counts.adt <- lapply(hdf5, `[[`, 'Antibody Capture')

seurat.obj <- CreateSeuratObject(counts = counts.rna, project = yml$SeuratProjectName, min.cells = 3, min.features = 200)
adt_assay <- CreateAssay5Object(counts = counts.adt)
seurat.harmonized@assays$ADT <- adt_assay
```
When I then try to run the normalization on the ADT assay I encounter this error:
```
seurat.harmonized <- NormalizeData(seurat.harmonized,assay = "ADT", normalization.method = "CLR", margin = 2)
Normalizing layer: counts
Normalizing across cells
  |==================================================| 100% elapsed=00s  
Error in vapply(X = .FilterObjects(object = object, classes.keep = c("Assay",  : 
  values must be length 1,
 but FUN(X[[2]]) result is length 0
 ```
I've tried to follow the documentation in [https://satijalab.org/seurat/articles/multimodal_vignette.html#additional-visualizations-of-multimodal-data](url) using only one of my samples (out of the 10) and it works without errors.
```
pbmc10k.data <- Read10X(data.dir = "sample1/sample_filtered_feature_bc_matrix/")
pbmc10k <- CreateSeuratObject(counts = pbmc10k.data[["Gene Expression"]], min.cells = 3, min.features = 200)
pbmc10k <- NormalizeData(pbmc10k)
pbmc10k[["ADT"]] <- CreateAssayObject(pbmc10k.data[["Antibody Capture"]][, colnames(x = pbmc10k)])
pbmc10k <- NormalizeData(pbmc10k, assay = "ADT", normalization.method = "CLR")
```

**Comment by adyzh** [comment] 2024-10-11 19:55
Hi @NNazeu ,
Thank you for reaching out! We’re always grateful when folks take the time to help make Seurat better :slightly_smiling_face:
Unfortunately, with the details provided, we cannot reproduce your issue. To help us better understand and resolve this issue, please ensure that you provide the following information when reporting a bug:
1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.
We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost and we will be more than happy to help you resolve the problem.

**Closed by adyzh** 2024-10-11 19:55 UTC
