### ISSUE TITLE
RunCCA error

### ISSUE THREAD

**Issue by KingstonData** [satijalab/seurat#1074] opened 2019-01-18 23:35 UTC
Hello,

I'm trying to merge two 10x single nuclei RNAseq data sets from the same tissue in two difference conditions.

When I tried to RunCCA using Seurat v3.0, the following error was displayed:
Error in cca.results$ccv[colnames(combined.object), ] : 
  subscript out of bounds

Any help would be appreciated!

Code:
> g.1 <-head(rownames(HVFInfo(object = doca)), n = 1000)
> g.2 <-head(rownames(HVFInfo(object = sham)), n = 1000)
> genes.use <-union(c(g.1, g.2))
Error in as.vector(y) : argument "y" is missing, with no default
> genes.use <-unique(c(g.1, g.2))
> genes.use <-intersect(genes.use, rownames(GetAssayData(object = doca, slot = "scale.data")))
> genes.use <-intersect(genes.use, rownames(GetAssayData(object = sham, slot = "scale.data")))
> arc_combined <- RunCCA(sham, doca, features = genes.use, num.cc = 30)
Running CCA
Merging objects
Error in cca.results$ccv[colnames(combined.object), ] : 
  subscript out of bounds

**Comment by KingstonData** [comment] 2019-01-20 19:37
Hello Tim,

Here are the info requested:

> length(genes.use)
[1] 1000
> traceback()
5: is.data.frame(x)
4: colnames(x = embeddings)
3: CreateDimReducObject(embeddings = cca.results$ccv[colnames(combined.object), 
       ], assay = assay1, key = "CC_")
2: RunCCA.Seurat(object1 = sham, object2 = doca, genes.use = genes.use, 
       num.cc = 30)
1: RunCCA(object1 = sham, object2 = doca, genes.use = genes.use, 
       num.cc = 30)
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Seurat_3.0.0.9000

loaded via a namespace (and not attached):
 [1] httr_1.4.0          tidyr_0.8.2         viridisLite_0.3.0  
 [4] jsonlite_1.6        splines_3.5.2       lsei_1.2-0         
 [7] R.utils_2.7.0       gtools_3.8.1        Rdpack_0.10-1      
[10] assertthat_0.2.0    ggrepel_0.8.0       globals_0.12.4     
[13] pillar_1.3.1        lattice_0.20-38     reticulate_1.10    
[16] glue_1.3.0          digest_0.6.18       RColorBrewer_1.1-2 
[19] SDMTools_1.1-221    colorspace_1.4-0    cowplot_0.9.4      
[22] htmltools_0.3.6     Matrix_1.2-15       R.oo_1.22.0        
[25] plyr_1.8.4          pkgconfig_2.0.2     bibtex_0.4.2       
[28] tsne_0.1-3          listenv_0.7.0       purrr_0.2.5        
[31] scales_1.0.0        RANN_2.6.1          gdata_2.18.0       
[34] Rtsne_0.15          tibble_2.0.1        ggplot2_3.1.0      
[37] ROCR_1.0-7          pbapply_1.3-4       lazyeval_0.2.1     
[40] survival_2.43-3     magrittr_1.5        crayon_1.3.4       
[43] R.methodsS3_1.7.1   future_1.10.0       nlme_3.1-137       
[46] MASS_7.3-51.1       gplots_3.0.1        ica_1.0-2          
[49] tools_3.5.2         fitdistrplus_1.0-11 data.table_1.12.0  
[52] gbRd_0.4-11         stringr_1.3.1       plotly_4.8.0       
[55] munsell_0.5.0       cluster_2.0.7-1     irlba_2.3.2        
[58] bindrcpp_0.2.2      compiler_3.5.2      rsvd_1.0.0         
[61] caTools_1.17.1.1    rlang_0.3.1         grid_3.5.2         
[64] ggridges_0.5.1      rstudioapi_0.9.0    htmlwidgets_1.3    
[67] igraph_1.2.2        bitops_1.0-6        npsurv_0.4-0       
[70] gtable_0.2.0        codetools_0.2-15    R6_2.3.0           
[73] zoo_1.8-4           dplyr_0.7.8         future.apply_1.1.0 
[76] bindr_0.1.1         KernSmooth_2.23-15  metap_1.0          
[79] ape_5.2             stringi_1.2.4       parallel_3.5.2     
[82] Rcpp_1.0.0          png_0.1-7           tidyselect_0.2.5   
[85] lmtest_0.9-36      
> length(intersect(sham@cell.names, doca@cell.names))
Error in as.vector(y) : 
  no slot of name "cell.names" for this object of class "Seurat"
> length(intersect(colnames(sham), colnames(doca)))
[1] 21

I am using Seurat v3 since I've used Cell Ranger 3 to generate the barcode, features, and matrix files for my samples. I've adopted the commands to Seurat v3 used in this tutorial: https://satijalab.org/seurat/immune_alignment.html to align my samples. If it helps, I've provide the commands I've used:

> setwd("C:/Users/eyeso/Desktop/DOCA_ARC snRNA")
> library(Seurat)
> doca.dir <-"C:/Users/eyeso/Desktop/DOCA_ARC snRNA/DOCA_53915393/filtered_feature_bc_matrix"
> list.files(doca.dir)
[1] "barcodes.tsv.gz" "features.tsv.gz" "matrix.mtx.gz"  
> doca.data <-Read10X(data.dir = doca.dir)
10X data contains more than one type and is being returned as a list containing matrices of each type.
> doca <-CreateSeuratObject(counts = doca.data)
> sham.dir <-"C:/Users/eyeso/Desktop/DOCA_ARC snRNA/Sham_54125403/filtered_feature_bc_matrix"
> list.files(sham.dir)
[1] "barcodes.tsv.gz" "features.tsv.gz" "matrix.mtx.gz"  
> sham.data <-Read10X(data.dir = sham.dir)
10X data contains more than one type and is being returned as a list containing matrices of each type.
> sham <-CreateSeuratObject(counts = sham.data)
> doca <-NormalizeData(doca)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> doca <-ScaleData(doca)
Scaling data matrix
  |===============================================================| 100%
> sham <-NormalizeData(sham)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> sham <-ScaleData(sham)
Scaling data matrix
  |===============================================================| 100%
> doca <-FindVariableFeatures(object = doca, selection.method = "vst", nfeatures = 1000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> sham <-FindVariableFeatures(object = sham, selection.method = "vst", nfeatures = 1000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> g.1 <-head(rownames(HVFInfo(object = doca)), n = 1000)
> g.2 <-head(rownames(HVFInfo(object = sham)), n = 1000)
> genes.use <-unique(c(g.1,g.2))
> genes.use <-intersect(genes.use, rownames(GetAssayData(object = doca, slot = "scale.data")))
> genes.use <-intersect(genes.use, rownames(GetAssayData(object = sham, slot = "scale.data")))
> sham@meta.data$doca <- "Sham"
> doca@meta.data$doca <- "Doca"
> genes.use <-intersect(genes.use, rownames(GetAssayData(object = sham, slot = "scale.data")))
> genes.use <-intersect(genes.use, rownames(GetAssayData(object = doca, slot = "scale.data")))
> arc.combined <- RunCCA(object1 = sham, object2 = doca, genes.use=genes.use, num.cc = 30)
Running CCA
Merging objects
Error in cca.results$ccv[colnames(combined.object), ] : 
  subscript out of bounds

Thank you very much for all the help!

**Comment by timoast** [comment] 2019-01-21 00:02
Ok since you have non-unique cell names in the two objects can you try adding a cell ID prefix in the RunCCA call? For example:

```r
RunCCA(object1 = sham, object2 = doca, genes.use=genes.use, num.cc = 30, add.cell.id1='sham', add.cell.id2='doca')
```

By the way, in Seurat v3 you can add metadata just using the `$` operator, so your line `sham@meta.data$doca <- "Sham"` can be replaced with `sham$doca <- "Sham"` (this is unrelated to the issue just a tip)

**Comment by KingstonData** [comment] 2019-01-21 00:14
Thanks for the advice, Tim.

Unfortunately, after running adding cell ID prefix, the error still persists:

> arc.combined <- RunCCA(object1 = sham, object2 = doca, genes.use=genes.use, num.cc = 30, add.cell.id1='sham', add.cell.id2='doca')
Running CCA
Merging objects
Error in cca.results$ccv[colnames(combined.object), ] : 
  subscript out of bounds

**Comment by aaronliuUBC** [comment] 2019-01-23 01:11
Hi Tim,

I am having the exact same issue with 10X data too. I haven't seen this issue before when I have used RunCCA on v2.3.4. Although my data is a little bit different, I am still comparing two groups in this case Adult v. Cord blood cells. Could the fix simply be adding the cell names in the beginning when creating the seurat object?

I would like to use V3 to do the analysis of this dataset, but might have to revert back to v2.3.4.

**Comment by timoast** [comment] 2019-01-24 17:40
@KingstonData it's difficult to work out what the problem is without access to a dataset that reproduces the error, so if you're open to sharing your dataset (or a minimal version that still gives this error) for the purposes of debugging you can email me (tstuart@nygenome.org)

**Comment by ShannonSzeto** [comment] 2019-01-31 06:22
I'm having the same issue in Seurat V3, would like to know if this has been resolved in Seurat 3.

Thanks!

**Comment by harinipras** [comment] 2019-02-08 14:32
> Just a quick follow up. I fixed the issue by using the RenameCells function just after I created the Seurat Object. It seemed to fix it. Not an ideal situation but it seems to be a quick fix.
> 
> Cheers!
> 
> Aaron

That worked for me too. Thank you so much for the help Aaron !

**Comment by aapetti** [comment] 2019-02-12 16:51
> Just a quick follow up. I fixed the issue by using the RenameCells function just after I created the Seurat Object. It seemed to fix it. Not an ideal situation but it seems to be a quick fix.

Thanks for the tip, Aaron - you saved me a lot of time!

**Comment by elfore** [comment] 2019-03-22 08:19
How do you do the follow up alignment? I can't use function "AlignSubspace", seems like it is discarded in Seurat 3.0, any tips on it?

**Comment by timoast** [comment] 2019-03-25 16:51
@elfore we have new methods for integration in v3, see our integration vignette here: https://satijalab.org/seurat/pancreas_integration_label_transfer.html 
and preprint here: https://doi.org/10.1101/460147

**Comment by timoast** [comment] 2019-03-25 16:52
Closing this issue as I have not heard from @KingstonData

**Closed by timoast** 2019-03-25 16:52 UTC
