### ISSUE TITLE
x and y axes labels swapped in ImageDimPlot

### ISSUE THREAD

**Issue by orrzor** [satijalab/seurat#6132] opened 2022-06-30 14:47 UTC
Hi Seurat team! I noticed when doing the [imaging-data spatial vignette](https://satijalab.org/seurat/articles/spatial_vignette_2.html) that the x and y axes labels are swapped when running `ImageDimPlot(vizgen.obj, fov = "s2r1", axes = T)` and `ImageDimPlot(vizgen.obj, fov = "hippo", axes = T)`. It's pretty clear when you plot the cropped FOV that the cropping is correct but the labels of the x and y axes are swapped. Thanks for building all these helpful tools. Best, Orr

```r
ImageDimPlot(vizgen.obj, fov = "s2r1", axes = T)
ImageDimPlot(vizgen.obj, fov = "hippo", axes = T)
```

**Comment by pander21** [comment] 2022-07-28 15:07
Hi, I raised this issue previously here: [https://github.com/satijalab/seurat/issues/6110](url) and the answer was that this was done intentionally. However, I still think this behaviour is undesired and solution offered there is not sufficient for following reasons:

If one uses `coord_flip` from ggplot2 package as suggested:
`ImageDimPlot(data, fov = fov1, coord.fixed = TRUE) & coord_flip() `
This overrides argument `coord_fixed` in `ImageDimPlot` which results in distorted aspect ratio!

This can be overcomed again by specifying exact aspect ratio by adding `theme(aspect.ratio = your.precalculated.ratio)` as such:
`
my.ratio = range.y.axis / range.x.axis
ImageDimPlot(data, fov = fov1, coord.fixed = TRUE) & coord_flip() & theme(aspect.ratio = my.ratio)
`
And while this is bit cumbersome, it works, but ONLY with one field of view at a time.

However, if one wants to plot multiple fields of view, e.g. in replicated experiments by adding vector of fovs to `fov` argument of `ImageDimPlot`, even this solution fails, as each field of view will have different aspect ratio.
`ImageDimPlot(data, fov = c(fov1, fov2), coord.fixed = TRUE) & coord_flip() & theme(aspect.ratio = my.ratio)` - only first image is with correct orientation and correct axes ratio.

Perhaps Seurat team could look into this again and fix the `ImageDimPlot()` to have the desired behavior of plotting axes correctly in the first place, or providing another solution to plotting both axes and aspect ratios correctly, even with multiple fields of view. Thanks!

**Comment by longmanz** [comment] 2023-07-07 21:13
Hi, 
Thank you for noticing this issue. Although this is not a bug (as mentioned in https://github.com/satijalab/seurat/issues/6110#issuecomment-1172650788), this auto-flip will indeed distort the x and y ratio. We will likely be adding an enhancement to the ImageDimPlot() and ImageFeaturePlot() in our next release. 
I will close this issue for now, and will update you once the enhancement is added.

**Closed by longmanz** 2023-07-07 21:13 UTC
Labels: bug
