### ISSUE TITLE
A bug of VariableFeaturePlot

### ISSUE THREAD

**Issue by mqk98** [satijalab/seurat#4156] opened 2021-02-27 08:39 UTC
I used VariableFeaturePlot after sctransform, but it prompted "Unable to find variable feature information for method 'sct'", but I looked at the SCT array, the highly variable feature exists and can also be read using VariableFeatures function.
![QQ截图20210227163856](https://user-images.githubusercontent.com/62283509/109382244-4c3b5700-791a-11eb-8356-026ec885c632.png)

**Comment by samuel-marsh** [comment] 2021-03-03 12:46
Hi,

Not member of dev team but hopefully can be helpful.  I would suggest checking out discussion in #4018 and seeing if updating to the latest develop branch release solves your issue.

Best,
Sam

**Comment by mqk98** [comment] 2021-03-09 03:07
> Hi,
> 
> Not member of dev team but hopefully can be helpful. I would suggest checking out discussion in #4018 and seeing if updating to the latest develop branch release solves your issue.
> 
> Best,
> Sam

**Comment by duocang** [comment] 2021-03-12 16:03
> Hi,
> 
> Not member of dev team but hopefully can be helpful. I would suggest checking out discussion in #4018 and seeing if updating to the latest develop branch release solves your issue.
> 
> Best,
> Sam

The issue is still there.

**Comment by yuhanH** [comment] 2021-03-12 16:56
Hi, @mqk98  and @duocang 

Do you merge several SCT objects together?
After you update the latest develop branch, can you reproduce this example below?

```
DefaultAssay(pbmc_small)<-"RNA"
pbmc_small <- SCTransform(pbmc_small, variable.features.n = 10)
VariableFeaturePlot(pbmc_small, selection.method = "sct", assay = "SCT")
```

![image](https://user-images.githubusercontent.com/29529544/110972440-00c97580-832a-11eb-84c7-6180aa67221e.png)

**Comment by duocang** [comment] 2021-03-12 17:38
@yuhanH 

Hi.

True. I merged several seurat objs together. I remember this will cause some problems but I do not remember it.

I tried the code snippet, it works fine.

**Comment by yuhanH** [comment] 2021-03-12 17:43
HI, @duocang 
After you merge several SCT objects together, the merged object will have multimodal SCT models. 
`VariableFeaturePlot` for SCTAssay is based on one SCT model, so if you want to use `VariableFeaturePlot`, you need to run it on the individual object before merging.

**Comment by duocang** [comment] 2021-03-12 17:47
@yuhanH 

I see. Thanks.

**Comment by duocang** [comment] 2021-03-17 15:24
@yuhanH 

Hi. It puzzles me for days so If merged Seu obj has multimodal SCT modes, what is the purpose to merge them?

A lot of visualization of Seurat is using seu[["SCT"]]$scale.data. If a Seu obj with multimodal SCT modes, how can those visualization work?

**Closed** 2021-03-18 06:57 UTC
Labels: more-information-needed

**Comment by yuhanH** [comment] 2021-03-18 14:05
Hi,  @duocang 
We recommend you to do the visualization or differential on the SCT or RNA data slot. 
The residuals in the SCT scale.data is mainly used to RunPCA and define cell clusters.
