### ISSUE TITLE
logFC base

### ISSUE THREAD

**Issue by Xcubitor** [satijalab/seurat#991] opened 2018-12-05 22:52 UTC
Hello,
Is the base of logFC a log2 or a log10 in "findMarkers"?
Thanks

**Comment by sansense** [comment] 2018-12-06 10:32
I guess log2, as most of the DE software use log2.

**Comment by leonfodoulian** [comment] 2018-12-06 11:54
Hi @Xcubitor,

This is a duplicate of multiple issues (#77 and #332). But `avg_logFC` is in natural `log`. 

Best,
Leon

**Closed** 2018-12-06 15:16 UTC
