### ISSUE TITLE
crop = FALSE not functioning correctly for SpatialFeaturePlot etc

### ISSUE THREAD

**Issue by jeremycfd** [satijalab/seurat#2700] opened 2020-03-09 00:59 UTC
```
library(SeuratData)
brain <- LoadData("stxBrain", type = "anterior1")
SpatialFeaturePlot(brain, features = c("Hpca"))
SpatialFeaturePlot(brain, features = c("Hpca"), crop = FALSE)

```
![image](https://user-images.githubusercontent.com/19560008/76174744-24863880-6177-11ea-8e4a-52d391dbcebd.png)

![image](https://user-images.githubusercontent.com/19560008/76174733-1a643a00-6177-11ea-86f6-75ffc211830c.png)

**Comment by andrewwbutler** [comment] 2020-03-13 16:26
Thanks for reporting and giving a reproducible example! Will post back here when we have a fix.

**Comment by andrewwbutler** [comment] 2020-03-13 20:45
Looks like this was related to the recent ggplot2 update to version 3.3.0. I've pushed a fix now to the `spatial` branch. Reinstalling should fix the cropping issue.

**Closed** 2020-03-20 16:38 UTC
Labels: bug

**Comment by EternalEnvy10** [comment] 2021-01-26 09:38
> Looks like this was related to the recent ggplot2 update to version 3.3.0. I've pushed a fix now to the `spatial` branch. Reinstalling should fix the cropping issue.

Hi,I have the same issue that when I set crop = FALSE, spot will pan to the wrong place as a whole, as mentioned above. I have upgraded ggplot2 to the latest version 3.3.3.
Thanks!!
