### ISSUE TITLE
Different FindVariableFeatures  results in the same Seurat version 

### ISSUE THREAD

**Issue by sheenaseven** [satijalab/seurat#7849] opened 2023-09-28 05:22 UTC
I have installed the same version of R Seurat on two different Linux systems, A and B.
A: 
<img width="659" alt="image" src="https://github.com/satijalab/seurat/assets/37868618/a924d8e5-532e-4e1b-a761-1724471363a8">
B:
<img width="637" alt="image" src="https://github.com/satijalab/seurat/assets/37868618/3d5d69ba-de7f-47fa-9b18-f1661e7ef518">
 But when I run the same code for the FindVariableFeatures function (x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000, verbose = FALSE)), I obtain different sets of variable features.
A: 
<img width="561" alt="image" src="https://github.com/satijalab/seurat/assets/37868618/113066f1-2d2f-4d68-a540-46cd6f989762">
B:
<img width="558" alt="image" src="https://github.com/satijalab/seurat/assets/37868618/f3aebfc7-8adf-446f-aa8a-623a67770162">
Is there a possible reason for this difference, which is important for code reproduction.

**Comment by evchambers** [comment] 2023-10-09 11:58
Hi @sheenaseven, 

This issue has been observed previously - see #5358 and #6748.

I believe it is caused by differences in numerical precision of a Seurat package dependency between differing devices which can affect downstream visualisation.

https://github.com/satijalab/seurat/issues/5358#issuecomment-1625973821_

**Comment by mhkowalski** [comment] 2024-06-24 14:41
Thanks @sheenaseven  for reporting this and  @evchambers  for your answer. I'm closing this now as this has been solved, but please open a new issue if you continue have to have problems.

**Closed by mhkowalski** 2024-06-24 14:41 UTC
