### ISSUE TITLE
Unable to run FindAllMarkers()

### ISSUE THREAD

**Issue by jctac** [satijalab/seurat#5441] opened 2022-01-03 21:45 UTC
Hello,

I have been trying to run FindAllMarkers on an SCTransform'd dataset that has 6 clusters.  Below is the error message I get in every R session I tried to run the code.  However, I can run FindAllMarkers() on the pbmc3k dataset without any problems.  I would really appreciate your help.  

Thank you,
jctac

**ERROR MESSAGE:**

Calculating cluster 0
                                                           
Done!
Calculating cluster 1
                                                           
Done!
Calculating cluster 2
                                                           
Done!
Calculating cluster 3
                                                           
Done!
Calculating cluster 4
                                                           
Done!
Calculating cluster 5
                                                           
Done!
Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing 0 versus all:
	$ operator is invalid for atomic vectors
Warning: When testing 1 versus all:
	$ operator is invalid for atomic vectors
Warning: When testing 2 versus all:
	$ operator is invalid for atomic vectors
Warning: When testing 3 versus all:
	$ operator is invalid for atomic vectors
Warning: When testing 4 versus all:
	$ operator is invalid for atomic vectors
Warning: When testing 5 versus all:
	$ operator is invalid for atomic vectors

**CODE:**
```{r}
s45neg <- RunPCA(s45neg, verbose = FALSE)
ElbowPlot(s45neg, ndims = 50) 
s45neg <- RunUMAP(s45neg, reduction = "pca", dims = 1:16)
s45neg <- RunTSNE(s45neg, reduction = "pca", dims = 1:16)
s45neg <- FindNeighbors(s45neg, reduction = "pca", dims = 1:16)
s45neg <- FindClusters(s45neg, resolution = 0.5)
UMAPPlot(s45neg) 

s45neg.markers <- FindAllMarkers(s45neg, assay = "SCT", test.use = "MAST", only.pos = TRUE, min.pct = 0.10, logfc.threshold = 0.25)
```

**Comment by AohRveTPV** [comment] 2022-01-04 21:17
jctac, this is a bug with MAST in Seurat 4.0.6.  See this issue: https://github.com/satijalab/seurat/issues/5419

You can either use a previous version of Seurat, like 4.0.5, or a statistical test other than MAST.

**Comment by saketkc** [comment] 2022-01-14 17:44
This should have been fixed in `develop` branch. Can you try it from there?
https://satijalab.org/seurat/articles/install.html

Feel free to reopen if there are followup issues.

**Closed by saketkc** 2022-01-14 17:44 UTC
Labels: bug

**Comment by jctac** [comment] 2022-01-19 03:08
Thank you.  MAST works with v4.0.5!

**Comment by chasepagani** [comment] 2023-10-06 02:21
Hello. I am using Seurat 5 and am facing this issue. I have integrated data, but I am using the RNA assay. Can you please assist?

diffgenes.d1 <- FindAllMarkers(sets, assay="RNA",  logfc.threshold = 0.4,  test.use="negbinom", min.diff.pct=0.25, return.thresh=0.05)

returns this error: 
Calculating cluster 0
Calculating cluster 1
Calculating cluster 2
Calculating cluster 3
Calculating cluster 4
Calculating cluster 5
Calculating cluster 6
Calculating cluster 7
Calculating cluster 8
Calculating cluster 9
Calculating cluster 10
Calculating cluster 11
Calculating cluster 12
Calculating cluster 13
Calculating cluster 14
Calculating cluster 15
Calculating cluster 16
Calculating cluster 17
Warning: No DE genes identifiedWarning: The following tests were not performed: Warning: When testing 0 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 1 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 2 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 3 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 4 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 5 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 6 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 7 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 8 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 9 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 10 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 11 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 12 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 13 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 14 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 15 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 16 versus all:
	Cells in one or both identity groups are not present in the data requestedWarning: When testing 17 versus all:
	Cells in one or both identity groups are not present in the data requested

**Comment by zheng-sc** [comment] 2023-10-30 16:21
> Hello. I am using Seurat 5 and am facing this issue. I have integrated data, but I am using the RNA assay. Can you please assist?
> 
> diffgenes.d1 <- FindAllMarkers(sets, assay="RNA", logfc.threshold = 0.4, test.use="negbinom", min.diff.pct=0.25, return.thresh=0.05)
> 
> returns this error: Calculating cluster 0 Calculating cluster 1 Calculating cluster 2 Calculating cluster 3 Calculating cluster 4 Calculating cluster 5 Calculating cluster 6 Calculating cluster 7 Calculating cluster 8 Calculating cluster 9 Calculating cluster 10 Calculating cluster 11 Calculating cluster 12 Calculating cluster 13 Calculating cluster 14 Calculating cluster 15 Calculating cluster 16 Calculating cluster 17 Warning: No DE genes identifiedWarning: The following tests were not performed: Warning: When testing 0 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 1 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 2 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 3 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 4 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 5 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 6 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 7 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 8 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 9 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 10 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 11 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 12 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 13 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 14 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 15 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 16 versus all: Cells in one or both identity groups are not present in the data requestedWarning: When testing 17 versus all: Cells in one or both identity groups are not present in the data requested

is this solved? I got the same issue on Seurat5

**Comment by csu06gnauh** [comment] 2023-11-03 04:24
I've tried Seurat v4.3.1 with different tests, but I still got the issue.

**Comment by Jorges1000** [comment] 2023-11-09 23:37
Same here

**Comment by khpark00** [comment] 2023-11-28 14:51
same here, not working both in R 4.3-x86_64 and R 4.2-arm64. Seurat v5 and Seurat v4.4.0. MAST and other tests gave me the same issue.

**Comment by zahramesri** [comment] 2023-12-05 23:04
Anyone solved this issue?

**Comment by codingcane** [comment] 2023-12-05 23:19
If you're okay with using MAST I was finding explicit definition of group.by and test.use to circumvent this error, e.g.
`Seurat::FindAllMarkers(seu, group.by = "cellType", test.use = "MAST")`
I had thought the active.ident would be used as the group.by by default but I'm not seeing that.

**Comment by mjcamerino** [comment] 2023-12-12 20:57
I am still having this same problem with Seurat V5.0.1.

**Comment by alexey858** [comment] 2023-12-17 13:52
same here

**Comment by Ruth-hals** [comment] 2023-12-18 20:03
same here - cannot run find all markers.

Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing 0 versus all:
	Cells in one or both identity groups are not present in the data requested

Not sure if this is a related issue, but I am also not able to rename identities;  
Warning messages:
1: Cannot find cells provided

R version 4.3.2, Seurat_5.0.0

**Comment by alexey858** [comment] 2023-12-19 06:30
Just in case this could help. I realized that the active.ident should be assigned by Ident() instead of seurat.obj@active.ident <- if we want to change it manually. Then I solved this problem and calculated the markers.

**Comment by alexey858** [comment] 2023-12-19 06:31
seurat v5.0.1 and R for 4.3.2

**Comment by Ruth-hals** [comment] 2023-12-19 08:12
> Just in case this could help. I realized that the active.ident should be assigned by Ident() instead of [seurat.obj@active.ident](mailto:seurat.obj@active.ident) <- if we want to change it manually. Then I solved this problem and calculated the markers.

Yes! this worked for me too! thanks for sharing!

**Comment by CHEN1671** [comment] 2024-01-27 14:45
I still don't know in which step to do this：
the active.ident should be assigned by Ident() instead of [seurat.obj@active.ident](mailto:seurat.obj@active.ident)

**Comment by alexey858** [comment] 2024-01-28 02:19
in fact, you do not have to do this cause the active.ident would be assigned automatically when you run findcluster() function : )



---Original---
From: ***@***.***&gt;
Date: Sat, Jan 27, 2024 22:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [satijalab/seurat] Unable to run FindAllMarkers() (Issue #5441)




 
I still don't know in which step to do this：
 the active.ident should be assigned by Ident() instead of ***@***.***

**Comment by ygq556** [comment] 2024-03-26 02:01
> in fact, you do not have to do this cause the active.ident would be assigned automatically when you run findcluster() function : )
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sat, Jan 27, 2024 22:45 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [satijalab/seurat] Unable to run FindAllMarkers() (Issue #5441) I still don't know in which step to do this： the active.ident should be assigned by Ident() instead of ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

 The default setting was to analyze the differential expressed genes(DEGs) in clusters, but i want to analyze the DEGs in my annoted celltypes. So i want to change the active.ident to the celltypes~

**Comment by alexey858** [comment] 2024-03-26 02:36
> > in fact, you do not have to do this cause the active.ident would be assigned automatically when you run findcluster() function : )
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Sat, Jan 27, 2024 22:45 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [satijalab/seurat] Unable to run FindAllMarkers() (Issue #5441) I still don't know in which step to do this： the active.ident should be assigned by Ident() instead of _**@**_.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> The default setting was to analyze the differential expressed genes(DEGs) in clusters, but i want to analyze the DEGs in my annoted celltypes. So i want to change the active.ident to the celltypes~

just after the findcluster()

**Comment by nitinmahajan20** [comment] 2024-03-28 02:58
Not working and I am having the same issue

**Comment by apal6** [comment] 2024-03-29 00:05
Hi, 
I got the same error. Any updates?

**Comment by anayan321** [comment] 2024-03-29 11:45
Hello,
I'm using Seurat 5 and FindAllMarkers function seems to work fine, until I merge a new data frame with the object@meta.data with merge function. After that I got the very same error. It would seem that the row number was lost.

I loaded the object before merging the metadata and the function worked fine again. I guess left_join function might work better.

**Comment by urual** [comment] 2024-04-06 04:36
Hello, i know you may have many way to solve this problem.But, i also want to share the way that  solves the trouble by "joinlaryers()" function.You can solves this wrong by running "object <- joinlaryers(object)" after using FindAllMarkers.
P.S. object is your scRNA-seq data of Seurat.

**Comment by SiwakornP** [comment] 2024-04-22 20:15
> seurat_object <- JoinLayers(seurat_object )

I experienced the same issue with Seurat 5.0.3 and R 4.3.3. I had several datasets, which then merged with merge() similar to @anayan321. The issue is solved by JoinLayers().
Thanks!
