### ISSUE TITLE
Similar datasets do not align

### ISSUE THREAD

**Issue by Maija1** [satijalab/seurat#4202] opened 2021-03-09 20:22 UTC
Dear Seurat team,
I am trying to align single cell RNA seq data of the same tissue from five different labs. Three (1, 2,3) of them align very well, but the other two (4, 5) not at all according to the UMAP. They do not align to each other or the other three datasets. All five used 10X genomics for library preparation. Sequencing depth etc seem similar. The two that do not align are slightly larger (~2000 cells each) than the ones that align (~600 cells each). Could there be something in the metadata or something like that makes Seurat 'think' that the two very different from the others?
Thank you very much in advance!

**Comment by Dragonmasterx87** [comment] 2021-03-10 22:26
Hi @Maija1 im, not a Seurat dev, but I will try to help you. Very simply, you need to perform batch correction, when you do that, it no longer matters, what the sequencing depth/sequencing chemistry/lab performed the analysis and Seurat is capable of performing powerful cross-sample batch correction. Are you performing integration or simply merging your datasets? Please provide your code and if possible the output UMAP/tSNE of the 5 datasets.

**Comment by Maija1** [comment] 2021-03-11 08:56
Hi! I wanted to keep the cluster identities of the analyses of other labs in the metadata. For a few, I also needed to select clusters since more cell types were sequenced. Some of these datasets are already a merge of multiple sequencing runs.

Here is the code I used (I replaced the exact identifiers, but these are commands that I run) :
#pre-process data1
data1_ident <- data1_2020
data1_ident@meta.data$cell_type <- data1_ident@active.ident
data1_ident <- subset(x = data1_ident, idents = c(  "A" , "B" , "C", "D" ,
                                            "E" , "F" , "G"  , "H", "I"  , 
                                            "J" ))                                           
data1_ident@meta.data$orig.ident <- 'data1'

#pre-process data2
data2_ident <- data2
data2_ident@meta.data$cell_type <- data2_ident@active.ident
DefaultAssay(data2_ident) <- 'RNA'

#pre-process data3
data3_ident <- data3
data3_ident@meta.data$cell_type <- data3_ident@active.ident
data3_ident <- subset(x = data3_ident, idents = c( "AA",  "AB","AC"  ,"AD"))
data3_ident@meta.data$orig.ident <- 'data3'

#pre-process data4
data4_ident <- data4_r
data4_ident@meta.data$cell_type <- data4_ident@active.ident
data4_ident <- subset(x = data4_ident, idents = c('CA', 'CB', 'CC', 'CD'))
data4_ident@meta.data$orig.ident <- 'data4'

#pre-process data5
data5_ident <- data5_r
data5_ident@meta.data$cell_type <- data5_ident@active.ident
data5_ident@meta.data$orig.ident <- 'data5'

#normalize
data1_norm <- NormalizeData(object = data1_ident, verbose = FALSE)
data2_norm <- NormalizeData(object = data2_ident, verbose = FALSE)
data3_norm <- NormalizeData(object = data3_ident, verbose = FALSE)
data4_norm <- NormalizeData(object = data4_ident, verbose = FALSE)
data5_norm <- NormalizeData(object = data5_ident, verbose = FALSE)

#find variable geans
data1_var <- FindVariableFeatures(object = data1_norm, selection.method = "vst", nfeatures = 2000)
data2_var <- FindVariableFeatures(object = data2_norm, selection.method = "vst", nfeatures = 2000)
data3_var <- FindVariableFeatures(object = data3_norm, selection.method = "vst", nfeatures = 2000)
data4_var <- FindVariableFeatures(object = data4_norm, selection.method = "vst", nfeatures = 2000)
data5_var <- FindVariableFeatures(object = data5_norm, selection.method = "vst", nfeatures = 2000)

#find anchors, integrate
anchors <- FindIntegrationAnchors(object.list = list(data2_var,
                                                           data3_var,
                                                           data1_var,
                                                           data4_var,
                                                           data5_var), dims = 1:50)
data_combined <- IntegrateData(anchorset = anchors, dims = 1:50)

# Run the standard workflow for visualization and clustering
data_sc <- ScaleData(object = data_combined, verbose = FALSE)
data_PCA <- RunPCA(object = data_sc, npcs = 50, verbose = FALSE)
data_UMAP <- RunUMAP(object = data_PCA, reduction = "pca", dims = 1:50)

DimPlot(data_UMAP, group.by = 'orig.ident')
# here I see that data 4 and 5 do not align at all, while the other two do.

Is there anyting else I can do specifically for batch correction?
Thank you!

**Comment by Dragonmasterx87** [comment] 2021-03-11 16:30
Hi @Maija1 , first of all welcome to the growing community of Seurat users, I see now that this is your first issue on Seurat's issues section on github. As a general rule, try to always search in the main search bar of Seurat's Github repo, issues section for previous discussions on questions you may have. As you can see your question, has been addressed multiple times in the past (some examples) #3255, #1930, #1755, #1224, @ChristophH maintains `SCTransform` a powerful and highly reproducible negative binomial normalization technique, used primarily to adjust batch-batch variance. You can see his comment in this regard [here](https://github.com/ChristophH/sctransform/issues/32#issuecomment-517235017).

The reason I have taken the time to outline these points is that most of the time you will see people have already been faced with the problem you have and have discussed _ad nauseam_ the possible solutions, just for future refrence, it greatly helps when you try to find the answer in previous solutions. I find that this greatly increases your understanding of what one is doing and why.

Now since this is your first issue, lets try to solve your issues step by step.

1. As a recommendation when commenting in Github and writing code, please make it readable by following these suggestions [here](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) and [here](https://gist.github.com/viphat/7f883a18733ae5a7ebe45e74c348dbc0). Imagine you are a Seurat developer, make their life easy by making it easy to read your code, it is more likely that they will be able to quickly grasp your question and address it.

2.  Always share the output of `sessionInfo()` and you are getting an error `traceback()`

3.  Your issue of batch correction can be solved by using [this](https://satijalab.org/seurat/articles/integration_introduction.html) workflow.

4. I understand that you have pre-merged datasets, but I would integrate all datasets and then eliminate clusters of cells based on what you don't need. Generally in my opinion the more the cell types are present the better the integration will be, but it depends on the tissue of origin. 

5. I would personally pull out each of the datasets from the merged data (this is possible as the origin lab should have donor/sample-specific data in a metadata entry. Emphasis on the word 'should'). This just allows the process of metadata addition and data organization to become so much easier, making it easier to analyze your data and troubleshoot downstream.

So once you have run the classical time-tested-robust Integration vignette on your data, please share the UMAP plots before and after integration. Although I am sure you will not need to because the process of dataset integration is excellent.

I hope that helps, please feel free to update us once you try the solutions outlined above.

🐲

**Closed** 2021-03-26 17:19 UTC
Labels: more-information-needed
