### ISSUE TITLE
How are you supposed to handle Layers upon merge?

### ISSUE THREAD

**Issue by vertesy** [satijalab/seurat#8409] opened 2024-02-02 14:47 UTC
Dear Seurat Team,

I am unfortunately a bit confused about how one is supposed to handle Layers after a merge.

I read [integration_introduction](https://satijalab.org/seurat/articles/integration_introduction.html), [seurat5_integration](https://satijalab.org/seurat/articles/seurat5_integration), [seurat5_essential_commands](https://satijalab.org/seurat/articles/seurat5_essential_commands), but do not have a clear understanding what it the expected 

### v4 workflow (to analyze a combined dataset)

```r
combined.obj <- merge(list.of.Seurats[[1]], list.of.Seurats[2:length(list.of.Seurats)])
 
combined.obj <- FindVariableFeatures(object = combined.obj, assay = "RNA", verbose = T)
combined.obj <- ScaleData(combined.obj, assay = "RNA", verbose = T)
combined.obj <- RunPCA(combined.obj, npcs = p$"n.PC", verbose = T)
combined.obj <- RunUMAP(combined.obj, reduction = "pca", dims = 1:p$"n.PC")
combined.obj <- FindNeighbors(combined.obj, reduction = "pca", dims = 1:p$"n.PC")
combined.obj <- FindClusters(combined.obj, resolution = p$"snn_res")

# ... FindAllMarkers()....
  
```

### ?? v5 workflow

```r

combined.obj <- merge(list.of.Seurats[[1]], list.of.Seurats[2:length(list.of.Seurats)])
combined.obj <- JoinLayers(combined.obj,  assay = "RNA")

combined.obj <- FindVariableFeatures(object = combined.obj, assay = "RNA", verbose = T)
combined.obj <- ScaleData(combined.obj, assay = "RNA", verbose = T)
combined.obj <- RunPCA(combined.obj, npcs = p$"n.PC", verbose = T)
combined.obj <- RunUMAP(combined.obj, reduction = "pca", dims = 1:p$"n.PC")
combined.obj <- FindNeighbors(combined.obj, reduction = "pca", dims = 1:p$"n.PC")
combined.obj <- FindClusters(combined.obj, resolution = p$"snn_res")
  
# ... FindAllMarkers()....
```

## Obervations

1. Seurat only throws an error for not running `JoinLayers`  at `FindAllMarkers`, earlier functions work.  
   1. They seem to run on any layer present. Are they supposed to run **only** on the joined-layer?
   2. So should I (1) `JoinLayers()`, then (2) `NukeOldLayers`, then (3) continue with `FindVariableFeatures()`

2. ~~`JoinLayers` does not remove individual layers - What is the official way to `NukeOldLayers`?~~ *
3. I see many variants of the `JoinLayers()` call - which are okay to use?
```r
combined.obj <- JoinLayers(combined.obj,  assay = "RNA")
# or
combined.obj[[RNA]] <- JoinLayers(combined.obj,  assay = "RNA")
# or
combined.obj[[RNA]] <- JoinLayers(combined.obj[[RNA]])
```
4. Is it the same for _integration_, just as for _merge_?

----
*This is invalid, I cannot reproduce it.

**Comment by zskylarli** [comment] 2024-02-02 20:48
Hi - not super sure why `JoinLayers()` is not removing the split layers for you, as that is the expected behavior (just as we show [here](https://satijalab.org/seurat/articles/seurat5_integration). The object might be broken due to the way you are merging objects; although this may be time-consuming, I would suggest merging one by one instead of what you are doing, which is the first object merged with all of the rest.

**Comment by vertesy** [comment] 2024-02-02 22:18
Hey, thank you, yes -  I know noticed that if I merge objects 1:3, layers are removed exactly as you say. I previously merged 83 objects, and then the layers stayed. I am trying to reproduce that - just need so much memory that I cant get atm.

**Comment by vertesy** [comment] 2024-06-24 18:37
Thanks for checking on it, no I didn't encounter it again.

**Comment by Gesmira** [comment] 2024-06-24 19:36
Great, closing now!

**Closed by Gesmira** 2024-06-24 19:36 UTC
