### ISSUE TITLE
Error in validObject(.Object) : invalid class "ScaledMatrix" object: the supplied seed must support extract_array()

### ISSUE THREAD

**Issue by Flu09** [satijalab/seurat#8935] opened 2024-05-26 11:26 UTC
I had multiple seurat objects and I wrote each to disk then merged them. 

write_matrix_dir(mat = object1[["RNA"]]$counts, dir = '/tmp/object1')
counts.mat.object1 <- open_matrix_dir(dir = "/tmp/object1")
counts.mat.object1
object1[["RNA"]]$counts <- counts.mat.object1

write_matrix_dir(mat = object2[["RNA"]]$counts, dir = '/tmp/object2')
counts.mat.object2 <- open_matrix_dir(dir = "/tmp/object2")
counts.mat.object2
object2[["RNA"]]$counts <- counts.mat.object2

merged <- merge (object1, c(object2, object3, object4))
merged <- NormalizeData(merged)
merged[["RNA"]] <- split(merged[["RNA"]], f = merged$dataset)
merged <- JoinLayers(merged)
merged <- FindVariableFeatures(merged)
merged <- SketchData(object = merged, ncells = 10000, method = "LeverageScore", sketched.assay = "sketch")
DefaultAssay(merged) <- "sketch"
merged <- FindVariableFeatures(merged, verbose = F)
merged <- ScaleData(merged, verbose = F)
merged <- RunPCA(merged, verbose = F)

merged <- IntegrateLayers(
object = merged, method = FastMNNIntegration,
new.reduction = "integrated.mnn",
verbose = TRUE
)

Converting layers to SingleCellExperiment
Running fastMNN
Error in validObject(.Object) : invalid class "ScaledMatrix" object:
the supplied seed must support extract_array()

**Comment by longmanz** [comment] 2024-06-24 18:52
Hi @Flu09,

Thank you for reaching out! We’re always grateful when folks take the time to [blank] and help make Seurat better 🙂

Unfortunately, with the details provided, we cannot reproduce your issue. To help us better understand and resolve this issue, please ensure that you provide the following information when reporting a bug:

1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.  
    
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
    
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the  
    
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.

We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost and we will be more than happy to help you resolve the problem.

**Closed by longmanz** 2024-06-24 18:52 UTC
Labels: bug
