### ISSUE TITLE
IntegrateLayers SparseMatrix error

### ISSUE THREAD

**Issue by trebbiano** [satijalab/seurat#7344] opened 2023-05-18 22:57 UTC
Hi, I'm having trouble implementing the new sketch integration. Specifically, I am experiencing memory issues at different steps of the integration. My understanding was that BPCells and sketching methods were designed to allow large datasets to be analyzed on limited RAM systems, but now I am having trouble integrating a sample even on a 512 GB node. The latest error message is below. Am I doing something incorrectly or does even sketch integration require >500GB RAM?

```R
Extracting anchors for merged samples
Finding integration vectors
Error in .T2C(newTMat(i = c(ij1[, 1], ij2[, 1]), j = c(ij1[, 2], ij2[,  :
  unable to coerce from TsparseMatrix to [CR]sparseMatrixwhen length of 'i' slot exceeds 2^31-1
In addition: Warning messages:
1: `invoke()` is deprecated as of rlang 0.4.0.
Please use `exec()` or `inject()` instead.
```

The command used was as follows:
```R
object <- IntegrateLayers(object, method=RPCAIntegration, orig="pca", new.reduction="integrated.rpca", 
dims=1:30, k.anchor=20, verbose=TRUE)
```

The dataset contains about 90 source samples adding up to ~350k cells. 

System details:
```bash
CentOS Linux release 7.9.2009 (Core)
> packageVersion("Seurat")
[1] ‘4.9.9.9044’
R version 4.3.0 (2023-04-21)
              total        used        free      shared  buff/cache   available
Mem:           503G         13G        486G         32M        3.2G        488G
Swap:           15G          0B         15G
```

Thanks!

**Comment by yuhanH** [comment] 2023-05-19 19:23
hi, Could you post the scripts you run for this sketch integration?

**Comment by trebbiano** [comment] 2023-05-19 20:13
Of course:
```R
library("Seurat")
load("./data/object.Rd")
object[["RNA"]] <- split(object[["RNA"]], f=object$orig.ident)
object <- FindVariableFeatures(object, verbose=TRUE)
object <- SketchData(object = object, ncells = 5000, method = "LeverageScore", sketched.assay = "sketch")
DefaultAssay(object) <- "sketch"
object <- FindVariableFeatures(object, verbose = TRUE)

library("future")
plan("multisession", workers=4)
options(future.globals.maxSize = 7000 * 1024^2)

object <- ScaleData(object, verbose = TRUE)
object <- RunPCA(object, verbose = F)
object <- IntegrateLayers(object, method=RPCAIntegration, orig="pca",
                         new.reduction="integrated.rpca",
                         dims=1:30,
                         k.anchor=20,
                         verbose=TRUE)
```

**Comment by cailing20** [comment] 2023-05-25 13:47
I did not use sketch integration, but have a similar problem. The error occurred in the middle of the IntegrateData step.
```
Integrating data
Merging dataset 3 13 1 into 2 17 18 5
Extracting anchors for merged samples
Finding integration vectors
Error in .T2C(newTMat(i = c(ij1[, 1], ij2[, 1]), j = c(ij1[, 2], ij2[,  : 
  unable to coerce from TsparseMatrix to [CR]sparseMatrixwhen length of 'i' slot exceeds 2^31-1
Calls: IntegrateData ... FindIntegrationMatrix -> - -> - -> .Arith.Csparse -> .T2C
Execution halted
```
Command used:
```
sc_list[] <- lapply(sc_list, FUN = RunPCA, features = features,npcs=50)
sc_anchors<-FindIntegrationAnchors(object.list = sc_list,normalization.method = "SCT",anchor.features = features, reduction = "rpca",dims = 1:50,k.anchor = 5)
sc_combined<-IntegrateData(anchorset = sc_anchors,normalization.method = "SCT",dims = 1:50)
```
I have 20 samples with a total of 146K cells. Ran on a 512GB node with:
```
SeuratObject_4.1.3 Seurat_4.3.0
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Red Hat Enterprise Linux Server 7.7 (Maipo)
```

Any suggestions would be apprecaited!

**Comment by jeraldnoble** [comment] 2023-05-26 19:31
I have the same sparse matrix error when using seurat v4 CCA integration but not in seurat v5. Perhaps the issue is the size limit for sparse matrices in the Matrix library?

**Comment by shivUSF** [comment] 2024-03-11 13:46
Did you find a solution for this ? if so can you please share ?

**Comment by mhkowalski** [comment] 2024-06-24 15:44
Hi, 

I'm closing this as this seems to be a v4 specific problem, and I'd highly recommend upgrading to v5 to run sketch integration for large datasets (and this should not take 512G of RAM). Please open a new issue if you continue to have this problem with sketch integration in Seurat v5.

**Closed by mhkowalski** 2024-06-24 15:44 UTC
Labels: more-information-needed
