### ISSUE TITLE
Warning message: No columnames present in cell embeddings, setting to 'integratedccafull_1:50' 

### ISSUE THREAD

**Issue by Sirin24** [satijalab/seurat#8941] opened 2024-05-27 20:01 UTC
merged <- ProjectIntegration(object = merged, sketched.assay = "sketch", assay = "RNA", reduction = "integrated.cca")
3600 atomic cells identified in the sketched.assay
Correcting embeddings
30000 atomic cells identified in the sketched.assay
Correcting embeddings
30000 atomic cells identified in the sketched.assay
Correcting embeddings
30000 atomic cells identified in the sketched.assay
Correcting embeddings
30000 atomic cells identified in the sketched.assay
Correcting embeddings
30000 atomic cells identified in the sketched.assay
Correcting embeddings
30000 atomic cells identified in the sketched.assay
Correcting embeddings
30000 atomic cells identified in the sketched.assay
Correcting embeddings
30000 atomic cells identified in the sketched.assay
Correcting embeddings
30000 atomic cells identified in the sketched.assay
Correcting embeddings
Warning message:
No columnames present in cell embeddings, setting to 'integratedccafull_1:50' 

Hello, what does this warning mean?

**Comment by longmanz** [comment] 2024-06-24 18:50
Hi @Sirin24 ,

Thank you for reaching out! Unfortunately, with the details provided, we cannot reproduce your issue. To help us better understand and resolve this issue, please ensure that you provide the following information when reporting a bug:

1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.  
    
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
    
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the  
    
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.

We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost and we will be more than happy to help you resolve the problem.

**Closed by longmanz** 2024-06-24 18:50 UTC
