### ISSUE TITLE
IntegrateData (rpca) error

### ISSUE THREAD

**Issue by StephanTir** [satijalab/seurat#1879] opened 2019-07-24 15:47 UTC
Hi,

I am trying to integrate a dataset of 31 samples (~150k cells) with the new reciprocal PCA method. Everything runs smoothly (and fast) until one of the very last steps of IntegrateData. I get the following error:

```
Merging dataset 4 9 14 15 13 12 into 11 25 21 18 22 5 1 8 30 10 7 16 17 28 29 24 23 31 27 2 20 6 19 3
Extracting anchors for merged samples
Finding integration vectors
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive
```

Using the same code with less samples/cells (15, ~50k cells) worked fine.

Thanks in advance!

Best

Stephan

**Comment by HuyNguyen97** [comment] 2019-07-29 09:32
How much Ram do you have on your computer?

**Comment by StephanTir** [comment] 2019-07-29 11:11
64GB. Of course RAM limitation would makes sense, but why this cryptic error message?

**Comment by andrewwbutler** [comment] 2019-08-02 16:45
I don't think this is a RAM limitation. Could you post the code you ran up until this point? (or if you could share the data/reproducible example that'd be great too).

**Comment by StephanTir** [comment] 2019-08-08 11:14
Here is the code I used:

`ME_list <- list()
ME_list[["ME_2FTMUU_pre"]] <- ME_2FTMUU_pre
ME_list[["ME_2FTMUU_post"]] <- ME_2FTMUU_post
ME_list[["ME_6K8YTY_pre"]] <- ME_6K8YTY_pre
ME_list[["ME_6K8YTY_post"]] <- ME_6K8YTY_post
ME_list[["ME_6KLSUS_pre"]] <- ME_6KLSUS_pre
ME_list[["ME_8YGUU8_pre"]] <- ME_8YGUU8_pre
ME_list[["ME_8YGUU8_post"]] <- ME_8YGUU8_post
ME_list[["ME_32ARQL_pre"]] <- ME_32ARQL_pre
ME_list[["ME_CSU6UB_pre"]] <- ME_CSU6UB_pre
ME_list[["ME_CSU6UB_post"]] <- ME_CSU6UB_post
ME_list[["ME_E79WZA_pre"]] <- ME_E79WZA_pre
ME_list[["ME_N5CC3E_pre"]] <- ME_N5CC3E_pre
ME_list[["ME_N5CC3E_post"]] <- ME_N5CC3E_post
ME_list[["ME_N7ZK3L_pre"]] <- ME_N7ZK3L_pre
ME_list[["ME_N7ZK3L_post"]] <- ME_N7ZK3L_post
ME_list[["ME_NUL141_pre"]] <- ME_NUL141_pre
ME_list[["ME_NUL141_post"]] <- ME_NUL141_post
ME_list[["ME_PUVQFD_pre"]] <- ME_PUVQFD_pre
ME_list[["ME_R1H4HE_pre"]] <- ME_R1H4HE_pre
ME_list[["ME_R1H4HE_post"]] <- ME_R1H4HE_post
ME_list[["ME_R1V8RN_pre"]] <- ME_R1V8RN_pre
ME_list[["ME_R1V8RN_post"]] <- ME_R1V8RN_post
ME_list[["ME_TS6ZX9_pre"]] <- ME_TS6ZX9_pre
ME_list[["ME_VP6CSY_pre"]] <- ME_VP6CSY_pre
ME_list[["ME_VP6CSY_post"]] <- ME_VP6CSY_post
ME_list[["ME_XF2DTB_pre"]] <- ME_XF2DTB_pre
ME_list[["ME_XF2DTB_post"]] <- ME_XF2DTB_post
ME_list[["ME_YK554L_pre"]] <- ME_YK554L_pre
ME_list[["ME_YK554L_post"]] <- ME_YK554L_post
ME_list[["ME_ZPMZFJ_pre"]] <- ME_ZPMZFJ_pre
ME_list[["ME_ZPMZFJ_post"]] <- ME_ZPMZFJ_post


for (i in 1:length(ME_list)) {
  ME_list[[i]] <- NormalizeData(ME_list[[i]], verbose = FALSE)
  ME_list[[i]] <- FindVariableFeatures(ME_list[[i]], selection.method = "vst", 
                                       nfeatures = 2000, verbose = FALSE)
}

features <- SelectIntegrationFeatures(object.list = ME_list)
ME_list <- lapply(X = ME_list, FUN = function(x) {
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, features = features, verbose = FALSE)
})

anchors <- FindIntegrationAnchors(object.list = ME_list, reduction = "rpca", dims = 1:40)
ME.integrated <- IntegrateData(anchorset = anchors, dims = 1:40)
`

**Comment by StephanTir** [comment] 2019-08-08 11:16
Here is the code I used:

```
ME_list <- list()
ME_list[["ME_2FTMUU_pre"]] <- ME_2FTMUU_pre
ME_list[["ME_2FTMUU_post"]] <- ME_2FTMUU_post
ME_list[["ME_6K8YTY_pre"]] <- ME_6K8YTY_pre
ME_list[["ME_6K8YTY_post"]] <- ME_6K8YTY_post
ME_list[["ME_6KLSUS_pre"]] <- ME_6KLSUS_pre
ME_list[["ME_8YGUU8_pre"]] <- ME_8YGUU8_pre
ME_list[["ME_8YGUU8_post"]] <- ME_8YGUU8_post
ME_list[["ME_32ARQL_pre"]] <- ME_32ARQL_pre
ME_list[["ME_CSU6UB_pre"]] <- ME_CSU6UB_pre
ME_list[["ME_CSU6UB_post"]] <- ME_CSU6UB_post
ME_list[["ME_E79WZA_pre"]] <- ME_E79WZA_pre
ME_list[["ME_N5CC3E_pre"]] <- ME_N5CC3E_pre
ME_list[["ME_N5CC3E_post"]] <- ME_N5CC3E_post
ME_list[["ME_N7ZK3L_pre"]] <- ME_N7ZK3L_pre
ME_list[["ME_N7ZK3L_post"]] <- ME_N7ZK3L_post
ME_list[["ME_NUL141_pre"]] <- ME_NUL141_pre
ME_list[["ME_NUL141_post"]] <- ME_NUL141_post
ME_list[["ME_PUVQFD_pre"]] <- ME_PUVQFD_pre
ME_list[["ME_R1H4HE_pre"]] <- ME_R1H4HE_pre
ME_list[["ME_R1H4HE_post"]] <- ME_R1H4HE_post
ME_list[["ME_R1V8RN_pre"]] <- ME_R1V8RN_pre
ME_list[["ME_R1V8RN_post"]] <- ME_R1V8RN_post
ME_list[["ME_TS6ZX9_pre"]] <- ME_TS6ZX9_pre
ME_list[["ME_VP6CSY_pre"]] <- ME_VP6CSY_pre
ME_list[["ME_VP6CSY_post"]] <- ME_VP6CSY_post
ME_list[["ME_XF2DTB_pre"]] <- ME_XF2DTB_pre
ME_list[["ME_XF2DTB_post"]] <- ME_XF2DTB_post
ME_list[["ME_YK554L_pre"]] <- ME_YK554L_pre
ME_list[["ME_YK554L_post"]] <- ME_YK554L_post
ME_list[["ME_ZPMZFJ_pre"]] <- ME_ZPMZFJ_pre
ME_list[["ME_ZPMZFJ_post"]] <- ME_ZPMZFJ_post

for (i in 1:length(ME_list)) {
ME_list[[i]] <- NormalizeData(ME_list[[i]], verbose = FALSE)
ME_list[[i]] <- FindVariableFeatures(ME_list[[i]], selection.method = "vst",
nfeatures = 2000, verbose = FALSE)
}

features <- SelectIntegrationFeatures(object.list = ME_list)
ME_list <- lapply(X = ME_list, FUN = function(x) {
x <- ScaleData(x, features = features, verbose = FALSE)
x <- RunPCA(x, features = features, verbose = FALSE)
})

anchors <- FindIntegrationAnchors(object.list = ME_list, reduction = "rpca", dims = 1:40)
ME.integrated <- IntegrateData(anchorset = anchors, dims = 1:40)

```

**Comment by timoast** [comment] 2019-08-09 14:00
Hi @StephanTir, how many cells do you have in each object? Can you provide the output of:

```r
sapply(ME_list, ncol)
```

**Comment by StephanTir** [comment] 2019-08-09 14:47
ME_2FTMUU_pre                                       1329
ME_2FTMUU_post                                      4180
ME_6K8YTY_pre                                       3237
ME_6K8YTY_post                                      9622
ME_6KLSUS_pre                                      12746
ME_8YGUU8_pre                                       2916
ME_8YGUU8_post                                      9040
ME_32ARQL_pre                                       2076
ME_CSU6UB_pre                                       2902
ME_CSU6UB_post                                      4250
ME_E79WZA_pre                                      16818
ME_N5CC3E_pre                                        844
ME_N5CC3E_post                                      3397
ME_N7ZK3L_pre                                       3698
ME_N7ZK3L_post                                      2404
ME_NUL141_pre                                       2226
ME_NUL141_post                                      1369
ME_PUVQFD_pre                                       9732
ME_R1H4HE_pre                                       4866
ME_R1H4HE_post                                      4899
ME_R1V8RN_pre                                       2913
ME_R1V8RN_post                                      1958
ME_TS6ZX9_pre                                       1966
ME_VP6CSY_pre                                       1747
ME_VP6CSY_post                                      1377
ME_XF2DTB_pre                                       2866
ME_XF2DTB_post                                      3718
ME_YK554L_pre                                       2823
ME_YK554L_post                                     10676
ME_ZPMZFJ_pre                                       2684
ME_ZPMZFJ_post                                       377

**Comment by eregenyi** [comment] 2019-10-04 08:27
Hi, 
I am getting the same error message: 
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive

When running RunPCA().

**Comment by adamZhang-J2018** [comment] 2019-11-18 17:12
Hi 
I got the same error message as StephanTir when using rPCA
I am wondering if it is due to the sample size, like too many samples and cells.
I have over 50 samples to integrate. No matter using CCA or rPCA, the "IntegrateData" function failed. Looking forward to a solution for this problem, since there are more and more studies to integrate multiple samples.
Thanks a lot!

**Comment by yingyonghui** [comment] 2020-07-06 01:11
Hi, all,
I got the same error when using rPCA with ~120k cells.
Is there any new suggestions?

Thx~

**Comment by zji90** [comment] 2020-07-24 15:09
Same problem here.

**Comment by talban14** [comment] 2020-07-27 13:14
Same problem here as well.  It works okay with refernce based thoough.  I don't think it's a memory issue as i'm workin on 3TB of ram and have around 300K cells.

**Comment by jmonte25** [comment] 2020-10-22 15:15
I have the same error as well. Seems that issues pertaining to RAM are not a problem for me. 

This error arises when I try to integrate greater than 7 - 9 samples that average 300 total cells on default parameters. 

The error is resolved when I do the following: 
1) Lower the default parameters in the FindIntegrationAnchors function by a considerable amount.
2) Use datasets with a greater number of cells
3) Use fewer than 7-9 samples. 

Please let me know if there are any updates on resolving this issue.

Thank you!

**Comment by uberholzer** [comment] 2021-02-12 15:37
Hi @timoast @andrewwbutler @satijalab, Can you please comment about your current thinking on this still-open issue? I am running into this error but with v 4.0.0 and the new rPCA vignette at https://satijalab.org/seurat/articles/integration_rpca.html I was hoping that the issue had perhaps been fixed. 

Do you agree with jmonte25 that the number of datasets and number of cells will limit whether rPCA integration can be run successfully?

Thank you!

**Comment by zhiiiyang** [comment] 2021-03-02 05:07
I saw many people are raising questions about getting an error from using `rPCA` integration. Based on my attempt at using the exact same code from this vignette https://satijalab.org/seurat/articles/integration_rpca.html, it works perfectly on ~130k cells of three datasets.

**Comment by Shiywa** [comment] 2021-03-23 10:19
same error.

**Comment by yuhanH** [comment] 2022-03-25 18:38
I will close this issue. If you have new integrateData error, please open up a new issue.

**Closed by yuhanH** 2022-03-25 18:38 UTC
