### ISSUE TITLE
错误于xtfrm.data.frame(x): 无法 xtfrm 数据帧

### ISSUE THREAD

**Issue by Hannahh66** [satijalab/seurat#9334] opened 2024-09-25 09:22 UTC
https://satijalab.org/seurat/articles/spatial_vignette.html#acknowledgments

When I followed the above process, R kept reporting errors
SpatialFeaturePlot(slide.seq, features = head(SpatiallyVariableFeatures(slide.seq, selection.method = "moransi"),6), ncol = 3, alpha = c(0.1, 1), max.cutoff = "q95")
错误于xtfrm.data.frame(x): 无法 xtfrm 数据帧

**Comment by adyzh** [comment] 2024-10-11 20:45
Hi @Hannahh66 ,
Thank you for reaching out! We’re always grateful when folks take the time to help make Seurat better :slightly_smiling_face:
Unfortunately, with the details provided, we cannot reproduce your issue. To help us better understand and resolve this issue, please ensure that you provide the following information when reporting a bug:
1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.
We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost and we will be more than happy to help you resolve the problem.

**Closed by adyzh** 2024-10-11 20:45 UTC
