### ISSUE TITLE
plotting problems: caught illegal operation 

### ISSUE THREAD

**Issue by atermanini** [satijalab/seurat#1654] opened 2019-06-07 16:18 UTC
Hello, I have a problem when generating a plot with Seurat 3.0.1 with R 3.6 under Debian Linux.
By running this code:

g = Seurat::VlnPlot(S, features = "percent.mt", combine = TRUE);
pdf(file="test.pdf");
plot(g);
dev.off()

I got this error:

 *** caught illegal operation ***
address 0x7ffba54c8fa0, cause 'illegal operand'

Traceback:
 1: plyr::id(data[disc], drop = TRUE)
 2: add_group(evaled)
 3: f(..., self = self)
 4: l$compute_aesthetics(d, plot)
 5: f(l = layers[[i]], d = data[[i]])
 6: by_layer(function(l, d) l$compute_aesthetics(d, plot))
 7: ggplot_build.ggplot(x)
 8: ggplot_build(x)
 9: plot.ggplot(g)
10: plot(g)
11: makeQCPlots(S, folderTo, pt.size = ptSize, prefix = "Unfilt",  printStatus = printStatus)
(makeQCPlots is a function where I load data and I make some plots).

However, I can generate pdf correctly if I am creating ggplot objects without Seurat like with:
data(mtcars);
g = ggplot(data = mtcars, mapping = aes(x = wt, y = mpg)) + geom_point();
pdf(file="test.ggplot.pdf");
plot(g);
dev.off();

In addition, if I am saving the Seurat ggplot to file, and I read it in RStudio under Mac OS X, its works:
g = Seurat::VlnPlot(S, features = "percent.mt", combine = TRUE);
saveRDS(g, file = "g.Rds", compress = TRUE);
[..reading on Mac OS X, plotting: ok]

Below is the output of sessionInfo(), and I am attaching the ggplot object created with Seurat.

Can you help me? I have spent several times but without results.

Thanks very much,
Alberto

------------------------------------------------------------------------

R version 3.6.0 (2019-04-26)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /mnt/isilon/bioinformatica/atermanini/projects/test/scRNA-Seq/conda/R/lib/R/lib/libRblas.so

locale:
[1] it_IT.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.1.1 Matrix_1.2-17 Seurat_3.0.1 

loaded via a namespace (and not attached):
 [1] httr_1.4.0          tidyr_0.8.3         jsonlite_1.6       
 [4] viridisLite_0.3.0   splines_3.6.0       lsei_1.2-0         
 [7] R.utils_2.8.0       gtools_3.8.1        Rdpack_0.11-0      
[10] assertthat_0.2.1    ggrepel_0.8.1       globals_0.12.4     
[13] pillar_1.3.1        lattice_0.20-38     reticulate_1.12    
[16] glue_1.3.1          digest_0.6.18       RColorBrewer_1.1-2 
[19] SDMTools_1.1-221.1  colorspace_1.4-1    cowplot_0.9.4      
[22] htmltools_0.3.6     R.oo_1.22.0         plyr_1.8.4         
[25] pkgconfig_2.0.2     bibtex_0.4.2        tsne_0.1-3         
[28] listenv_0.7.0       purrr_0.3.2         scales_1.0.0       
[31] RANN_2.6.1          gdata_2.18.0        Rtsne_0.15         
[34] tibble_2.1.1        withr_2.1.2         ROCR_1.0-7         
[37] pbapply_1.4-0       lazyeval_0.2.2      survival_2.44-1.1  
[40] magrittr_1.5        crayon_1.3.4        R.methodsS3_1.7.1  
[43] future_1.13.0       nlme_3.1-139        MASS_7.3-51.3      
[46] gplots_3.0.1.1      ica_1.0-2           tools_3.6.0        
[49] fitdistrplus_1.0-14 data.table_1.12.2   gbRd_0.4-11        
[52] stringr_1.4.0       plotly_4.9.0        munsell_0.5.0      
[55] cluster_2.0.8       irlba_2.3.3         compiler_3.6.0     
[58] rsvd_1.0.1          caTools_1.17.1.2    rlang_0.3.4        
[61] grid_3.6.0          ggridges_0.5.1      htmlwidgets_1.3    
[64] igraph_1.2.4.1      labeling_0.3        bitops_1.0-6       
[67] npsurv_0.4-0        gtable_0.3.0        codetools_0.2-16   
[70] reshape2_1.4.3      R6_2.4.0            gridExtra_2.3      
[73] zoo_1.8-5           dplyr_0.8.0.1       future.apply_1.2.0 
[76] KernSmooth_2.23-15  metap_1.1           ape_5.3            
[79] stringi_1.4.3       parallel_3.6.0      Rcpp_1.0.1         
[82] sctransform_0.2.0   png_0.1-7           tidyselect_0.2.5   
[85] lmtest_0.9-37      

[g.pdf](https://github.com/satijalab/seurat/files/3266766/g.pdf)

[g.Rds.zip](https://github.com/satijalab/seurat/files/3266772/g.Rds.zip)

**Comment by andrewwbutler** [comment] 2019-06-10 17:28
Hi,

I'm not able to replicate the issue. Does using `ggsave` work?

```R
ggplot2::ggsave(filename = "test.pdf", plot = g)
```

**Comment by atermanini** [comment] 2019-06-11 09:32
Hi Andrew,

thanks very much for your help. No, with ggsave I got an error (text below).
I am attaching the Seurat object as an Rds file, hoping this can help reproducing the problem.

Thanks again,
Alberto

---
ggplot2::ggsave(filename = "test.pdf", plot = g)

[SeuratObject.Rds.zip](https://github.com/satijalab/seurat/files/3275707/SeuratObject.Rds.zip)

Saving 7 x 7 in image

 *** caught illegal operation ***
address 0x7f626d8c8fa0, cause 'illegal operand'

Traceback:
 1: plyr::id(data[disc], drop = TRUE)
 2: add_group(evaled)
 3: f(..., self = self)
 4: l$compute_aesthetics(d, plot)
 5: f(l = layers[[i]], d = data[[i]])
 6: by_layer(function(l, d) l$compute_aesthetics(d, plot))
 7: ggplot_build.ggplot(x)
 8: ggplot_build(x)
 9: print.ggplot(x)
10: print(x)
11: grid.draw.ggplot(plot)
12: grid.draw(plot)
13: ggplot2::ggsave(filename = "test.pdf", plot = g)
14: makeQCPlots(S, folderTo, pt.size = ptSize, prefix = "Unfilt",     printStatus = printStatus)
An irrecoverable exception occurred. R is aborting now ...

**Comment by andrewwbutler** [comment] 2019-06-14 15:02
Hmm, I'm not able to reproduce it from the object you provided. Can you post the code for your `makeQCPlots` function. Maybe something is happening in that which is causing the issue.

**Comment by satijalab** [comment] 2019-06-21 15:53
Really sorry about this. I am closing this issue as we unfortunately cannot reproduce it on the same object with our system, suggesting it is something more specific to your session. If this reproduces on multiple computers, let us know, and we'll take another look.

**Closed by satijalab** 2019-06-21 15:53 UTC
Labels: more-information-needed
