### ISSUE TITLE
DotPlot only show gradient of grey, when the value in split variable contains '_'

### ISSUE THREAD

**Issue by shendong124** [satijalab/seurat#1620] opened 2019-06-02 08:29 UTC
Hi Seurat Team,
I am trying to use Dot plot on my dataset and it seems that I can not get any other vcolors than gradient of greys.
here is my code:

DotPlot(mergetest2.big, features = rev(markers.to.plot), cols = c("blue", "red", "blue"), dot.scale = 8, 
split.by = "orig.ident") + RotatedAxis()

and the result:
![Rplot02](https://user-images.githubusercontent.com/29153026/58758791-86718d80-84d5-11e9-818c-9463476894a8.png)

Thank you very much
Shen

**Comment by MediciPrime** [comment] 2019-06-07 19:55
I have the same question.  I am trying to create a DotPlot using data from an integrated Seurat analysis but for some reason I can only see a single grey color gradient.  Please help!

**Comment by osvobod** [comment] 2019-06-14 16:46
Hi, 
I have the same problem. Have you been able to find any solution to this?
Thank you,

Ondrej

**Comment by shendong124** [comment] 2019-06-14 18:43
Hi Satijalab/Seurat team,

I am still having this issue....

Shen

**Comment by shendong124** [comment] 2019-06-14 18:58
Never mind. It is working now.
I actually have not changed anything that I am sure made a difference. I just specified the genes for features.  Also maybe library(ggplot2)?

here is my code:
DotPlot(merge007001.big, features = c("CD247", "CD3E", "CD3D", "CD3G", "CD8B", "CD8A", "CD79A", "CD79B", "HLA-DRA", "CD27", "CD28", "CD4"), cols = c("blue", "red", "green"), split.by = "orig.ident")

![image](https://user-images.githubusercontent.com/29153026/59531743-9442ed80-8e9b-11e9-861d-50f15c7b57ad.png)

Hope it will work for you :)
Shen

**Comment by Liuy12** [comment] 2019-06-20 20:49
I encountered similar issues. Turns out that if you have '_' in your split variable, the color scheme will not work. This seems to be a bug.

**Comment by shendong124** [comment] 2019-06-20 21:10
Yes indeed!!
Thank you for the clarification!!!

Shen

**Comment by danmoore1987** [comment] 2020-01-24 02:08
Dear Seurat team, it appears that this bug has not been resolved, even the latest Seurat gives the same problem.

**Comment by owenwilkins** [comment] 2020-02-25 21:33
this is a most annoying bug

**Comment by yuhanH** [comment] 2020-02-25 22:07
Thanks for @Liuy12 's answer. If the value in your split variable contains '_', the color scheme will not work. We will fix this bug soon.

**Comment by satijalab** [comment] 2020-03-05 19:22
Closing as this is a duplicate

**Closed by satijalab** 2020-03-05 19:22 UTC
Labels: bug

**Comment by pullmebro** [comment] 2022-05-13 06:50
> I encountered similar issues. Turns out that if you have '_' in your split variable, the color scheme will not work. This seems to be a bug.

right

**Comment by hartmannmark** [comment] 2022-07-05 23:03
Guess this isn't resolved, yet... Still doesn't work for me!

**Comment by guilledelavega** [comment] 2022-10-28 08:31
The bug is still in that plot. You missed the legend about AvgExpression, and now you have the color grey in your plot, whereas in the original one the grey color doesnt appear if you establish the argument "cols". 

This is not working properly.

**Comment by Kadd-L** [comment] 2022-11-22 04:45
> 

Hi guilledelavega, a typo when I was copy-pasting my code - color statement I actually used was: 
x1 <- c("#efedf5", "#7fafed")
x2 <- c("#efedf5", "#dd1c77")
panel <- data.frame(x1, x2)
So I set 2 color gradient for 2 stims: Blue->Gray correlates with higher to lower average expression in condition1, while Pink->Gray correlates with higher to lower expression in condition2. My plot still have gray dots because these dots represent a much lower expressed genes. If you check them closely you can find actually there are intermediate colors - very light gray pink or like that, which means an intermediate level of expression in this group.

**Comment by guilledelavega** [comment] 2022-11-22 13:56
Thanks for your answer Kadd-L. The problem is that I dont understand the size of the plots then. If the colour is related to the expression, the size is the number of cells?. Still, the size of each point is different for the same conditions, which is very weird. 
The legends in these plots are wrong no?
Thank you too much

**Comment by Kadd-L** [comment] 2022-12-08 18:32
> @Kadd-L Hello, thank you for your answer. I was trying to do a dotplot for my four conditions. I did: <img alt="Screen Shot 2022-12-08 at 4 27 31 PM" width="112" src="https://user-images.githubusercontent.com/90501211/206396773-36b08f3a-6dfe-4002-aff3-844f47fe3167.png"> so I had four rows for my panel. Then I did: `myplot = DotPlot(seu, assay = 'RNA', features = features, group.by = 'cluster', split.by = 'orig.ident', cols=panel)`
> 
> However, it's still telling me `Not enough colors for the number of groups`, I am sure my `unique(seu$orig.ident` gives only four terms.
> 
> Do you have some ideas why? Thank you so much!

Hi @Jiayi-Zheng , 

"Not enough colors for the number of groups" indicated that you have more than 4 groups (instead of stim conditions). Try NOT to state your group. 
Besides, are you trying to plot all the genes? Check my code and you'll find I'm only plotting top10 genes.

**Comment by Kadd-L** [comment] 2022-12-08 18:35
> Thanks for your answer Kadd-L. The problem is that I dont understand the size of the plots then. If the colour is related to the expression, the size is the number of cells?. Still, the size of each point is different for the same conditions, which is very weird. The legends in these plots are wrong no? Thank you too much

Hi @guilledelavega , 
Color of the dot - Average expression level
Size of the dot - Percentage of the cells that are expressing this gene
The bug does exist in this package that when you're plotting too many colors, the legend looks weird. I have not come up with a solution but would suggest you do the legend manually by yourself. Hope it helps.
