### ISSUE TITLE
SubsetData fails to return `cells.use` with other arguments set to `NULL`

### ISSUE THREAD

**Issue by jacobkimmel** [satijalab/seurat#428] opened 2018-04-21 12:39 UTC
Using `SubsetData` with a simple character of cell names for the `cells.use` argument currently returns a `Seurat object` with `p` genes by `0` cells.

The error arises during the call to `WhichCells`, which fails to simply return `cells.use` when other arguments are passed as `NULL`. 

I can file a PR to simply fix this with an `if (!is.null(cells.use)){return(cells.use)}` as the documentation suggests, but the code indicates this may not actually be the currently desired functionality.

**Comment by mojaveazure** [comment] 2018-04-27 19:44
Hi Jacob,

I'm unable to reproduce this issue
```R
> data('pbmc_small')
> pbmc_small
An object of class seurat in project SeuratProject 
 230 genes across 80 samples.
> cells.use <- sample(x = pbmc_small@cell.names, 10)
> pbmc_subset <- SubsetData(object = pbmc_small, cells.use = cells.use)
> pbmc_subset
An object of class seurat in project SeuratProject 
 230 genes across 10 samples.
> all(pbmc_subset@cell.names %in% cells.use)
[1] TRUE
> all(rownames(x = pbmc_subset@meta.data) %in% cells.use)
[1] TRUE
> all(colnames(x = pbmc_subset@data) %in% cells.use)
[1] TRUE
> all(colnames(x = pbmc_subset@scale.data) %in% cells.use)
[1] TRUE
```

**Comment by satijalab** [comment] 2018-07-06 22:45
Closing the issue as we have not been able to reproduce, but can re-open in the future if needed

**Closed by satijalab** 2018-07-06 22:45 UTC
Labels: bug
