### ISSUE TITLE
Spatial RNA-seq:  Error in FUN(left, right) : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by cplaisier** [satijalab/seurat#6426] opened 2022-09-15 15:07 UTC
There is an issue in the spatial RNA-seq tutorial. If you try and run it on any data that is not your example dataset. That is loading from the output of spaceranger.

When you try and run the first set of plots you get the error:

Error in FUN(left, right) : non-numeric argument to binary operator

Which is caused by a simple issue that the coordinates data is non-numeric. **Easy fix. Please implement.** Details here:

https://stackoverflow.com/questions/73131436/error-in-funleft-right-non-numeric-argument-to-binary-operator-when-runni

**Comment by AustinHartman** [comment] 2022-09-23 19:56
Hi @cplaisier, I am having trouble reproducing on the latest version of Seurat using a [human melanoma dataset from 10x](https://www.10xgenomics.com/resources/datasets/human-melanoma-if-stained-ffpe-2-standard). Could you post your session info and possibly a publicly available dataset where you are running into this error?

**Comment by AustinHartman** [comment] 2023-06-30 19:29
Closing because of non-response and I'm unable to reproduce.

**Closed by AustinHartman** 2023-06-30 19:29 UTC
