### ISSUE TITLE
count_table format

### ISSUE THREAD

**Issue by pbrazda** [satijalab/seurat#233] opened 2017-11-29 23:05 UTC
Hi, 

Being new to the field, I first followed the pbmc3k tutorial and then I tried to apply it to my sample. I did a SORT-seq experiment and created the expression matrix with the CEL-seq2 pipeline. I failed to create a Seurat-object:

peri <- CreateSeuratObject(raw.data = matrixdata, min.cells = 3, min.genes = 200, project = "PERI")

Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be numeric
In addition: Warning message:
In Ops.factor(left, right) : '>' not meaningful for factors

I attached a part of my matrix (in total it has 384cells and 58k genes). Do I need to modify the format, or what might be the problem here?

Thank you!

[matrixdata.xlsx](https://github.com/satijalab/seurat/files/1515863/matrixdata.xlsx)

**Comment by leonfodoulian** [comment] 2017-11-29 23:22
Hi,

The problem is that one of your columns (the first one, corresponding to gene IDs) is not numeric. You should remove the header of the first column, save the file in `.csv` format, then read it using the following code:

```
d <- read.csv(file = "matrixdata.csv", sep = ",", row.names = 1, header = T)

head(d)
                   Periscope_100_A_sample_0100 Periscope_101_A_sample_0101
ENSG00000000003.14                           0                           0
ENSG00000000005.5                            0                           0
ENSG00000000419.12                           0                           0
                   Periscope_102_A_sample_0102 Periscope_103_A_sample_0103
ENSG00000000003.14                           0                           0
ENSG00000000005.5                            0                           0
ENSG00000000419.12                           0                           0
                   Periscope_104_A_sample_0104 Periscope_105_A_sample_0105
ENSG00000000003.14                           0                           0
ENSG00000000005.5                            0                           0
ENSG00000000419.12                           7                           0
```

Best,
Leon

**Comment by leonfodoulian** [comment] 2017-11-30 20:35
Great! Could you please close this issue?

Best,
Leon

**Closed** 2017-11-30 20:36 UTC
