### ISSUE TITLE
Seurat SpatialDimPlot Error

### ISSUE THREAD

**Issue by kasumaz** [satijalab/seurat#3644] opened 2020-10-26 14:24 UTC
Dear Seurat team, 
I have been attempting to extract some data from the spatial brain vignette. 

> ISpatialDimPlot(brain, interactive = TRUE)
Error in ISpatialDimPlot(brain, interactive = TRUE) : 
  unused argument (interactive = TRUE)
> 
> SpatialDimPlot(brain, interactive = TRUE)
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments

I have this problem on a new session/different new sessions and after reinstalling the dev version as well as the latest versions, restarting and updating any other dependent packages. 
I restart each time a new R session as I mentioned. I have the same errors as pasted above. 
I tried  'ISpatialDimPlot' and also 'SpatialDimPlot' - I saw in another closed thread to put an I in front. I cant get past this error. 

Is there something that I can do to get off this problem? 
The rest of the script works. I just need to use the interactive plot to zoom into 2 areas of the brain. 
Any suggestions/instructions would be great. 
Many thanks once again.

**Comment by cdarby** [comment] 2020-10-26 17:49
Duplicate of #3648

**Closed by cdarby** 2020-10-26 17:49 UTC
Labels: bug, duplicate
