### ISSUE TITLE
CreateSeuratObject fails to add metadata

### ISSUE THREAD

**Issue by eblchen** [satijalab/seurat#9021] opened 2024-06-17 16:01 UTC
Trying to generate a Seurat object:
```
> patient.seurat <- CreateSeuratObject(counts = assay(patient.sce, "counts"),
+                                      assay = "RNA",
+                                      meta.data = patient.meta)
Warning: `i` must be one of "Hepato_Tumour_AAACAGCCACAAGCCT-1", "Hepato_Tumour_AAACAGCCACCAGCAT-1", "Hepato_Tumour_AAACAGCCACGAATTT-1", "Hepato_Tumour_AAACAGCCAGTAAAGC-1", "Hepato_Tumour_AAACAGCCAGTATGTT-1", "Hepato_Tumour_AAACAGCCATTGACAT-1", "Hepato_Tumour_AAACATGCAAAGGCCA-1", "Hepato_Tumour_AAACATGCACTCAACA-1", "Hepato_Tumour_AAACATGCAGGCAAGC-1", "Hepato_Tumour_AAACATGCAGGTCCTG-1", "Hepato_Tumour_AAACATGCATTGTGAT-1", "Hepato_Tumour_AAACCAACACAAGCCT-1", "Hepato_Tumour_AAACCAACACAGACTC-1", "Hepato_Tumour_AAACCAACACATAGCC-1", "Hepato_Tumour_AAACCAACACCTCAGG-1", "Hepato_Tumour_AAACCAACATAGCGAG-1", "Hepato_Tumour_AAACCAACATTAGGTT-1", "Hepato_Tumour_AAACCGAAGACCATAC-1", "Hepato_Tumour_AAACCGAAGGACCTGC-1", "Hepato_Tumour_AAACCGAAGGGCCATC-1", "Hepato_Tumour_AAACCGAAGGTCCTAG-1", "Hepato_Tumour_AAACCGAAGTTAGCCG-1", "Hepato_Tumour_AAACCGCGTAATGGCC-1", "Hepato_Tumour_AAACCGCGTACCGTAA-1", "Hepato_Tumour_AAACCGCGTCGCGCAA-1", "Hepato_Tumour_AAACCGCGTGGTTAGC-1", "Hepato_Tumour_AAACCGGCAAACCTTG-1", "Hepato_T [... truncated]

```
Metadata (below) fails to be added:
```
> head(patient.meta)
                                        Sample            Barcode                           CellID sizeFactor        batch  sum
Hepato_Tumour_AAACAGCCACAAGCCT-1 Hepato_Tumour AAACAGCCACAAGCCT-1 Hepato_Tumour_AAACAGCCACAAGCCT-1  0.6660449 Hepato_T.... 2587
Hepato_Tumour_AAACAGCCACCAGCAT-1 Hepato_Tumour AAACAGCCACCAGCAT-1 Hepato_Tumour_AAACAGCCACCAGCAT-1  1.2486741 Hepato_T.... 4761
Hepato_Tumour_AAACAGCCACGAATTT-1 Hepato_Tumour AAACAGCCACGAATTT-1 Hepato_Tumour_AAACAGCCACGAATTT-1  0.9745942 Hepato_T.... 2846
Hepato_Tumour_AAACAGCCAGTAAAGC-1 Hepato_Tumour AAACAGCCAGTAAAGC-1 Hepato_Tumour_AAACAGCCAGTAAAGC-1  0.8186945 Hepato_T.... 3503
Hepato_Tumour_AAACAGCCAGTATGTT-1 Hepato_Tumour AAACAGCCAGTATGTT-1 Hepato_Tumour_AAACAGCCAGTATGTT-1  1.0787898 Hepato_T.... 2945
Hepato_Tumour_AAACAGCCATTGACAT-1 Hepato_Tumour AAACAGCCATTGACAT-1 Hepato_Tumour_AAACAGCCATTGACAT-1  1.0854867 Hepato_T.... 3212
                                 detected subsets_mt_sum subsets_mt_detected subsets_mt_percent subsets_linc_sum subsets_linc_detected
Hepato_Tumour_AAACAGCCACAAGCCT-1     1412             28                   8          1.0823348              195                    45
Hepato_Tumour_AAACAGCCACCAGCAT-1     2160             37                   9          0.7771477              344                    52
Hepato_Tumour_AAACAGCCACGAATTT-1     1492             15                   6          0.5270555              238                    39
Hepato_Tumour_AAACAGCCAGTAAAGC-1     1654            259                  13          7.3936626              219                    33
Hepato_Tumour_AAACAGCCAGTATGTT-1     1475            156                  12          5.2971138              234                    60
Hepato_Tumour_AAACAGCCATTGACAT-1     1595             50                  10          1.5566625              241                    36
                                 subsets_linc_percent subsets_ribo_sum subsets_ribo_detected subsets_ribo_percent total
Hepato_Tumour_AAACAGCCACAAGCCT-1             7.537688                5                     4            0.1932741  2587
Hepato_Tumour_AAACAGCCACCAGCAT-1             7.225373               21                    19            0.4410838  4761
Hepato_Tumour_AAACAGCCACGAATTT-1             8.362614                3                     3            0.1054111  2846
Hepato_Tumour_AAACAGCCAGTAAAGC-1             6.251784               30                    21            0.8564088  3503
Hepato_Tumour_AAACAGCCAGTATGTT-1             7.945671               10                     9            0.3395586  2945
Hepato_Tumour_AAACAGCCATTGACAT-1             7.503113               10                     8            0.3113325  3212
```
```
> head(patient.seurat@meta.data)
                                 orig.ident nCount_RNA nFeature_RNA
Hepato_Tumour_AAACAGCCACAAGCCT-1     Hepato       2502         1366
Hepato_Tumour_AAACAGCCACCAGCAT-1     Hepato       4632         2100
Hepato_Tumour_AAACAGCCACGAATTT-1     Hepato       2786         1462
Hepato_Tumour_AAACAGCCAGTAAAGC-1     Hepato       3165         1598
Hepato_Tumour_AAACAGCCAGTATGTT-1     Hepato       2710         1411
Hepato_Tumour_AAACAGCCATTGACAT-1     Hepato       3090         1545
```
Checked that rownames of counts assay and colnames of meta data match:
```
> identical(rownames(patient.meta), colnames(assay(patient.sce, "counts")))
[1] TRUE
```
Session Info:
```
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8    LC_MONETARY=English_United Kingdom.utf8
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.utf8    

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] EnsDb.Hsapiens.v86_2.99.0   ensembldb_2.26.0            AnnotationFilter_1.26.0     GenomicFeatures_1.54.1     
 [5] AnnotationDbi_1.64.1        hues_0.2.0                  reshape2_1.4.4              cowplot_1.1.3              
 [9] lubridate_1.9.3             forcats_1.0.0               stringr_1.5.1               dplyr_1.1.4                
[13] purrr_1.0.2                 readr_2.1.5                 tidyr_1.3.1                 tibble_3.2.1               
[17] tidyverse_2.0.0             biomaRt_2.58.0              BiocParallel_1.36.0         igraph_2.0.1.1             
[21] DropletUtils_1.22.0         scMerge_1.18.0              Seurat_5.0.3                SeuratObject_5.0.1         
[25] sp_2.1-3                    scater_1.30.1               ggplot2_3.4.2               scran_1.30.0               
[29] scuttle_1.12.0              SingleCellExperiment_1.24.0 SummarizedExperiment_1.32.0 Biobase_2.62.0             
[33] GenomicRanges_1.54.1        GenomeInfoDb_1.38.5         IRanges_2.36.0              S4Vectors_0.40.2           
[37] BiocGenerics_0.48.1         MatrixGenerics_1.14.0       matrixStats_1.2.0           patchwork_1.2.0            
[41] Matrix_1.6-5               

loaded via a namespace (and not attached):
  [1] R.methodsS3_1.8.2         dichromat_2.0-0.1         progress_1.2.3            nnet_7.3-19               goftest_1.2-3            
  [6] Biostrings_2.70.1         HDF5Array_1.30.0          rstan_2.32.6              vctrs_0.6.5               spatstat.random_3.2-2    
 [11] digest_0.6.34             png_0.1-8                 ggrepel_0.9.5             deldir_2.0-2              parallelly_1.36.0        
 [16] batchelor_1.18.1          MASS_7.3-60.0.1           httpuv_1.6.13             withr_3.0.0               xfun_0.41                
 [21] ellipsis_0.3.2            survival_3.5-7            memoise_2.0.1             proxyC_0.4.1              ggbeeswarm_0.7.2         
 [26] systemfonts_1.0.5         ragg_1.2.7                zoo_1.8-12                gtools_3.9.5              pbapply_1.7-2            
 [31] R.oo_1.25.0               DEoptimR_1.1-3            Formula_1.2-5             prettyunits_1.2.0         KEGGREST_1.42.0          
 [36] promises_1.2.1            httr_1.4.7                restfulr_0.0.15           globals_0.16.2            fitdistrplus_1.1-11      
 [41] cvTools_0.3.3             rhdf5filters_1.14.1       rhdf5_2.46.1              rstudioapi_0.15.0         miniUI_0.1.1.1           
 [46] generics_0.1.3            base64enc_0.1-3           curl_5.2.0                zlibbioc_1.48.0           sfsmisc_1.1-18           
 [51] ScaledMatrix_1.10.0       polyclip_1.10-6           GenomeInfoDbData_1.2.11   SparseArray_1.2.3         xtable_1.8-4             
 [56] evaluate_0.23             S4Arrays_1.2.0            BiocFileCache_2.10.1      hms_1.1.3                 irlba_2.3.5.1            
 [61] colorspace_2.1-0          filelock_1.0.3            ROCR_1.0-11               reticulate_1.35.0         spatstat.data_3.0-4      
 [66] magrittr_2.0.3            lmtest_0.9-40             later_1.3.2               viridis_0.6.5             lattice_0.22-5           
 [71] mapproj_1.2.11            spatstat.geom_3.2-8       future.apply_1.11.1       robustbase_0.99-1         scattermore_1.2          
 [76] XML_3.99-0.16             RcppAnnoy_0.0.22          Hmisc_5.1-1               pillar_1.9.0              StanHeaders_2.32.7       
 [81] nlme_3.1-164              caTools_1.18.2            compiler_4.3.2            beachmat_2.18.0           RSpectra_0.16-1          
 [86] stringi_1.8.3             tensor_1.5                GenomicAlignments_1.38.1  plyr_1.8.9                BiocIO_1.12.0            
 [91] crayon_1.5.2              abind_1.4-5               locfit_1.5-9.8            pals_1.8                  bit_4.0.5                
 [96] codetools_0.2-19          textshaping_0.3.7         BiocSingular_1.18.0       QuickJSR_1.1.3            plotly_4.10.4            
[101] mime_0.12                 splines_4.3.2             Rcpp_1.0.12               fastDummies_1.7.3         dbplyr_2.4.0             
[106] sparseMatrixStats_1.14.0  knitr_1.45                blob_1.2.4                utf8_1.2.4                reldist_1.7-2            
[111] listenv_0.9.1             checkmate_2.3.1           DelayedMatrixStats_1.24.0 pkgbuild_1.4.3            statmod_1.5.0            
[116] tzdb_0.4.0                startupmsg_0.9.6.1        pkgconfig_2.0.3           tools_4.3.2               cachem_1.0.8             
[121] RSQLite_2.3.4             viridisLite_0.4.2         DBI_1.2.1                 numDeriv_2016.8-1.1       fastmap_1.1.1            
[126] rmarkdown_2.25            scales_1.3.0              grid_4.3.2                ica_1.0-3                 Rsamtools_2.18.0         
[131] dotCall64_1.1-1           RANN_2.6.1                rpart_4.1.23              farver_2.1.1              mgcv_1.9-1               
[136] yaml_2.3.8                foreign_0.8-86            rtracklayer_1.62.0        cli_3.6.2                 leiden_0.4.3.1           
[141] lifecycle_1.0.4           uwot_0.1.16               M3Drop_1.28.8             mvtnorm_1.2-4             bluster_1.12.0           
[146] backports_1.4.1           distr_2.9.3               rjson_0.2.21              timechange_0.2.0          gtable_0.3.4             
[151] ggridges_0.5.6            densEstBayes_1.0-2.2      progressr_0.14.0          parallel_4.3.2            limma_3.58.1             
[156] jsonlite_1.8.8            edgeR_4.0.9               RcppHNSW_0.6.0            bitops_1.0-7              bit64_4.0.5              
[161] Rtsne_0.17                spatstat.utils_3.0-4      BiocNeighbors_1.20.2      RcppParallel_5.1.7        bdsmatrix_1.3-6          
[166] metapod_1.10.1            dqrng_0.3.2               loo_2.7.0                 R.utils_2.12.3            lazyeval_0.2.2           
[171] shiny_1.8.0               ruv_0.9.7.1               htmltools_0.5.7           sctransform_0.4.1         rappdirs_0.3.3           
[176] glue_1.7.0                spam_2.10-0               ResidualMatrix_1.12.0     XVector_0.42.0            RCurl_1.98-1.14          
[181] gridExtra_2.3             R6_2.5.1                  gplots_3.1.3.1            labeling_0.4.3            cluster_2.1.6            
[186] bbmle_1.0.25.1            Rhdf5lib_1.24.1           ProtGenerics_1.34.0       rstantools_2.4.0          DelayedArray_0.28.0      
[191] tidyselect_1.2.0          vipor_0.4.7               htmlTable_2.4.2           maps_3.4.2                xml2_1.3.6               
[196] inline_0.3.19             future_1.33.1             rsvd_1.0.5                munsell_0.5.0             KernSmooth_2.23-22       
[201] data.table_1.15.0         htmlwidgets_1.6.4         RColorBrewer_1.1-3        rlang_1.1.3               spatstat.sparse_3.0-3    
[206] spatstat.explore_3.2-6    fansi_1.0.6               beeswarm_0.4.0           
> 
```

**Comment by zskylarli** [comment] 2024-06-24 15:25
Hi - could you try to alternatively add the metadata with `patient.seurat[[]] <- patient.meta`, or see if individual metadata columns could be added, such as patient.seurat$Sample <- patient.meta[,'Sample']? 

On an additional note, the more standard way to create the Seurat object would be:

```
patient.seurat <- CreateSeuratObject(counts = patient.sce[['RNA']]$counts,
                                     meta.data = patient.meta)
```

I will close this for now as this seems to be an object-specific issue and was not reproducible with our PBMC dataset, but please feel free to reopen if none of these suggestions works.

**Closed by zskylarli** 2024-06-24 15:25 UTC
Labels: bug

**Comment by onurcanbektas** [comment] 2024-10-18 20:22
this is an existing problem

**Comment by timtheoya** [comment] 2024-10-30 10:52
I was having this same issue.  Yours was the only thread I could find.

At least in my case, it turns out that one of the metadata columns I was trying to add had a data type of "list" (check with typeof(metadata$columnname[1])

when I made it a "character" type it worked no problem.

Hope this helps!!!
