### ISSUE TITLE
subset fails when spatial coordinates layers are modified

### ISSUE THREAD

**Issue by jsicherman** [satijalab/seurat#7462] opened 2023-06-16 17:53 UTC
# Summary
Attempting to `subset` a `SeuratObject` after adding a spatial coordinates layer (via. `Seurat.object[["example"]] <- Crop(Seurat.object, ...)`, for example) results in an error:

```
Error in subset.Centroids(x = x[[i]], cells = cells) :
  None of the requested cells found
```

This is not limited to modifying via. the `Crop` function. It can also happen, for example, when multiple datasets are `merge`d.

For posterity, the current workaround is to first subset any relevant `SeuratObject`s, and manipulate any spatial coordinates layers afterward.

# Reprex
```r
Seurat.object <- LoadXenium("/path/to/experiment")
Seurat.object$example <- sample(LETTERS[1:3], ncol(Seurat.object), TRUE)
Seurat.object[["zoom"]] <- Crop(Seurat.object[["fov"]], x = c(1200, 2900), y = c(3750, 4550), coords = "plot")
subset(Seurat.object, example == "A")
```

```
SeuratObject_4.1.3 Seurat_4.3.0.9003 
```

If I have time in the next few weeks, I'll take a stab at a fix.

**Comment by alikhuseynov** [comment] 2023-06-19 13:34
It's more related to [`SeuratObject`](https://github.com/mojaveazure/seurat-object) take a look at [this](https://github.com/satijalab/seurat/issues/6409#issuecomment-1568808941) same issue basically.
I have modified version for `subset` [here](https://github.com/alikhuseynov/add-on_R/blob/develop/R/subset_obj_seurat.R) and recently updated one [here](https://github.com/alikhuseynov/add-on_R/blob/develop/R/subset_obj_seurat_v2.R)
..didn't have time to PR it yet.
best

**Comment by AustinHartman** [comment] 2023-07-07 14:21
@jsicherman Could you point me to the dataset you're using in the reproducible example? I'm unable to replicate using the xenium_tiny_subset dataset and a slightly newer version of Seurat develop (4.3.0.9008).

**Comment by alikhuseynov** [comment] 2023-07-07 15:10
@AustinHartman does your `xenium_tiny_subset` obj contains at least 2 FOVs or samples?
`subset()` works only if at least few cells are found in all FOVs present in an object. 
If we use, say only first 10 cells in an object with at least 2 FOVs, then:
```
# Vizgen data object
subset(obj, cells = Cells(obj)[1:10])
Warning message:
“Adding image data that isn't associated with any assay present”
Error in subset.Centroids(x = x[[i]], cells = cells): None of the requested cells found
Traceback:

1. subset(obj, cells = Cells(obj)[1:10])
2. subset(obj, cells = Cells(obj)[1:10])
3. subset.Seurat(obj, cells = Cells(obj)[1:10])
4. base::subset(x = x[[image]], cells = cells)
5. subset.FOV(x = x[[image]], cells = cells)
6. subset(x = x[[i]], cells = cells)
7. subset.Centroids(x = x[[i]], cells = cells)
8. stop("None of the requested cells found")
```
```
package.version("Seurat")
'4.3.0.9002'
package.version("SeuratObject")
'4.1.3'
```

Additionally, if subsetting to keep, say 1-2 genes, works only for `"centroids"` and `"segmentation"`, `"molecules"` are not subsetted

**Comment by alikhuseynov** [comment] 2024-01-26 20:34
Hi @AustinHartman and @jsicherman,  
I just wanted to touch base on this, since the issue still persists with `subset`, even with most recent version 
`SeuratObject 5.0.1`
Sometime ago, I implement [`subset_opt`](https://github.com/alikhuseynov/add-on_R/blob/develop/R/subset_obj_seurat_v2.R) as an intermediate solution that also subsets features (if provided).
I could optimize the code and PR that to `SeuratObject`? Or do you guys have something more efficient?
Thanks

**Comment by balthasar0810** [comment] 2024-05-13 07:06
Is there any solution now for this? I cannot subset my Xenium object for a sample

**Comment by alikhuseynov** [comment] 2024-05-13 07:35
> Is there any solution now for this? I cannot subset my Xenium object for a sample

does this temporary solution works? https://github.com/alikhuseynov/add-on_R/blob/develop/R/subset_obj_seurat_v2.R
see this thread https://github.com/satijalab/seurat/issues/6409#issuecomment-2102985338

**Comment by balthasar0810** [comment] 2024-05-14 07:45
I will try this, thank you. It is just strange that this simple method is not included in Seurat yet...

**Comment by alikhuseynov** [comment] 2024-05-14 08:25
ok for the info, it is supported in `SeuratObject` `5.0.2` but has warnings.. try out if it works for you..
see this issue #8848

**Comment by dcollins15** [comment] 2024-05-17 17:30
As @alikhuseynov pointed out, this issue has been resolved in `SeuratObject` v5.0.2 - you should be able to safely ignore the validation warnings (we probably ought to be silencing these...)

**Closed by dcollins15** 2024-05-17 17:30 UTC
Labels: bug

**Comment by balthasar0810** [comment] 2024-05-25 09:37
I tried the subset_opt function on my Xenium object but just getting an error:
tmp2 = subset_opt(tmp, idents = sam)
Updating object slots..
Error in object %<>% UpdateSlots() : could not find function "%<>%"

Any ideas?

Thanks, Chris

> sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /fast/AG_Schmidt-Ott/tcga_data/miniconda/envs/seu5/lib/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Europe/Berlin
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] spacexr_2.2.1      Seurat_5.0.3       SeuratObject_5.0.1 sp_2.1-3

loaded via a namespace (and not attached):
  [1] deldir_2.0-4           pbapply_1.7-2          gridExtra_2.3
  [4] rlang_1.1.3            magrittr_2.0.3         RcppAnnoy_0.0.22
  [7] matrixStats_1.2.0      ggridges_0.5.6         compiler_4.3.3
 [10] spatstat.geom_3.2-9    png_0.1-8              vctrs_0.6.5
 [13] reshape2_1.4.4         quadprog_1.5-8         stringr_1.5.1
 [16] crayon_1.5.2           pkgconfig_2.0.3        fastmap_1.1.1
 [19] ellipsis_0.3.2         utf8_1.2.4             promises_1.2.1
 [22] purrr_1.0.2            jsonlite_1.8.8         goftest_1.2-3
 [25] later_1.3.2            spatstat.utils_3.0-4   irlba_2.3.5.1
 [28] parallel_4.3.3         cluster_2.1.6          R6_2.5.1
 [31] ica_1.0-3              stringi_1.8.3          RColorBrewer_1.1-3
 [34] spatstat.data_3.0-4    reticulate_1.35.0      parallelly_1.37.1
 [37] lmtest_0.9-40          scattermore_1.2        iterators_1.0.14
 [40] Rcpp_1.0.12            tensor_1.5             future.apply_1.11.1
 [43] zoo_1.8-12             sctransform_0.4.1      httpuv_1.6.14
 [46] Matrix_1.6-5           splines_4.3.3          igraph_2.0.3
 [49] tidyselect_1.2.1       abind_1.4-5            doParallel_1.0.17
 [52] spatstat.random_3.2-3  codetools_0.2-19       miniUI_0.1.1.1
 [55] spatstat.explore_3.2-7 listenv_0.9.1          lattice_0.22-6
 [58] tibble_3.2.1           plyr_1.8.9             shiny_1.8.0
 [61] ROCR_1.0-11            Rtsne_0.17             future_1.33.1
 [64] fastDummies_1.7.3      survival_3.5-8         polyclip_1.10-6
 [67] fitdistrplus_1.1-11    pillar_1.9.0           KernSmooth_2.23-22
 [70] foreach_1.5.2          plotly_4.10.4          generics_0.1.3
 [73] RcppHNSW_0.6.0         ggplot2_3.5.1          munsell_0.5.1
 [76] scales_1.3.0           globals_0.16.3         xtable_1.8-4
 [79] glue_1.7.0             lazyeval_0.2.2         tools_4.3.3
 [82] data.table_1.15.4      RSpectra_0.16-1        RANN_2.6.1
 [85] leiden_0.4.3.1         dotCall64_1.1-1        cowplot_1.1.3
 [88] grid_4.3.3             tidyr_1.3.1            colorspace_2.1-0
 [91] nlme_3.1-164           patchwork_1.2.0        cli_3.6.2
 [94] spatstat.sparse_3.0-3  spam_2.10-0            fansi_1.0.6
 [97] viridisLite_0.4.2      dplyr_1.1.4            uwot_0.1.16
[100] gtable_0.3.5           digest_0.6.35          progressr_0.14.0
[103] ggrepel_0.9.5          htmlwidgets_1.6.4      htmltools_0.5.8.1
[106] lifecycle_1.0.4        httr_1.4.7             mime_0.12
[109] MASS_7.3-60.0.1
>

**Comment by alikhuseynov** [comment] 2024-05-25 16:55
> I tried the subset_opt function on my Xenium object but just getting an error:
> 
> tmp2 = subset_opt(tmp, idents = sam)
> 
> Updating object slots..
> 
> Error in object %<>% UpdateSlots() : could not find function "%<>%"
> 
> 
> 
> Any ideas?
> 
> 
> 
> Thanks, Chris
> 
> 
> 
> > sessionInfo()
> 
> R version 4.3.3 (2024-02-29)
> 
> Platform: x86_64-conda-linux-gnu (64-bit)
> 
> Running under: CentOS Linux 7 (Core)
> 
> 
> 
> Matrix products: default
> 
> BLAS/LAPACK: /fast/AG_Schmidt-Ott/tcga_data/miniconda/envs/seu5/lib/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0
> 
> 
> 
> locale:
> 
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
> 
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
> 
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
> 
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
> 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
> 
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
> 
> 
> 
> time zone: Europe/Berlin
> 
> tzcode source: system (glibc)
> 
> 
> 
> attached base packages:
> 
> [1] stats     graphics  grDevices utils     datasets  methods   base
> 
> 
> 
> other attached packages:
> 
> [1] spacexr_2.2.1      Seurat_5.0.3       SeuratObject_5.0.1 sp_2.1-3
> 
> 
> 
> loaded via a namespace (and not attached):
> 
>   [1] deldir_2.0-4           pbapply_1.7-2          gridExtra_2.3
> 
>   [4] rlang_1.1.3            magrittr_2.0.3         RcppAnnoy_0.0.22
> 
>   [7] matrixStats_1.2.0      ggridges_0.5.6         compiler_4.3.3
> 
>  [10] spatstat.geom_3.2-9    png_0.1-8              vctrs_0.6.5
> 
>  [13] reshape2_1.4.4         quadprog_1.5-8         stringr_1.5.1
> 
>  [16] crayon_1.5.2           pkgconfig_2.0.3        fastmap_1.1.1
> 
>  [19] ellipsis_0.3.2         utf8_1.2.4             promises_1.2.1
> 
>  [22] purrr_1.0.2            jsonlite_1.8.8         goftest_1.2-3
> 
>  [25] later_1.3.2            spatstat.utils_3.0-4   irlba_2.3.5.1
> 
>  [28] parallel_4.3.3         cluster_2.1.6          R6_2.5.1
> 
>  [31] ica_1.0-3              stringi_1.8.3          RColorBrewer_1.1-3
> 
>  [34] spatstat.data_3.0-4    reticulate_1.35.0      parallelly_1.37.1
> 
>  [37] lmtest_0.9-40          scattermore_1.2        iterators_1.0.14
> 
>  [40] Rcpp_1.0.12            tensor_1.5             future.apply_1.11.1
> 
>  [43] zoo_1.8-12             sctransform_0.4.1      httpuv_1.6.14
> 
>  [46] Matrix_1.6-5           splines_4.3.3          igraph_2.0.3
> 
>  [49] tidyselect_1.2.1       abind_1.4-5            doParallel_1.0.17
> 
>  [52] spatstat.random_3.2-3  codetools_0.2-19       miniUI_0.1.1.1
> 
>  [55] spatstat.explore_3.2-7 listenv_0.9.1          lattice_0.22-6
> 
>  [58] tibble_3.2.1           plyr_1.8.9             shiny_1.8.0
> 
>  [61] ROCR_1.0-11            Rtsne_0.17             future_1.33.1
> 
>  [64] fastDummies_1.7.3      survival_3.5-8         polyclip_1.10-6
> 
>  [67] fitdistrplus_1.1-11    pillar_1.9.0           KernSmooth_2.23-22
> 
>  [70] foreach_1.5.2          plotly_4.10.4          generics_0.1.3
> 
>  [73] RcppHNSW_0.6.0         ggplot2_3.5.1          munsell_0.5.1
> 
>  [76] scales_1.3.0           globals_0.16.3         xtable_1.8-4
> 
>  [79] glue_1.7.0             lazyeval_0.2.2         tools_4.3.3
> 
>  [82] data.table_1.15.4      RSpectra_0.16-1        RANN_2.6.1
> 
>  [85] leiden_0.4.3.1         dotCall64_1.1-1        cowplot_1.1.3
> 
>  [88] grid_4.3.3             tidyr_1.3.1            colorspace_2.1-0
> 
>  [91] nlme_3.1-164           patchwork_1.2.0        cli_3.6.2
> 
>  [94] spatstat.sparse_3.0-3  spam_2.10-0            fansi_1.0.6
> 
>  [97] viridisLite_0.4.2      dplyr_1.1.4            uwot_0.1.16
> 
> [100] gtable_0.3.5           digest_0.6.35          progressr_0.14.0
> 
> [103] ggrepel_0.9.5          htmlwidgets_1.6.4      htmltools_0.5.8.1
> 
> [106] lifecycle_1.0.4        httr_1.4.7             mime_0.12
> 
> [109] MASS_7.3-60.0.1
> 
> >
> 
> 
> 
> 
> 
> 

That's margittr assignment pipe, you need that package. 
But if you use SeuratObject version 5.2.0 then the subset will work

**Comment by balthasar0810** [comment] 2024-05-26 10:03
thanks, this solved the issue, i wasn't aware of the update.


---------------------------------------
PD Dr. med. Dipl.-Math. Christian Hinze
Oberarzt der Klinik für Nieren- und Hochdruckerkrankungen
Bereichsleitung Nierentransplantationsnachsorge
OE6840 Zentrum Innere Medizin
Medizinische Hochschule Hannover
Carl-Neuberg-Str. 1
30625 Hannover
Tel.: (+49) 176-1532 6305
https://www.mhh.de/nephrologie
https://www.mhh.de/nephrologie/forschung/ag-dr-med-christian-hinze

________________________________
Von: alikhuseynov ***@***.***>
Gesendet: Samstag, 25. Mai 2024 18:55:36
An: satijalab/seurat
Cc: balthasar0810; Comment
Betreff: [ext] Re: [satijalab/seurat] subset fails when spatial coordinates layers are modified (Issue #7462)


I tried the subset_opt function on my Xenium object but just getting an error:

tmp2 = subset_opt(tmp, idents = sam)

Updating object slots..

Error in object %<>% UpdateSlots() : could not find function "%<>%"

Any ideas?

Thanks, Chris

sessionInfo()

R version 4.3.3 (2024-02-29)

Platform: x86_64-conda-linux-gnu (64-bit)

Running under: CentOS Linux 7 (Core)

Matrix products: default

BLAS/LAPACK: /fast/AG_Schmidt-Ott/tcga_data/miniconda/envs/seu5/lib/libopenblasp-r0.3.26.so; LAPACK version 3.12.0

locale:

[1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C

[3] LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8

[5] LC_MONETARY=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8

[7] LC_PAPER=en_US.UTF-8 LC_NAME=C

[9] LC_ADDRESS=C LC_TELEPHONE=C

[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Europe/Berlin

tzcode source: system (glibc)

attached base packages:

[1] stats graphics grDevices utils datasets methods base

other attached packages:

[1] spacexr_2.2.1 Seurat_5.0.3 SeuratObject_5.0.1 sp_2.1-3

loaded via a namespace (and not attached):

[1] deldir_2.0-4 pbapply_1.7-2 gridExtra_2.3

[4] rlang_1.1.3 magrittr_2.0.3 RcppAnnoy_0.0.22

[7] matrixStats_1.2.0 ggridges_0.5.6 compiler_4.3.3

[10] spatstat.geom_3.2-9 png_0.1-8 vctrs_0.6.5

[13] reshape2_1.4.4 quadprog_1.5-8 stringr_1.5.1

[16] crayon_1.5.2 pkgconfig_2.0.3 fastmap_1.1.1

[19] ellipsis_0.3.2 utf8_1.2.4 promises_1.2.1

[22] purrr_1.0.2 jsonlite_1.8.8 goftest_1.2-3

[25] later_1.3.2 spatstat.utils_3.0-4 irlba_2.3.5.1

[28] parallel_4.3.3 cluster_2.1.6 R6_2.5.1

[31] ica_1.0-3 stringi_1.8.3 RColorBrewer_1.1-3

[34] spatstat.data_3.0-4 reticulate_1.35.0 parallelly_1.37.1

[37] lmtest_0.9-40 scattermore_1.2 iterators_1.0.14

[40] Rcpp_1.0.12 tensor_1.5 future.apply_1.11.1

[43] zoo_1.8-12 sctransform_0.4.1 httpuv_1.6.14

[46] Matrix_1.6-5 splines_4.3.3 igraph_2.0.3

[49] tidyselect_1.2.1 abind_1.4-5 doParallel_1.0.17

[52] spatstat.random_3.2-3 codetools_0.2-19 miniUI_0.1.1.1

[55] spatstat.explore_3.2-7 listenv_0.9.1 lattice_0.22-6

[58] tibble_3.2.1 plyr_1.8.9 shiny_1.8.0

[61] ROCR_1.0-11 Rtsne_0.17 future_1.33.1

[64] fastDummies_1.7.3 survival_3.5-8 polyclip_1.10-6

[67] fitdistrplus_1.1-11 pillar_1.9.0 KernSmooth_2.23-22

[70] foreach_1.5.2 plotly_4.10.4 generics_0.1.3

[73] RcppHNSW_0.6.0 ggplot2_3.5.1 munsell_0.5.1

[76] scales_1.3.0 globals_0.16.3 xtable_1.8-4

[79] glue_1.7.0 lazyeval_0.2.2 tools_4.3.3

[82] data.table_1.15.4 RSpectra_0.16-1 RANN_2.6.1

[85] leiden_0.4.3.1 dotCall64_1.1-1 cowplot_1.1.3

[88] grid_4.3.3 tidyr_1.3.1 colorspace_2.1-0

[91] nlme_3.1-164 patchwork_1.2.0 cli_3.6.2

[94] spatstat.sparse_3.0-3 spam_2.10-0 fansi_1.0.6

[97] viridisLite_0.4.2 dplyr_1.1.4 uwot_0.1.16

[100] gtable_0.3.5 digest_0.6.35 progressr_0.14.0

[103] ggrepel_0.9.5 htmlwidgets_1.6.4 htmltools_0.5.8.1

[106] lifecycle_1.0.4 httr_1.4.7 mime_0.12

[109] MASS_7.3-60.0.1

That's margittr assignment pipe, you need that package.
But if you use SeuratObject version 5.2.0 then the subset will work

**Comment by Yijia-Jiang** [comment] 2024-11-26 20:19
@alikhuseynov Hello, when using this function, I got the following message. The warning is still there, but I assume it is updated by  subset_opt function? Do I still need to worry about the warning?


> subset_opt(object, cells = remain_spots )
Updating object slots..
Cloing object..
Matching cells in FOVs..
Cell subsets are found in all FOVs!
Subsetting object..
Warning: Not validating Centroids objects
Warning: Not validating Centroids objects
Warning: Not validating FOV objects
Warning: Not validating FOV objects
Warning: Not validating FOV objects
Warning: Not validating FOV objects
Warning: Not validating FOV objects
Warning: Not validating FOV objects
Warning: Not validating Seurat objects
Subsetting FOVs..
Updating object..
Validating object structure
Updating object slots
Ensuring keys are in the proper structure
Ensuring keys are in the proper structure
Ensuring feature names don't have underscores or pipes
Updating slots in Spatial
Updating slots in slice1
Setting assay used for NormalizeData.Spatial to Spatial
Validating object structure for Assay5 ‘Spatial’
Validating object structure for VisiumV2 ‘slice1’
Object representation is consistent with the most current Seurat version
Object is ready!
An object of class Seurat 
18085 features across 104956 samples within 1 assay 
Active assay: Spatial (18085 features, 0 variable features)
 2 layers present: counts, data
 1 spatial field of view present: slice1

**Comment by alikhuseynov** [comment] 2024-11-27 09:55
> @alikhuseynov Hello, when using this function, I got the following message. The warning is still there, but I assume it is updated by subset_opt function? Do I still need to worry about the warning?
> 
> > subset_opt(object, cells = remain_spots )
> > Updating object slots..
> > Cloing object..
> > Matching cells in FOVs..
> > Cell subsets are found in all FOVs!
> > Subsetting object..
> > Warning: Not validating Centroids objects
> > Warning: Not validating Centroids objects
> > Warning: Not validating FOV objects
> > Warning: Not validating FOV objects
> > Warning: Not validating FOV objects
> > Warning: Not validating FOV objects
> > Warning: Not validating FOV objects
> > Warning: Not validating FOV objects
> > Warning: Not validating Seurat objects
> > Subsetting FOVs..
> > Updating object..
> > Validating object structure
> > Updating object slots
> > Ensuring keys are in the proper structure
> > Ensuring keys are in the proper structure
> > Ensuring feature names don't have underscores or pipes
> > Updating slots in Spatial
> > Updating slots in slice1
> > Setting assay used for NormalizeData.Spatial to Spatial
> > Validating object structure for Assay5 ‘Spatial’
> > Validating object structure for VisiumV2 ‘slice1’
> > Object representation is consistent with the most current Seurat version
> > Object is ready!
> > An object of class Seurat
> > 18085 features across 104956 samples within 1 assay
> > Active assay: Spatial (18085 features, 0 variable features)
> > 2 layers present: counts, data
> > 1 spatial field of view present: slice1

Hi. The warnings are fine. But in `SeuratObject` version 5 the `subset` function was updated and should work for you, then no need to use `subset_opt` since that was a temporary solution I had to do that time.
