### ISSUE TITLE
IntegrateData return all genes

### ISSUE THREAD

**Issue by WalterMuskovic** [satijalab/seurat#2350] opened 2019-11-22 03:22 UTC
Similar to ["Questions for IntegrateData #2270"](https://github.com/satijalab/seurat/issues/2270) posted by @lh12565, I'd like to return all of the genes present in the dataset following the use of `IntegrateData()`. However when I run `IntegrateData()` with argument `features.to.integrate=all_genes` I come across the following error:

_Merging dataset 2 into 1
Extracting anchors for merged samples
Finding integration vectors
Error in GetAssayData(object = object, assay = assay, slot = "data")[features.integrate,  : 
  subscript out of bounds_

Which can be reproduced with the following code:

```
library(dplyr)
library(tidyverse)
pbmc_data <- Read10X(data.dir = "/data/pbmc3k_filtered_gene_bc_matrices/filtered_gene_bc_matrices/hg19/")

pbmc <- CreateSeuratObject(counts = pbmc_data)

set.seed(1234)
pbmc$split <- sample(c(1,2),ncol(pbmc),replace = TRUE)

pbmc.list <- SplitObject(pbmc, split.by = "split")

for (i in 1:length(pbmc.list)) {
    suppressWarnings(pbmc.list[[i]] <- SCTransform(pbmc.list[[i]], verbose = FALSE, return.only.var.genes=FALSE))
}

pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list, nfeatures = 3000)

pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = pbmc.features, verbose = FALSE)

pbmc.anchors <- FindIntegrationAnchors(object.list = pbmc.list, normalization.method = "SCT", anchor.features = pbmc.features, verbose = FALSE)

all_genes <- lapply(pbmc.list, row.names) %>% Reduce(intersect, .) 

smartseq.integrated <- IntegrateData(anchorset = pbmc.anchors, normalization.method = "SCT", verbose = TRUE, features.to.integrate = all_genes)
```
Any help would be greatly appreciated!

**Comment by timoast** [comment] 2019-11-22 16:43
What is `all_genes`? Can you show the output of `head(all_genes)` and `length(all_genes)`?

**Comment by toddknutson** [comment] 2019-11-22 22:36
I am having the same error. In my case, I am adding 3 extra genes to the previously found anchors:

```
genes_to_integrate <- unique(c(seurat_list_anchors@anchor.features, "Cd8a", "Cd8b1", "Trac"))
seurat_list_integrated <- IntegrateData(anchorset = seurat_list_anchors, features.to.integrate = genes_to_integrate, normalization.method = "SCT", verbose = TRUE)

```

However, downgraded my version of Seurat to 3.1.0. Then the above code works fine -- so the issue must occur somewhere after that v3.1.0. Thanks for a great package!

**Comment by toddknutson** [comment] 2019-11-23 13:13
I'm sorry that I don't have a reproducible example, but I tried running my code with a couple different Seurat versions. For me, the issue occurs due to changes in this commit: 5740868c693223aed67fda49e1eac53ed2a9520d.



Thanks again.

```
# Error!
install_git("git://github.com/satijalab/seurat.git", ref = "5740868c693223aed67fda49e1eac53ed2a9520d")
# Works!
install_git("git://github.com/satijalab/seurat.git", ref = "775dab45366f2c5c6872214d806e9f5c9db8d2e1")
```

**Comment by WalterMuskovic** [comment] 2019-11-24 07:01
Hi @timoast, `all_genes` is a character vector containing the gene names present in both Seurat objects contained in `pbmc.list` after running `SCTransform()`.

```
class(all_genes)
```
[1] "character"

```
head(all_genes)
```
[1] "LINC00115" "NOC2L"     "HES4"      "ISG15"     "C1orf159"  "TNFRSF18"

```
length(all_genes)
```
[1] 10742

**Comment by timoast** [comment] 2019-11-25 22:30
@WalterMuskovic is your issue also solved by rolling back to an earlier commit, eg 775dab45366f2c5c6872214d806e9f5c9db8d2e1 ?

**Comment by WalterMuskovic** [comment] 2019-11-26 02:32
Hi @timoast, can confirm 775dab4 doesn't produce the error:
```{r}
githubinstall::gh_install_packages("Seurat", ref = "775dab4")
library(Seurat)
library(tidyverse)
packageVersion("Seurat")
#[1] ‘3.0.3.9039’
pbmc_data <- Read10X(data.dir = "/data/pbmc3k_filtered_gene_bc_matrices/filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc_data)
# Add metadatacolumn so we can split the dataset in two
set.seed(1234)
pbmc$split <- sample(c(1,2),ncol(pbmc),replace = TRUE)
# Create a list of Seurat objects to integrate
pbmc.list <- SplitObject(pbmc, split.by = "split")
# run SCTransform on each object separately
for (i in 1:length(pbmc.list)) {
    suppressWarnings(pbmc.list[[i]] <- SCTransform(pbmc.list[[i]], verbose = FALSE, return.only.var.genes=FALSE))
}
# select features for downstream integration
pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list, nfeatures = 3000)
# run PrepSCTIntegration, which ensures that all necessary Pearson residuals have been calculated
pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = pbmc.features, verbose = FALSE)
# identify anchors - will give this error "Cannot find more nearest neighbours than there are points" because some samples have a small number of cells, so we set k.filter argument to NA
pbmc.anchors <- FindIntegrationAnchors(object.list = pbmc.list, normalization.method = "SCT", anchor.features = pbmc.features, verbose = FALSE)
# integrate the datasets (integrate ALL genes)
all_genes <- lapply(pbmc.list, row.names) %>% Reduce(intersect, .) # get gene names present in ALL SCTransform'd datasets
smartseq.integrated <- IntegrateData(anchorset = pbmc.anchors, normalization.method = "SCT", verbose = TRUE, features.to.integrate = all_genes)
```
Merging dataset 2 into 1
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
```{r}
smartseq.integrated@assays$integrated
```
Assay data with 10742 features for 2700 cells
Top 10 variable features:
 S100A9, LYZ, GNLY, S100A8, NKG7, FTL, GZMB, CCL5, FTH1, HLA-DRA

**Comment by timoast** [comment] 2019-12-13 15:58
We just released version 3.1.2 on CRAN, could you try again with the latest release and see if you still have the same issue?

**Comment by WalterMuskovic** [comment] 2019-12-17 01:15
Hi @timoast, just reran the [example code](https://github.com/satijalab/seurat/issues/2350#issue-526964218) with v3.1.2. Still produces the following error
```
Merging dataset 2 into 1
Extracting anchors for merged samples
Finding integration vectors
Error in GetAssayData(object = object, assay = assay, slot = "data")[features.integrate,  : 
  subscript out of bounds
```

**Comment by wzhang1984** [comment] 2019-12-20 00:35
Hi @timoast, I have a similar question here. I'm trying to run the code below:
`all_genes <- Reduce(intersect, lapply(obj_list, rownames))
obj_anchors <- FindIntegrationAnchors(object.list = obj_list, normalization.method = "SCT",  k.filter=NA,  anchor.features = BCL_features)
BCL_integrated <- IntegrateData(anchorset = obj_anchors, normalization.method = "SCT", features.to.integrate = all_genes)`

And I got the following error message. Can you please let me know how to solve this problem? Thanks!

Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE): invalid character indexing
Traceback:

1. IntegrateData(anchorset = obj_anchors, normalization.method = "SCT", 
 .     features.to.integrate = all_genes)
2. PairwiseIntegrateReference(anchorset = anchorset, new.assay.name = new.assay.name, 
 .     normalization.method = normalization.method, features = features, 
 .     features.to.integrate = features.to.integrate, dims = dims, 
 .     k.weight = k.weight, weight.reduction = weight.reduction, 
 .     sd.weight = sd.weight, sample.tree = sample.tree, preserve.order = preserve.order, 
 .     do.cpp = do.cpp, eps = eps, verbose = verbose)
3. RunIntegration(filtered.anchors = filtered.anchors, normalization.method = normalization.method, 
 .     reference = object.1, query = object.2, cellnames.list = cellnames.list, 
 .     new.assay.name = new.assay.name, features.to.integrate = features.to.integrate, 
 .     features = features, dims = dims, weight.reduction = weight.reduction, 
 .     do.cpp = do.cpp, k.weight = k.weight, sd.weight = sd.weight, 
 .     eps = eps, verbose = verbose)
4. FindIntegrationMatrix(object = merged.obj, integration.name = integration.name, 
 .     features.integrate = features.to.integrate, verbose = verbose)
5. t(x = GetAssayData(object = object, assay = assay, slot = "data")[features.integrate, 
 .     nn.cells1])
6. GetAssayData(object = object, assay = assay, slot = "data")[features.integrate, 
 .     nn.cells1]
7. GetAssayData(object = object, assay = assay, slot = "data")[features.integrate, 
 .     nn.cells1]
8. callGeneric(x, i = i, j = j, drop = TRUE)
9. eval(call, parent.frame())
10. eval(call, parent.frame())
11. x[i = i, j = j, drop = TRUE]
12. x[i = i, j = j, drop = TRUE]
13. subCsp_ij(x, i, j, drop = drop)
14. intI(i, n = d[1], dn[[1]], give.dn = FALSE)
15. stop("invalid character indexing")

**Comment by ctoen** [comment] 2020-01-03 09:59
Hi @timoast,

Did somebody already resolve this isssue?

I have exactly the same problem as @WalterMuskovic. I can only resolve it by setting 'nfeatures' in SelectIntegrationFeatures to the number of common genes in the datasets to integrate. But doesn't that  result in more noise when performing the integration?

Best,
Christa

**Comment by jorgcalis** [comment] 2020-02-03 10:23
Hi @timoast @WalterMuskovic and others,
I ran into the same problem with v3.1.2, but solved it by adding all features in the PrepSCTIntegration step and running that step and FindIntegrationAnchors again, for your example it would be like this:

all_genes <- lapply(pbmc.list, row.names) %>% Reduce(intersect, .) 

#to integrate all features from all_genes, add them to the PrepSCTIntegration step, rerun the PrepSCTIntegration and FindIntegrationAnchors steps
pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = all_genes)
pbmc.anchors <- FindIntegrationAnchors(object.list = pbmc.list, normalization.method = "SCT", anchor.features = pbmc.features)

# now IntegrateData takes the features.to.integrate 
smartseq.integrated <- IntegrateData(anchorset = pbmc.anchors, normalization.method = "SCT", verbose = TRUE, features.to.integrate = all_genes)

Best, Jorg

**Comment by JingleW** [comment] 2020-02-18 00:59
> Hi @timoast @WalterMuskovic and others,
> I ran into the same problem with v3.1.2, but solved it by adding all features in the PrepSCTIntegration step and running that step and FindIntegrationAnchors again, for your example it would be like this:
> 
> ```
> all_genes <- lapply(pbmc.list, row.names) %>% Reduce(intersect, .) 
> 
> #to integrate all features from all_genes, add them to the PrepSCTIntegration step, rerun the PrepSCTIntegration and FindIntegrationAnchors steps
> pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = all_genes)
> pbmc.anchors <- FindIntegrationAnchors(object.list = pbmc.list, normalization.method = "SCT", anchor.features = pbmc.features)
> 
> #now IntegrateData takes the features.to.integrate 
> smartseq.integrated <- IntegrateData(anchorset = pbmc.anchors, normalization.method = "SCT", verbose = TRUE, features.to.integrate = all_genes)
> ```
> 
> Best, Jorg

Hi, Jorg, 
I could do the integration with the pbmc data as what you said. However, I cannot do the integration with my own data. Could you please help to figure out what is the problem? Thank you very much. 
My scripts are as follows. 
#1
A <- CreateSeuratObject(counts = A.data, project = "A")
B <- CreateSeuratObject(counts = B.data, project = "B")
AB.list <- list(A, B)
for (i in 1:length(AB.list)) {
  AB.list[[i]] <- SCTransform(AB.list[[i]], verbose = FALSE, return.only.var.genes=FALSE)
}
AB.features <- SelectIntegrationFeatures(object.list = AB.list, nfeatures = 3000)
all_genes <- lapply(AB.list, row.names) %>% Reduce(intersect, .) 
AB.list <- PrepSCTIntegration(object.list = AB.list, anchor.features = all_genes)
AB.anchors <- FindIntegrationAnchors(object.list = AB.list, normalization.method = "SCT", anchor.features = AB.features)
AB.integrated <- IntegrateData(anchorset = AB.anchors, normalization.method = "SCT", verbose = TRUE, features.to.integrate = all_genes)
    The above script worked for the pbmc data, but not for my own data.  After running FindIntegrationAnchors, "Error: Object 1 assay - SCT has not been processed by PrepSCTIntegration. Please run PrepSCTIntegration prior to FindIntegrationAnchors if using assays generated by SCTransform." was shown. 

#2. Re-run the PrepSCTIntegration and FindIntegrationAnchors as follows. 
AB.list <- list(A, B)
for (i in 1:length(AB.list)) {
  AB.list[[i]] <- SCTransform(AB.list[[i]], verbose = FALSE, return.only.var.genes=FALSE)
}
AB.features <- SelectIntegrationFeatures(object.list = AB.list, nfeatures = 3000)                      
AB.list <- PrepSCTIntegration(object.list = AB.list, anchor.features = AB.features)
AB.anchors <- FindIntegrationAnchors(object.list = AB.list, normalization.method = "SCT", anchor.features = AB.features)
all_genes <- lapply(AB.list, row.names) %>% Reduce(intersect, .) 
AB.list <- PrepSCTIntegration(object.list = AB.list, anchor.features = all_genes)
AB.anchors <- FindIntegrationAnchors(object.list = AB.list, normalization.method = "SCT", anchor.features = AB.features)
AB.integrated <- IntegrateData(anchorset = AB.anchors, normalization.method = "SCT", verbose = TRUE, features.to.integrate = all_genes)
    The above script also did not work. After running the second FindIntegrationAnchors, "Error: Object 1 assay - SCT has not been processed by PrepSCTIntegration. Please run PrepSCTIntegration prior to FindIntegrationAnchors if using assays generated by SCTransform." was shown.

**Comment by satijalab** [comment] 2020-03-05 18:47
Apologies. We understand the issue now and are looking into it, and will respond to #2270

**Closed by satijalab** 2020-03-05 18:47 UTC

**Comment by nealgravindra** [comment] 2020-03-11 21:44
I am still having problems with this and I'm using Seurat v3.1.4. I tried JingleW's solution as well but still get `subscript out of bounds errors`. Here is my code:

```sdata.list <- SplitObject(sdata,split.by="Sample")
all_features <- lapply(sdata.list, row.names) %>% Reduce(intersect, .) 
for (i in 1:length(sdata.list)) {
    sdata.list[[i]] <- SCTransform(sdata.list[[i]], verbose = FALSE)
}
options(future.globals.maxSize = 12000 * 1024^2) # set bigger globals size
tic("Preparing scTransform...")
sdata.features <- SelectIntegrationFeatures(object.list = sdata.list, 
                                            nfeatures = length(rownames(sdata))) # this did not yield 27773 integrated feat
# sdata.features <- SelectIntegrationFeatures(object.list = sdata.list, 
#                                             nfeatures = 3000)
sdata.list <- PrepSCTIntegration(object.list = sdata.list, 
                                 anchor.features = all_features,verbose = FALSE)
toc()

tic("Finding anchors")
sdata.anchors <- FindIntegrationAnchors(object.list = sdata.list, 
                                        normalization.method = "SCT", 
                                        anchor.features = sdata.features, verbose = FALSE)
toc()
tic("Integrating dataset")
all_features <- lapply(sdata.list, row.names) %>% Reduce(intersect, .) 
sdata.integrated <- IntegrateData(anchorset = sdata.anchors, 
                                  normalization.method = "SCT", 
                                  features.to.integrate = all_features,
                                  verbose = FALSE)
toc()
```

And this is the error:

```
Error in scale.data[anchor.features, ]: subscript out of bounds
Traceback:

1. PrepSCTIntegration(object.list = sdata.list, anchor.features = all_features, 
 .     verbose = FALSE)

```
