### ISSUE TITLE
How to combine clusters?

### ISSUE THREAD

**Issue by adistman** [satijalab/seurat#3277] opened 2020-07-17 09:36 UTC
I have done a metadata analysis, and I identified about 24 clusters called "0-23", After I identified the cell kind of clusters, I found there were several clusters with same cell type. I just want to know HOW to combined the same cell type into 1 cluster?

**Comment by samuel-marsh** [comment] 2020-07-17 10:20
Hi,

See #3202 for more info.

Best,
Sam

**Comment by mojaveazure** [comment] 2020-07-17 16:23
Duplicate of #3202

**Closed by mojaveazure** 2020-07-17 16:23 UTC
Labels: duplicate
