### ISSUE TITLE
How to do VlnPlot in Seurat with assigned order

### ISSUE THREAD

**Issue by qingfengwu** [satijalab/seurat#475] opened 2018-05-11 08:42 UTC
I found that DoHeatmap has a "group.order" in Seurat. However, how to reassign the order of groups in VlnPlot. Thank you.

**Comment by mschilli87** [comment] 2018-05-11 08:46
duplicate of https://github.com/satijalab/seurat/issues/454?

**Comment by qingfengwu** [comment] 2018-05-11 10:30
Yeah, I have fixed the issue as per $454. Thank you.

**Closed** 2018-05-11 12:47 UTC
