### ISSUE TITLE
Reference Mapping Error

### ISSUE THREAD

**Issue by Victoriat0618** [satijalab/seurat#6384] opened 2022-09-06 16:00 UTC
I am bumping this issue again with a another submit

I'm trying to run map query on one of the metadata in my reference dataset. It's giving me this error and I couldn't figure out why.

Predicting cell labels
Error: Feature names of data matrix cannot be empty

Error only occurs in using this metadata as reference.celltype. Other metadata in the same reference dataset didn't show this error.
Any suggestions will be helpful. Thanks

**Comment by yuhanH** [comment] 2022-09-23 18:07
Hi @Victoriat0618 
Are there any NA or wired characters in your `reference.celltype`? It is hard to know why this error happens.
It will be best if you can provide a reproducible example.

**Comment by yuhanH** [comment] 2022-11-04 19:20
Hi @Victoriat0618 
Since i haven't obtained reply from you, i will close this issue now. 
If you have further questions, you can reopen it.

**Closed by yuhanH** 2022-11-04 19:20 UTC
Labels: more-information-needed
