### ISSUE TITLE
object 'min_var_custom' not found when running FindTransferAnchors based on a Seurat v5 object

### ISSUE THREAD

**Issue by LanqiGong** [satijalab/seurat#7375] opened 2023-05-25 02:40 UTC
I used scRNA-seq object generated by Seurat v5 as a reference to deconvolute Visium data. But I got the following error when I run the code: 

reference <- SCTransform(reference, ncells = 3000, verbose = FALSE)
anchors <- FindTransferAnchors(reference = reference, query = object, normalization.method = "SCT")

Normalizing query using reference SCT model
Performing PCA on the provided reference using 2974 features as input.
Projecting cell embeddings
Error in FetchResiduals_reference(object = query, reference.SCT.model = reference.SCT.model,  : 
  object 'min_var_custom' not found

I saw a similar issue at https://github.com/satijalab/seurat/issues/7131. It seems that the "FindTransferAnchors" function is not compatible with the Seurat v5 object. I tried to update the "FindTransferAnchors" function but do not know how. I was wondering if you could help me solve this problem? Thank you very much!

**Comment by saketkc** [comment] 2023-05-26 19:12
Hi @LanqiGong This was fixed in the latest seurat5 branch. Can you update and try again?

**Comment by LanqiGong** [comment] 2023-05-27 02:12
Hi,

Thank you very much for the information. I updated and tried it again but the error became 

"Warning: No layers found matching search pattern provided"
Error in `subset()`:
! No cells found

**Comment by LanqiGong** [comment] 2023-05-27 02:12
> Hi @LanqiGong This was fixed in the latest seurat5 branch. Can you update and try again?

Hi,

Thank you very much for the information. I updated and tried it again but the error became

"Warning: No layers found matching search pattern provided"
Error in subset():
! No cells found

**Comment by saketkc** [comment] 2023-07-07 20:39
Hi @LanqiGong,

I am unable to reproduce this. Can you update to the latest seurat5 branch and create a new-issue if you are still facing issues?

```r
remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE)
```

Also make sure to update your `reference` object if it is an older version:
```r
object <- UpdateSeuratObject(reference)
```

**Closed by saketkc** 2023-07-07 20:39 UTC
Labels: more-information-needed
