### ISSUE TITLE
no slot of name "threads" for this object of class "ColBindMatrices"

### ISSUE THREAD

**Issue by zheng-sc** [satijalab/seurat#8199] opened 2023-12-17 20:52 UTC
Dear Seurat team, thanks for developing the tool. I got the error whenever I want to access the on-disk RNA assay.
Seurat v5.0.1
```
Error in iter_function(iterators, x@threads) : 
  no slot of name "threads" for this object of class "ColBindMatrices"
```
could you please help me how to get rid of this? thanks a lot

**Comment by zheng-sc** [comment] 2023-12-17 21:07
I generated the seurat object using 'Seurat 4.9.9.9091' months ago.
after updating to current Seurat 5.0.1. the error appears.

**Comment by mhkowalski** [comment] 2023-12-18 22:32
Hello, 

Could you please try recreating your on-disk RNA assay with Seurat 5.0.1 and SeuratObject 5.0.1 installed?

**Comment by Gesmira** [comment] 2024-06-24 14:11
Hi @zheng-sc, 
Thank you for reaching out! Unfortunately, with the details provided, we cannot reproduce your issue. To help us better understand and resolve this issue, please ensure that you provide the following information when reporting a bug:

1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.  
    
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
    
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error.
    
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.

We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost and we will be more than happy to help you resolve the problem.

**Closed by Gesmira** 2024-06-24 14:11 UTC
