### ISSUE TITLE
Read_10X_h5 error

### ISSUE THREAD

**Issue by bennjmo** [satijalab/seurat#6998] opened 2023-03-01 13:10 UTC
I am getting an error when trying to load an h5 file (GSE190889_annoted_fullsize.h5) I downloaded from GEO https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE190889 

```

suppressPackageStartupMessages(library(scater))
suppressPackageStartupMessages(library(MuSiC))
suppressPackageStartupMessages(library(Biobase))
suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(SeuratDisk))
suppressPackageStartupMessages(library(hdf5r))

dat <- Read10X_h5("GSE190889_annoted_fullsize.h5")
Error in `[[.H5File`(infile, paste0(genome, "/data")) : 
  An object with name matrix/data does not exist in this group
```

I found this post discussing the same issue related to CellBender, but I'm not sure how to apply the solution to my problem and cited workflow for this data does not mention CellBender.

https://github.com/broadinstitute/CellBender/issues/66

Thank you!

--
Session info
```
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.7.3

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] hdf5r_1.3.7                 SeuratDisk_0.0.0.9020       forcats_0.5.2              
 [4] stringr_1.5.0               purrr_1.0.1                 readr_2.1.3                
 [7] tidyr_1.2.1                 tibble_3.1.8                tidyverse_1.3.2            
[10] dplyr_1.1.0                 SeuratObject_4.1.3          Seurat_4.3.0               
[13] MuSiC_1.0.0                 TOAST_1.12.0                quadprog_1.5-8             
[16] limma_3.54.1                EpiDISH_2.14.1              nnls_1.4                   
[19] scater_1.26.1               ggplot2_3.4.1               scuttle_1.8.3              
[22] SingleCellExperiment_1.20.0 SummarizedExperiment_1.28.0 Biobase_2.58.0             
[25] GenomicRanges_1.50.1        GenomeInfoDb_1.34.4         IRanges_2.32.0             
[28] S4Vectors_0.36.1            BiocGenerics_0.44.0         MatrixGenerics_1.10.0      
[31] matrixStats_0.63.0         

loaded via a namespace (and not attached):
  [1] utf8_1.2.3                spatstat.explore_3.0-5    reticulate_1.27          
  [4] tidyselect_1.2.0          htmlwidgets_1.6.1         grid_4.2.2               
  [7] BiocParallel_1.32.4       Rtsne_0.16                munsell_0.5.0            
 [10] ScaledMatrix_1.6.0        codetools_0.2-18          ica_1.0-3                
 [13] future_1.30.0             miniUI_0.1.1.1            withr_2.5.0              
 [16] spatstat.random_3.0-1     colorspace_2.1-0          progressr_0.13.0         
 [19] knitr_1.41                rstudioapi_0.14           ROCR_1.0-11              
 [22] tensor_1.5                listenv_0.9.0             GenomeInfoDbData_1.2.9   
 [25] polyclip_1.10-4           MCMCpack_1.6-3            bit64_4.0.5              
 [28] coda_0.19-4               parallelly_1.34.0         vctrs_0.5.2              
 [31] generics_0.1.3            xfun_0.36                 timechange_0.1.1         
 [34] R6_2.5.1                  doParallel_1.0.17         ggbeeswarm_0.7.1         
 [37] rsvd_1.0.5                bitops_1.0-7              spatstat.utils_3.0-1     
 [40] reshape_0.8.9             DelayedArray_0.24.0       assertthat_0.2.1         
 [43] promises_1.2.0.1          scales_1.2.1              googlesheets4_1.0.1      
 [46] beeswarm_0.4.0            gtable_0.3.1              beachmat_2.14.0          
 [49] globals_0.16.2            goftest_1.2-3             mcmc_0.9-7               
 [52] rlang_1.0.6               MatrixModels_0.5-1        splines_4.2.2            
 [55] lazyeval_0.2.2            gargle_1.2.1              spatstat.geom_3.0-3      
 [58] broom_1.0.2               modelr_0.1.10             yaml_2.3.6               
 [61] reshape2_1.4.4            abind_1.4-5               backports_1.4.1          
 [64] httpuv_1.6.8              tools_4.2.2               ellipsis_0.3.2           
 [67] RColorBrewer_1.1-3        proxy_0.4-27              ggridges_0.5.4           
 [70] Rcpp_1.0.9                plyr_1.8.8                sparseMatrixStats_1.10.0 
 [73] zlibbioc_1.44.0           RCurl_1.98-1.9            deldir_1.0-6             
 [76] pbapply_1.7-0             viridis_0.6.2             cowplot_1.1.1            
 [79] zoo_1.8-11                haven_2.5.1               ggrepel_0.9.2            
 [82] cluster_2.1.4             fs_1.5.2                  magrittr_2.0.3           
 [85] data.table_1.14.6         scattermore_0.8           SparseM_1.81             
 [88] reprex_2.0.2              lmtest_0.9-40             RANN_2.6.1               
 [91] googledrive_2.0.0         fitdistrplus_1.1-8        hms_1.1.2                
 [94] patchwork_1.1.2           mime_0.12                 evaluate_0.20            
 [97] xtable_1.8-4              readxl_1.4.1              gridExtra_2.3            
[100] compiler_4.2.2            crayon_1.5.2              KernSmooth_2.23-20       
[103] htmltools_0.5.4           tzdb_0.3.0                corpcor_1.6.10           
[106] later_1.3.0               lubridate_1.9.0           DBI_1.1.3                
[109] dbplyr_2.2.1              MASS_7.3-58.1             Matrix_1.5-1             
[112] cli_3.6.0                 parallel_4.2.2            igraph_1.3.5             
[115] pkgconfig_2.0.3           locfdr_1.1-8              sp_1.5-1                 
[118] plotly_4.10.1             spatstat.sparse_3.0-0     xml2_1.3.3               
[121] foreach_1.5.2             vipor_0.4.5               XVector_0.38.0           
[124] rvest_1.0.3               digest_0.6.31             sctransform_0.3.5        
[127] RcppAnnoy_0.0.20          spatstat.data_3.0-0       cellranger_1.1.0         
[130] rmarkdown_2.19            leiden_0.4.3              uwot_0.1.14              
[133] DelayedMatrixStats_1.20.0 shiny_1.7.4               quantreg_5.94            
[136] lifecycle_1.0.3           nlme_3.1-160              jsonlite_1.8.4           
[139] BiocNeighbors_1.16.0      viridisLite_0.4.1         fansi_1.0.4              
[142] pillar_1.8.1              lattice_0.20-45           GGally_2.1.2             
[145] fastmap_1.1.0             httr_1.4.4                survival_3.4-0           
[148] glue_1.6.2                png_0.1-8                 iterators_1.0.14         
[151] bit_4.0.5                 class_7.3-20              stringi_1.7.12           
[154] BiocSingular_1.14.0       irlba_2.3.5.1             e1071_1.7-12             
[157] future.apply_1.10.0    
```

**Comment by samuel-marsh** [comment] 2023-03-01 14:14
Hi,

Not member of dev team but hopefully can be helpful.  It doesn't appear that file is a 10X H5 file.  It seems from the name that maybe that is annotated file but it's just in H5 format.  I would try just reading it in with hdf5r as H5 file and examining the contents.  `Read_10X_h5` is specifically only for reading 10X formatted H5 files.

Best,
Sam

**Comment by bennjmo** [comment] 2023-03-01 15:13
Thank you for your response.

I tried the following

```
test <- H5File$new("GSE190889_annoted_fullsize.h5", mode = "a")
Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: ../../src/hdf5-1.12.1/src/H5F.c in H5Fopen(): line 620: unable to open file
        class: HDF5
        major: File accessibility
        minor: Unable to open file

    error #001: ../../src/hdf5-1.12.1/src/H5VLcallback.c in H5VL_file_open(): line 3502: failed to iterate over available VOL connector plugins
        class: HDF5
        major: Virtual Object Layer
        minor: Iteration failed

    error #002: ../../src/hdf5-1.12.1/src/H5PLpath.c in H5PL__path_table_iterate(): line 579: can't iterate over plugins in plugin path '(null)'
        class: HDF5
        major: Plugin for dynamically loaded library
        minor: Iteration failed

    error #003: ../../src/hdf5-1.12.1/src/H5PLpath.c in H5PL__path_table_iterate_process_path(): line 620: can't open directory: /usr/local/hdf5/lib/plugin
        class: HDF5
        major: Plugin for dynamically loaded library
        minor: Can't open directory or file

    error #004: ../../src/hdf5-1.1

h5ls("GSE190889_annoted_fullsize.h5")
       group          name       otype  dclass           dim
0          /        matrix   H5I_GROUP                      
1    /matrix      barcodes H5I_DATASET  STRING         46199
2    /matrix        counts H5I_DATASET   FLOAT 17111 x 46199
3    /matrix         genes H5I_DATASET  STRING         17111
4          /      metadata   H5I_GROUP                      
5  /metadata     cell_type H5I_DATASET  STRING         46199
6  /metadata health_status H5I_DATASET  STRING         46199
7  /metadata         index H5I_DATASET  STRING         46199
8  /metadata   internal_id H5I_DATASET  STRING         46199
9  /metadata      n_counts H5I_DATASET   FLOAT         46199
10 /metadata       n_genes H5I_DATASET INTEGER         46199
```
Any suggestions for how to load this into R?

Thanks again for your help!

**Comment by samuel-marsh** [comment] 2023-03-01 15:50
Hi,

From their vignette I used the following and it seemed to load in with no errors:

```
library(hdf5r)

# load file
file.h5 <- H5File$new("~/Downloads/GSE190889_annoted_fullsize.h5", mode="r+")

# examine contents
file.h5$ls(recursive=TRUE)
```

Best,
Sam

**Comment by bennjmo** [comment] 2023-03-01 16:11
I restarted R and this works, so I can load in the file as you described. However, I still can't figure out how to access the components of the h5 file or convert to a seurat object.

```
names(file.h5)
[1] "matrix"   "metadata"
```
I could not find/figure out from the hdf5r vignette how to read out from the file.

Any assistance you can provide or documentation you can point me to would be very helpful! Thank you again!

Ben

**Comment by samuel-marsh** [comment] 2023-03-01 16:37
Hi Ben,

So easiest way to read everything (that uses syntax similar to other formats) is actually using rhdf5 package.  I tested this out and it works but there is a bit of confusing issue that I'm not sure about and would suggest contacting the authors and see what their instructions are to read in the file correctly.

```
library(rhdf5)
library(Seurat)

geo <- H5Fopen("~/Downloads/GSE190889_annoted_fullsize.h5")

h5ls(geo)

mat <- as.sparse(geo$matrix$counts)

barcodes <- geo$matrix$barcodes
features <- geo$matrix$genes

rownames(mat) <- features
colnames(mat) <- barcodes


seu <- CreateSeuratObject(counts = mat)

seu[["cell_type"]] <- geo$metadata$cell_type
seu[["health_status"]] <- geo$metadata$health_status
seu[["index"]] <- geo$metadata$index
seu[["internal_id"]] <- geo$metadata$internal_id
seu[["n_counts"]] <- geo$metadata$n_counts
seu[["n_genes"]] <- geo$metadata$n_genes
```

So the issue is that their data for n_counts and n_genes don't match the values you get when Seurat generates the object.  However the barcodes in the meta data match the barcodes in seurat object order.  So not sure what's going with those values not matching.  But I'd suggest checking with the authors.

I'm going to close this issue for now as it's not directly Seurat related but good luck!

Best,
Sam

**Closed by samuel-marsh** 2023-03-01 16:37 UTC

**Comment by bennjmo** [comment] 2023-03-01 16:38
Thanks!
