### ISSUE TITLE
tSNE with original identities from merged data sets

### ISSUE THREAD

**Issue by dtatarak** [satijalab/seurat#824] opened 2018-10-03 21:44 UTC
I am working with 10x single cell data and have merged two datasets into one using the following code:

```R
zf_arch1_14hpf_WT_vs_lmo7aMO <- MergeSeurat(object1 = zf_arch1_14hpf, object2 = zf_arch1_14hpf_lmo7aMO, add.cell.id1 = '14hpf_WT', add.cell.id2 = '14hpf_lmo7aMO', project = 'WT_vs_lmo7aMO')
```

My understanding is that now the cells' names have been appended with their original IDs "14hpf_WT" and "14hpf_lmo7aMO" and in addition, the original project IDs have been stored in 

```R
object@meta.data$orig.ident
```

I then went about doing differential expression analysis on this new merged object, ran a tSNE, and then created a tSNE plot. That all worked fine. Now I want to label the tSNE plot so that each cell is colored according to its original ID. I cannot figure out how to do this. After much googling, I have yet to find a tutorial that shows this. I feel like this should be simple to do since those IDs exist in two different places within the object.

Please help!!

**Comment by leonfodoulian** [comment] 2018-10-03 22:15
Hi @dtatarak,

Please refer to issue #492 (which your issue is a duplicate of). 

Best,
Leon

**Closed** 2018-10-03 22:58 UTC
Labels: duplicate, question
