### ISSUE TITLE
when does a vlnplot show a contour?

### ISSUE THREAD

**Issue by MichaelPeibo** [satijalab/seurat#335] opened 2018-02-27 07:46 UTC
Hi,
I am confused by features of vlnplot(shows expression probability distributions across clusters), when does a vlnplot show a contour?
Take the picture below as an example, CCL5 is also expressed in CD4 T cells, but does not have a contour such as CD8 T cells;

 Why? is this defined in plot function?
![image](https://user-images.githubusercontent.com/32219336/36716339-05cf0f0a-1bd5-11e8-902b-c439f6611666.png)

Also, how to get the cell number information of cells in each cluster?
Thanks!

**Comment by leonfodoulian** [comment] 2018-02-27 10:58
Hi Michael,

This issue is a duplicate of [issue #297](https://github.com/satijalab/seurat/issues/297). I hope you can find your answer(s) there.

Regarding your second question, you can use the `table` function from base R on the `object@ident` slot of the Seurat object:

```R
table(object@ident)
```

Best,
Leon

**Comment by MichaelPeibo** [comment] 2018-02-27 13:14
Hi Leon,
Really thanks for your help, that is a simple code, haha, forgive me a beginner;

For first question, I roughly know that how vlnplot works；
1) whether to draw the rotated kernal is dependent on the proportion of cell expressing certain genes, but is there a threshold for how much majority?
2)  according to your answer, 'the width of the violin plots is independent of cell number, and is not affected by cell number differences across clusters', but in some plot, different does have different width(figure below), but you also mentioned 'Defining scale = "width" will set the same maximum width for all violin plots across all clusters. ' I am confused, is it possible scale = "width" is not the default setting, while scale = "area" is default?
Thanks!
![image](https://user-images.githubusercontent.com/32219336/36730612-fbdd2f6c-1c02-11e8-82ac-89e6297a5631.png)

**Comment by leonfodoulian** [comment] 2018-02-27 16:04
Hi Michael,

> whether to draw the rotated kernal is dependent on the proportion of cell expressing certain genes, but is there a threshold for how much majority?

I am not sure if I understand your question correctly, but if you're asking what is the required proportion of cells per group to draw a rotated kernel, I don't know the answer to that. You might find an answer in [this technical paper describing violin plots](http://www.stat.cmu.edu/~rnugent/PCMI2016/papers/ViolinPlots.pdf).

> according to your answer, 'the width of the violin plots is independent of cell number, and is not affected by cell number differences across clusters', but in some plot, different does have different width(figure below), but you also mentioned 'Defining scale = "width" will set the same maximum width for all violin plots across all clusters. ' I am confused, is it possible scale = "width" is not the default setting, while scale = "area" is default?

Regarding your second question, the default setting in Seurat is `scale = "width"`, and you can check that in the source code at [lines 642 to 647 in plotting_internal.R](https://github.com/satijalab/seurat/blob/master/R/plotting_internal.R#L642-L647). The maximum width of all violin plots is the same, although the width might change at different gene expression levels (defined by the y axis in this case) depending on the distribution of gene expression across the cells within a given cluster. In cases where you don't see a rotated kernel (e.g. cluster 0 in the _LMX1A_ plot), this is because the maximum width is achieved at expression level of 0. Also, note that the maximum width can be displayed at high or low expression levels depending again on the distribution of gene expression across the cells from a given cluster.

I hope I was clear in my answers!

Best,
Leon

**Closed** 2018-03-01 19:54 UTC

**Comment by MichaelPeibo** [comment] 2018-03-02 16:36
Hi leon
thanks for patient explanation!
It’s quite clear for me.
Thanks again for the powerful Seurat package!
