### ISSUE TITLE
Subset Scrambles Ident

### ISSUE THREAD

**Issue by Xeophyn** [satijalab/seurat#1373] opened 2019-04-15 16:33 UTC
When the subset function is told to return all of the clusters it will return the object but with the ident/cell relationship scrambled. 

I just thought this should be recorded. In case there are some functions that might automatically call subset and then request the entire object back.

**Comment by andrewwbutler** [comment] 2019-04-15 18:28
Hi, 

I am unable to reproduce this. For example:

```R
> library(Seurat)
> data("pbmc_small")
> p2 <- subset(x = pbmc_small, idents = levels(pbmc_small))
> all.equal(Idents(object = p2), Idents(object = pbmc_small))
[1] TRUE
> p2 <- subset(x = pbmc_small)
> all.equal(Idents(object = p2), Idents(object = pbmc_small))
[1] TRUE
```

Can you make sure you're running the latest version and if the problem persists, provide a reproducible example?

**Comment by satijalab** [comment] 2019-04-26 22:42
We haven't been able to reproduce this on our end so I'm closing this for now, but feel free to post an example if this persists for you

**Closed by satijalab** 2019-04-26 22:42 UTC
Labels: more-information-needed
