### ISSUE TITLE
seurat subset Error

### ISSUE THREAD

**Issue by dingyaozhang** [satijalab/seurat#7696] opened 2023-08-18 09:20 UTC
The error says:
None of the provided identity class levels were found 

The subset bug happens in seurat 4.3.1, SeuratObject 4.1.3 when:

```r
Idents(object = datain) = "aa"
datain = subset(x = datain, subset = celltype == "Keratinocytes")


#It is fixed when:
Idents(object = datain) = datain@meta.data$celltype
datain = subset(x = datain, subset = celltype == "Keratinocytes")
Idents(object = datain) = "aa"
```

**Comment by Gesmira** [comment] 2023-08-23 13:30
Hi, 
If I understand correctly, you are trying to set the idents to a character string and then subset based on a specific metadata column. We are unable to reproduce the issue in Seurat v5 or with the specific package versions you have loaded in.

**Comment by dingyaozhang** [comment] 2023-08-25 01:53
Sorry, Gesmira, thank you so much for your help!!! I tried to provide the whole environment, but I found the bug has gone unexpectedly, I suspected there is some background variable influenced it but I could not reproduce it, either...... Really sorry for it.

**Comment by Gesmira** [comment] 2023-08-25 12:59
No problem! Glad it is fixed now!

**Closed by Gesmira** 2023-08-25 12:59 UTC
Labels: bug
