### ISSUE TITLE
Integration with all features is incompatible with SCTransform workflow

### ISSUE THREAD

**Issue by davisidarta** [satijalab/seurat#2590] opened 2020-02-07 21:31 UTC
Hi there Seurat team! Hope you people are doing great.

I've recently noticed that is has become impossible to integrate data with all genes with CCA anchor-based merging when running a `SCTransform` workflow. This because `IntegrateData` will only merge datasets that contain in the `scale.data` slot all `features.to.integrate`.  Otherwise, it throws an error:

```
Error in GetAssayData(object = object, assay = assay, slot = "data")[features.integrate, :
subscript out of bounds
```

However, PrepSCTIntegration returns a list of Seurat objects with the selected integration features on the scale.data slot, without any argument to disable this mechanic.

When trying to integrate data processed by `SCTransform` with` FindIntegrationAnchors`, it throws this error:

`Error: Object 1 assay - SCT has not been processed by PrepSCTIntegration. Please run PrepSCTIntegration prior to FindIntegrationAnchors if using assays generated by SCTransform.
`

These issues ([#1808](https://github.com/satijalab/seurat/issues/1808),[ #2350 ](https://github.com/satijalab/seurat/issues/2350), #2473 , among others ) are all related to this incompatibility between CCA anchor-based merging and SCTransform. Maybe adding an argument to `PrepSCTIntegration` to add all features to the `scale.data` slot should solve it?

With this in mind, is it right to recommend, at least for now, that users should fall back to the NormalizeData, FindVariableFeatures and ScaleData workflow if they intend to be able to visualize any genes expressed in their data other then those chosen by FindIntegrationFeatures?

P.S.: Kind regards to @andrewwbutler and @timoast . Hope to bump into you guys in some conference this year.

**Comment by chlee-tabin** [comment] 2020-02-17 05:25
I am not from the development team, but thanks for pointing this out. It helped me quickly realize the issue I had as well.

I made a workaround of resetting the Assay object of SCT assay scale.data using `SetAssayData` before `IntegrateData`. After this, setting `features.to.integrate` did not generate an error and retained the features.

**Comment by JingleW** [comment] 2020-02-17 10:31
> I am not from the development team, but thanks for pointing this out. It helped me quickly realize the issue I had as well.
> 
> I made a workaround of resetting the Assay object of SCT assay scale.data using `SetAssayData` before `IntegrateData`. After this, setting `features.to.integrate` did not generate an error and retained the features.

Hi, chlee-tabin,
Could you please specify how to make it work? 
I followed the discussion in #2350 (https://github.com/satijalab/seurat/issues/2350) to do SCTransform and integration on the pbmc data with all features as the following script and it works. 
data(pbmc3k)
set.seed(1234)
pbmc3k$split <- sample(c(1,2),ncol(pbmc3k),replace = TRUE)
pbmc3k.list <- SplitObject(pbmc3k, split.by = "split")
for (i in 1:length(pbmc3k.list)) {
  suppressWarnings(pbmc3k.list[[i]] <- SCTransform(pbmc3k.list[[i]], verbose = FALSE, return.only.var.genes=FALSE))
}
pbmc3k.features <- SelectIntegrationFeatures(object.list = pbmc3k.list, nfeatures = 3000)
all_genes <- lapply(pbmc3k.list, row.names) %>% Reduce(intersect, .)
length(all_genes)
pbmc3k.list <- PrepSCTIntegration(object.list = pbmc3k.list, anchor.features = all_genes)
pbmc3k.anchors <- FindIntegrationAnchors(object.list = pbmc3k.list, normalization.method = "SCT", anchor.features = pbmc3k.features)
smartseq.integrated <- IntegrateData(anchorset = pbmc3k.anchors, normalization.method = "SCT", verbose = TRUE, features.to.integrate = all_genes)
smartseq.integrated@assays$integrated
head(smartseq.integrated@meta.data)

However, when I worked on my own data (A and B), it failed. My codes are as following:
A.data <- Read10X(data.dir = "/10x_sc-RNA/count/A/outs/filtered_feature_bc_matrix/")
A <- CreateSeuratObject(counts = A.data, project = "A")
B.data <- Read10X(data.dir = "/10x_sc-RNA/count/B/outs/filtered_feature_bc_matrix/")
B <- CreateSeuratObject(counts = B.data, project = "B")
AB.list <- c(A, B)
for (i in 1:length(Integration.list)) {
  Integration.list[[i]] <- SCTransform(Integration.list[[i]], verbose = FALSE, return.only.var.genes=FALSE)
}
AB.features <- SelectIntegrationFeatures(object.list = AB.list, nfeatures = 3000)
all_genes <- lapply(AB.list, row.names) %>% Reduce(intersect, .) 
length(all_genes)
AB.list <- PrepSCTIntegration(object.list = AB.list, anchor.features = all_genes)
AB.anchors <- FindIntegrationAnchors(object.list = AB.list, normalization.method = "SCT", anchor.features = AB.features, dims = 1:30)
AB.integrated <- IntegrateData(anchorset = AB.anchors, normalization.method = "SCT", verbose = TRUE, features.to.integrate = all_genes, dims = 1:30)
AB.integrated@assays$integrated

Could you please help to figure out where is the problem? 

Thank you very much.

**Comment by JingleW** [comment] 2020-02-18 00:33
> `SetAssayData`

Hi, chlee-tabin, 
Could you please specify how to do it? Thank you very much.

**Comment by chlee-tabin** [comment] 2020-02-18 03:19
```
options(future.globals.maxSize = 20000 * 1024^2)

features <- SelectIntegrationFeatures( object.list = seurat.objects[1:3], nfeatures = 3000 )

seurat.list <- PrepSCTIntegration( object.list = seurat.objects[1:3], anchor.features = features, verbose = T )

for (i in 1:3 ) {
  seurat.list[[i]][["SCT"]] <- SetAssayData( 
    object = seurat.list[[i]][["SCT"]], 
    slot = "scale.data", 
    new.data = GetAssayData( seurat.objects[[i]], assay = "SCT", slot = "scale.data" )
  )
}

# https://github.com/satijalab/seurat/issues/997#issuecomment-505207415
k.filter <- min(200, min(sapply(lung.filter$seurat[1:3], ncol)))

anchors <- FindIntegrationAnchors( 
  object.list = seurat.list, 
  normalization.method = "SCT",
  anchor.features = features,
  k.filter = k.filter,
  verbose = F
)

integrated <- IntegrateData( 
  anchorset = anchors, 
  normalization.method = "SCT",
  features.to.integrate = 
    Reduce( 
      intersect, 
      map( 
        seurat.list,
        ~rownames( GetAssayData( .x, slot = "scale.data", assay = "SCT" ) )
      ) 
    ),
  verbose = T
)
```

I believe the above will still utilize only the features extracted from `SelectIntegrationFeatures` rather than using all features that might be noisy (and defeat the purpose of using `SCTransform`), and then just overriding the `SCT` assay `scale.data` slot using `SetAssayData`.

This retains the `scale.data` from `SCTransform` (given you have run the `SCTransform` with `return.only.var.genes = FALSE`), and since the `FindIntegrationAnchors` still subsets the `anchor.features` from the `scale.data` slot for CCA, I believe (I haven't done extensive comparison) it would still generate anchors based on the specified top features, not the entire feature sets. The `FindIntegrationAnchor` will carry still the objects with the expanded `scale.data` in `SCT` slot which could be utilized by `IntegrateData`.

But I have to emphasize I am not from the development team, nor can I say I understand fully the inner workings of `IntegrateData` and `SCTransform`. For example, I am a bit unsure whether it would be still valid to utilize the Pearson residuals (calculated individually from the `SCTransform`s after integration and clustering using the `integrated` assay).

If I may add a question that might be picked up by the development team, the reason of the question above is because I still don't know how to make the integration work such the integration is done "hiearchically". That is, first integrate libraries from different batches and then those integrated datasets again with different technologies for example. If anyone could suggest best way forward would be greatly appreciated. At the moment, I re-integrate the data with just the standard integration procedure again, because running the SCT flow will reset the calculation made library-by-library basis.

I hope this helps and hope to obtain better clarification how to move forward.

**Comment by chlee-tabin** [comment] 2020-02-18 03:23
```
options(future.globals.maxSize = 20000 * 1024^2)

features <- SelectIntegrationFeatures( object.list = seurat.objects[1:3], nfeatures = 3000 )

seurat.list <- PrepSCTIntegration( object.list = seurat.objects[1:3], anchor.features = features, verbose = T )

# Added override step
for (i in 1:3 ) {
  seurat.list[[i]][["SCT"]] <- SetAssayData( 
    object = seurat.list[[i]][["SCT"]], 
    slot = "scale.data", 
    new.data = GetAssayData( seurat.objects[[i]], assay = "SCT", slot = "scale.data" )
  )
}

# https://github.com/satijalab/seurat/issues/997#issuecomment-505207415
k.filter <- min(200, min(sapply(lung.filter$seurat[1:3], ncol)))

anchors <- FindIntegrationAnchors( 
  object.list = seurat.list, 
  normalization.method = "SCT",
  anchor.features = features,
  k.filter = k.filter,
  verbose = F
)

integrated <- IntegrateData( 
  anchorset = anchors, 
  normalization.method = "SCT",
  features.to.integrate = 
    Reduce( 
      intersect, 
      map( 
        seurat.list,
        ~rownames( GetAssayData( .x, slot = "scale.data", assay = "SCT" ) )
      ) 
    ),
  verbose = T
)
```

I believe the above will still utilize only the features extracted from `SelectIntegrationFeatures` rather than using all features that might be noisy (and defeat the purpose of using `SCTransform`). The addition is just overriding the `SCT` assay `scale.data` slot using `SetAssayData` to match the original data.

This retains the `scale.data` from `SCTransform` (given you have run the `SCTransform` with `return.only.var.genes = FALSE`), and since the `FindIntegrationAnchors` still subsets the `anchor.features` from the `scale.data` slot for CCA, I believe (I haven't done extensive comparison) it would still generate anchors based on the specified top features, not the entire feature sets. The `FindIntegrationAnchor` will carry still the objects with the expanded `scale.data` in `SCT` slot which could be utilized by `IntegrateData`.

But I have to emphasize I am not from the development team, nor can I say I understand fully the inner workings of `IntegrateData` and `SCTransform`. For example, I am a bit unsure whether it would be still valid to utilize the Pearson residuals (calculated individually from the `SCTransform`s after integration and clustering using the `integrated` assay.

If I may add a question that might be picked up by the development team, the reason of the question above is because I still don't know how to make the integration work such the integration is done "hiearchically". That is, first integrate libraries from different batches and then those integrated datasets again with different technologies for example. If anyone could suggest best way forward would be greatly appreciated. At the moment, I re-integrate the data with just the standard integration procedure again, because running the SCT flow will reset the calculation made library-by-library basis.

I hope this helps and hope to obtain better clarification how to move forward.

**Comment by JingleW** [comment] 2020-02-18 03:30
@chlee-tabin Thank you very much. I will try it and wait for the response from Seurat team.

**Comment by satijalab** [comment] 2020-03-05 17:16
I apologize that I'm struggling to understand the question, before i answer I'm hoping you can clarify that you wish to do the following:

1. Identify anchors using a subset of variable features
2. 'Batch-correct' the expression of all features, based on the previously identified anchors

Thanks for confirming, and we'll look into this as well (@yuhanH)

**Comment by davisidarta** [comment] 2020-03-05 17:47
Hi @satijalab

That's exactly the case: 

- I (and others) want to identify anchors using only a subset of features, 
- but still batch correct all features,
- after using the SCTransform workflow for each dataset.

Thank you for looking into this!

**Comment by akshatkarambe** [comment] 2020-03-10 23:11
> Hi @satijalab
> 
> That's exactly the case:
> 
> * I (and others) want to identify anchors using only a subset of features,
> * but still batch correct all features,
> * after using the SCTransform workflow for each dataset.
> 
> Thank you for looking into this!

Hello Guys,

Do we have any update on this?
I am working on something for which I need all the features batch corrected.

Thank you so much

**Comment by yuhanH** [comment] 2020-03-10 23:35
Hi, Aksha
It is updated in the latest develop brach.  
You can set `features.to.integrate = target.features` with the features you want to correct.
```
all_features <- lapply(seurat.list, row.names) %>% Reduce(intersect, .) 
integrated <- IntegrateData( 
  anchorset = anchors, 
  normalization.method = "SCT",
  features.to.integrate = all_features,
  verbose = T
)
```

**Comment by akshatkarambe** [comment] 2020-03-11 17:50
> Hi, Aksha
> It is updated in the latest develop brach.
> You can set `features.to.integrate = target.features` with the features you want to correct.
> 
> ```
> all_features <- lapply(seurat.list, row.names) %>% Reduce(intersect, .) 
> integrated <- IntegrateData( 
>   anchorset = anchors, 
>   normalization.method = "SCT",
>   features.to.integrate = all_features,
>   verbose = T
> )
> ```

Ohh Great, Thanks for replying and what about the earlier steps?

pancreas.features <- SelectIntegrationFeatures(object.list = pancreas.list, nfeatures = 3000)

pancreas.list <- PrepSCTIntegration(object.list = pancreas.list, anchor.features = pancreas.features, 
    verbose = FALSE)

pancreas.anchors <- FindIntegrationAnchors(object.list = pancreas.list, normalization.method = "SCT", 
    anchor.features = pancreas.features, verbose = FALSE)

do we have to select the features which we get from the SelectIntegrationFeatures() like mentioned above? or we have to uses all genes?

Thanks for the help

**Comment by yuhanH** [comment] 2020-03-11 21:30
Hi, Aksha
The earlier steps are the same. `SelectIntegrationFeatures` will produce 3000 anchor genes which are used to build anchors between datasets. 

`features.to.integrate` in `IntegrateData` are the features you want to correct based on the previously identified anchors. If you set `features.to.integrate` with all genes, it will return correct value for all genes and the correction is based on anchor genes.

**Comment by akshatkarambe** [comment] 2020-03-12 17:16
> Hi, Aksha
> The earlier steps are the same. `SelectIntegrationFeatures` will produce 3000 anchor genes which are used to build anchors between datasets.
> 
> `features.to.integrate` in `IntegrateData` are the features you want to correct based on the previously identified anchors. If you set `features.to.integrate` with all genes, it will return correct value for all genes and the correction is based on anchor genes.

Thanks Yuhan,

I did what you mentioned but it threw an error.
Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing
Can you please ket me know what is happening here?

Thanks

**Comment by yuhanH** [comment] 2020-03-12 17:18
Hi, Aksha
Could you post the scripts you used? Thanks.

**Comment by akshatkarambe** [comment] 2020-03-12 17:21
> Hi, Aksha
> Could you post the scripts you used? Thanks.

seurat.list <- list(A, B, C)

for (i in 1:length(seurat.list)) {
    seurat.list[[i]] <- SCTransform(seurat.list[[i]], return.only.var.genes = FALSE, verbose = TRUE)
}

all_features <- lapply(seurat.list, row.names) %>% Reduce(intersect, .) 

features <- SelectIntegrationFeatures( object.list = seurat.list, nfeatures = 25912 , verbose = TRUE )
#here 25912 is the total number of genes in all_features variable. 

seurat.list <- PrepSCTIntegration( object.list = seurat.list, anchor.features = features, verbose = T )


combined.anchors <- FindIntegrationAnchors(object.list = seurat.list, normalization.method = "SCT", anchor.features = features, verbose = TRUE)


combined <- IntegrateData( 
  anchorset = combined.anchors, 
  normalization.method = "SCT",
  features.to.integrate = all_features,
  verbose = T
)

**Comment by yuhanH** [comment] 2020-03-12 18:01
You use all features as anchor features, but we suggest you only use the variable genes as the anchor genes to build anchors between datasets.
`features <- SelectIntegrationFeatures( object.list = seurat.list, nfeatures = 3000 , verbose = TRUE )`
You can set all your features in the `features.to.integrate` to return the batch-corrected value.

**Comment by akshatkarambe** [comment] 2020-03-13 16:28
> You use all features as anchor features, but we suggest you only use the variable genes as the anchor genes to build anchors between datasets.
> `features <- SelectIntegrationFeatures( object.list = seurat.list, nfeatures = 3000 , verbose = TRUE )`
> You can set all your features in the `features.to.integrate` to return the batch-corrected value.

Hello Yuhan,

I did what you mentioned and it is still giving me the same error.

Error:

Merging dataset 1 into 3
Extracting anchors for merged samples
Finding integration vectors
Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing

Code used:

for (i in 1:length(seurat.list)) {
    seurat.list[[i]] <- SCTransform(seurat.list[[i]], return.only.var.genes = FALSE, verbose = TRUE)
}

all_features <- lapply(seurat.list, row.names) %>% Reduce(intersect, .) 

features <- SelectIntegrationFeatures( object.list = seurat.list, nfeatures = 3000 , verbose = TRUE )

seurat.list <- PrepSCTIntegration( object.list = seurat.list, anchor.features = features, verbose = TRUE)


combined.anchors <- FindIntegrationAnchors(object.list = seurat.list, normalization.method = "SCT", anchor.features = features, verbose = TRUE)


combined <- IntegrateData( 
  anchorset = combined.anchors, 
  normalization.method = "SCT",
  features.to.integrate = all_features,
  verbose = T
)

Anything I am missing here?

Thanks for the help.

**Comment by Lesdormis** [comment] 2020-04-06 21:33
I think I got a similar issue here. 
But the errors is:
Error in GetAssayData(object = object, assay = assay, slot = "data")[features.integrate,  : 
  subscript out of bounds

**Comment by scheloni** [comment] 2020-04-25 17:42
Same for me.  This is the error I get:

```
Merging dataset 1 into 2
Extracting anchors for merged samples
Finding integration vectors
Error in GetAssayData(object = object, assay = assay, slot = "data")[features.integrate,  : 
  subscript out of bounds
```
And this is the code I have used:

`
seurat_AML1 <- Seurat::SubsetData(object= seurat, cells= s_cells_AML1, do.clean= F, subset.raw = T)
seurat_AML2 <- Seurat::SubsetData(object= seurat, cells= s_cells_AML2, do.clean= F, subset.raw = T)
list_AML <- c(seurat_AML1,seurat_AML2)
for (i in 1:length(list_AML)) {
    list_AML[[i]] <- SCTransform(list_AML[[i]], verbose = T)
}
AML_features <- SelectIntegrationFeatures(object.list = list_AML, nfeatures = 3000)
list_AML <- PrepSCTIntegration(object.list = list_AML, anchor.features = AML_features,
                               verbose = T)
AML_anchors <- FindIntegrationAnchors(object.list = list_AML, normalization.method = "SCT",
                                      anchor.features = AML_features, verbose = T)
all_genes <- lapply(list_AML, row.names) %>% Reduce(intersect, .)
AML_integrated <- IntegrateData(anchorset = AML_anchors, normalization.method = "SCT",
                                verbose = T, features.to.integrate = all_genes)`

**Comment by yuhanH** [comment] 2020-05-01 16:41
Hi, 
I am curious if you have updated to the latest version of the develop branch. 
I cannot reproduce the error when I return all features.  When you update to the latest version, if you still meet this error, could you please have a try on these pancreas datasets? 
Then, we can figure out where the errors are from. 

```
library(Seurat)
library(ggplot2)
library(patchwork)
library(SeuratData)
options(future.globals.maxSize = 4000 * 1024^2)
data("panc8")
pancreas.list <- SplitObject(panc8, split.by = "tech")
pancreas.list <- pancreas.list[c("celseq", "celseq2", "fluidigmc1", "smartseq2")]
for (i in 1:length(pancreas.list)) {
  pancreas.list[[i]] <- SCTransform(pancreas.list[[i]], verbose = FALSE)
}
pancreas.features <- SelectIntegrationFeatures(object.list = pancreas.list, nfeatures = 3000)
pancreas.list <- PrepSCTIntegration(object.list = pancreas.list, anchor.features = pancreas.features, 
                                    verbose = FALSE)

pancreas.anchors <- FindIntegrationAnchors(object.list = pancreas.list, normalization.method = "SCT", 
                                           anchor.features = pancreas.features, verbose = FALSE)
all_features <- lapply(pancreas.list, row.names) %>% Reduce(intersect, .)
pancreas.integrated <- IntegrateData(anchorset = pancreas.anchors, normalization.method = "SCT", features.to.integrate = all_features, verbose = FALSE)


nrow(pancreas.integrated[["integrated"]]@scale.data)
length(all_features)
```

**Closed by yuhanH** 2020-05-01 16:41 UTC

**Comment by Kikibarmpa** [comment] 2020-08-10 12:26
Hello,

I am sorry for commenting on this closed issue but I also have the same problem even after updating everything (Seurat oackage, R and R studio). Did someone manage to find the solution? 

Thanks a lot in advance!

**Comment by yuhanH** [comment] 2020-08-10 14:15
Hi, 
Could you run the pancreases code i provided above?

**Comment by Kikibarmpa** [comment] 2020-09-08 16:17
Hi,
I am sorry for my late response. There was an issue with R and R studio. Now it runs without errors! 

Thank you!

**Comment by MeganS92** [comment] 2020-10-31 13:24
Hi @yuhanH and @satijalab, I have been trying to run the pancreas codes using the SCTransform Vignette as provided. I have the latest Seurat version (3.9.9.9008), however I have been getting this error when running this code: 
```
for (i in 1:length(pancreas.list)) {
  pancreas.list[[i]] <- SCTransform(pancreas.list[[i]], verbose = FALSE)
}
```
Error: Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': missing value where TRUE/FALSE needed


When I reach the code: 
```
pancreas.features <- SelectIntegrationFeatures(object.list = pancreas.list,
+  nfeatures = 3000)
```
I get this error: 
No variable features found for object3 in the object.list.
No variable features found for object4 in the object.list.


So eventually if I kept going to the code: 
`pancreas.list <- PrepSCTIntegration(object.list = pancreas.list, 
                                    anchor.features = pancreas.features, 
                                    verbose = FALSE)`
I get this error: 
Error: The following assays have not been processed with SCTransform:
 object: 3 - assay: RNA
 object: 4 - assay: RNA



When I tried running SCTransform on both the object 3 ("fluidigmc1") and object 4 ("smartseq2"), I realised that it spits out the "Error: Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': missing value where TRUE/FALSE needed" as well. Meaning that for some reason SCTransform cannot be run on these 2 datasets. 

Could I please get some help here? Thanks a lot.

**Comment by yuhanH** [comment] 2020-10-31 14:28
HI, @MeganS92 
it seems that SCTransform failed on the third object. 

`pancreas.list[[ 3 ]] <- SCTransform(pancreas.list[[ 3 ]], verbose = FALSE)`
That's why all downstream analyses failed 
Can you post how you generated `pancreas.list`? and how many cells in `pancreas.list[[ 3 ]]`

**Comment by MeganS92** [comment] 2020-10-31 14:42
Hi @yuhanH ,

Thanks for the prompt response. Yes you are right - SCTransform failed on both the third and forth object, which are the `fluidigmc1` and `smartseq2` objects. 

This is the code I have ran: 
`library(Seurat)
library(SeuratData)
options(future.globals.maxSize = 4000 * 1024^2)
data("panc8")
pancreas.list <- SplitObject(panc8, split.by = "tech")
pancreas.list <- pancreas.list[c("celseq", "celseq2", "fluidigmc1", "smartseq2")]
pancreas.3 <- pancreas.list$fluidigmc1
dim(pancreas.3@meta.data)`

To answer your question, object 3 has 638 cells. 

Thanks again.

**Comment by andrewwbutler** [comment] 2020-11-01 19:46
Hi,

There is a known issue with the current release of sctransform (https://github.com/satijalab/seurat/issues/3663). Please try installing from the develop branch and rerunning.

```R
remotes::install_github("ChristophH/sctransform@develop")
```

**Comment by MeganS92** [comment] 2020-11-02 22:55
Hi Andrew,

Thanks so much for getting back to my query. Apologies for not seeing the other issue.

I will try this asap!
________________________________
