### ISSUE TITLE
Reproducible SCTransform crash

### ISSUE THREAD

**Issue by ms3389** [satijalab/seurat#5424] opened 2021-12-27 19:45 UTC
Reproducible SCTransform crash on a particular Seurat object:

library(Seurat)
sample.tmp.seurat = readRDS(file = 'SCTransform_crash.rds')
sample.tmp.seurat <- SCTransform(sample.tmp.seurat, verbose = TRUE)

Seurat object dropbox link: https://www.dropbox.com/s/g1a04widdj9jvp3/SCTransform_crash.rds?dl=0

Error:

>       sample.tmp.seurat <- SCTransform(sample.tmp.seurat, verbose = TRUE)
Calculating cell attributes from input UMI matrix: log_umi
Variance stabilizing transformation of count matrix of size 16720 by 5628
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 5000 cells
  |===================================================================================================================                                      |  75%

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': missing value where TRUE/FALSE needed
In addition: There were 50 or more warnings (use warnings() to see the first 50)

sessionInfo:

> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SeuratObject_4.0.4 Seurat_4.0.6      

loaded via a namespace (and not attached):
  [1] nlme_3.1-152          matrixStats_0.61.0    spatstat.sparse_2.1-0 RcppAnnoy_0.0.19      RColorBrewer_1.1-2    httr_1.4.2            sctransform_0.3.2    
  [8] tools_4.1.1           utf8_1.2.2            R6_2.5.1              irlba_2.3.5           rpart_4.1-15          KernSmooth_2.23-20    uwot_0.1.11          
 [15] mgcv_1.8-36           DBI_1.1.2             lazyeval_0.2.2        colorspace_2.0-2      tidyselect_1.1.1      gridExtra_2.3         compiler_4.1.1       
 [22] plotly_4.10.0         scales_1.1.1          lmtest_0.9-39         spatstat.data_2.1-2   ggridges_0.5.3        pbapply_1.5-0         goftest_1.2-3        
 [29] stringr_1.4.0         digest_0.6.28         spatstat.utils_2.3-0  pkgconfig_2.0.3       htmltools_0.5.2       parallelly_1.30.0     fastmap_1.1.0        
 [36] htmlwidgets_1.5.4     rlang_0.4.12          shiny_1.7.1           generics_0.1.1        zoo_1.8-9             jsonlite_1.7.2        ica_1.0-2            
 [43] dplyr_1.0.7           magrittr_2.0.1        patchwork_1.1.1       Matrix_1.3-4          Rcpp_1.0.7            munsell_0.5.0         fansi_0.5.0          
 [50] abind_1.4-5           reticulate_1.22       lifecycle_1.0.1       stringi_1.7.6         MASS_7.3-54           Rtsne_0.15            plyr_1.8.6           
 [57] grid_4.1.1            parallel_4.1.1        listenv_0.8.0         promises_1.2.0.1      ggrepel_0.9.1         crayon_1.4.2          miniUI_0.1.1.1       
 [64] deldir_1.0-6          lattice_0.20-44       cowplot_1.1.1         splines_4.1.1         tensor_1.5            knitr_1.37            pillar_1.6.4         
 [71] igraph_1.2.7          spatstat.geom_2.3-1   future.apply_1.8.1    reshape2_1.4.4        codetools_0.2-18      leiden_0.3.9          glue_1.4.2           
 [78] data.table_1.14.2     png_0.1-7             vctrs_0.3.8           httpuv_1.6.4          gtable_0.3.0          RANN_2.6.1            purrr_0.3.4          
 [85] spatstat.core_2.3-2   polyclip_1.10-0       tidyr_1.1.4           scattermore_0.7       future_1.23.0         assertthat_0.2.1      ggplot2_3.3.5        
 [92] xfun_0.27             mime_0.12             xtable_1.8-4          later_1.3.0           survival_3.2-11       viridisLite_0.4.0     tibble_3.1.5         
 [99] cluster_2.1.2         globals_0.14.0        fitdistrplus_1.1-6    ellipsis_0.3.2        ROCR_1.0-11

**Comment by saketkc** [comment] 2022-01-07 17:58
Duplicate of https://github.com/satijalab/sctransform/issues/120

**Closed by saketkc** 2022-01-07 17:58 UTC
Labels: bug
