### ISSUE TITLE
cropping issue with SpatialFeaturePlot

### ISSUE THREAD

**Issue by mvhunter1** [satijalab/seurat#2772] opened 2020-03-25 19:57 UTC
Hi, I'm currently having the same issue as reported in issue #2700 , although strangely I only see this issue with my own data - setting crop = FALSE when calling SpatialFeaturePlot works fine with the SeuratData brain dataset, but not with my own data (I still see an offset between the image and the spots). Happy to provide any more information if needed. I just installed the latest Seurat Spatial version, restarted RStudio, etc and it didn't fix the issue.
Thanks!

**Comment by andrewwbutler** [comment] 2020-03-27 17:56
Hi,

Hmm, that is strange. If you're able to share an example object where this is happening, I can look into it further (abutler@nygenome.org).

**Comment by minhtran1309** [comment] 2020-04-14 07:25
I also have the same problem, when I plot the SpatialFeaturePlot with crop=FALSE, everything works well the spatial scale factors are used properly. However, when I set crop=TRUE, the scale factors failed to cover the whole tissue
![Screenshot from 2020-04-14 17-23-40](https://user-images.githubusercontent.com/53423600/79197314-d8649d00-7e74-11ea-8dba-b39dd69501ff.png)
![Screenshot from 2020-04-14 17-22-56](https://user-images.githubusercontent.com/53423600/79197319-dac6f700-7e74-11ea-96f5-6ab7d9b581ef.png)

**Comment by andrewwbutler** [comment] 2020-04-17 16:32
Hi @minhtran1309 ,

Are you able to share an example dataset that reproduces this behavior?

**Comment by minhtran1309** [comment] 2020-04-20 23:13
Thanks, I can possibly share it with you the file is large it may take time. Also, it's not my priority now since I got it to work with Visium tool already, I will contact you with the data from the email you posted.

**Comment by JoyOtten** [comment] 2021-04-20 17:40
Hi, I'm running at the moment in the same bug/issue. Are there any updates on this bug?

**Comment by andrewwbutler** [comment] 2021-05-14 15:37
Hi all,

I believe this issue should now be resolved in the develop branch. Could you try installing that (instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1)) and see if that resolves the issue?

**Closed** 2021-05-28 16:20 UTC
Labels: bug, more-information-needed
