### ISSUE TITLE
Failure to identify predicted cell types on a UMAP representation of the scATAC-seq data

### ISSUE THREAD

**Issue by sylestiel** [satijalab/seurat#3269] opened 2020-07-15 21:54 UTC
Hi ,

I'm encountering a failure to transfer cluster labels at the following step in the scATAC-scRNA seq integration Vignette. There is a warning message that reads as shown below. As a result the scATAC UMAP is showing up in grey.
However, the co-embedding step downstream of it works fine. Any suggestions on how to correct for this error?
Thanks,

> SH3.atac.filtered <- subset(SH3.atac, subset = prediction.score.max > 0.35)
> SH3.atac.filtered$predicted.id <- factor(SH3.atac.filtered$predicted.id, levels = levels(SH3.rna))  # to make the colors match
> p1 <- DimPlot(SH3.atac.filtered, group.by = "predicted.id", label = TRUE, label.size = 8, pt.size = 1, repel = TRUE) + ggtitle("scATAC-seq cells") + 
+     NoLegend() + scale_colour_hue(drop = FALSE)
> p2 <- DimPlot(SH3.rna,pt.size = 1, label = FALSE, label.size = 5, repel = TRUE) + ggtitle("scRNA-seq cells") + 
+     NoLegend()
> p1 + p2
Warning message:
### Removed 1800 rows containing missing values (geom_text_repel).

**Comment by satijalab** [comment] 2020-07-17 16:37
Just to check - what are the values in SH3.atac.filtered$predicted.id before converting to a factor? 

To ask another way, does this work if you remove the second line of your code?

**Comment by sylestiel** [comment] 2020-07-19 02:11
Should I eliminate the second line of code and run the rest it gives me seurat cluster designations but not the names assigned to the Seurat clusters.
Suggestions?

**Comment by timoast** [comment] 2020-08-07 16:46
I don't understand what you mean exactly that it gives the cluster designations but not the names? The `predicted.id` metadata column will be whatever was transferred using `TransferData`. Can you elaborate and also provide the full code you're running?

**Comment by sylestiel** [comment] 2020-08-07 21:54
Hi Tim,

The code is as follows:

celltype.predictions <- TransferData(anchorset = transfer.anchors, refdata = SH9_E165.rna$seurat_clusters, 
    weight.reduction = SH9_E165.atac[["lsi"]])
SH9_E165.atac <- AddMetaData(SH9_E165.atac, metadata = celltype.predictions)


SH9_E165.atac.filtered <- subset(SH9_E165.atac, subset = prediction.score.max > 0.2)
#SH9_E165.atac.filtered$predicted.id <- factor(SH9_E165.atac.filtered$predicted.id, levels = levels(SH9_E165.rna))  # to make the colors match
p1 <- DimPlot(SH9_E165.atac.filtered, group.by = "predicted.id", label = FALSE, label.size = 8, pt.size = 0.5, repel = TRUE) + ggtitle("scATAC-seq cells") + scale_colour_hue(drop = FALSE)
p2 <- DimPlot(SH9_E165.rna, pt.size = 0.5, label = FALSE, label.size = 8, repel = TRUE) + ggtitle("scRNA-seq cells") 
p1 + p2


I want to be able to see the clusters with the 10X ATAC dataset instead of it being just one cluster within the coembed data.
If the seurat object (generated from scRNA seq has say 5 clusters then the coembed shows one additional cluster as 10XATAC without showing the so called corresponding clusters in the scATAC dataset. 

Thanks!

**Comment by timoast** [comment] 2020-08-07 23:22
> I want to be able to see the clusters with the 10X ATAC dataset instead of it being just one cluster within the coembed data.

I'm still not understanding what the issue is, it might help if you show the plots p1 and p2

**Comment by sylestiel** [comment] 2020-08-08 00:46
> SH9_E165.markers <- FindAllMarkers(coembed, only.pos = FALSE, min.pct = 0.1, logfc.threshold = 0.25, return.thresh = 0.01)
Calculating cluster 0
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=17s  
Calculating cluster 1
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=19s  
Calculating cluster 10x_ATAC
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 58s
Calculating cluster 2
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=27s  
Calculating cluster 3
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=25s  
Calculating cluster 4
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=16s  
Calculating cluster 5
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=18s  
Calculating cluster 6
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=36s  
Calculating cluster 7
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=28s 

When finding markers the ATAC data is represented as 1 cluster.  I  want to be able to see what features are present  in each Predicted  cluster within the ATAC dataset  after the transferring of anchors..
Also previously when  I has assigned new names to seurat clusters  the names  given were not showing up in the ATAC data but where  showing up  in the scRNA seq  UMAP.
<img width="684" alt="image" src="https://user-images.githubusercontent.com/64283689/89698411-a1fcd300-d8e6-11ea-8694-476c17aeec13.png">

**Closed** 2020-08-17 20:33 UTC
