### ISSUE TITLE
TPM and Normalization

### ISSUE THREAD

**Issue by sudhirthakurela** [satijalab/seurat#181] opened 2017-10-17 19:02 UTC
Hi,

Just had a follow up question Log Transformation and Normalization of TPM data. As TPM data is already normalized and results to colSum of 1M, do I still need to run Normalization step in Seurat or supplying log transformed values to CreareSeuratObject as raw data will be enough?

ST

**Comment by andrewwbutler** [comment] 2017-10-17 19:38
Duplicate of #171

**Closed by andrewwbutler** 2017-10-17 19:38 UTC

**Comment by sudhirthakurela** [comment] 2017-10-17 21:04
I am sorry but it is not same question as before. I would like to know if I need to perform normalization step in seurat even after importing TPM values. Issue #171 just stated that "TPM data can be imported to Seurat" but doesn't shed any light if processing of that data should be same or need changes as TPM values are already normalized.
