### ISSUE TITLE
How to load matrix like this to the Seurat object ??

### ISSUE THREAD

**Issue by janghyunss** [satijalab/seurat#6512] opened 2022-10-06 19:55 UTC
Hi all !

I want to make Seurat object and analyze this kind of dataset.
As I know, row names should be genes and column name should be barcode.
However, in this case, matrix is weird to me.
I want to convert this matrix.

How can I do it?

Thanks

![image](https://user-images.githubusercontent.com/115187663/194406434-b65a2c44-cd4d-4757-b55c-4565f77d4842.png)

**Comment by AngCamp** [comment] 2022-10-06 20:10
You need to change the matrix into a count matrix, go on stack exchange and post a reproducible example of a scaled down version of this problem.  

```
gene <- c('gene_a', 'gene_a', 'gene_b', 'gene_b')
 cellid <- c('cell_a', 'cell_b', 'cell_a', 'cell_b')
  count <- c(23,1,5,3)

df <- data.frame(gene,cellid,count)
```
`countmatrix <- ?`
And you want a 4x4 dataframe that has `rownames(countmatrix) == unique(df$gene ) `is TRUE and `colnames(countmatrix) == unique(df$cellid) ` is TRUE.

**Comment by AngCamp** [comment] 2022-10-06 20:25
I you post what I wrote above on stack some one there should help you.  Follow their guidelines and try to frame it as a more general R related question rather than rna-seq related.  You could call gene and cell_id something more abstract for instance, but in principle this is your problem taking a frequency table and converting it into a frequency matrix.

**Comment by samuel-marsh** [comment] 2022-10-07 13:02
Hi,

Not member of dev team but hopefully can be helpful.  This is exactly what the `pivot_wider` function is built for in tidyr package. 

Here is example using small matrix.
```
library(tidyr)
library(magrittr)
library(tibble)

barcode <- c("A", "B", "C", "A", "B", "C")
count <- c(1, 2, 0, 1, 2, 0)
gene <- c("GeneA", "GeneA", "GeneA", "GeneB", "GeneB", "GeneB")

mat <- data.frame(gene, barcode, count)

mat_seurat <- pivot_wider(data = mat, names_from = barcode, values_from = count) %>% 
  column_to_rownames("gene")
```

One caveat being that it will be slightly dependent on size of matrix and how much RAM you have available on system because this will be in dense format.

Best,
Sam

**Comment by torkencz** [comment] 2022-10-07 16:29
Thank you @AngCamp and @samuel-marsh. Both of those answers would work.

**Closed by torkencz** 2022-10-07 16:29 UTC
