### ISSUE TITLE
Leiden algorithm with igraph method

### ISSUE THREAD

**Issue by orrzor** [satijalab/seurat#2168] opened 2019-10-04 01:49 UTC
Hi Seurat team  and @TomKellyGenetics ,
I am having trouble running the Leiden algorithm with the igraph method #1645. I see this error when I run on both my own data, and the PBMC vignette https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html.

```
library(dplyr)
library(Seurat)

# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "/Users/orr/Downloads/seurat/filtered_gene_bc_matrices/hg19/")

# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)

pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
pbmc <- ScaleData(pbmc, features = rownames(pbmc))
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5, algorithm = 4, method = "igraph", random.seed = 100) # fail
pbmc <- FindClusters(pbmc, resolution = 0.5, algorithm = 4, method = "matrix", random.seed = 100) # success

pbmc <- RunUMAP(pbmc, dims = 1:20)
DimPlot(pbmc, reduction = "umap")
```

I get the following error
```
pbmc <- FindClusters(pbmc, resolution = 0.5, algorithm = 4, method = "igraph", random.seed = 100) # fail
Warning: The following arguments are not used: method
Error in switch(EXPR = is(object), Graph = input <- graph_from_adjacency_matrix(adjmatrix = object),  : 
  EXPR must be a length 1 vector
```

Also when I use the matrix method, I get the warning
```
pbmc <- FindClusters(pbmc, resolution = 0.5, algorithm = 4, method = "matrix", random.seed = 100) # success
Warning: The following arguments are not used: method
```

My session info is as follows, and I am using development version of Seurat 3.1.1 pulled today.
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Seurat_3.1.1 dplyr_0.8.3 

loaded via a namespace (and not attached):
 [1] tsne_0.1-3          nlme_3.1-141        bitops_1.0-6        RcppAnnoy_0.0.13    RColorBrewer_1.1-2 
 [6] httr_1.4.1          sctransform_0.2.0   tools_3.6.1         backports_1.1.5     R6_2.4.0           
[11] irlba_2.3.3         KernSmooth_2.23-15  uwot_0.1.4          lazyeval_0.2.2      colorspace_1.4-1   
[16] npsurv_0.4-0        tidyselect_0.2.5    gridExtra_2.3       compiler_3.6.1      plotly_4.9.0       
[21] labeling_0.3        caTools_1.17.1.2    scales_1.0.0        lmtest_0.9-37       ggridges_0.5.1     
[26] pbapply_1.4-2       stringr_1.4.0       digest_0.6.21       R.utils_2.9.0       pkgconfig_2.0.3    
[31] htmltools_0.3.6     bibtex_0.4.2        htmlwidgets_1.3     rlang_0.4.0         rstudioapi_0.10    
[36] zoo_1.8-6           jsonlite_1.6        ica_1.0-2           gtools_3.8.1        R.oo_1.22.0        
[41] magrittr_1.5        Matrix_1.2-17       Rcpp_1.0.2          munsell_0.5.0       ape_5.3            
[46] reticulate_1.13     lifecycle_0.1.0     R.methodsS3_1.7.1   stringi_1.4.3       yaml_2.2.0         
[51] gbRd_0.4-11         MASS_7.3-51.4       gplots_3.0.1.1      Rtsne_0.15          plyr_1.8.4         
[56] grid_3.6.1          parallel_3.6.1      gdata_2.18.0        listenv_0.7.0       ggrepel_0.8.1      
[61] crayon_1.3.4        lattice_0.20-38     cowplot_1.0.0       splines_3.6.1       SDMTools_1.1-221.1 
[66] zeallot_0.1.0       pillar_1.4.2        igraph_1.2.4.1      future.apply_1.3.0  reshape2_1.4.3     
[71] codetools_0.2-16    leiden_0.3.1        glue_1.3.1          lsei_1.2-0          metap_1.1          
[76] RcppParallel_4.4.4  data.table_1.12.4   vctrs_0.2.0         png_0.1-7           Rdpack_0.11-0      
[81] gtable_0.3.0        RANN_2.6.1          purrr_0.3.2         tidyr_1.0.0         future_1.14.0      
[86] assertthat_0.2.1    ggplot2_3.2.1       rsvd_1.0.2          RSpectra_0.15-0     survival_2.44-1.1  
[91] viridisLite_0.3.0   tibble_2.1.3        cluster_2.1.0       globals_0.12.4      fitdistrplus_1.0-14
[96] ROCR_1.0-7         
```

Thanks for your help! -Orr

**Comment by TomKellyGenetics** [comment] 2019-10-04 06:44
Thanks for bringing this to my attention. The issue is that "method" input is enabled for FindClusters.default by not the FindClusters.Seurat method for Seurat objects. I've tested this on the `pbmc_small` dataset and both implementations run. The patch has been submitted by PR to the `develop` branch.

**Comment by TomKellyGenetics** [comment] 2019-10-04 06:48
It's also been brought to my attention that Cole Trapnell lab has a "leidenbase" R package in development that avoids the Python dependency (by running Leiden in C). It may be worth looking into this for improved performance.

My colleague ran into issue compiling this with clang in Mac but it seems to work with gcc and on our Linux servers. 

https://github.com/cole-trapnell-lab/leidenbase

**Comment by orrzor** [comment] 2019-10-04 14:26
Hi Tom @TomKellyGenetics . Thanks for your answer. I clearly see the difference in the arguments between the two functions. Can you please tell me how to specify usage of `FindClusters.default`? I see the function in the code, but can't seem to call it.
```
> pbmc <- FindClusters.default(pbmc, resolution = 0.5, algorithm = 4, method = "igraph", random.seed = 100) # fail
Error in FindClusters.default(pbmc, resolution = 0.5, algorithm = 4, method = "igraph",  : 
  could not find function "FindClusters.default"
```

**Comment by TomKellyGenetics** [comment] 2019-10-08 08:00
`FindClusters.default` is called by `FindClusters.Seurat`. The error is due to adding an argument to one function but not the other when adding this functionality by PR #1858 to resolve #1645. You should not need worry about this once the patch is merged. They are both S3 methods that are called by:

    FindClusters(object, resolution = 0.5, algorithm = 4, method = "igraph", random.seed = 100)

The only difference is that `FindClusters.Seurat` will be run when `object` is a Seurat Class. Otherwise `FindClusters.default` expects a sparse matrix such as `pmbc[["RNA_snn"]]` and returns the partitions, not a Seurat object. As a workaround, you can run:

    partition <- FindClusters(pmbc[["RNA_snn"]], resolution = 0.5, algorithm = 4, method = "igraph", random.seed = 100)
    colnames(partition) <- paste0("RNA_snn_", colnames(partition)
    Idents(pmbc) <- colnames(partition)[ncol(partition)]
    levels <- levels(pbmc)
    Idents(pbmc) <- factor(Idents(pbmc), levels = sort(levels))
    pbmc[['seurat_clusters']] <- Idents(pbmc)

This workaround _should not_ be necessary once the updated version of `FindClusters.Seurat` is merged.

You can also try the updated version of the function by installing the development version from my PR:

    devtools::install_github("TomKellyGenetics/seurat", ref = "develop")

**Comment by mojaveazure** [comment] 2019-10-25 21:25
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Closed by mojaveazure** 2019-10-25 21:25 UTC

**Comment by orrzor** [comment] 2019-10-25 21:54
Hi Tom and Paul. Thank you so much! I appreciate your hard work on Seurat and fixing this issue- Orr
