### ISSUE TITLE
Cells lost when using ImageDimPlot 

### ISSUE THREAD

**Issue by pamelaxu213** [satijalab/seurat#9263] opened 2024-08-27 17:27 UTC
I have a few groups of cells `"CTX1"   "CTX2-3" "CTX2/3" "CTX4"   "CTX5"   "CTX6"` labelled in the meta-data, And I attempted plotting spacial image by grouping on them. However, only one group is shown in the plot. The cells belonging to other groups of CTX are missing from the plot even though they are present in the Seurat object.

```
> test.obj = readRDS("cleaned-08-13-2024/CTX_cluster_vascular.rds")
> table(test.obj$Custom.cell.groups)

  CTX1 CTX2-3 CTX2/3   CTX4   CTX5   CTX6 
  6930    176   4625   5044   7472   6805 

> test.obj

An object of class Seurat 
1506 features across 31052 samples within 3 assays 
Active assay: SCT (500 features, 500 variable features)
 3 layers present: counts, data, scale.data
 2 other assays present: Vizgen, integrated
 2 dimensional reductions calculated: pca, umap
 70 spatial fields of view present: X3742N.P21.WT X3743L.P21.Hemi ... etc.

> ImageDimPlot(test.obj,
             group.by = "Custom.cell.groups"
)
```
The technology used is MERFISH.

I am able to plot individual groups of cells from `Custom.cell.groups`. Whenever I included 2 categories, the function only plots the first occurring group.

Has anyone encountered this issue? Looking back on the ImageDimPlot function code, cells are dropped out at line `df <- fortify(model = object[[img]][[l]])` https://rdrr.io/github/satijalab/seurat/src/R/visualization.R 

Any help is appreciated!

```
> sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS/LAPACK: /envs/seurat/lib/libopenblasp-r0.3.27.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Seurat_5.0.3       SeuratObject_5.0.1 sp_2.1-3          

loaded via a namespace (and not attached):
  [1] deldir_2.0-4           pbapply_1.7-2          gridExtra_2.3          rlang_1.1.3            magrittr_2.0.3        
  [6] RcppAnnoy_0.0.22       matrixStats_1.3.0      ggridges_0.5.6         compiler_4.3.3         spatstat.geom_3.2-9   
 [11] png_0.1-8              vctrs_0.6.5            reshape2_1.4.4         stringr_1.5.1          pkgconfig_2.0.3       
 [16] fastmap_1.1.1          utf8_1.2.4             promises_1.3.0         purrr_1.0.2            jsonlite_1.8.8        
 [21] goftest_1.2-3          later_1.3.2            spatstat.utils_3.0-4   irlba_2.3.5.1          parallel_4.3.3        
 [26] cluster_2.1.6          R6_2.5.1               ica_1.0-3              stringi_1.8.3          RColorBrewer_1.1-3    
 [31] spatstat.data_3.0-4    reticulate_1.36.0      parallelly_1.37.1      lmtest_0.9-40          scattermore_1.2       
 [36] Rcpp_1.0.12            tensor_1.5             future.apply_1.11.2    zoo_1.8-12             sctransform_0.4.1     
 [41] httpuv_1.6.15          Matrix_1.6-5           splines_4.3.3          igraph_2.0.3           tidyselect_1.2.1      
 [46] rstudioapi_0.16.0      abind_1.4-5            spatstat.random_3.2-3  codetools_0.2-20       miniUI_0.1.1.1        
 [51] spatstat.explore_3.2-7 listenv_0.9.1          lattice_0.22-6         tibble_3.2.1           plyr_1.8.9            
 [56] shiny_1.8.1.1          ROCR_1.0-11            Rtsne_0.17             future_1.33.2          fastDummies_1.7.3     
 [61] survival_3.5-8         polyclip_1.10-6        fitdistrplus_1.1-11    pillar_1.9.0           KernSmooth_2.23-22    
 [66] plotly_4.10.4          generics_0.1.3         RcppHNSW_0.6.0         ggplot2_3.5.1          munsell_0.5.1         
 [71] scales_1.3.0           globals_0.16.3         xtable_1.8-4           glue_1.7.0             lazyeval_0.2.2        
 [76] tools_4.3.3            data.table_1.15.4      RSpectra_0.16-1        RANN_2.6.1             leiden_0.4.3.1        
 [81] dotCall64_1.1-1        cowplot_1.1.3          grid_4.3.3             tidyr_1.3.1            colorspace_2.1-0      
 [86] nlme_3.1-164           patchwork_1.2.0        cli_3.6.2              spatstat.sparse_3.0-3  spam_2.10-0           
 [91] fansi_1.0.6            viridisLite_0.4.2      dplyr_1.1.4            uwot_0.2.1             gtable_0.3.5          
 [96] digest_0.6.35          progressr_0.14.0       ggrepel_0.9.5          htmlwidgets_1.6.4      htmltools_0.5.8.1     
[101] lifecycle_1.0.4        httr_1.4.7             mime_0.12              MASS_7.3-60 
```

**Comment by adyzh** [comment] 2024-10-11 21:04
Hi @pamelaxu213 ,
Thank you for reaching out! We’re always grateful when folks take the time to help make Seurat better :slightly_smiling_face:
Unfortunately, with the details provided, we cannot reproduce your issue. To help us better understand and resolve this issue, please ensure that you provide the following information when reporting a bug:
1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.
We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost and we will be more than happy to help you resolve the problem.

**Closed by adyzh** 2024-10-11 21:04 UTC
Labels: bug
