### ISSUE TITLE
Unable to generate interactive plot using the seurat object as given in the documentation

### ISSUE THREAD

**Issue by diyabasu97** [satijalab/seurat#9039] opened 2024-06-21 08:06 UTC
Hi all,
I was trying to generate interactive plots using the seurat package as given in the below tutorial 
https://satijalab.org/seurat/articles/visualization_vignette#interactive-plotting-features

I am able to generate a static PCA plot using DimPlot() function. However, when I ran the HoverLocator function it gave me a white screen instead of an interactive plot. 

I have given the code snippet as well as the screenshot of the issue. 
<img width="931" alt="issue" src="https://github.com/satijalab/seurat/assets/116066133/166081b7-a235-49c9-9760-65a4b2c5121c">

Please can you have a look at this and let me know if I am doing something wrong. Any kind of help will be appreciated. Thanks in advance.

Regards,
Diya

```r
#Code to generate interactive PCA plot
data<-pbmc_small
plot <- DimPlot(data, reduction = "pca")
HoverLocator(plot = plot) 

```

**Comment by zskylarli** [comment] 2024-06-24 14:45
Hi - thank you for your message! I am unable to reproduce this error with pbmc_small or pbmc3k; can you restart your RStudio session, since there may just be an issue with the IDE, or try in another environment such as VSCode? I will close this for now as this behavior is not reproducible, but feel free to reopen the issue if you continue experiencing problems.

**Closed by zskylarli** 2024-06-24 14:45 UTC
Labels: bug

**Comment by diyabasu97** [comment] 2024-06-25 05:13
Hi @zskylarli ,
Thank you for your response. The issue seemed to be with the R version 4.4.0. After I updated it to 4.4.1 it works fine. Thanks again for your help.

Regards,
Diya.
