### ISSUE TITLE
Seurat V5 IntegrateLayers vcters::vec_slice() error with BPCells

### ISSUE THREAD

**Issue by alwhiteh** [satijalab/seurat#7192] opened 2023-04-20 00:02 UTC
Hello,

I am trying to integrate two single cell objects using the new V5 IntegrateLayers command. I have one dataset from mouse lungs and one from mouse muscle, and this information is stored in the $tissue metadata. I converted each assay to v5 using the as() command, wrote the assays to the disk using BPCells, merged the datasets, and then ran the commands from the Integrative Analysis vignette.

I also tried this with some other datasets and they returned the same error:

> Error in `vctrs::vec_slice()`:
> ! Can't subset elements that don't exist.
> ✖ Elements `Igkv4-59`, `Igkv8-18`, `Igkv8-26`, `Zbbx`, `Ralyl`, etc. don't exist.
> Backtrace:
>     ▆
>  1. └─Seurat::IntegrateLayers(...)
>  2.   └─Seurat (local) method(...)
>  3.     ├─SeuratObject::CreateSeuratObject(...)
>  4.     ├─object[[layers[i]]][features, ]
>  5.     └─object[[layers[i]]][features, ]
>  6.       └─BPCells:::selection_index(i, nrow(x), rownames(x))
>  7.         └─vctrs::vec_slice(indices, selection)
> 
> 

The code is below:

```r
mouse <- merge(mmuscle, mlung)
mouse <- NormalizeData(mouse)
mouse <- FindVariableFeatures(mouse)
mouse <- ScaleData(mouse)
mouse <- RunPCA(mouse) # took 1.5ish hours
mouse <- FindNeighbors(mouse, dims = 1:30, reduction = "pca")
mouse <- FindClusters(mouse, resolution = 0.3, cluster.name = "unintegrated_clusters")
mouse <- RunUMAP(mouse, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")
DimPlot(mouse, reduction = "umap.unintegrated", group.by = "tissue")
# Integrate
mouse <- IntegrateLayers(
  object = mouse, method = RPCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.rpca",
  verbose = FALSE, group.by = "tissue")
```

SessionInfo:

> R version 4.1.2 (2021-11-01)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS 13.3.1
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats4    stats     graphics  grDevices datasets  utils     methods   base     
> 
> other attached packages:
>  [1] BPCells_0.1.0               Azimuth_0.4.6.9002          shinyBS_0.61.1              EnsDb.Hsapiens.v86_2.99.0  
>  [5] ensembldb_2.18.4            AnnotationFilter_1.18.0     GenomicFeatures_1.46.5      AnnotationDbi_1.56.2       
>  [9] SeuratWrappers_0.3.1        lubridate_1.9.2             forcats_1.0.0               readr_2.1.4                
> [13] tidyr_1.3.0                 tibble_3.2.1                tidyverse_2.0.0             anndata_0.7.5.6            
> [17] purrr_1.0.1                 biomaRt_2.50.3              limma_3.50.3                SeuratDisk_0.0.0.9020      
> [21] scater_1.22.0               scuttle_1.4.0               SingleCellExperiment_1.16.0 SummarizedExperiment_1.24.0
> [25] Biobase_2.54.0              GenomicRanges_1.46.1        GenomeInfoDb_1.30.1         IRanges_2.28.0             
> [29] S4Vectors_0.32.4            BiocGenerics_0.40.0         MatrixGenerics_1.6.0        matrixStats_0.63.0         
> [33] reticulate_1.28             pheatmap_1.0.12             glmGamPoi_1.6.0             data.table_1.14.8          
> [37] R.utils_2.12.2              R.oo_1.25.0                 R.methodsS3_1.8.2           Seurat_4.9.9.9041          
> [41] SeuratObject_4.9.9.9081     sp_1.6-0                    stringr_1.5.0               dplyr_1.1.1                
> [45] ggplot2_3.4.2               renv_0.17.3                
> 
> loaded via a namespace (and not attached):
>   [1] rappdirs_0.3.3                    rtracklayer_1.54.0                scattermore_0.8                  
>   [4] JASPAR2020_0.99.10                bit64_4.0.5                       knitr_1.42                       
>   [7] irlba_2.3.5.1                     DelayedArray_0.20.0               TFBSTools_1.32.0                 
>  [10] KEGGREST_1.34.0                   RCurl_1.98-1.12                   generics_0.1.3                   
>  [13] ScaledMatrix_1.2.0                cowplot_1.1.1                     RSQLite_2.3.1                    
>  [16] RANN_2.6.1                        future_1.32.0                     bit_4.0.5                        
>  [19] tzdb_0.3.0                        spatstat.data_3.0-1               xml2_1.3.3                       
>  [22] httpuv_1.6.9                      assertthat_0.2.1                  DirichletMultinomial_1.36.0      
>  [25] gargle_1.3.0                      viridis_0.6.2                     xfun_0.38                        
>  [28] hms_1.1.3                         promises_1.2.0.1                  fansi_1.0.4                      
>  [31] restfulr_0.0.15                   progress_1.2.2                    caTools_1.18.2                   
>  [34] dbplyr_2.3.2                      igraph_1.4.1                      DBI_1.1.3                        
>  [37] htmlwidgets_1.6.2                 spatstat.geom_3.1-0               googledrive_2.1.0                
>  [40] ellipsis_0.3.2                    RSpectra_0.16-1                   annotate_1.72.0                  
>  [43] deldir_1.0-6                      sparseMatrixStats_1.6.0           vctrs_0.6.1                      
>  [46] remotes_2.4.2                     ROCR_1.0-11                       abind_1.4-5                      
>  [49] cachem_1.0.7                      withr_2.5.0                       batchelor_1.10.0                 
>  [52] BSgenome.Hsapiens.UCSC.hg38_1.4.4 BSgenome_1.62.0                   progressr_0.13.0                 
>  [55] presto_1.0.0                      sctransform_0.3.5                 GenomicAlignments_1.30.0         
>  [58] prettyunits_1.1.1                 goftest_1.2-3                     cluster_2.1.2                    
>  [61] seqLogo_1.60.0                    dotCall64_1.0-2                   lazyeval_0.2.2                   
>  [64] crayon_1.5.2                      hdf5r_1.3.8                       spatstat.explore_3.1-0           
>  [67] labeling_0.4.2                    pkgconfig_2.0.3                   nlme_3.1-153                     
>  [70] vipor_0.4.5                       ProtGenerics_1.26.0               rlang_1.1.0                      
>  [73] globals_0.16.2                    lifecycle_1.0.3                   miniUI_0.1.1.1                   
>  [76] filelock_1.0.2                    fastDummies_1.6.3                 BiocFileCache_2.2.1              
>  [79] SeuratData_0.2.2.9001             rsvd_1.0.5                        cellranger_1.1.0                 
>  [82] polyclip_1.10-4                   RcppHNSW_0.4.1                    lmtest_0.9-40                    
>  [85] Matrix_1.5-1                      Rhdf5lib_1.16.0                   zoo_1.8-11                       
>  [88] beeswarm_0.4.0                    googlesheets4_1.1.0               ggridges_0.5.4                   
>  [91] png_0.1-8                         viridisLite_0.4.1                 rjson_0.2.21                     
>  [94] shinydashboard_0.7.2              bitops_1.0-7                      rhdf5filters_1.6.0               
>  [97] KernSmooth_2.23-20                spam_2.9-1                        Biostrings_2.62.0                
> [100] blob_1.2.4                        DelayedMatrixStats_1.16.0         parallelly_1.35.0                
> [103] spatstat.random_3.1-4             CNEr_1.30.0                       beachmat_2.10.0                  
> [106] scales_1.2.1                      memoise_2.0.1                     magrittr_2.0.3                   
> [109] plyr_1.8.8                        ica_1.0-3                         zlibbioc_1.40.0                  
> [112] compiler_4.1.2                    BiocIO_1.4.0                      RColorBrewer_1.1-3               
> [115] fitdistrplus_1.1-8                Rsamtools_2.10.0                  cli_3.6.1                        
> [118] XVector_0.34.0                    listenv_0.9.0                     patchwork_1.1.2                  
> [121] pbapply_1.7-0                     MASS_7.3-54                       tidyselect_1.2.0                 
> [124] stringi_1.7.12                    yaml_2.3.7                        BiocSingular_1.10.0              
> [127] ggrepel_0.9.3                     grid_4.1.2                        fastmatch_1.1-3                  
> [130] tools_4.1.2                       timechange_0.2.0                  future.apply_1.10.0              
> [133] parallel_4.1.2                    rstudioapi_0.14                   TFMPvalue_0.0.9                  
> [136] gridExtra_2.3                     farver_2.1.1                      Rtsne_0.16                       
> [139] digest_0.6.31                     BiocManager_1.30.20               pracma_2.4.2                     
> [142] shiny_1.7.4                       Rcpp_1.0.10                       later_1.3.0                      
> [145] RcppAnnoy_0.0.20                  httr_1.4.5                        colorspace_2.1-0                 
> [148] fs_1.6.1                          XML_3.99-0.14                     tensor_1.5                       
> [151] splines_4.1.2                     RcppRoll_0.3.0                    uwot_0.1.14                      
> [154] spatstat.utils_3.0-2              plotly_4.10.1                     xtable_1.8-4                     
> [157] poweRlaw_0.70.6                   jsonlite_1.8.4                    R6_2.5.1                         
> [160] pillar_1.9.0                      htmltools_0.5.5                   mime_0.12                        
> [163] DT_0.27                           glue_1.6.2                        fastmap_1.1.1                    
> [166] BiocParallel_1.28.3               BiocNeighbors_1.12.0              codetools_0.2-18                 
> [169] Signac_1.9.0.9000                 utf8_1.2.3                        lattice_0.20-45                  
> [172] spatstat.sparse_3.0-1             ResidualMatrix_1.4.0              curl_5.0.0                       
> [175] ggbeeswarm_0.7.1                  leiden_0.4.3                      gtools_3.9.4                     
> [178] shinyjs_2.1.0                     GO.db_3.14.0                      survival_3.2-13                  
> [181] munsell_0.5.0                     rhdf5_2.38.1                      GenomeInfoDbData_1.2.7           
> [184] reshape2_1.4.4                    gtable_0.3.3

**Comment by yuhanH** [comment] 2023-04-21 19:17
hi,
For Seurat v5 `IntegrateLayer` function, you need to split the assay into multiple batch-specific layers. 
For example, after merging, you need to run this split step.
```
mouse <- merge(mmuscle, mlung)
mouse[['RNA']] <- split(mouse[["RNA"]], f = mouse$tissue)
```
You can also have a look at our [v5 integration vignette](https://satijalab.org/seurat/articles/seurat5_integration.html)

**Comment by alwhiteh** [comment] 2023-04-21 19:25
Hello, 

When I try that I get the following error:

```
Error in .local(x, f, drop, ...) : 
  Those layers are splitted already: data.1 counts.1 scale.data.1 counts.2 data.2
Please join those layers before splitting
```

I assumed that the merge function kept  the layers separate already? 

running "mouse" gives:

```
An object of class Seurat 
71905 features across 354199 samples within 2 assays 
Active assay: RNA (40636 features, 0 variable features)
 5 layers present: data.1, counts.1, scale.data.1, counts.2, data.2
 1 other assay present: SCT
```

**Comment by yuhanH** [comment] 2023-04-21 19:33
I see. The assay has splited already. Could you post the entire scripts you used?

**Comment by alwhiteh** [comment] 2023-04-21 19:42
Here's the first bit for the muscle data:

```
load("/Users/alexwhitehead/sc_RNA_raw_data/Muscle/Mouse/doi_10.5061_dryad.t4b8gtj34__v7/scMuscle_mm10_slim_v1-1.RData")
mmuscle <- scMuscle.slim.seurat
rm(scMuscle.slim.seurat)

# Note: this dataset contains injured (cardiotoxin and notexin) and uninjured muscle
# if we use D0, we should have uninjured tissue
# It might be interesting to see how cells change with inflammation
age_by_inj <- table(mmuscle@meta.data$age, mmuscle@meta.data$injury.days)
# about 170k uninjured cells

mmuscle

# Save the "normal" seurat objects
saveRDS(mmuscle,"/Users/alexwhitehead/Documents/Postdoc/Bl_Eng2_Priming/Vax_PRRs/mouse/mmuscle_total.RDS")
Idents(mmuscle) <- "injury.days"
mmuscle_ctrl <- subset(mmuscle, idents = "0") #169063 cells
Idents(mmuscle_ctrl) <- "seurat_clusters"
saveRDS(mmuscle_ctrl,"/Users/alexwhitehead/Documents/Postdoc/Bl_Eng2_Priming/Vax_PRRs/mouse/mmuscle_ctrl.RDS")

# Now convert to BPCells and re-save
mmuscle[["RNA"]] <- as(object = mmuscle[["RNA"]], Class = "Assay5")
mmuscle_ctrl[["RNA"]] <- as(object = mmuscle_ctrl[["RNA"]], Class = "Assay5")
write_matrix_dir(mat = mmuscle[["RNA"]]$counts, dir = "./mouse/bpcells_muscle/RNA")
write_matrix_dir(mat = mmuscle_ctrl[["RNA"]]$counts, dir = "./mouse/bpcells_muscle_ctrl/RNA")
counts.mat <- open_matrix_dir(dir = "/Users/alexwhitehead/Documents/Postdoc/Bl_Eng2_Priming/Vax_PRRs/mouse/bpcells_muscle/RNA")
mmuscle[["RNA"]]$counts <- counts.mat
counts.mat <- open_matrix_dir(dir = "/Users/alexwhitehead/Documents/Postdoc/Bl_Eng2_Priming/Vax_PRRs/mouse/bpcells_muscle_ctrl/RNA")
mmuscle_ctrl[["RNA"]]$counts <- counts.mat
saveRDS(
  object = mmuscle,
  file = "mmuscle_v5.Rds",
  destdir = "/Users/alexwhitehead/Documents/Postdoc/Bl_Eng2_Priming/Vax_PRRs/mouse/bpcells_muscle")
saveRDS(
  object = mmuscle_ctrl,
  file = "mmuscle_ctrl_v5.Rds",
  destdir = "Users/alexwhitehead/Documents/Postdoc/Bl_Eng2_Priming/Vax_PRRs/mouse/bpcells_muscle_ctrl/RNA")
```
 Then I converted the mlung object:
```

mlung <- readRDS("./mouse/mlung.combined.filtered.RDS")

mlung
# An object of class Seurat 
# 80764 features across 185136 samples within 3 assays 
# Active assay: SCT (31269 features, 0 variable features)
#  3 layers present: counts, data, scale.data
#  2 other assays present: RNA, integrated
#  2 dimensional reductions calculated: pca, umap
mlung[["integrated"]] <- NULL
mlung[["RNA"]] <- as(object = mlung[["RNA"]], Class = "Assay5")
mlung[["SCT"]] <- as(object = mlung[["SCT"]], Class = "Assay5")
write_matrix_dir(mat = mlung[["RNA"]]$counts, dir = "./mouse/bpcells/RNA")
write_matrix_dir(mat = mlung[["SCT"]]$counts, dir = "./mouse/bpcells/SCT")
counts.mat <- open_matrix_dir(dir = "./mouse/bpcells/RNA")
mlung[["RNA"]]$counts <- counts.mat
counts.mat <- open_matrix_dir(dir = "./mouse/bpcells/SCT")
mlung[["SCT"]]$counts <- counts.mat
saveRDS(
  object = mlung,
  file = "mlung_v5.Rds",
  destdir = "./mouse/bpcells"
)


mlung <- readRDS("/Users/alexwhitehead/Documents/Postdoc/Bl_Eng2_Priming/Vax_PRRs/mouse/bpcells/mlung_v5.RDS")


```

After saving with BPCells, I then loaded the mmuscle and mlung objects and did:

```
mlung <- readRDS("./mouse/bpcells/mlung_v5.RDS")
mmuscle <- readRDS("./mouse/bpcells_muscle_ctrl/mmuscle_ctrl_v5.RDS")

mlung <- UpdateSeuratObject(mlung) #unsure if this is necessary
mmuscle <- UpdateSeuratObject(mmuscle)

levels(as.factor(mmuscle$tissue))
mmuscle$muscle_origin <- mmuscle$tissue
mmuscle$tissue <- "muscle"
mlung$tissue <- "lung"

mouse <- merge(mmuscle, mlung)
#mouse[['RNA']] <- split(mouse[["RNA"]], f = mouse$tissue)
mouse <- NormalizeData(mouse)
mouse <- FindVariableFeatures(mouse)
mouse <- ScaleData(mouse)
mouse <- RunPCA(mouse) # took 1.5ish hours
mouse <- FindNeighbors(mouse, dims = 1:30, reduction = "pca")
mouse <- FindClusters(mouse, resolution = 0.3, cluster.name = "unintegrated_clusters")
mouse <- RunUMAP(mouse, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")
DimPlot(mouse, reduction = "umap.unintegrated", group.by = "tissue")
# Integrate
mouse <- IntegrateLayers(
  object = mouse, method = RPCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.rpca",
  verbose = FALSE, group.by = "tissue")
```

**Comment by yuhanH** [comment] 2023-04-21 19:49
hi 
It might be a BPCells directory issue.  When you save the object, you can try not set `destdir`, which means that it will not move the stored BPCells directory to different place. 
```
saveRDS(
  object = mlung,
  file = "mlung_v5.Rds"
)
```

**Comment by alwhiteh** [comment] 2023-04-21 22:46
Hello again,

I re-saved the objects using the command you posted, but I got the same vctrs::vec_slice() error as before when running the integration command

**Comment by yuhanH** [comment] 2023-05-05 20:55
hi @alwhiteh 
sorry about the delay. Could you make a reproducible example for us?

**Comment by alwhiteh** [comment] 2023-05-05 21:56
@yuhanH No problem, I subsetted the datasets to be really small and uploaded them to my google drive:
https://drive.google.com/drive/folders/13kaZnmMfosLC9BAuYcGNWhsueNnx0z2G?usp=sharing

The code is: 

`# Load packages
#| label: load-packages
#| echo: FALSE
library(renv)
library(ggplot2)
library(dplyr)
library(stringr)
library(Seurat)
library(SeuratObject)
library(R.utils)
library(data.table)
library(glmGamPoi) #makes SCTransform Faster
library(pheatmap)
library(reticulate)
library(scater)
library(SeuratDisk)
library(limma)
library(biomaRt)
library(dplyr)
library(purrr)
library(anndata)
library(tidyverse)
# for Seurat 5 
#library(Seurat)
library(SeuratWrappers)
library(EnsDb.Hsapiens.v86)
library(Azimuth)
library(BPCells)
options(future.globals.maxSize = 1e9)
options(Seurat.object.assay.version = "v5")

# Read in data
mlung <- readRDS("./tiny_mlung.RDS")
mmuscle <- readRDS("./tiny_mmuscle.RDS")
# Merge
mouse <- merge(mmuscle, mlung)
mouse <- NormalizeData(mouse)
mouse <- FindVariableFeatures(mouse)
mouse <- ScaleData(mouse)
mouse <- RunPCA(mouse) 
mouse <- FindNeighbors(mouse, dims = 1:30, reduction = "pca")
mouse <- FindClusters(mouse, resolution = 0.3, cluster.name = "unintegrated_clusters")
mouse <- RunUMAP(mouse, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")
DimPlot(mouse, reduction = "umap.unintegrated", group.by = "tissue")
# Integrate
mouse <- IntegrateLayers(
  object = mouse, method = RPCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.rpca",
  verbose = FALSE, group.by = "tissue")`

**Comment by yuhanH** [comment] 2023-05-08 21:35
hi @alwhiteh 
Thank you for providing the scripts and the object.  The issue is quite tricky since only one object contains scale.data, causing JoinLayers to malfunction. We will address this bug shortly. 
In the meantime, you can remove the scale.data.1 layer after merging, followed by JoinLayers and split.
For example, 
```
mouse <- merge(mmuscle, mlung)
DefaultAssay(mouse) <- 'RNA'
mouse[['RNA']]$scale.data.1 <- NULL
mouse[['RNA']] <- JoinLayers(mouse[['RNA']] )
mouse[['RNA']] <- split(x = mouse[['RNA']], f = mouse$tissue)

```

**Comment by alwhiteh** [comment] 2023-05-09 16:10
Hi @yuhanH,

When I try that with the downsampled data I provided, I get the following error:

```
Counts matrix provided is not sparse. Creating V5 assay in Seurat Object.
Warning: No layers found matching search pattern provided
Error: In function min_by_row: "vals" must be greater than zero
     ▆
  1. └─Seurat::IntegrateLayers(...)
  2.   └─Seurat (local) method(...)
  3.     ├─Seurat::ScaleData(object = object.list[[i]], verbose = FALSE)
  4.     └─Seurat:::ScaleData.Seurat(object = object.list[[i]], verbose = FALSE)
  5.       ├─Seurat::ScaleData(...)
  6.       └─Seurat:::ScaleData.StdAssay(...)
  7.         ├─Seurat::ScaleData(...)
  8.         └─Seurat:::ScaleData.IterableMatrix(...)
  9.           └─BPCells::min_by_row(...)
 10.             └─BPCells:::assert_greater_than_zero(vals)
```

**Comment by yuhanH** [comment] 2023-07-06 16:27
This ScaleData bug is fixed in the latest seurat5 branch.

**Closed by yuhanH** 2023-07-06 16:27 UTC
Labels: bug

**Comment by Pascalduc** [comment] 2023-11-09 17:21
Same issue with CellCycleScoring.
Seems like everything using GetAssayData is not compatible with V5.

**Comment by gskoufos** [comment] 2023-11-10 09:35
@Pascalduc 

I had the same issue!

You need to use the function JoinLayers on your merged object first, like that:

`object <- JoinLayers(object)`
 
After that, CellCycleScoring function (and any other function that utilizes GetAssayData) works perfectly fine!
