### ISSUE TITLE
SketchData() crashed when running with big data

### ISSUE THREAD

**Issue by Shiyc-Lab** [satijalab/seurat#7838] opened 2023-09-26 02:45 UTC
Because the problem that NormalizeData() can not be finished in Seurat v5, I performed it in v4 and save it as rds file and read it using v5. But when I tried to use SketchData to downsample, I encountered the error like this:
`
10. stop("No cell overlap between new meta data and Seurat object", 
  .     call. = FALSE)
`
Besides, I have set the verbose=False in SketchData(). However, the output of this function was too big and always lead to jupyter's collapse.
![image](https://github.com/satijalab/seurat/assets/141720203/c15322f2-cd2b-4ebd-a821-76b6bd1da182)

**Comment by zhanghao-njmu** [comment] 2023-10-18 07:55
This error is likely caused by Seurat v5. SCP will undergo compatibility modifications after the official release of Seurat v5.

**Comment by mhkowalski** [comment] 2024-06-24 14:48
Hi @Shiyc-Lab,

Thank you for reaching out! We’re always grateful when folks take the time to report issues they're experiencing. 

Unfortunately, with the details provided, we cannot reproduce your issue. To help us better understand and resolve this issue, please ensure that you provide the following information when reporting a bug:

1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.  
    
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
    
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the  
    
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.

We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost and we will be more than happy to help you resolve the problem.

**Closed by mhkowalski** 2024-06-24 14:48 UTC
