### ISSUE TITLE
Error when subsetting 

### ISSUE THREAD

**Issue by cadyyuheng** [satijalab/seurat#6336] opened 2022-08-23 04:03 UTC
Hello, 

I've been trying to subset an object with `subset(obj, cells=cell.ind)` and got the following error:
```
Error in if (!DefaultAssay(object = value) %in% Assays(object = x)) { : 
  argument is of length zero
```

The object contains the following info:
```
An object of class Seurat 
81640 features across 8700 samples within 4 assays 
Active assay: integrated (3000 features, 3000 variable features)
 3 other assays present: Spatial, SCT, RNA
 2 dimensional reductions calculated: pca, umap
 1 image present: slice1
```
After some digging, I believe the issue comes from the function subset.VisiumV1
specifically for the line
```
  slot(object = x, name = "coordinates") <- coordinates
```
I got the error 
```
Error in if (!DefaultAssay(object = value) %in% Assays(object = x)) { : 
  argument is of length zero
```
` slot(object = x, name = "coordinates")`  alone outputs the full coordinates of spatial data

`coordinates` alone outputs the subsetted coordinates 

However, the assignment 
  `slot(object = x, name = "coordinates") <- coordinates` doesn't work

**Comment by longmanz** [comment] 2022-12-02 20:34
Hi, 
Have you checked if cells listed in your "cell.ind" do present in your data? 
In addition, it seems that I cannot reproduce this issue. If you have any reproducible example/dataset, could you please share it with us so we can look into this further?

**Comment by mhkowalski** [comment] 2023-06-30 19:13
Hello- I'm closing this issue for now, please open a new issue if you are continuing to have trouble.

**Closed by mhkowalski** 2023-06-30 19:13 UTC
