### ISSUE TITLE
conda BPCells and Seurat S4 is not subsettable

### ISSUE THREAD

**Issue by Flu09** [satijalab/seurat#8604] opened 2024-03-11 17:45 UTC
The full error when I try to NormalizeData()
Error in methods::slot(object = object, name = "layers")[[layer]][features,  : 
  object of type 'S4' is not subsettable
Calls: as ... .class1 -> $ -> $.Assay5 -> LayerData -> LayerData.Assay5
Execution halted

I followed seurat vignette to convert from h5ad to BP then created a seurat object. Then came across this issue when I tried to normalize data. I would appreciate it if you can help me. I think the problem is conda specific because I tried without conda and it worked fine but I must submit through slurm and conda.

The code:
 library(Seurat)
Loading required package: SeuratObject
Loading required package: sp

Attaching package: ‘SeuratObject’

The following object is masked from ‘package:base’:

    intersect

 library(BPCells)
 object <- readRDS("/user/brainref/seurat_object.rds")
 object <- NormalizeData(object)
Normalizing layer: counts
Error in methods::slot(object = object, name = "layers")[[layer]][features,  : 
  object of type 'S4' is not subsettable

 sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Rocky Linux 9.1 (Blue Onyx)

Matrix products: default
BLAS/LAPACK: /user/conda-environments/Rtools/lib/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=C.UTF-8           LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BPCells_0.1.0      Seurat_5.0.2       SeuratObject_5.0.1 sp_2.1-3          

loaded via a namespace (and not attached):
  [1] deldir_2.0-4           pbapply_1.7-2          gridExtra_2.3         
  [4] rlang_1.1.3            magrittr_2.0.3         RcppAnnoy_0.0.22      
  [7] matrixStats_1.2.0      ggridges_0.5.6         compiler_4.3.2        
 [10] spatstat.geom_3.2-9    png_0.1-8              vctrs_0.6.5           
 [13] reshape2_1.4.4         stringr_1.5.1          pkgconfig_2.0.3       
 [16] fastmap_1.1.1          ellipsis_0.3.2         utf8_1.2.4            
 [19] promises_1.2.1         purrr_1.0.2            jsonlite_1.8.8        
 [22] goftest_1.2-3          later_1.3.2            spatstat.utils_3.0-4  
 [25] irlba_2.3.5.1          parallel_4.3.2         cluster_2.1.6         
 [28] R6_2.5.1               ica_1.0-3              stringi_1.8.3         
 [31] RColorBrewer_1.1-3     spatstat.data_3.0-4    reticulate_1.35.0     
 [34] parallelly_1.37.1      lmtest_0.9-40          scattermore_1.2       
 [37] Rcpp_1.0.12            tensor_1.5             future.apply_1.11.1   
 [40] zoo_1.8-12             sctransform_0.4.1      httpuv_1.6.14         
 [43] Matrix_1.6-3           splines_4.3.2          igraph_2.0.2          
 [46] tidyselect_1.2.0       abind_1.4-5            spatstat.random_3.2-3 
 [49] codetools_0.2-19       miniUI_0.1.1.1         spatstat.explore_3.2-6
 [52] listenv_0.9.1          lattice_0.22-5         tibble_3.2.1          
 [55] plyr_1.8.9             shiny_1.8.0            ROCR_1.0-11           
 [58] Rtsne_0.17             future_1.33.1          fastDummies_1.7.3     
 [61] survival_3.5-8         polyclip_1.10-6        fitdistrplus_1.1-11   
 [64] pillar_1.9.0           KernSmooth_2.23-22     plotly_4.10.4         
 [67] generics_0.1.3         RcppHNSW_0.6.0         ggplot2_3.5.0         
 [70] munsell_0.5.0          scales_1.3.0           globals_0.16.3        
 [73] xtable_1.8-4           glue_1.7.0             lazyeval_0.2.2        
 [76] tools_4.3.2            data.table_1.15.2      RSpectra_0.16-1       
 [79] RANN_2.6.1             leiden_0.4.3.1         dotCall64_1.1-1       
 [82] cowplot_1.1.3          grid_4.3.2             tidyr_1.3.1           
 [85] colorspace_2.1-0       nlme_3.1-164           patchwork_1.2.0       
 [88] cli_3.6.2              spatstat.sparse_3.0-3  spam_2.10-0           
 [91] fansi_1.0.6            viridisLite_0.4.2      dplyr_1.1.4           
 [94] uwot_0.1.16            gtable_0.3.4           digest_0.6.34         
 [97] progressr_0.14.0       ggrepel_0.9.5          htmlwidgets_1.6.4     
[100] htmltools_0.5.7        lifecycle_1.0.4        httr_1.4.7            
[103] mime_0.12              MASS_7.3-60

**Comment by igrabski** [comment] 2024-06-24 19:23
Thank you for reaching out! 

Unfortunately, with the details provided, we cannot reproduce your issue. To help us better understand and resolve this issue, please ensure that you provide the following information when reporting a bug:

1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.  
    
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
    
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the  
    
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.

We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost and we will be more than happy to help you resolve the problem.

**Closed by igrabski** 2024-06-24 19:23 UTC
Labels: bug
