### ISSUE TITLE
Eastimate RNA velocity using seurat

### ISSUE THREAD

**Issue by sikh09** [satijalab/seurat#2555] opened 2020-01-30 16:21 UTC
I am try ing to estimate RNA velocity using Seurat. I have dropest file: counts.matrices.rds
But I am getting error. My code is as follow

> file<- readRDS(file ="counts.matrices.rds") 
> bm <- as.Seurat(x = S1_rds)
> bm <- SCTransform(object = bm, assay = "spliced")
**Error in GetAssay.Seurat(object = object, assay = assay) : 
  spliced is not an assay present in the given object. Available assays are: exon, intron, spanning**

**below is the structure of rds file**

List of 3
 $ exon    :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. ..@ i       : int [1:3364826] 0 1 2 3 4 5 6 7 8 9 ...
  .. ..@ p       : int [1:4946] 0 85 169 247 331 418 494 574 659 739 ...
  .. ..@ Dim     : int [1:2] 17284 4945
  .. ..@ Dimnames:List of 2
  .. .. ..$ : chr [1:17284] "GFP_cassette" "ENSORLG00000016114" "ENSORLG00000012561" "ENSORLG00000017361" ...
  .. .. ..$ : chr [1:4945] "TTAACTCGTGAACCTT" "AGCTCCTAGTACGTAA" "CCTTTCTGTATAATGG" "CTAACTTGTTGAGTTC" ...
  .. ..@ x       : num [1:3364826] 1 1 1 1 2 1 1 1 1 1 ...
  .. ..@ factors : list()
 $ intron  :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. ..@ i       : int [1:1369810] 0 1 2 3 4 5 6 7 8 9 ...
  .. ..@ p       : int [1:4946] 0 82 180 191 211 228 313 407 423 434 ...
  .. ..@ Dim     : int [1:2] 15036 4945
  .. ..@ Dimnames:List of 2
  .. .. ..$ : chr [1:15036] "ENSORLG00000029794" "ENSORLG00000014696" "ENSORLG00000003723" "ENSORLG00000002306" ...
  .. .. ..$ : chr [1:4945] "TTAACTCGTGAACCTT" "AGCTCCTAGTACGTAA" "CCTTTCTGTATAATGG" "CTAACTTGTTGAGTTC" ...
  .. ..@ x       : num [1:1369810] 1 1 2 1 1 1 1 1 2 1 ...
  .. ..@ factors : list()
 $ spanning:Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. ..@ i       : int [1:685115] 0 1 2 3 4 5 6 7 8 9 ...
  .. ..@ p       : int [1:4946] 0 10 19 34 44 56 74 88 102 107 ...
  .. ..@ Dim     : int [1:2] 13766 4945
  .. ..@ Dimnames:List of 2
  .. .. ..$ : chr [1:13766] "ENSORLG00000010629" "ENSORLG00000011476" "ENSORLG00000002549" "ENSORLG00000023504" ...
  .. .. ..$ : chr [1:4945] "TTAACTCGTGAACCTT" "AGCTCCTAGTACGTAA" "CCTTTCTGTATAATGG" "CTAACTTGTTGAGTTC" ...
  .. ..@ x       : num [1:685115] 1 1 1 1 1 1 1 1 1 1 ...
  .. ..@ factors : list()

**Comment by praneet1988** [comment] 2020-01-30 17:02
Dear Khadeeja,
Did you run velocyto (http://velocyto.org/velocyto.py/tutorial/index.html#estimating-rna-velocity) on your single cell bam files to obtain .loom file?
Seurat wrapper for velocyto.r requires a .loom file to start with. This .loom file has information on spliced and unsliced counts matrix which will be required by RunVelocity function to calculate velocity embeddings.
Hope this helps.

Cheers !

Praneet

**Comment by chlee-tabin** [comment] 2020-01-30 18:31
I believe the count matrices are generated from `dropEst`. which `-V` option unfortunately generates names that are different from the `velocyto.py` default. So need to first change the name from exon -> spliced, intron -> unspliced, and ambiguous -> spanning.

I would just do the following (I don't know your structure so just guessed the code).

```
library(Seurat) 
library(velocyto.R)
library(SeuratWrappers)

file<- readRDS(file ="counts.matrices.rds")

bm[["spliced"]] <- CreateAssayObject( counts = file$exon )
bm[["unspliced"]] <- CreateAssayObject( counts = file$unspliced )
bm[["spanning"]] <- CreateAssayObject( counts = file$ambiguous )

bm <- RunVelocity( object = temp, deltaT = 1, kCells = 25, fit.quantile = 0.02 )
```

Hope this helps.

**Comment by praneet1988** [comment] 2020-01-30 19:08
I agree with Chlee-tabin. Sorry I missed the part that you used dropest function in velocyto.
Once exon, unspliced and ambiguous are name changed to spliced, unspliced and spanning then you should be able to run all the functions in seurat wrapper.


Cheers !!

Praneet

**Comment by KhadeejaSiddique** [comment] 2020-01-31 09:10
Following is the structure of my original file.
> str(file)
List of 3
 $ exon    :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. ..@ i       : int [1:3364826] 0 1 2 3 4 5 6 7 8 9 ...
  .. ..@ p       : int [1:4946] 0 85 169 247 331 418 494 574 659 739 ...
  .. ..@ Dim     : int [1:2] 17284 4945
  .. ..@ Dimnames:List of 2
  .. .. ..$ : chr [1:17284] "GFP_cassette" "ENSORLG00000016114" "ENSORLG00000012561" "ENSORLG00000017361" ...
  .. .. ..$ : chr [1:4945] "TTAACTCGTGAACCTT" "AGCTCCTAGTACGTAA" "CCTTTCTGTATAATGG" "CTAACTTGTTGAGTTC" ...
  .. ..@ x       : num [1:3364826] 1 1 1 1 2 1 1 1 1 1 ...
  .. ..@ factors : list()
 $ intron  :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. ..@ i       : int [1:1369810] 0 1 2 3 4 5 6 7 8 9 ...
  .. ..@ p       : int [1:4946] 0 82 180 191 211 228 313 407 423 434 ...
  .. ..@ Dim     : int [1:2] 15036 4945
  .. ..@ Dimnames:List of 2
  .. .. ..$ : chr [1:15036] "ENSORLG00000029794" "ENSORLG00000014696" "ENSORLG00000003723" "ENSORLG00000002306" ...
  .. .. ..$ : chr [1:4945] "TTAACTCGTGAACCTT" "AGCTCCTAGTACGTAA" "CCTTTCTGTATAATGG" "CTAACTTGTTGAGTTC" ...
  .. ..@ x       : num [1:1369810] 1 1 2 1 1 1 1 1 2 1 ...
  .. ..@ factors : list()
 $ spanning:Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. ..@ i       : int [1:685115] 0 1 2 3 4 5 6 7 8 9 ...
  .. ..@ p       : int [1:4946] 0 10 19 34 44 56 74 88 102 107 ...
  .. ..@ Dim     : int [1:2] 13766 4945
  .. ..@ Dimnames:List of 2
  .. .. ..$ : chr [1:13766] "ENSORLG00000010629" "ENSORLG00000011476" "ENSORLG00000002549" "ENSORLG00000023504" ...
  .. .. ..$ : chr [1:4945] "TTAACTCGTGAACCTT" "AGCTCCTAGTACGTAA" "CCTTTCTGTATAATGG" "CTAACTTGTTGAGTTC" ...
  .. ..@ x       : num [1:685115] 1 1 1 1 1 1 1 1 1 1 ...
  .. ..@ factors : list()


I tried this.
> file<-readRDS(file ="counts.matrices.rds")
> bm <- as.Seurat(x = file)
> bm[["spliced"]] <- CreateAssayObject( counts = file$exon )
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
> bm[["unspliced"]] <- CreateAssayObject( counts = file$intron)
> bm[["ambiguous"]] <- CreateAssayObject( counts = file$spanning)
> bm <- SCTransform(object = bm, assay = "spliced")
Calculating cell attributes for input UMI matrix
Variance stabilizing transformation of count matrix of size 13528 by 4945
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 4945 cells
  |=====================================================================================================================================| 100%
Found 12 outliers - those will be ignored in fitting/regularization step

Second step: Get residuals using fitted parameters for 13528 genes
  |=====================================================================================================================================| 100%
Computing corrected count matrix for 13528 genes
  |=====================================================================================================================================| 100%
Calculating gene attributes
Wall clock passed: Time difference of 2.918335 mins
Determine variable features
Set 3000 variable features
Place corrected count matrix in counts slot
Centering data matrix
  |=====================================================================================================================================| 100%
Set default assay to SCT
There were 50 or more warnings (use warnings() to see the first 50)

But. after applying the above commands. I have now both exon, intron, spanning and spliced, unspliced, ambiguous. Is that possible to delete intron, exon and spanning from my file?

**Comment by KhadeejaSiddique** [comment] 2020-01-31 21:16
Thank you chlee-tabin and praneet1988 for the response. It helped a lot and now I have successfully run velocyto on my data. 
But,  I have another issue now. I have 4945 cells in my dropest file. I did some filtration because many doublets were present in my data. 
Is that possible to filter those cells from dropest using Seurat?

**Comment by timoast** [comment] 2020-02-14 20:16
Closing now (last question addressed in https://github.com/satijalab/seurat/issues/2597)

**Closed by timoast** 2020-02-14 20:16 UTC
