### ISSUE TITLE
Follow up of previous issue #7033

### ISSUE THREAD

**Issue by LBH2021** [satijalab/seurat#7040] opened 2023-03-11 00:22 UTC
In reference to issue #7033:

The issue was closed without a solution. The initial solution provided by @alikhuseynov was very helpful, but I still need to make some adjustments to generate the final plot.

Here is the problem I'm still having:
https://github.com/satijalab/seurat/issues/7033#issuecomment-1464190193

Thank you also to @yuhanH who also tried to help.

**Comment by alikhuseynov** [comment] 2023-03-11 14:12
hey @LBH2021 
I'm not from Seurat team.. sometimes it's a bit tricky to make customized plot.
Here is another try as from previous issue. I think the problem is the sorting of clusters. 
Try out:

```
top_clonotypes <- names(table(pbmc_small$RNA_snn_res.1) %>% sort(decreasing = TRUE))[1:2] # first 2 clusters
colors <- rainbow(length(top_clonotypes) + 1)
highlight_rows_clonotype <- 
  lapply(top_clonotypes, function(c) {
    Cells(pbmc_small)[which(pbmc_small$RNA_snn_res.1 == c)]
  })
highlight_rows_clonotype %>% str
# run UMAP
if (!any(Reductions(pbmc_small) == "umap")) { 
  pbmc_small %<>% RunUMAP(reduction = "pca", dims = c(1:10))
  }

pl1 <- 
  DimPlot(pbmc_small,
          reduction = "umap",
          pt.size = 0.5,
          group.by = "RNA_snn_res.1",
          cells.highlight = highlight_rows_clonotype,
          order = highlight_rows_clonotype,
          cols.highlight = colors,
          sizes.highlight = rep(2, highlight_rows_clonotype %>% length()), # make highlighted cells larger
  )
pl1 # this should work as default to show "Unselected" or NA cells

## change colors and cluster names ----

# convert factor to character sting
if (is.factor(pl1$data$highlight)) { 
  pl1$data$highlight %<>% as.character.factor()
  }

# change "Unselected" to NA
pl1$data$highlight[which(pl1$data$highlight == "Unselected")] <- "NA"

# sort cluster groups, ie 1st cluster is the most abundant.
new.level <- names(table(pl1$data$highlight) %>% sort(decreasing = TRUE))
pl1$data$highlight %<>% factor(levels = new.level)

# plot again with custom colors and labels.
pl1 & scale_color_manual(values = colors, label = top_clonotypes)
```

**Comment by Gesmira** [comment] 2023-07-14 19:20
Thank you @alikhuseynov for providing a solution! Closing for now, but please feel free to reopen @LBH2021 if you continue to run into issues.

**Closed by Gesmira** 2023-07-14 19:20 UTC
