### ISSUE TITLE
CCA problem: crashes with IntegrateData

### ISSUE THREAD

**Issue by SFF-singecell-user** [satijalab/seurat#1355] opened 2019-04-10 12:57 UTC
Hello,
I am trying to perform a CCA following the Seurat v3.0 tutorial. I am comparing two datasets, each of which contains data from about 5,000 cells. Every time I get to the IntegrateData stage, my R studio crashes. I am working on a server with access to 300GB of memory.
This is the code, up to the point when the computer crashes

# Set up ctrl object
ctrl <- C30
ctrl$stim <- "UNINFECTED"
ctrl <- subset(x = ctrl, subset = nFeature_RNA > 500)
ctrl <- NormalizeData(object = ctrl, verbose = FALSE)
ctrl <- FindVariableFeatures(object = ctrl, selection.method = "vst", nfeatures = 2000)

# Set up Disease object
stim <- C33
stim$stim <- "DISEASE"
stim <- subset(x = stim, subset = nFeature_RNA > 500)
stim <- NormalizeData(object = stim, verbose = FALSE)
stim <- FindVariableFeatures(object = stim, selection.method = "vst", nfeatures = 2000)

#perform integration
immune.anchors <- FindIntegrationAnchors(object.list = list(ctrl, stim), dims = 1:20)
immune.combined <- IntegrateData(anchorset = immune.anchors, dims = 1:20)

**Comment by lzj1769** [comment] 2019-04-10 13:49
I got the same problem, here is the error message:

> Computing 2000 integration features
> Scaling features for provided objects
> Finding all pairwise anchors
> Running CCA
> Merging objects
> Error in RowMergeMatrices(mat1 = mat1, mat2 = mat2, mat1_rownames = mat1.names,  : 
>   std::bad_alloc
> Calls: FindIntegrationAnchors ... merge.Assay -> RowMergeSparseMatrices -> RowMergeMatrices
> Execution halted

I tried to merge two datasets, each of them has ~8K cells.
Seurat was run on our server with 200GB of memory.

**Comment by satijalab** [comment] 2019-04-10 17:05
Thanks for writing - and we will look into this. This is certainly not an issue of memory, as we've integrated datasets of hundreds of thousands of cells with significantly less RAM.

Are you able to integrate the control/stim datasets in our vignette. These should run quickly on a standard laptop, and has ~16k cells total.
https://satijalab.org/seurat/v3.0/immune_alignment.html

Would you be able to send the matrices or Seurat objects you are working with, so that we can debug on our end?

**Comment by Dragonmasterx87** [comment] 2019-04-10 17:08
This is very puzzling, I am having issues reproducing this error. I ran 10K cells (3000k + 7000k) on 4 cores with 32GB Ram and it worked fine.

**Comment by SFF-singecell-user** [comment] 2019-04-10 17:17
Thanks so much,
I will try the datasets in your online vignette. I am happy to send you my matrices/Seurat objects- what is the best way to privately do that?
Thank you again for your help.

**Comment by SFF-singecell-user** [comment] 2019-04-10 17:46
OK, I was able to run the online vignette with the online control/stim datasets, no problem. So, I'm not sure why I am not able to do this with my own data (which works fine for simple cluster/UMAP/etc analyses)

**Comment by Emmavb1988** [comment] 2019-04-26 13:54
I'm getting the same error. Strange enough, I've integrated the same datasets before and it worked fine. The only thing that I changed is that I now used ScaleData() on all genes within each object before I integrated the data, instead of only the most variable genes (default). 
Not sure if this could give a clue or if the issue has been resolved in the mean time. If so, it would be great to know how. Thanks in advance!

**Comment by Emmavb1988** [comment] 2019-04-26 14:03
> I'm getting the same error. Strange enough, I've integrated the same datasets before and it worked fine. The only thing that I changed is that I now used ScaleData() on all genes within each object before I integrated the data, instead of only the most variable genes (default).
> Not sure if this could give a clue or if the issue has been resolved in the mean time. If so, it would be great to know how. Thanks in advance!

Sorry, after restarting R I did not get the erro anymore and the integration worked.

**Comment by SFF-singecell-user** [comment] 2019-04-26 14:10
Thats what happened for me, too

**Closed** 2019-04-26 22:50 UTC

**Comment by OpenIDUser6** [comment] 2019-07-29 09:58
I have the same problem. when I run IntegrateData for two or four samples, it works. however, when I run 17 samples (34,000 cells), I got error message as:
Computing 2000 integration features
Scaling features for provided objects
Finding all pairwise anchors
Running CCA
Merging objects
Error in RowMergeMatrices(mat1 = mat1, mat2 = mat2, mat1_rownames = mat1.names, :
std::bad_alloc
Calls: FindIntegrationAnchors ... merge.Assay -> RowMergeSparseMatrices -> RowMergeMatrices
Execution halted

is there number of cells limitation? or is there an option to deal with large number of cells?
It will be really appreciated if you could help me out here!

**Comment by sunwu93** [comment] 2019-10-11 22:13
I also stumbled across this issue. It seemed to occur during the re-clustering of subsetted data that was already integrated (using default params). It also only happened to larger numbers of cells (~56k but not downsampled ~40k). 

> Error in RowMergeMatrices(mat1 = mat1, mat2 = mat2, mat1_rownames = mat1.names,  : Need S4 class dgRMatrix for a sparse matrix

The error noting RowMergeMatrices seems to be memory related to me. Removing the integrated assay of each object prior to integration seemed to fix this issue. FindIntegrationAnchors did not complain anymore. 

`for (i in 1:length(temp_subset_cells_list)) {
  
  # remove integrated assay 
  temp_subset_cells_list[[i]]@assays$integrated <- NULL
  
  # normalise and FVGs
  DefaultAssay(temp_subset_cells_list[[i]]) <- "RNA"
  temp_subset_cells_list[[i]] <- 
    NormalizeData(temp_subset_cells_list[[i]], 
                  verbose = F)
  
  temp_subset_cells_list[[i]] <- 
    FindVariableFeatures(temp_subset_cells_list[[i]], 
                         verbose = F,
                         selection.method = "dispersion")
}
`
Hope this helps !
