### ISSUE TITLE
Error in GetAssayData(object = xxxx, slot = "counts") :    object 'to.return' not found

### ISSUE THREAD

**Issue by iakovrudenko** [satijalab/seurat#1308] opened 2019-04-01 17:46 UTC
Good afternoon everyone,

I am trying to run the following script:
library(dplyr)
## 
## 
## 
##     intersect, setdiff, setequal, union
library(Seurat)
S540.data <- Read10X_h5("raw_gene_bc_matrices_h5.h5")
sparse.size <- object.size(x = S540.data)
sparse.size
## 470488992 bytes
temp <- S540.data[c(rownames(x=S540.data)[!duplicated(rownames(x=S540.data))]),]
S540 <- CreateSeuratObject(counts = temp, min.cells = 3, min.features = 200, project = "10X_S540")
S540
## Active assay: RNA (25925 features)
mito.features <- grep(pattern = "^MT-", x = rownames(x = S540), value = TRUE)
percent.mito <- Matrix::colSums(x = GetAssayData(object = S540, slot = 'counts')[mito.features, ]) / Matrix::colSums(x = GetAssayData(object = S540, slot = 'counts'))

After the last command Rstudio showed me the following error:
Error in GetAssayData(object = S540, slot = "counts") : 
  object 'to.return' not found

Would greatly appreciate any advice. 

Sincerely,

Iakov

P.S. I am using PC

**Comment by andrewwbutler** [comment] 2019-04-02 15:18
Hi,

I'm not able to reproduce that error. Can you share a downsampled version of your object that reproduces the issue?

**Comment by iakovrudenko** [comment] 2019-04-02 15:20
Thanks for trying.
The code worked on Mac. Probably the problem with PC.

**Comment by andrewwbutler** [comment] 2019-04-04 14:07
I'm not sure why this would be OS specific but I'm glad you got it to work. Closing for now unless it becomes a reproducible issue.

**Closed by andrewwbutler** 2019-04-04 14:07 UTC
