### ISSUE TITLE
Error in h(simpleError(msg, call)) when running FindTransferAnchors

### ISSUE THREAD

**Issue by FionaMoon** [satijalab/seurat#8368] opened 2024-01-24 14:02 UTC
Hi all,
I met an error when running `FindTransferAnchors`
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': error in evaluating the argument 'x' in selecting a method for function 't': non-conformable arguments
```
Nothing wrong with my reference which has been used many times.
My query data is preprocessed by the following code.
```
obj <- merge(x = pbmc3k, y = c(Granulocytes, data))
saveRDS(obj, paste0(D_path, "/merged.rds"))

## run standard anlaysis workflow
obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern = "^MT-")
obj <- subset(obj, subset = nFeature_RNA > 50 & nFeature_RNA < 10000 & percent.mt < 10)
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)
obj <- ScaleData(obj)
obj <- RunPCA(obj)
obj <- FindNeighbors(obj, dims = 1:30, reduction = "pca")
obj <- FindClusters(obj, resolution = 2, cluster.name = "unintegrated_clusters")
obj <- RunUMAP(obj, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")
```

**Comment by igrabski** [comment] 2024-01-26 20:47
Hi Fiona, can you show the output of `obj` as well as your reference object, and also can you show the line where you are running `FindTransferAnchors`?

**Comment by joachimsiaw** [comment] 2024-02-18 14:16
Hi , 
I got the same error when i tried to run FindTransferAnchores. Similarly, I have run FindTransferAnchores an these same seurat_objs several time before and it worked everytime except now. 
Below are my codes, error message and sessionInfo.

### Run SCTransform and DimReduc
seu_obj_ref<- SCTransform(seu.seu_obj_ref,  verbose = T) 
seu_obj_ref<- RunPCA(seu_obj_ref, verbose = TRUE)
seu_obj_ref<-RunUMAP(seu_obj_ref, dims = 1:20)

### SCTransformed Query seu_obj
seu.obj_query 

### anchors
 anchors <- FindTransferAnchors(reference = seu_obj_ref, query = obj_query , normalization.method = "SCT")
        
 anchors <- FindTransferAnchors(reference = seu_obj_ref, query = obj_query, normalization.method = "SCT")
Normalizing query using reference SCT model
Warning: No layers found matching search pattern provided
Performing PCA on the provided reference using 1924 features as input.
Projecting cell embeddings
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': error in evaluating the argument 'x' in selecting a method for function 't': non-conformable arguments     

### sessionfo:
[1] spam_2.9-1                  plyr_1.8.9                  igraph_1.5.1                lazyeval_0.2.2             
  [5] splines_4.2.2               RcppHNSW_0.5.0              listenv_0.9.0               scattermore_1.2            
  [9] GenomeInfoDb_1.34.9         digest_0.6.33               htmltools_0.5.6.1           fansi_1.0.5                
 [13] magrittr_2.0.3              tensor_1.5                  cluster_2.1.4               ROCR_1.0-11                
 [17] tzdb_0.4.0                  globals_0.16.2              matrixStats_1.1.0           timechange_0.2.0           
 [21] spatstat.sparse_3.0-2       colorspace_2.1-0            ggrepel_0.9.4               tcltk_4.2.2                
 [25] RCurl_1.98-1.12             jsonlite_1.8.7              progressr_0.14.0            spatstat.data_3.0-1        
 [29] survival_3.5-7              zoo_1.8-12                  glue_1.6.2                  polyclip_1.10-6            
 [33] gtable_0.3.4                zlibbioc_1.44.0             XVector_0.38.0              leiden_0.4.3               
 [37] DelayedArray_0.24.0         future.apply_1.11.0         BiocGenerics_0.44.0         abind_1.4-5                
 [41] scales_1.2.1                spatstat.random_3.1-6       miniUI_0.1.1.1              Rcpp_1.0.11                
 [45] viridisLite_0.4.2           xtable_1.8-4                reticulate_1.34.0           dotCall64_1.1-0            
 [49] stats4_4.2.2                htmlwidgets_1.6.2           httr_1.4.7                  RColorBrewer_1.1-3         
 [53] ellipsis_0.3.2              ica_1.0-3                   pkgconfig_2.0.3             farver_2.1.1               
 [57] uwot_0.1.16                 deldir_1.0-9                utf8_1.2.3                  tidyselect_1.2.0           
 [61] labeling_0.4.3              rlang_1.1.1                 reshape2_1.4.4              later_1.3.1                
 [65] munsell_0.5.0               tools_4.2.2                 cli_3.6.1                   generics_0.1.3             
 [69] ggridges_0.5.4              fastmap_1.1.1               goftest_1.2-3               fitdistrplus_1.1-11        
 [73] RANN_2.6.1                  pbapply_1.7-2               nlme_3.1-163                sparseMatrixStats_1.10.0   
 [77] mime_0.12                   compiler_4.2.2              rstudioapi_0.15.0           plotly_4.10.2              
 [81] png_0.1-8                   spatstat.utils_3.0-3        glmGamPoi_1.10.0            stringi_1.7.12             
 [85] RSpectra_0.16-1             lattice_0.21-9              Matrix_1.6-5                vctrs_0.6.4                
 [89] pillar_1.9.0                lifecycle_1.0.3             spatstat.geom_3.2-5         lmtest_0.9-40              
 [93] RcppAnnoy_0.0.21            data.table_1.14.8           cowplot_1.1.1               bitops_1.0-7               
 [97] irlba_2.3.5.1               httpuv_1.6.11               GenomicRanges_1.50.0        R6_2.5.1                   
[101] promises_1.2.1              KernSmooth_2.23-22          gridExtra_2.3               IRanges_2.32.0             
[105] parallelly_1.36.0           sessioninfo_1.2.2           codetools_0.2-19            fastDummies_1.7.3          
[109] MASS_7.3-60                 SummarizedExperiment_1.28.0 withr_2.5.1                 sctransform_0.4.1          
[113] S4Vectors_0.36.0            GenomeInfoDbData_1.2.9      parallel_4.2.2              hms_1.1.3                  
[117] grid_4.2.2                  DelayedMatrixStats_1.20.0   MatrixGenerics_1.10.0       Rtsne_0.16                 
[121] spatstat.explore_3.2-3      Biobase_2.58.0              shiny_1.7.5.1

**Comment by ybaeus** [comment] 2024-02-18 17:30
Hi, I also faced the same issue. Here I am showing the reference, query object and the code i ran. 

 **My reference object**
 ```
  > pbmc_multimodal_2023
An object of class Seurat 
20957 features across 161764 samples within 2 assays 
Active assay: SCT (20729 features, 3000 variable features)
 2 layers present: counts, data
 1 other assay present: ADT
 6 dimensional reductions calculated: apca, aumap, pca, spca, umap, wnn.umap
 ```

 
 **My query object** 
```
> pbmc_alzheimer_SCT.combined
An object of class Seurat 
47901 features across 74134 samples within 3 assays 
Active assay: SCT (21737 features, 0 variable features)
 3 layers present: counts, data, scale.data
 2 other assays present: RNA, integrated
 3 dimensional reductions calculated: pca, umap, tsne
```
 
```
 anchor <- FindTransferAnchors(
	reference = pbmc_multimodal_2023,
	query = pbmc_alzheimer_SCT.combined, # Pearson residuals 
	reference.reduction = "spca",
	normalization.method = "SCT",
	dims = 1:50
)
```

**Comment by sugarglider12** [comment] 2024-02-19 22:44
I am having the same issue. I have tried using different numbers of dims, the cell IDs are unique. 


anchors <- FindTransferAnchors(reference = annotation.ref, query = data.query, dims = 1:50, reference.reduction = "pca") 
Projecting cell embeddings
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': subscript out of bounds


> data.query
An object of class Seurat 
33723 features across 8447 samples within 1 assay 
Active assay: RNA (33723 features, 2000 variable features)
 13 layers present: counts.1.1.1, counts.2, counts.2.1, counts.2.1.1, data.1.1.1, scale.data.1.1.1, data.2.1.1, scale.data.2.1.1, data.2.1, scale.data.2.1, data.2, scale.data.2, scale.data
 2 dimensional reductions calculated: pca, umap

> annotation.ref
An object of class Seurat 
34707 features across 19427 samples within 1 assay 
Active assay: RNA (34707 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 2 dimensional reductions calculated: pca, umap


Session Info:
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Matrix_1.6-4       ggprism_1.0.4      lubridate_1.9.3    forcats_1.0.0      stringr_1.5.1     
 [6] dplyr_1.1.4        purrr_1.0.2        readr_2.1.4        tidyr_1.3.0        tibble_3.2.1      
[11] ggplot2_3.4.4      tidyverse_2.0.0    Seurat_5.0.1       SeuratObject_5.0.1 sp_2.1-2          

loaded via a namespace (and not attached):
  [1] deldir_2.0-2           pbapply_1.7-2          gridExtra_2.3          rlang_1.1.2           
  [5] magrittr_2.0.3         RcppAnnoy_0.0.21       matrixStats_1.2.0      ggridges_0.5.5        
  [9] compiler_4.3.2         spatstat.geom_3.2-7    png_0.1-8              vctrs_0.6.5           
 [13] reshape2_1.4.4         pkgconfig_2.0.3        fastmap_1.1.1          ellipsis_0.3.2        
 [17] labeling_0.4.3         utf8_1.2.4             promises_1.2.1         tzdb_0.4.0            
 [21] jsonlite_1.8.8         goftest_1.2-3          later_1.3.2            spatstat.utils_3.0-4  
 [25] irlba_2.3.5.1          parallel_4.3.2         cluster_2.1.4          R6_2.5.1              
 [29] ica_1.0-3              stringi_1.8.3          RColorBrewer_1.1-3     spatstat.data_3.0-3   
 [33] reticulate_1.34.0      parallelly_1.36.0      lmtest_0.9-40          scattermore_1.2       
 [37] Rcpp_1.0.12            tensor_1.5             future.apply_1.11.1    zoo_1.8-12            
 [41] sctransform_0.4.1      timechange_0.2.0       httpuv_1.6.13          splines_4.3.2         
 [45] igraph_1.6.0           tidyselect_1.2.0       rstudioapi_0.15.0      abind_1.4-5           
 [49] spatstat.random_3.2-2  codetools_0.2-19       miniUI_0.1.1.1         spatstat.explore_3.2-5
 [53] listenv_0.9.0          lattice_0.21-9         plyr_1.8.9             withr_2.5.2           
 [57] shiny_1.8.0            ROCR_1.0-11            Rtsne_0.17             future_1.33.1         
 [61] fastDummies_1.7.3      survival_3.5-7         polyclip_1.10-6        fitdistrplus_1.1-11   
 [65] pillar_1.9.0           KernSmooth_2.23-22     plotly_4.10.3          generics_0.1.3        
 [69] RcppHNSW_0.5.0         hms_1.1.3              munsell_0.5.0          scales_1.3.0          
 [73] globals_0.16.2         xtable_1.8-4           glue_1.7.0             lazyeval_0.2.2        
 [77] tools_4.3.2            data.table_1.14.10     RSpectra_0.16-1        RANN_2.6.1            
 [81] leiden_0.4.3.1         dotCall64_1.1-1        cowplot_1.1.2          grid_4.3.2            
 [85] colorspace_2.1-0       nlme_3.1-163           patchwork_1.1.3        cli_3.6.2             
 [89] spatstat.sparse_3.0-3  spam_2.10-0            fansi_1.0.6            viridisLite_0.4.2     
 [93] uwot_0.1.16            gtable_0.3.4           digest_0.6.33          progressr_0.14.0      
 [97] ggrepel_0.9.4          farver_2.1.1           htmlwidgets_1.6.4      htmltools_0.5.7       
[101] lifecycle_1.0.4        httr_1.4.7             mime_0.12              MASS_7.3-60

**Comment by joachimsiaw** [comment] 2024-02-19 22:57
I was able to fix my problem. In my case, I was working with a merged seurat object, this implies I have multiple SCT models in the SCTModel.list in the SCT assay layer. When I run PrepSCTFindMarkers;
`seu_obj_merge<-` `PrepSCTFindMarkers(seu_obj_merge)` 
 this recorrects the individual counts th of each sample and returns a single SCT model in the SCTModel.list.
I then run `FindIntegrationAnchors` which works.

I get error if I dont convert the multiple SCTModels to a single model via PrepSCTFindMarkers.
I would assume that for integrated datasets , maybe setting the integrated assay to default might help.

**Closed** 2024-02-23 20:59 UTC

**Comment by z5ouyang** [comment] 2024-04-16 08:46
@joachimsiaw , which version of Seurat (I am using 5.0.3) are you using? I would love to have merged SCT model, but ```PrepSCTFindMarkers``` does NOT return a single SCT model in ```SCTModel.list```, no change in the model list.
Thanks!

**Comment by 1274650861** [comment] 2025-03-26 06:06
I checked the source code of FindTransferAnchors and found that the issue occurs in the following function. The root cause is that query = LayerData(object = query, layer = layers.set[i]) extracts data from each layer of the query separately. However, the features in each query layer are missing compared to the features in reference[[pca]]:
```
features <- Reduce(f = intersect, x = list(rownames(x = Loadings(object = reference[[reduction]])), rownames(x = reference[[reference.assay]]))) 
...
features <- features %||% rownames(x = Loadings(object = reference[[reduction]]))
```
As a result, an error occurs at query <- query[features, ].
# To resolve this issue, before running FindTransferAnchors, execute:
`pancreas.query <- JoinLayers(pancreas.query, assay = "RNA")`
Additionally, ensure that the common genes from the reference dataset are present in the query dataset:
# Obtain common genes from the reference dataset (intersection of PCA loadings and RNA assay)
```
reference_pca_genes <- rownames(Loadings(pancreas.ref[["pca"]]))
reference_rna_genes <- rownames(pancreas.ref[["RNA"]])
common_ref_genes <- intersect(reference_pca_genes, reference_rna_genes)
```

# Check if these common genes are present in the query dataset's RNA assay
`common_in_query <- common_ref_genes %in% rownames(pancreas.query[["RNA"]])`

# Output missing genes (if any)
```
missing_genes <- common_ref_genes[!common_in_query]
if (length(missing_genes) > 0) {
  print(paste("Missing genes in query data:", paste(missing_genes, collapse = ", ")))
} else {
  print("All features are present in query data.")
}

```
# source code of FindTransferAnchors
```
ProjectCellEmbeddings.StdAssay(query = query[[query.assay]], 
    reference = reference, reference.assay = reference.assay, 
    reduction = reduction, dims = dims, scale = scale, normalization.method = normalization.method, 
    verbose = verbose, nCount_UMI = nCount_UMI, feature.mean = feature.mean, 
    feature.sd = feature.sd)
{
    reference.assay <- reference.assay %||% DefaultAssay(object = reference)
    features <- Reduce(f = intersect, x = list(rownames(x = Loadings(object = reference[[reduction]])), 
        rownames(x = reference[[reference.assay]])))
    if (normalization.method == "SCT") {
        layers.set <- Layers(object = query, search = "counts")
    }
    else {
        layers.set <- Layers(object = query, search = "data")
    }
    proj.pca.list <- list()
    cell.list <- list()
    for (i in seq_along(layers.set)) {
        proj.pca.list[[i]] <- t(ProjectCellEmbeddings(query = LayerData(object = query, 
            layer = layers.set[i]), reference = reference, reference.assay = reference.assay, 
            reduction = reduction, dims = dims, scale = scale, 
            normalization.method = normalization.method, verbose = verbose, 
            features = features, nCount_UMI = nCount_UMI[Cells(x = query, 
                layer = layers.set[i])], feature.mean = feature.mean, 
            feature.sd = feature.sd))
        cell.list[[i]] <- colnames(proj.pca.list[[i]])
    }
    proj.pca <- matrix(data = unlist(proj.pca.list), nrow = nrow(proj.pca.list[[1]]), 
        ncol = ncol(query))
    rownames(proj.pca) <- rownames(proj.pca.list[[1]])
    colnames(proj.pca) <- unlist(cell.list)
    proj.pca <- t(proj.pca)
    proj.pca <- proj.pca[colnames(query), ]
    return(proj.pca)
 ProjectCellEmbeddings.default(query = LayerData(object = query, 
    layer = layers.set[i]), reference = reference, reference.assay = reference.assay, 
    reduction = reduction, dims = dims, scale = scale, normalization.method = normalization.method, 
    verbose = verbose, features = features, nCount_UMI = nCount_UMI[Cells(x = query, 
        layer = layers.set[i])], feature.mean = feature.mean, 
    feature.sd = feature.sd)
{
    

features <- features %||% rownames(x = Loadings(object = reference[[reduction]]))

    if (normalization.method == "SCT") {
        reference.SCT.model <- slot(object = reference[[reference.assay]], 
            name = "SCTModel.list")[[1]]
        query <- FetchResiduals_reference(object = query, reference.SCT.model = reference.SCT.model, 
            features = features, nCount_UMI = nCount_UMI)
    }
    else {
        query <- query[features, ]
        if (inherits(x = reference[[reference.assay]], what = "Assay5")) {
            reference.data.list <- c()
            for (i in Layers(object = reference[[reference.assay]], 
                search = "data")) {
                reference.data.list[[i]] <- LayerData(object = reference[[reference.assay]], 
                  layer = i)[features, ]
            }
            reference.data <- do.call(cbind, reference.data.list)
        }
        else {
            reference.data <- GetAssayData(object = reference, 
                assay = reference.assay, slot = "data")[features, 
                ]
        }
        if (is.null(x = feature.mean)) {
            if (inherits(x = reference.data, what = "dgCMatrix")) {
                feature.mean <- RowMeanSparse(mat = reference.data)
            }
            else if (inherits(x = reference.data, what = "IterableMatrix")) {
                bp.stats <- BPCells::matrix_stats(matrix = reference.data, 
                  row_stats = "variance")
                feature.mean <- bp.stats$row_stats["mean", ]
            }
            else {
                feature.mean <- rowMeans2(x = reference.data)
            }
            if (scale) {
                if (inherits(x = reference.data, what = "IterableMatrix")) {
                  feature.sd <- sqrt(bp.stats$row_stats["variance", 
                    ])
                }
                else {
                  feature.sd <- sqrt(x = RowVarSparse(mat = as.sparse(reference.data)))
                }
                feature.sd[is.na(x = feature.sd)] <- 1
                feature.sd[feature.sd == 0] <- 1
            }
            else {
                feature.sd <- rep(x = 1, nrow(x = reference.data))
            }
            feature.mean[is.na(x = feature.mean)] <- 1
        }
        store.names <- dimnames(x = query)
        if (is.numeric(x = feature.mean)) {
            query <- FastSparseRowScaleWithKnownStats(mat = as.sparse(x = query), 
                mu = feature.mean, sigma = feature.sd, display_progress = FALSE)
        }
        dimnames(x = query) <- store.names
    }
    ref.feature.loadings <- Loadings(object = reference[[reduction]])[features, 
        dims]
    proj.pca <- t(crossprod(x = ref.feature.loadings, y = query))
    return(proj.pca)
}
```
