### ISSUE TITLE
Failed to read h5ad file. 

### ISSUE THREAD

**Issue by cougarlj** [satijalab/seurat#3089] opened 2020-05-29 01:35 UTC
Dear developer,

I want to use ReadH5AD in Seurat to read in a h5ad file, but I fail in many times. I have tried in Windows, Linux and MAC, and failed always. The error info is the same as fellow. 

srtSample<-ReadH5AD(chrInput)
Pulling expression matrices and metadata
Error in self$read_low_level(file_space = self_space_id, mem_space = mem_space_id,  : 
  HDF5-API Errors:
    error #000: ../../src/hdf5-1.10.0-1/src/H5Dio.c in H5Dread(): line 170: can't read data
        class: HDF5
        major: Dataset
        minor: Read failed

    error #001: ../../src/hdf5-1.10.0-1/src/H5Dio.c in H5D__read(): line 543: can't read data
        class: HDF5
        major: Dataset
        minor: Read failed

    error #002: ../../src/hdf5-1.10.0-1/src/H5Dchunk.c in H5D__chunk_read(): line 2046: unable to read raw data chunk
        class: HDF5
        major: Low-level I/O
        minor: Read failed

    error #003: ../../src/hdf5-1.10.0-1/src/H5Dchunk.c in H5D__chunk_lock(): line 3401: data pipeline read failed
        class: HDF5
        major: Data filters
        minor: Filter operation failed

    error #004: ../../src/hdf5-1.10.0-1/src/H5Z.c in H5Z_pipeline(): line 1351: required filter 'lzf' is not registered
        class: HDF5
        major: Data filters
        minor: Read failed

    error #005: ../../src/hdf5-1.10.0-1/src/H5PL.c i

Would you like to give some suggestions for solusion?

Best Wishes,
   Jiang

**Comment by mojaveazure** [comment] 2020-05-29 20:20
Duplicate of #2977

**Closed by mojaveazure** 2020-05-29 20:20 UTC
