### ISSUE TITLE
Differential expression between conditions - FindMarkers

### ISSUE THREAD

**Issue by Kikibarmpa** [satijalab/seurat#3583] opened 2020-10-08 07:19 UTC
Hello,

I am using the FindMarkers function in the integration analysis to find differentially expressed genes between two conditions in a specific cluster. My code is the following:

Idents(object) = object$seurat_clusters

cluster2 <- subset(object, idents = "2")
Idents(cluster2 ) = cluster2$Models
Cl2WTvsCl2MUT <- FindMarkers(cluster2, ident.1 = "WT", ident.2 = "MUT", logfc.threshold = 0.25, only.pos = T)

From this I expect to have a list with the differentially expressed genes of the WT compared the MUT. When I run the same command but with inverted idents (ident.1 = "MUT", ident.2 = "WT") it gives me the same list of genes but also the same fold change and p-value. So in this case I cannot evaluate the upregulation or downregulation of genes of the ident.1 in comparison with ident.2.
Do you know why this is happening and if there is a logical explanation? 

Thank you a lot for your time and help!

**Comment by timoast** [comment] 2020-10-09 16:56
Can you provide a reproducible example?

**Comment by Kikibarmpa** [comment] 2020-10-16 13:49
> 
> 
> Can you provide a reproducible example?

Hello,

I am sorry for the delayed answer. I ran the code from scratch and I get now different DEG lists for each case. I am still not able to identify what I did wrong in the first place but the function seems to be working as expected. I cannot provide you a reproducible example with my data but if it is helpful for you I can create the same analysis with your vignette data.

Thank you for your time!

**Comment by timoast** [comment] 2020-10-16 13:59
>  I ran the code from scratch and I get now different DEG lists for each case. I am still not able to identify what I did wrong in the first place but the function seems to be working as expected

In that case I'll close this issue

**Closed by timoast** 2020-10-16 13:59 UTC

**Comment by nsbc6** [comment] 2022-01-24 12:22
Hello all!

I reopen the thread because I got a problem when I tried to apply "FindMarkers" between conditions (3 samples D vs 2 samples Control). I read that harmony integration per condition of the samples would be a good for my data. So, first of all I performed that integration and then the DE. However, it returned the following error:
``Error in FindMarkers.SCTAssay(object = data.use, slot = slot, cells.1 = cells$cells.1,  : 
  Object contains multiple models with unequal library sizes. Run `PrepSCTFindMarkers()` before running `FindMarkers()``

I cannot elucidate why it occurs. Could you please give me some advise?

Here I write the code:

```
### Only infiltration - selection of clusters
Idents(D1) <- "SCT_snn_res.0.75"
inf_D1 <- subset(D1, idents = c("3"))
#
Idents(D2) <- "SCT_snn_res.0.1"
inf_D2<- subset(D2, idents = c("1"))
#
Idents(D3) <- "SCT_snn_res.1"
inf_D3<- subset(D3, idents = c("0", "3", "5"))
#
Idents(C1) <- "SCT_snn_res.0.5"
inf_C1<- subset(C1, idents = c("0"))
#
Idents(C2) <- "SCT_snn_res.0.3"
inf_C2<- subset(C2, idents = c("0"))

### Samples + condition

>inf_D1@meta.data[["Condition"]] <- "D"
>inf_D2@meta.data[["Condition"]] <- "D"
>inf_D3@meta.data[["Condition"]] <- "D"
>
>inf_C1@meta.data[["Condition"]] <- "Controls"
>inf_C2@meta.data[["Condition"]] <- "Controls"
>
>list_of_combinations <- list(inf_D1, inf_D2, inf_D3, inf_C1, inf_C2)
>
>list_of_combinations <- lapply(X = list_of_combinations,
>                                      FUN = SCTransform, assay = "Spatial")
>
>var.features <- SelectIntegrationFeatures(object.list = list_of_combinations,
>                                          nfeatures = 3000)

>together <- merge(x = list_of_combinations[[1]],
>                 y = list_of_combinations[2:length(list_of_combinations)],
>                  merge.data=TRUE)
>
### Integration
>VariableFeatures(together) <- var.features
>
>together <- RunPCA(together, verbose = FALSE)
>
>together <- RunHarmony(together, assay.use="SCT", group.by.vars = "Condition")
>
### DE
>Ident(together) <- "Condition"
>mark <- FindMarkers(together, ident.1 = "D", ident.2 = "Controls")
Error in FindMarkers.SCTAssay(object = data.use, slot = slot, cells.1 = cells$cells.1,  : 
  Object contains multiple models with unequal library sizes. Run `PrepSCTFindMarkers()` before running `FindMarkers()`.

```
Thank you in advance!

**Comment by jyopadi** [comment] 2022-04-01 22:58
##Split Object by (assign cell cluster as identity) identity then differential exp or FoldChange for each cluster by condition
Idents(SeuratObject)
SeuratObject_splitlist<-SplitObject(SeuratObject, split.by = "ident")

##assign identity as condition
for (i in 1:length(SeuratObject_splitlist)) {
    Idents(SeuratObject_splitlist[[i]]) <- "condition" }

## Check the split object and names of individual cluster in the file 
SeuratObject_splitlist

## cluster wise FC and save the file. FC will be as in the same sequence as the split object cluster sequence separated by header
SeuratObject_splitlist <- lapply(X = SeuratObject_splitlist, FUN = function(x){
    x <- FindMarkers(x, ident.1 = 'Disease', ident.2= 'Normal', min.pct=0.25, logfc.threshold=0.25)
    write.table(x, file = "SeuratObject_splitlist_Condition_diffgenes.csv", sep = ",", append = TRUE)
})
