### ISSUE TITLE
Error in deparse when filtering large Seurat v5 object

### ISSUE THREAD

**Issue by jcorn427** [satijalab/seurat#7987] opened 2023-11-08 21:27 UTC
Hello, I'm trying to filter low quality cells from a large Seurat object and I'm getting the following error:

`> merged.obj_filt <- subset(merged.obj, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent_mito < 5)
Error in deparse(expr = object, width.cutoff = width.cutoff, nlines = nlines) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537
Error in stopifnot(length(class2) == 1L) : 
  INTEGER() can only be applied to a 'integer', not a 'closure'`

```r
> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.4.4          scCustomize_1.9.9.9034 Seurat_5.0.0           SeuratObject_5.0.0     sp_2.1-1               shinyBS_0.61.1        
[7] BPCells_0.1.0         

loaded via a namespace (and not attached):
  [1] IRanges_2.34.1                    R.methodsS3_1.8.2                 progress_1.2.2                    urlchecker_1.0.1                 
  [5] poweRlaw_0.70.6                   goftest_1.2-3                     DT_0.30                           Biostrings_2.68.1                
  [9] vctrs_0.6.4                       spatstat.random_3.2-1             digest_0.6.33                     png_0.1-8                        
 [13] shape_1.4.6                       ggrepel_0.9.4                     deldir_1.0-9                      parallelly_1.36.0                
 [17] MASS_7.3-60                       Signac_1.12.9000                  reshape2_1.4.4                    httpuv_1.6.12                    
 [21] BiocGenerics_0.46.0               withr_2.5.1                       ggrastr_1.0.2                     xfun_0.40                        
 [25] ellipsis_0.3.2                    survival_3.5-5                    EnsDb.Hsapiens.v86_2.99.0         memoise_2.0.1                    
 [29] ggbeeswarm_0.7.2                  janitor_2.2.0                     profvis_0.3.8                     zoo_1.8-12                       
 [33] GlobalOptions_0.1.2               gtools_3.9.4                      pbapply_1.7-2                     R.oo_1.25.0                      
 [37] prettyunits_1.2.0                 rematch2_2.1.2                    KEGGREST_1.40.1                   promises_1.2.1                   
 [41] httr_1.4.7                        restfulr_0.0.15                   globals_0.16.2                    fitdistrplus_1.1-11              
 [45] rhdf5filters_1.12.1               ps_1.7.5                          rhdf5_2.44.0                      PCAtools_2.12.0                  
 [49] rstudioapi_0.15.0                 miniUI_0.1.1.1                    generics_0.1.3                    processx_3.8.2                   
 [53] curl_5.1.0                        S4Vectors_0.38.2                  zlibbioc_1.46.0                   ScaledMatrix_1.8.1               
 [57] polyclip_1.10-6                   GenomeInfoDbData_1.2.10           xtable_1.8-4                      stringr_1.5.0                    
 [61] pracma_2.4.2                      evaluate_0.22                     S4Arrays_1.0.6                    BiocFileCache_2.8.0              
 [65] hms_1.1.3                         GenomicRanges_1.52.1              irlba_2.3.5.1                     colorspace_2.1-0                 
 [69] filelock_1.0.2                    hdf5r_1.3.8                       ROCR_1.0-11                       reticulate_1.34.0                
 [73] spatstat.data_3.0-3               magrittr_2.0.3                    lmtest_0.9-40                     snakecase_0.11.1                 
 [77] readr_2.1.4                       viridis_0.6.4                     later_1.3.1                       lattice_0.21-8                   
 [81] spatstat.geom_3.2-7               future.apply_1.11.0               scuttle_1.10.3                    scattermore_1.2                  
 [85] XML_3.99-0.14                     cowplot_1.1.1                     matrixStats_1.0.0                 RcppAnnoy_0.0.21                 
 [89] pillar_1.9.0                      nlme_3.1-162                      caTools_1.18.2                    compiler_4.3.1                   
 [93] beachmat_2.16.0                   RSpectra_0.16-1                   stringi_1.7.12                    tensor_1.5                       
 [97] SummarizedExperiment_1.30.2       lubridate_1.9.3                   devtools_2.4.5                    GenomicAlignments_1.36.0         
[101] plyr_1.8.9                        scater_1.28.0                     crayon_1.5.2                      abind_1.4-5                      
[105] BiocIO_1.10.0                     googledrive_2.1.1                 bit_4.0.5                         dplyr_1.1.3                      
[109] fastmatch_1.1-4                   codetools_0.2-19                  BiocSingular_1.16.0               SeuratData_0.2.2.9001            
[113] paletteer_1.5.0                   plotly_4.10.3                     mime_0.12                         splines_4.3.1                    
[117] circlize_0.4.15                   Rcpp_1.0.11                       fastDummies_1.7.3                 dbplyr_2.3.4                     
[121] sparseMatrixStats_1.12.2          cellranger_1.1.0                  knitr_1.44                        blob_1.2.4                       
[125] utf8_1.2.4                        seqLogo_1.66.0                    AnnotationFilter_1.24.0           fs_1.6.3                         
[129] listenv_0.9.0                     DelayedMatrixStats_1.22.6         pkgbuild_1.4.2                    openxlsx_4.2.5.2                 
[133] tibble_3.2.1                      Matrix_1.6-1.1                    callr_3.7.3                       tzdb_0.4.0                       
[137] pkgconfig_2.0.3                   tools_4.3.1                       cachem_1.0.8                      RSQLite_2.3.1                    
[141] viridisLite_0.4.2                 DBI_1.1.3                         rmarkdown_2.25                    fastmap_1.1.1                    
[145] scales_1.2.1                      grid_4.3.1                        usethis_2.2.2                     ica_1.0-3                        
[149] shinydashboard_0.7.2              Rsamtools_2.16.0                  patchwork_1.1.3                   ggprism_1.0.4                    
[153] dotCall64_1.1-0                   RANN_2.6.1                        yaml_2.3.7                        MatrixGenerics_1.12.3            
[157] rtracklayer_1.60.1                cli_3.6.1                         purrr_1.0.2                       stats4_4.3.1                     
[161] leiden_0.4.3                      lifecycle_1.0.3                   uwot_0.1.16                       Biobase_2.60.0                   
[165] presto_1.0.0                      sessioninfo_1.2.2                 BSgenome.Hsapiens.UCSC.hg38_1.4.5 BiocParallel_1.34.2              
[169] annotate_1.78.0                   timechange_0.2.0                  gtable_0.3.4                      rjson_0.2.21                     
[173] ggridges_0.5.4                    progressr_0.14.0                  parallel_4.3.1                    jsonlite_1.8.7                   
[177] RcppHNSW_0.5.0                    TFBSTools_1.38.0                  bitops_1.0-7                      bit64_4.0.5                      
[181] Rtsne_0.16                        BiocNeighbors_1.18.0              spatstat.utils_3.0-4              zip_2.3.0                        
[185] CNEr_1.36.0                       dqrng_0.3.1                       shinyjs_2.1.0                     SeuratDisk_0.0.0.9020            
[189] R.utils_2.12.2                    lazyeval_0.2.2                    shiny_1.7.5.1                     Azimuth_0.4.6.9004               
[193] htmltools_0.5.6.1                 GO.db_3.17.0                      sctransform_0.4.1                 rappdirs_0.3.3                   
[197] ensembldb_2.24.1                  glue_1.6.2                        TFMPvalue_0.0.9                   spam_2.10-0                      
[201] googlesheets4_1.1.1               XVector_0.40.0                    RCurl_1.98-1.12                   BSgenome_1.68.0                  
[205] gridExtra_2.3                     JASPAR2020_0.99.10                igraph_1.5.1                      R6_2.5.1                         
[209] SingleCellExperiment_1.22.0       tidyr_1.3.0                       forcats_1.0.0                     RcppRoll_0.3.0                   
[213] GenomicFeatures_1.52.2            cluster_2.1.4                     pkgload_1.3.3                     Rhdf5lib_1.22.1                  
[217] gargle_1.5.2                      GenomeInfoDb_1.36.4               DirichletMultinomial_1.42.0       DelayedArray_0.26.7              
[221] tidyselect_1.2.0                  vipor_0.4.5                       ProtGenerics_1.32.0               xml2_1.3.5                       
[225] AnnotationDbi_1.62.2              future_1.33.0                     rsvd_1.0.5                        munsell_0.5.0                    
[229] KernSmooth_2.23-21                data.table_1.14.8                 htmlwidgets_1.6.2                 RColorBrewer_1.1-3               
[233] biomaRt_2.56.1                    rlang_1.1.1                       spatstat.sparse_3.0-3             spatstat.explore_3.2-5           
[237] remotes_2.4.2.1                   fansi_1.0.5                       beeswarm_0.4.0 
```

**Comment by igrabski** [comment] 2024-06-24 14:41
Hi, we are unable to reproduce this issue on our end. Are you able to provide a reproducible example using one of the datasets available through SeuratData? I will close this issue for now, but please feel free to open a new issue with a reproducible example or with more detail about your object where you are experiencing this problem.

**Closed by igrabski** 2024-06-24 14:41 UTC
Labels: bug
