### ISSUE TITLE
SpatialFeaturePlot returning error

### ISSUE THREAD

**Issue by MarcElosua** [satijalab/seurat#2707] opened 2020-03-10 14:54 UTC
Hello,
I'm taking a look at the spatial data vignette and I am getting an error when running _SpatialFeaturePlot_ at the very beginning. 
I had previously been able to run it successfully in the past weeks and have not changed anything major. I've tried to reinstall the package from github but its still not working.

The code I'm running is the one showed in the vignette
> devtools::install_github("satijalab/seurat",` ref = "spatial", force = TRUE)
> library(Seurat)
> library(SeuratData) # devtools::install_github('satijalab/seurat-data')
> library(ggplot2)
> library(cowplot)
> library(dplyr)

> InstallData("stxBrain")
> brain <- LoadData("stxBrain", type = "anterior1")
> SpatialFeaturePlot(brain, features = "nCount_Spatial") + theme(legend.position = "right")

The error I'm getting is the following:
_Error in data[[features[j]]] : subscript out of bounds_

I've checked and nCount_Spatial exists in the metadata of the Seurat object.

Could you please point towards what may be happening?

Thank you very much,
Marc

**Comment by rtower1** [comment] 2020-03-10 19:04
I am having the same problem. I also tried to directly download the files from the 10X website rather than using the SeuratData function.

**Comment by MarcElosua** [comment] 2020-03-11 13:01
> I am having the same problem. I also tried to directly download the files from the 10X website rather than using the SeuratData function.

Have also tried this and get the same error as well.

**Comment by lima1** [comment] 2020-03-11 16:53
https://github.com/satijalab/seurat/issues/2695

**Comment by lima1** [comment] 2020-03-11 19:57
The problem is `data` is a matrix, so subsetting by feature does not work. Converting data to a data.frame in SpatialPlot fixes the issue.

**Comment by rtower1** [comment] 2020-03-11 20:06
How do you convert data to a data.frame?

**Comment by lima1** [comment] 2020-03-11 20:13
@rtower1, I'm not a Seurat developer. But looks like a bug in the SpatialPlot function. This change in that function fixed it for me:

```
   rownames(x = data) <- colnames(x = object)
+  data <- as.data.frame(data)
   facet.highlight <- facet.highlight && (!is.null(x = cells.highlight) && is.list(x = cells.highlight))

```

**Comment by rtower1** [comment] 2020-03-11 20:58
When I gave this a try I got the following error:
rownames(x = data) <- colnames(x = object)
Error in `rownames<-`(`*tmp*`, value = c("AAACAAGTATCTCCCA-1", "AAACACCAATAACTGC-1",  : 
  attempt to set 'rownames' on an object with no dimensions

**Comment by andrewwbutler** [comment] 2020-03-11 21:13
Thanks for reporting! I just pushed a fix for this. Please try reinstalling the `spatial` branch.

**Comment by rtower1** [comment] 2020-03-13 13:29
I am trying to reinstall the package, but the reinstall in unsuccessful. The problem seems to be the package "glue". It needs to be compiled to install the spatial package, but it cannot be updated because it is in use by devtools to install the spatial package in the first place:

installing *source* package 'glue' ...
** package 'glue' successfully unpacked and MD5 sums checked
ERROR: cannot remove earlier installation, is it in use?
Error in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE)
Execution halted
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘glue’ had non-zero exit status

If I try to not update glue, the following error message comes up:
Error: package 'glue' does not have a namespace
Execution halted
ERROR: lazy loading failed for package 'Seurat'

**Comment by rtower1** [comment] 2020-03-13 13:30
I have also tried to delete the 00LOCK-glue folder and retry with the same results

**Comment by rtower1** [comment] 2020-03-13 13:43
I have also tried to manually move 00LOCK-glue\glue\libs\x64\glue.dll into the glue\libs\x64\glue.dll location, but the devtools no longer works

**Comment by andrewwbutler** [comment] 2020-03-13 15:11
Hi,

Try starting a fresh R session to update `glue`/any other packages. ( `R --vanilla`)

Alternatively, you don't need all of devtools to install, just `remotes` so you could try `remotes::install_github` instead of `devtools::install_github`

**Comment by rtower1** [comment] 2020-03-13 15:35
I have restarted R and deleted all packages and tried to reinstall but nothing changed. I tried again from scratch using the remotes function and got the following message:

*** arch - i386
Error in system(cmd) : (converted from warning) 'make' not found
* removing 'C:/Users/Clemens Lab/Documents/R/win-library/3.6/Seurat'
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘C:/Users/CLEMEN~1/AppData/Local/Temp/RtmpAZkmyp/file191c34f568a9/Seurat_3.1.4.9902.tar.gz’ had non-zero exit status
In addition: Warning message:
In missing_devel_warning(pkgdir) :
  Package Seurat has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools (https://cran.r-project.org/bin/windows/Rtools/).Then use the pkgbuild package, or make sure that Rtools in the PATH.

I have the newest Rtools installed but I seem to require devtools for the find_rtools() function to work. Installing devtools after trying the spatial Seurat restores the glue compiling issue above.

**Comment by andrewwbutler** [comment] 2020-04-10 16:31
@MarcElosua, I'm assuming the new code fixed the original issue but if not feel free to reopen.

@rtower1 If you're still having installation issues, please start a new issue.

**Closed by andrewwbutler** 2020-04-10 16:31 UTC
Labels: bug

**Comment by andrewjkwok** [comment] 2023-06-01 03:31
Hi - I've now updated to Seurat v5, but am facing an error with the SpatialFeaturePlot function similar to the one mentioned in this thread:

```
 > SpatialFeaturePlot(vizgen.obj, features = c("percent_mito"))
Error in data[rownames(x = coordinates), features[j], drop = FALSE] : 
  subscript out of bounds
```

This is the traceback:
```
> traceback()
9: data.frame(..., check.names = FALSE)
8: cbind(deparse.level, ...)
7: cbind(coordinates, data[rownames(x = coordinates), features[j], 
       drop = FALSE])
6: is.data.frame(x)
5: colnames(x = data)
4: col.by %in% colnames(x = data)
3: SingleSpatialPlot(data = cbind(coordinates, data[rownames(x = coordinates), 
       features[j], drop = FALSE]), image = image.use, image.alpha = image.alpha, 
       col.by = features[j], cols = cols, alpha.by = if (is.null(x = group.by)) {
           features[j]
       } else {
           NULL
       }, pt.alpha = if (!is.null(x = group.by)) {
           alpha[j]
       } else {
           NULL
       }, geom = if (inherits(x = image.use, what = "STARmap")) {
           "poly"
       } else {
           "spatial"
       }, cells.highlight = highlight.use, cols.highlight = cols.highlight, 
       pt.size.factor = pt.size.factor, stroke = stroke, crop = crop)
2: SpatialPlot(object = object, features = features, images = images, 
       crop = crop, slot = slot, keep.scale = keep.scale, min.cutoff = min.cutoff, 
       max.cutoff = max.cutoff, ncol = ncol, combine = combine, 
       pt.size.factor = pt.size.factor, alpha = alpha, image.alpha = image.alpha, 
       stroke = stroke, interactive = interactive, information = information)
1: SpatialFeaturePlot(vizgen.obj, features = c("percent_mito"))

```

Just wondering what the issue might be?

**Comment by Prathyusha-konda** [comment] 2024-02-06 22:50
I am encountering this same error. Is there a fix for this?

**Comment by RayRay-23** [comment] 2024-04-12 03:40
I soved these issue by syncronize the cell names and metadata cell names. You can first check if your `Cells(object)` are identical to `colnames(object)`, if not then run:

```
metadata=object[[]]
rownames(metadata) <- Cells(object)
slot(object,name="meta.data")<-metadata

```

Replace the `object` with `your object name`

**Comment by vukojicic-nevena** [comment] 2024-04-25 10:35
I have the same issue and my cell and column names are identical. Did anyone find a solution?

**Comment by babiddy** [comment] 2024-05-23 00:08
@Prathyusha-konda @vukojicic-nevena 

I was having the same issue. I switched to using the `ImageFeaturePlot` function instead of `SpatialFeaturePlot`. I don't know why but `ImageFeaturePlot` worked for my dataset and `SpatialFeaturePlot` did not.

**Comment by aksaikumarjayalatha** [comment] 2024-07-05 09:13
Has anyone been able to fix this issue "
I have the same issue and my cell and column names are identical. Did anyone find a solution?". I am having the same problem, its Seurat v5 and my cell, column names are identical. So any fixes besides switching to ImageFeaturePlot?

**Comment by jiw181** [comment] 2024-08-22 17:56
I have the same problem, though my cell and column names are identical. 
ImageFeaturePlot also did not work for me. Got error: Warning: No FOV associated with assay 'Spatial', using global default FOV
Error in ImageFeaturePlot(ST, features = "nCount_Spatial") : 
  No compatible spatial coordinates present

Any suggestions?
