### ISSUE TITLE
Wired JackStrawPlot() result

### ISSUE THREAD

**Issue by Leran10** [satijalab/seurat#7048] opened 2023-03-14 22:31 UTC
Hi,

I was trying to plot jackstraw plot but I got this:

![image](https://user-images.githubusercontent.com/17597071/225156241-1624049a-2390-4c4a-980e-55c6eff486e0.png)

Below is my code:
```
seurat.combined <- NormalizeData(seurat.combined, normalization.method = "LogNormalize", scale.factor = 10000)
seurat.combined <- FindVariableFeatures(seurat.combined, selection.method = "vst", nfeatures = 2000)
seurat.combined <- ScaleData(seurat.combined, verbose = FALSE)
seurat.combined <- RunPCA(seurat.combined, npcs = 30, verbose = FALSE)
seurat.combined <- RunUMAP(seurat.combined, dims = 1:20,reduction = "pca")
seurat.combined <- RunTSNE(object =seurat.combined,reduction = "pca")
seurat.combined <- FindNeighbors(seurat.combined, reduction = "pca", dims = 1:20)
seurat.combined <- FindClusters(seurat.combined, resolution = 0.5)


seurat.combined <- JackStraw(seurat.combined, dims = 30)
seurat.combined <- ScoreJackStraw(seurat.combined, dims = 1:30)
JackStrawPlot(seurat.combined, dims = 1:30)

```

Is there anything wrong that I have done?

Thank you!
Leran

**Comment by longmanz** [comment] 2023-04-21 19:12
Hi, 
Sorry for the late response. Have you fixed the issue? Your codes seem alright to me so I think the problem was probably driven by your data. Have you checked if your data's DefaultAssay() has been set to the correct one?

**Comment by MengjurJ** [comment] 2023-07-03 12:02
> Hi, Sorry for the late response. Have you fixed the issue? Your codes seem alright to me so I think the problem was probably driven by your data. Have you checked if your data's DefaultAssay() has been set to the correct one?

I have the same problem when I try to run JackStraw() and ScoreJackStraw(), the data was generated by merged different datasets, and the data's DefaultAssay() was 'RNA'. Is that normal?
Thanks!

**Comment by longmanz** [comment] 2023-07-06 20:13
Hi @MengjurJ , 
Have you fixed this issue. It is weird that we cannot reproduce it from our end. What does your jackstraw plot looks like? 
It would be nice if you have a small reproducible dataset for us to test. And could you give us your codes and SessionInfo?

**Comment by MengjurJ** [comment] 2023-07-07 07:40
> 

Hi,there is Rstudio  information:
sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default
‘Seurat’ version 4.3.0

![image](https://github.com/satijalab/seurat/assets/126403827/04d16a1e-06cf-4420-b5a7-de2a494ec1de)
![image](https://github.com/satijalab/seurat/assets/126403827/3137d269-66c7-4b58-8854-04e23435793b)

The first picture contanins 50,000 cells, the second picture contains about 500,000 cells. The data used to analyze is integrated from different scRNAseq data I collected.  Sorry, the data size is too big to upload.
Does this have any impact on the subsequent results?
Below is my code:
```r
pbmc0 <- NormalizeData(pbmc0, normalization.method = "LogNormalize", scale.factor = 40000)
pbmc0 <- FindVariableFeatures(pbmc0, selection.method = "vst", nfeatures = 4000)
pbmc0 <- ScaleData(pbmc0, features = top4000)
pbmc0 <- RunPCA(pbmc0, features = VariableFeatures(object = pbmc0))
pbmc0 <- JackStraw(pbmc0, num.replicate = 100,dims = 30)
pbmc0 <- ScoreJackStraw(pbmc0, dims = 1:30)
p5=JackStrawPlot(pbmc0, dims = 1:15)

``` 
Thanks!

**Comment by MengjurJ** [comment] 2023-07-07 07:45
> 

top4000 <-  head(VariableFeatures(pbmc0), 4000)

**Comment by longmanz** [comment] 2023-07-07 15:16
Hi,
Thank you for your quick response. Although it is rare to see all top 20 PCs are straight lines (P = 0), but this could indicate your top 20 PCs are capturing a huge proportion of variation in your data (given this is an integrated dataset). 
Have you checked the elbow plot of your dataset? This will show the percentage of variance explained by each PC. If that looks normal to you, then this should not be an issue. 
Alternatively, you can try to increase the number of dims in your JackStraw test. You should see more "normal" lines for > 20th PCs. 
I am closing this issue for now. But if the problem still persists, we will reopen it and investigate.

**Closed by longmanz** 2023-07-07 15:16 UTC
