### ISSUE TITLE
HTODemux error in Seurat 2.3

### ISSUE THREAD

**Issue by rmenafra** [satijalab/seurat#1093] opened 2019-01-25 14:11 UTC
Hi everybody,
I have been trying to run HTODemux function in Seurat 2.3. with 2 different datasets.
In the first I have 7 hashtag oligos, if I don't set the init_centers = 7 the function will give me error saying "Error in SetAssayData(object = toRet, assay.type = names(x = data.return)[i],  : 
  Wrong number of cells being added: should be 7"
I don't fully understand what are the consequences of forcing the init_center value, since I understood that in principle the function tries to identify 7 + 1 clusters (where the extra 1 is the negative cluster).
The second dataset has 9 hashtags and basically if I don't set init_center=8 it will not run the demux function.
Could you give me any feedback on this and is it a problem forcing init_center to those lower values?

I would really appreciate your help.
Best regards,
Roberta

**Comment by rmenafra** [comment] 2019-01-28 06:54
I attached an example of the result of my HTOdemux using the init_center=7 in a dataset with 7 HTO and ~1400 cells. As you can see from the heatmap there are cells clearly positive for hto_7 that ends up in the negative group. Would there be a way to "rescue" them and re-assign them to the proper group?
![htoheatmap](https://user-images.githubusercontent.com/39999649/51819229-f37bd900-22d1-11e9-8141-3b0d51e41613.png)

**Comment by rmenafra** [comment] 2019-01-28 17:48
Hi Matt,
I followed exactly the HTOdemux vignette on the seurat page as you suggest (https://satijalab.org/seurat/hashing_vignette.html), without applying any filter. 
Here is the str(s) result of my Seurat object.
Formal class 'seurat' [package "Seurat"] with 20 slots
  ..@ raw.data    :Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:1077006] 21 27 32 33 38 40 43 46 49 54 ...
  .. .. ..@ j       : int [1:1077006] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..@ Dim     : int [1:2] 33694 1408
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:33694] "RP11-34P13.3" "FAM138A" "OR4F5" "RP11-34P13.7" ...
  .. .. .. ..$ : chr [1:1408] "AAACCTGCAACGCACC" "AAACCTGCATTACGAC" "AAACCTGGTCATATCG" "AAACCTGTCTAGCACA" ...
  .. .. ..@ x       : num [1:1077006] 1 2 1 1 1 1 1 3 1 1 ...
  .. .. ..@ factors : list()
  ..@ data        :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:1077006] 21 27 32 33 38 40 43 46 49 54 ...
  .. .. ..@ p       : int [1:1409] 0 1641 2724 3583 4416 4675 5477 6049 6347 7277 ...
  .. .. ..@ Dim     : int [1:2] 33694 1408
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:33694] "RP11-34P13.3" "FAM138A" "OR4F5" "RP11-34P13.7" ...
  .. .. .. ..$ : chr [1:1408] "AAACCTGCAACGCACC" "AAACCTGCATTACGAC" "AAACCTGGTCATATCG" "AAACCTGTCTAGCACA" ...
  .. .. ..@ x       : num [1:1077006] 0.948 1.426 0.948 0.948 0.948 ...
  .. .. ..@ factors : list()
  ..@ scale.data  : num [1:3811, 1:1408] -0.19 2.789 1.604 0.191 0.759 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:3811] "FO538757.2" "NOC2L" "HES4" "ISG15" ...
  .. .. ..$ : chr [1:1408] "AAACCTGCAACGCACC" "AAACCTGCATTACGAC" "AAACCTGGTCATATCG" "AAACCTGTCTAGCACA" ...
  ..@ var.genes   : chr [1:3811] "FO538757.2" "NOC2L" "HES4" "ISG15" ...
  ..@ is.expr     : num 0
  ..@ ident       : Factor w/ 9 levels "Doublet","hto1",..: 5 1 8 9 9 9 4 5 9 9 ...
  .. ..- attr(*, "names")= chr [1:1408] "AAACCTGCAACGCACC" "AAACCTGCATTACGAC" "AAACCTGGTCATATCG" "AAACCTGTCTAGCACA" ...
  ..@ meta.data   :'data.frame':	1408 obs. of  9 variables:
  .. ..$ nGene                    : int [1:1408] 1641 1083 859 833 259 802 572 298 930 523 ...
  .. ..$ nUMI                     : num [1:1408] 6326 3421 2085 1717 2250 ...
  .. ..$ orig.ident               : Factor w/ 1 level "SeuratProject": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ hash_maxID               : Factor w/ 7 levels "hto1","hto2",..: 4 4 7 3 1 4 3 4 5 3 ...
  .. ..$ hash_secondID            : Factor w/ 7 levels "hto1","hto2",..: 5 1 3 1 2 1 5 2 4 5 ...
  .. ..$ hash_margin              : num [1:1408] 1.94541 0.31195 1.66047 0.00563 0.27554 ...
  .. ..$ hto_classification       : Factor w/ 28 levels "hto1","hto1_hto2",..: 18 4 27 28 28 28 13 18 28 28 ...
  .. ..$ hto_classification_global: Factor w/ 3 levels "Doublet","Negative",..: 3 1 3 2 2 2 3 3 2 2 ...
  .. ..$ hash_ID                  : Factor w/ 9 levels "Doublet","hto1",..: 5 1 8 9 9 9 4 5 9 9 ...
  ..@ project.name: chr "SeuratProject"
  ..@ dr          : list()
  ..@ assay       :List of 1
  .. ..$ HTO:Formal class 'assay' [package "Seurat"] with 7 slots
  .. .. .. ..@ raw.data  :'data.frame':	7 obs. of  1408 variables:
  .. .. .. .. ..$ AAACCTGCAACGCACC: int [1:7] 0 0 0 20 1 0 0
  .. .. .. .. ..$ AAACCTGCATTACGAC: int [1:7] 3 0 3 6 0 0 0
  .. .. .. .. ..$ AAACCTGGTCATATCG: int [1:7] 0 0 1 0 0 0 7
  .. .. .. .. ..$ AAACCTGTCTAGCACA: int [1:7] 1 0 2 0 0 0 0
  .. .. .. .. ..$ AAACCTGTCTCTGAGA: int [1:7] 2 1 2 1 0 0 0
  .. .. .. .. ..$ AAACGGGAGATGCCAG: int [1:7] 0 0 0 2 0 0 0
  .. .. .. .. ..$ AAACGGGCATACTACG: int [1:7] 1 0 14 0 2 0 0
  .. .. .. .. ..$ AAAGATGGTCTAAACC: int [1:7] 0 1 0 3 1 0 0
  .. .. .. .. ..$ AAAGCAATCAGCACAT: int [1:7] 0 0 2 2 2 0 0
  .. .. .. .. ..$ AAAGTAGAGAGCCCAA: int [1:7] 0 0 4 0 1 0 0
  .. .. .. .. ..$ AAAGTAGAGATGTCGG: int [1:7] 1 0 3 5 1 0 0
  .. .. .. .. ..$ AAAGTAGTCATTGCGA: int [1:7] 1 1 1 1 0 0 0
  .. .. .. .. ..$ AAATGCCAGGCTAGAC: int [1:7] 4 0 2 1 0 0 0
  .. .. .. .. ..$ AAATGCCCATGTTCCC: int [1:7] 0 0 1 0 0 0 0
  .. .. .. .. ..$ AAATGCCGTTCAGTAC: int [1:7] 0 0 3 0 0 0 0
  .. .. .. .. ..$ AACACGTCACTATCTT: int [1:7] 0 0 0 0 0 1 0
  .. .. .. .. ..$ AACACGTCAGCCTTTC: int [1:7] 2 1 7 0 0 0 0
  .. .. .. .. ..$ AACACGTCATCCGCGA: int [1:7] 1 0 1 1 2 0 0
  .. .. .. .. ..$ AACCATGAGGCTAGCA: int [1:7] 0 0 3 1 0 0 0
  .. .. .. .. ..$ AACCGCGGTCATCCCT: int [1:7] 0 0 0 0 0 3 1
  .. .. .. .. ..$ AACCGCGGTTCCTCCA: int [1:7] 1 0 1 0 0 1 1
  .. .. .. .. ..$ AACGTTGAGGGTGTTG: int [1:7] 1 4 17 0 0 0 3
  .. .. .. .. ..$ AACGTTGCAAGCCCAC: int [1:7] 3 0 0 4 0 0 0
  .. .. .. .. ..$ AACGTTGGTGGGTCAA: int [1:7] 0 0 1 1 1 0 0
  .. .. .. .. ..$ AACGTTGTCTTCGGTC: int [1:7] 2 0 4 0 2 0 0
  .. .. .. .. ..$ AACTCAGAGCAGCCTC: int [1:7] 1 0 2 1 0 0 2
  .. .. .. .. ..$ AACTCAGCAATGTTGC: int [1:7] 1 0 2 1 5 0 0
  .. .. .. .. ..$ AACTCAGTCGGAGGTA: int [1:7] 0 0 2 0 0 1 0
  .. .. .. .. ..$ AACTCCCCATTCACTT: int [1:7] 2 1 3 1 1 0 0
  .. .. .. .. ..$ AACTCCCGTTCAACCA: int [1:7] 1 0 1 1 1 0 0
  .. .. .. .. ..$ AACTCCCTCAGAGACG: int [1:7] 4 1 2 0 2 0 0
  .. .. .. .. ..$ AACTCCCTCTGGAGCC: int [1:7] 0 0 0 0 0 1 0
  .. .. .. .. ..$ AACTCTTGTCTTGATG: int [1:7] 1 0 4 0 0 0 0
  .. .. .. .. ..$ AACTCTTGTGATGCCC: int [1:7] 0 0 2 1 0 0 0
  .. .. .. .. ..$ AACTCTTTCAAAGACA: int [1:7] 1 0 1 0 0 1 0
  .. .. .. .. ..$ AACTGGTAGATCGGGT: int [1:7] 1 0 2 0 0 1 0
  .. .. .. .. ..$ AACTGGTGTAAACCTC: int [1:7] 2 0 3 0 2 1 1
  .. .. .. .. ..$ AACTGGTTCTCGAGTA: int [1:7] 0 0 9 0 0 5 1
  .. .. .. .. ..$ AACTTTCAGGAGTTTA: int [1:7] 0 0 0 2 0 0 0
  .. .. .. .. ..$ AACTTTCCAAACCTAC: int [1:7] 0 0 3 0 1 0 0
  .. .. .. .. ..$ AACTTTCCACAACTGT: int [1:7] 0 0 0 1 2 0 0
  .. .. .. .. ..$ AACTTTCCACATGACT: int [1:7] 0 0 2 1 0 0 1
  .. .. .. .. ..$ AACTTTCCACCGAATT: int [1:7] 0 0 3 22 2 0 0
  .. .. .. .. ..$ AACTTTCCATTACGAC: int [1:7] 1 1 0 1 0 0 3
  .. .. .. .. ..$ AAGACCTTCACCCGAG: int [1:7] 0 0 2 1 0 0 1
  .. .. .. .. ..$ AAGCCGCGTTCGTGAT: int [1:7] 6 0 2 0 1 0 0
  .. .. .. .. ..$ AAGCCGCTCACGATGT: int [1:7] 0 0 1 1 2 0 0
  .. .. .. .. ..$ AAGGAGCAGCCCAATT: int [1:7] 0 0 1 0 0 0 0
  .. .. .. .. ..$ AAGGAGCAGTGCCAGA: int [1:7] 0 0 1 2 1 0 0
  .. .. .. .. ..$ AAGGAGCCAGTATAAG: int [1:7] 2 0 4 0 0 0 0
  .. .. .. .. ..$ AAGGAGCGTGTTTGGT: int [1:7] 0 0 3 4 0 0 0
  .. .. .. .. ..$ AAGGCAGCATATGCTG: int [1:7] 1 1 6 0 4 0 3
  .. .. .. .. ..$ AAGGCAGGTCAGATAA: int [1:7] 3 1 4 0 1 0 3
  .. .. .. .. ..$ AAGGCAGGTTCAACCA: int [1:7] 1 0 2 0 0 1 0
  .. .. .. .. ..$ AAGGTTCCAATACGCT: int [1:7] 0 0 3 0 0 0 0
  .. .. .. .. ..$ AAGGTTCGTGCAGGTA: int [1:7] 0 0 4 7 2 0 0
  .. .. .. .. ..$ AAGGTTCTCTCTGAGA: int [1:7] 0 0 7 1 0 0 0
  .. .. .. .. ..$ AAGTCTGAGTGTACTC: int [1:7] 3 0 2 0 3 1 0
  .. .. .. .. ..$ AAGTCTGCAGACACTT: int [1:7] 0 0 9 0 7 2 1
  .. .. .. .. ..$ AATCCAGAGAAGGGTA: int [1:7] 0 0 1 0 4 0 1
  .. .. .. .. ..$ AATCCAGGTTATTCTC: int [1:7] 0 0 1 0 2 2 0
  .. .. .. .. ..$ AATCCAGGTTGGAGGT: int [1:7] 7 0 4 1 1 0 0
  .. .. .. .. ..$ AATCCAGTCCCTCAGT: int [1:7] 0 0 3 0 0 1 0
  .. .. .. .. ..$ AATCGGTCAGCTGCTG: int [1:7] 0 0 1 4 1 0 0
  .. .. .. .. ..$ AATCGGTTCTGAGGGA: int [1:7] 0 0 2 0 0 0 0
  .. .. .. .. ..$ AATCGGTTCTTGACGA: int [1:7] 2 0 1 2 1 0 0
  .. .. .. .. ..$ ACACCAAAGAAGGACA: int [1:7] 2 0 3 1 0 2 0
  .. .. .. .. ..$ ACACCAAAGCGATGAC: int [1:7] 2 0 6 0 3 1 0
  .. .. .. .. ..$ ACACCAAAGCTAACAA: int [1:7] 0 0 3 0 1 0 1
  .. .. .. .. ..$ ACACCAACACCGCTAG: int [1:7] 0 2 0 7 0 0 1
  .. .. .. .. ..$ ACACCAAGTTCATGGT: int [1:7] 0 0 1 0 0 0 0
  .. .. .. .. ..$ ACACCCTAGGGTCGAT: int [1:7] 0 0 8 1 2 3 2
  .. .. .. .. ..$ ACACCCTAGTGTCTCA: int [1:7] 0 0 4 0 0 0 0
  .. .. .. .. ..$ ACACCCTCAGGACCCT: int [1:7] 0 0 0 1 0 0 0
  .. .. .. .. ..$ ACACCCTGTATATGGA: int [1:7] 1 3 6 2 0 0 1
  .. .. .. .. ..$ ACACCCTTCTATCCCG: int [1:7] 0 0 3 1 12 1 0
  .. .. .. .. ..$ ACACCGGAGAGACGAA: int [1:7] 2 0 0 6 0 0 0
  .. .. .. .. ..$ ACACCGGCACAGCGTC: int [1:7] 0 0 7 1 0 0 0
  .. .. .. .. ..$ ACACCGGCATGGTCTA: int [1:7] 0 0 3 5 0 0 0
  .. .. .. .. ..$ ACACCGGGTAAGGGCT: int [1:7] 0 0 2 9 0 0 0
  .. .. .. .. ..$ ACACCGGGTGATAAAC: int [1:7] 0 2 2 5 2 0 1
  .. .. .. .. ..$ ACACCGGGTGTGTGCC: int [1:7] 0 0 2 2 3 0 0
  .. .. .. .. ..$ ACACCGGTCGCGTAGC: int [1:7] 1 0 3 0 0 1 0
  .. .. .. .. ..$ ACACTGAAGACTTTCG: int [1:7] 0 0 6 0 0 0 0
  .. .. .. .. ..$ ACACTGAAGTATCTCG: int [1:7] 2 0 5 0 0 0 0
  .. .. .. .. ..$ ACACTGACACAGGCCT: int [1:7] 2 0 2 1 1 0 0
  .. .. .. .. ..$ ACACTGAGTCAGCTAT: int [1:7] 0 0 2 0 8 0 0
  .. .. .. .. ..$ ACACTGAGTTCCCGAG: int [1:7] 1 0 0 5 1 1 0
  .. .. .. .. ..$ ACAGCCGTCCTAGTGA: int [1:7] 1 0 2 0 1 0 0
  .. .. .. .. ..$ ACAGCTAAGGCCATAG: int [1:7] 0 2 5 0 1 1 1
  .. .. .. .. ..$ ACAGCTACAATGGTCT: int [1:7] 0 1 8 0 1 0 0
  .. .. .. .. ..$ ACAGCTACATTGCGGC: int [1:7] 0 0 2 2 0 0 0
  .. .. .. .. ..$ ACAGCTAGTAGAAGGA: int [1:7] 0 0 11 1 0 0 3
  .. .. .. .. ..$ ACAGCTAGTGCACGAA: int [1:7] 1 2 2 0 2 0 0
  .. .. .. .. ..$ ACAGCTAGTTGACGTT: int [1:7] 3 0 0 2 2 0 0
  .. .. .. .. ..$ ACAGCTAGTTGTTTGG: int [1:7] 1 2 2 1 1 0 0
  .. .. .. .. ..$ ACAGCTATCAGCTCGG: int [1:7] 0 0 1 3 0 0 0
  .. .. .. .. ..$ ACAGCTATCGCTGATA: int [1:7] 0 0 8 2 0 0 1
  .. .. .. .. ..$ ACAGCTATCTCAAACG: int [1:7] 0 0 4 1 1 0 1
  .. .. .. .. .. [list output truncated]
  .. .. .. ..@ data      : num [1:7, 1:1408] 0 0 0 2.413 0.468 ...
  .. .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. .. ..$ : chr [1:7] "hto1" "hto2" "hto3" "hto4" ...
  .. .. .. .. .. ..$ : chr [1:1408] "AAACCTGCAACGCACC" "AAACCTGCATTACGAC" "AAACCTGGTCATATCG" "AAACCTGTCTAGCACA" ...
  .. .. .. ..@ scale.data: NULL
  .. .. .. ..@ key       : chr(0) 
  .. .. .. ..@ misc      : NULL
  .. .. .. ..@ var.genes : logi(0) 
  .. .. .. ..@ mean.var  :'data.frame':	0 obs. of  0 variables
Formal class 'data.frame' [package "methods"] with 4 slots
  .. .. .. .. .. ..@ .Data    : list()
  .. .. .. .. .. ..@ names    : chr(0) 
  .. .. .. .. .. ..@ row.names: int(0) 
  .. .. .. .. .. ..@ .S3Class : chr "data.frame"
  ..@ hvg.info    :'data.frame':	33694 obs. of  3 variables:
  .. ..$ gene.mean             : num [1:33694] 3.95 1.98 4.58 3.31 3.83 ...
  .. ..$ gene.dispersion       : num [1:33694] 8.52 8.51 8.33 8.23 7.71 ...
  .. ..$ gene.dispersion.scaled: num [1:33694(1d)] 2.454 4.128 0.707 3.561 3.148 ...
  ..@ imputed     :'data.frame':	0 obs. of  0 variables
Formal class 'data.frame' [package "methods"] with 4 slots
  .. .. ..@ .Data    : list()
  .. .. ..@ names    : chr(0) 
  .. .. ..@ row.names: int(0) 
  .. .. ..@ .S3Class : chr "data.frame"
  ..@ cell.names  : chr [1:1408] "AAACCTGCAACGCACC" "AAACCTGCATTACGAC" "AAACCTGGTCATATCG" "AAACCTGTCTAGCACA" ...
  ..@ cluster.tree: list()
  ..@ snn         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int(0) 
  .. .. ..@ p       : int 0
  .. .. ..@ Dim     : int [1:2] 0 0
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : NULL
  .. .. .. ..$ : NULL
  .. .. ..@ x       : num(0) 
  .. .. ..@ factors : list()
  ..@ calc.params :List of 4
  .. ..$ CreateSeuratObject:List of 13
  .. .. ..$ project             : chr "SeuratProject"
  .. .. ..$ min.cells           : num 0
  .. .. ..$ min.genes           : num 0
  .. .. ..$ is.expr             : num 0
  .. .. ..$ normalization.method: NULL
  .. .. ..$ scale.factor        : num 10000
  .. .. ..$ do.scale            : logi FALSE
  .. .. ..$ do.center           : logi FALSE
  .. .. ..$ names.field         : num 1
  .. .. ..$ names.delim         : chr "_"
  .. .. ..$ display.progress    : logi TRUE
  .. .. ..$ ...                 : symbol 
  .. .. ..$ time                : POSIXct[1:1], format: "2019-01-28 18:42:06"
  .. ..$ NormalizeData     :List of 5
  .. .. ..$ assay.type          : chr "HTO"
  .. .. ..$ normalization.method: chr "genesCLR"
  .. .. ..$ scale.factor        : num 10000
  .. .. ..$ display.progress    : logi FALSE
  .. .. ..$ time                : POSIXct[1:1], format: "2019-01-28 18:42:13"
  .. ..$ FindVariableGenes :List of 18
  .. .. ..$ mean.function      : chr "ExpMean"
  .. .. ..$ dispersion.function: chr "LogVMR"
  .. .. ..$ do.plot            : logi FALSE
  .. .. ..$ set.var.genes      : logi TRUE
  .. .. ..$ x.low.cutoff       : num 0.1
  .. .. ..$ x.high.cutoff      : num 8
  .. .. ..$ y.cutoff           : num 1
  .. .. ..$ y.high.cutoff      : num Inf
  .. .. ..$ num.bin            : num 20
  .. .. ..$ binning.method     : chr "equal_width"
  .. .. ..$ selection.method   : chr "mean.var.plot"
  .. .. ..$ top.genes          : num 1000
  .. .. ..$ do.recalc          : logi TRUE
  .. .. ..$ sort.results       : logi TRUE
  .. .. ..$ do.cpp             : logi TRUE
  .. .. ..$ display.progress   : logi FALSE
  .. .. ..$ ...                : symbol 
  .. .. ..$ time               : POSIXct[1:1], format: "2019-01-28 18:42:08"
  .. ..$ ScaleData         :List of 16
  .. .. ..$ genes.use         : chr [1:3811] "FO538757.2" "NOC2L" "HES4" "ISG15" ...
  .. .. ..$ vars.to.regress   : symbol 
  .. .. ..$ model.use         : chr "linear"
  .. .. ..$ use.umi           : logi FALSE
  .. .. ..$ do.scale          : logi TRUE
  .. .. ..$ do.center         : logi TRUE
  .. .. ..$ scale.max         : num 10
  .. .. ..$ block.size        : num 1000
  .. .. ..$ min.cells.to.block: num 3000
  .. .. ..$ display.progress  : logi FALSE
  .. .. ..$ assay.type        : chr "RNA"
  .. .. ..$ do.cpp            : logi TRUE
  .. .. ..$ check.for.norm    : logi TRUE
  .. .. ..$ do.par            : logi FALSE
  .. .. ..$ num.cores         : num 1
  .. .. ..$ time              : POSIXct[1:1], format: "2019-01-28 18:42:10"
  ..@ kmeans      : NULL
  ..@ spatial     :Formal class 'spatial.info' [package "Seurat"] with 4 slots
  .. .. ..@ mix.probs    :'data.frame':	1408 obs. of  1 variable:
  .. .. .. ..$ nGene: int [1:1408] 1641 1083 859 833 259 802 572 298 930 523 ...
  .. .. ..@ mix.param    :'data.frame':	0 obs. of  0 variables
Formal class 'data.frame' [package "methods"] with 4 slots
  .. .. .. .. ..@ .Data    : list()
  .. .. .. .. ..@ names    : chr(0) 
  .. .. .. .. ..@ row.names: int(0) 
  .. .. .. .. ..@ .S3Class : chr "data.frame"
  .. .. ..@ final.prob   :'data.frame':	0 obs. of  0 variables
Formal class 'data.frame' [package "methods"] with 4 slots
  .. .. .. .. ..@ .Data    : list()
  .. .. .. .. ..@ names    : chr(0) 
  .. .. .. .. ..@ row.names: int(0) 
  .. .. .. .. ..@ .S3Class : chr "data.frame"
  .. .. ..@ insitu.matrix:'data.frame':	0 obs. of  0 variables
Formal class 'data.frame' [package "methods"] with 4 slots
  .. .. .. .. ..@ .Data    : list()
  .. .. .. .. ..@ names    : chr(0) 
  .. .. .. .. ..@ row.names: int(0) 
  .. .. .. .. ..@ .S3Class : chr "data.frame"
  ..@ misc        : NULL
  ..@ version     :Classes 'package_version', 'numeric_version'  hidden list of 1
  .. ..$ : int [1:3] 2 3 3

**Comment by rmenafra** [comment] 2019-01-30 13:04
Hi Matt,
I already tried that other tool you mentioned (Multiseq) and that also threw me an error (but I didn't look too much into details of that). Moreover the problem with the HTOdemux I also get it with a different dataset having more than 7000 cells and 9 HTOs (and is a much better dataset). In that case if I don't set init_center=8 the function would not demultiplex. I can send you the csv tables of both that I used to set the HTO assay (with just umi counts out of the CITE-seq-count pipeline). Thank you for your time.

[Archive.zip](https://github.com/satijalab/seurat/files/2811852/Archive.zip)

**Comment by MattPM** [comment] 2019-02-08 00:25
Hi, I just got a chance to take a look at your data. The distribution of counts across each cell in the first dataset is far to low. As you can see below the vast majority of raw counts for the **maximum** hto in each cell is **<10** which is lower than the level of background noise I typically see in my hashing data. In this case, I think you either have to re-sequence this with a higher percentage of the HTO libraryor you could have an alignment/mapping issue given the distributions.

![hashcount](https://user-images.githubusercontent.com/15280712/52449950-121a7500-2b07-11e9-95b4-994bd85b3e5a.png)

for the other dataset, I wasn't able to reproduce your error; `HTODemux()` default and with specifying `init.centers` both produced the same result, 5139 singlets. 

Hope that helps. 


```
h1 = read.csv("9hto_7kcells.csv", header = T)
h1 = h1[-c(10:12),]
rownames(h1)=NULL
h1 = h1 %>% tibble::column_to_rownames("hto")
HTODemux(p,init_centers = 10 )
p = SetAssayData(p, assay.type = "HTO",slot = "raw.data", new.data = h1)
p = NormalizeData(p,assay.type = "HTO",normalization.method = "genesCLR")
p = ScaleData(p, assay.type = "HTO", do.par = T, num.cores = 8,display.progress = F)
HTODemux(p)
```

NaNs producedNaNs produced[1] "Cutoff for hto1 : 81 reads"
NaNs producedNaNs produced[1] "Cutoff for hto2 : 39 reads"
NaNs producedNaNs producedNaNs producedNaNs produced[1] "Cutoff for hto3 : 95 reads"
NaNs producedNaNs produced[1] "Cutoff for hto4 : 28 reads"
NaNs producedNaNs produced[1] "Cutoff for hto5 : 19 reads"
NaNs producedNaNs produced[1] "Cutoff for hto6 : 40 reads"
NaNs producedNaNs produced[1] "Cutoff for hto7 : 30 reads"
NaNs producedNaNs produced[1] "Cutoff for hto8 : 12 reads"
NaNs producedNaNs produced[1] "Cutoff for hto9 : 6 reads"

 Doublet Negative  Singlet 
    1689      211     5139 
An object of class seurat in project SeuratProject 
 13741 genes across 7039 samples.




`HTODemux(p,init_centers = 10 )`


NaNs producedNaNs produced[1] "Cutoff for hto1 : 81 reads"
NaNs producedNaNs produced[1] "Cutoff for hto2 : 39 reads"
NaNs producedNaNs producedNaNs producedNaNs produced[1] "Cutoff for hto3 : 95 reads"
NaNs producedNaNs produced[1] "Cutoff for hto4 : 28 reads"
NaNs producedNaNs produced[1] "Cutoff for hto5 : 19 reads"
NaNs producedNaNs produced[1] "Cutoff for hto6 : 40 reads"
NaNs producedNaNs produced[1] "Cutoff for hto7 : 30 reads"
NaNs producedNaNs produced[1] "Cutoff for hto8 : 12 reads"
NaNs producedNaNs produced[1] "Cutoff for hto9 : 6 reads"

 Doublet Negative  Singlet 
    1689      211     5139 
An object of class seurat in project SeuratProject 
 13741 genes across 7039 samples.



`sessionInfo()`
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2.2    cluster_2.0.7-1   data.table_1.11.8 here_0.1          Seurat_2.3.4      Matrix_1.2-15     cowplot_0.9.3    
 [8] forcats_0.3.0     stringr_1.3.1     dplyr_0.7.7       purrr_0.2.5       readr_1.1.1       tidyr_0.8.2       tibble_1.4.2     
[15] ggplot2_3.1.0     tidyverse_1.2.1  

loaded via a namespace (and not attached):
  [1] Rtsne_0.15          colorspace_1.3-2    ggridges_0.5.1      class_7.3-14        modeltools_0.2-22   rprojroot_1.3-2    
  [7] mclust_5.4.1        htmlTable_1.12      base64enc_0.1-3     proxy_0.4-22        rstudioapi_0.8      npsurv_0.4-0       
 [13] bit64_0.9-7         flexmix_2.3-14      mvtnorm_1.0-8       lubridate_1.7.4     xml2_1.2.0          codetools_0.2-15   
 [19] splines_3.5.2       R.methodsS3_1.7.1   lsei_1.2-0          robustbase_0.93-3   knitr_1.20          Formula_1.2-3      
 [25] jsonlite_1.5        ica_1.0-2           broom_0.5.0         kernlab_0.9-27      png_0.1-7           R.oo_1.22.0        
 [31] compiler_3.5.2      httr_1.3.1          backports_1.1.2     assertthat_0.2.0    lazyeval_0.2.1      cli_1.0.1          
 [37] lars_1.2            acepack_1.4.1       htmltools_0.3.6     tools_3.5.2         igraph_1.2.2        gtable_0.2.0       
 [43] glue_1.3.0          reshape2_1.4.3      RANN_2.6            Rcpp_1.0.0          cellranger_1.1.0    trimcluster_0.1-2.1
 [49] gdata_2.18.0        ape_5.2             nlme_3.1-137        iterators_1.0.10    fpc_2.1-11.1        lmtest_0.9-36      
 [55] gbRd_0.4-11         rvest_0.3.2         irlba_2.3.2         gtools_3.8.1        DEoptimR_1.0-8      zoo_1.8-4          
 [61] MASS_7.3-51.1       scales_1.0.0        hms_0.4.2           doSNOW_1.0.16       parallel_3.5.2      RColorBrewer_1.1-2 
 [67] yaml_2.2.0          reticulate_1.10     pbapply_1.3-4       gridExtra_2.3       segmented_0.5-3.0   rpart_4.1-13       
 [73] latticeExtra_0.6-28 stringi_1.2.4       foreach_1.4.4       checkmate_1.8.5     caTools_1.17.1.1    bibtex_0.4.2       
 [79] Rdpack_0.10-1       SDMTools_1.1-221    rlang_0.3.0.1       pkgconfig_2.0.2     dtw_1.20-1          prabclus_2.2-6     
 [85] bitops_1.0-6        lattice_0.20-38     ROCR_1.0-7          bindr_0.1.1         htmlwidgets_1.3     bit_1.1-14         
 [91] tidyselect_0.2.5    plyr_1.8.4          magrittr_1.5        R6_2.3.0            snow_0.4-3          gplots_3.0.1       
 [97] Hmisc_4.1-1         pillar_1.3.0        haven_1.1.2         foreign_0.8-71      withr_2.1.2         mixtools_1.1.0     
[103] fitdistrplus_1.0-11 survival_2.43-3     nnet_7.3-12         tsne_0.1-3          hdf5r_1.0.1         modelr_0.1.2       
[109] crayon_1.3.4        KernSmooth_2.23-15  grid_3.5.2          readxl_1.1.0        metap_1.0           digest_0.6.18      
[115] diptest_0.75-7      R.utils_2.7.0       stats4_3.5.2        munsell_0.5.0

**Comment by timoast** [comment] 2019-05-17 15:18
Closing this issue as it seems to be dataset-specific, but please open a new issue if needed

**Closed by timoast** 2019-05-17 15:18 UTC
