### ISSUE TITLE
subset() seurat object based on a string expression

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#3965] opened 2021-01-23 14:06 UTC
Hello - this might be a ore generic R question than seurat, but perhaps you might know. One can subset a seurat object with an expression like this:

x <- subset(seuratObj, subset = ClusterNames_0.4 == 0)

I have a situation where I am trying to let users pass those expressions as a string, like "ClusterNames_0.4 == 0". Is there a way that I can either subset based on this string, or somehow parse a string in R to convert to an expression?

```

e <- "ClusterNames_0.4 == 0"
# Convert/parse string?
x <- subset(seuratObj, subset = e)

```

Thanks for any help.

**Comment by bbimber** [comment] 2021-01-23 15:54
Alternately, if not a string, can the expresison be a variable?

```
# Gives FetchData / None of the requested variables were found error:
e <- expression(ClusterNames_0.2 == 0)
seuratObj2 <- subset(seuratObj, subset = e)
```

**Comment by yuhanH** [comment] 2021-01-29 16:55
`FetchData ` can work using a string expression. 
This issue https://github.com/satijalab/seurat/issues/1053 can solve your question.

**Comment by bbimber** [comment] 2021-02-01 23:25
@yuhanH Thanks but that isnt quite my question. I did see the example with FetchData(), but unless i'm missing something, it's providing the name of a single column as the variable (i.e. ClusterNames_0.2), not the entire expression (ClusterNames_0.2 == 0). The point of this scenario would be to enable something like the following, where the entire query expression is the variable:

```
# This does not work and expression() is just used for illustration:
e <- expression(ClusterNames_0.2 == 0)
seuratObj2 <- subset(seuratObj, subset = e)
```

**Comment by mojaveazure** [comment] 2021-02-05 19:03
[As stated previously](https://github.com/satijalab/seurat/issues/1053#issuecomment-454512002), `subset` doesn't work programmatically. To get around this, you can use `FetchData` and `which` to handle programmatic subsets

```R
expr <- FetchData(seuratObj, vars = 'ClusterNames_0.2']
seuratObj2 <- seuratObj[, which(expr == 0)]
```

**Comment by mojaveazure** [comment] 2021-02-05 19:04
Duplicate of #1053

**Closed by mojaveazure** 2021-02-05 19:03 UTC

**Comment by daymegr** [comment] 2021-06-04 09:20
It would be very nice if one could construct expressions dynamically and pass them to the subset function as a variable. I wanted to integrate this functionality in an app where people could subset cells based on a criterion they have, i.e. gene1 > 0 | gene2 == 0, that I don't know beforehand and need to pass as a variable. Maybe for future Seurat versions....??

**Comment by jindall** [comment] 2022-07-05 20:05
how to make a subset of seurat object that contains the cells expressing certain gene:
[
<img width="792" alt="text_case" src="https://user-images.githubusercontent.com/10815307/177407301-e286c64e-af24-47a4-8c24-14b7d49db868.png">
](url)

**Comment by joan-yanqiong** [comment] 2023-03-03 03:09
@jindall I believe you can use: 
`myobj <- subset(seurat, features=gene_list)`

**Comment by jliu678** [comment] 2024-03-13 15:07
> ```r
> expr <- FetchData(seuratObj, vars = 'ClusterNames_0.2']
> seuratObj2 <- seuratObj[, which(expr == 0)]
> ```
the above did not working probably due to update in Fetchdata behavior in seurat V5. The below works for me by far
expr <-seuratObj[[]][['ClusterNames_0.2']]
seuratObj2 <- seuratObj[, which(expr == 0)]

**Comment by shashkat** [comment] 2025-03-21 16:31
Another way would be:
```
library(rlang)
seuratObj2 <- subset(seuratObj, subset = !!sym(ClusterNames_0.2) = 0)
```
sym() function allows creating a symbol object, which can be evaluated and injected into the function using `!!`.
