### ISSUE TITLE
Error when running SCTransform

### ISSUE THREAD

**Issue by linanzhang** [satijalab/seurat#3663] opened 2020-10-29 20:05 UTC
I'm running this vignette [https://satijalab.org/seurat/v3.2/spatial_vignette.html](url), and having problem with SCTransform in both Seurat 3.2 and Seruat 4.0. The syntax is:

```r
allen_reference <- SCTransform(allen_reference, ncells = 3000, verbose = FALSE)
```

The error massage is

Calculating cell attributes from input UMI matrix: log_umi
Variance stabilizing transformation of count matrix of size 34608 by 14249
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 3000 cells
  |======================                                                                |  25%
Error in while ((it <- it + 1) < limit && abs(del) > eps) { : 
  missing value where TRUE/FALSE needed
In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by ChristophH** [comment] 2020-10-29 22:07
There is a known issue with the current release (v0.3.1) of the sctransform package (which is used by the Seurat::SCTransform function). In some cases the poisson regression fails due to poor initialization. The problem has been fixed in the develop branch. To install from the develop branch run `remotes::install_github("ChristophH/sctransform@develop")`

Please install the develop version of sctransform, restart R, and try again.

**Closed** 2020-12-07 20:58 UTC
Labels: bug, more-information-needed
