### ISSUE TITLE
Read10Xfunction not available in R v 4.1.0 

### ISSUE THREAD

**Issue by kstriedinger** [satijalab/seurat#4574] opened 2021-06-03 19:02 UTC
I downloaded from cran hdf5r and rhdf5 packages. however the hdf5r is not loading upon calling on library(hdf5r) after multiples install and trial efforts and it keeps producing an Error:
"Error in Read10X_h5(filename = "/Volumes/LaCie/ihg-client.ucsf.edu/pomerantzj/201123_A00269_0437_AHVH7MDRXX_fastqs_analysis/HVH7MDRXX/outs/filtered_peak_bc_matrix.h5") : 
  could not find function "Read10X_h5"

I am using:
Version 1.4.1106  R studio
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)
MacOS Big Sur 11.4

```

**Comment by samuel-marsh** [comment] 2021-06-04 01:38
Hi,

Not member of dev team but hopefully can be helpful.  So the error you posted is not associated with the hdf5r package as `Read10X_h5` is from Seurat not hdf5r.  Have you loaded `Seurat` in your R session?    Could you post the results of `sessionInfo()`?

Best,
Sam

**Comment by timoast** [comment] 2021-06-04 18:49
I'm going to close this now, the issue is almost certainly because you haven't loaded the Seurat package

**Comment by kstriedinger** [comment] 2021-06-04 18:52
Hi,
To fix the issue of not been able to read h5 after loading Seurat, I had to install the hdf5 in a shell because of my mac OS operating system, more info here: https://hhoeflin.github.io/hdf5r/
Close all programs, reinstall all packages.
not a trivial thing.
thanks,

Katharine

**Comment by kstriedinger** [comment] 2021-06-04 18:53
Hi,
To fix the issue of not been able to read h5 after loading Seurat, I had to install the hdf5 in a shell because of my mac OS operating system, more info here: https://hhoeflin.github.io/hdf5r/
Close all programs, reinstall all packages.
not a trivial thing.
thanks,

Katharine

________________________________

**Closed** 2021-06-04 18:54 UTC
